### ISSUE TITLE
Structorizer should show it's release number in window title bar.

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#101]
Structorizer should show it's release number in window title bar. like: Structorizer 3.23-12 - filename.nsd

**Comment by codemanyak** [comment]
Makes sense with the current version frequence...
And the titlebar should give a hint, whether the Structorizer instance is the application root or a subordinate instance e.g. opened from Arranger (which may be closed without risk to kill the main process).
For the latter ones the title might be put in parentheses, e.g. "(Structorizer 3.23-13) - filename.nsd".

**Comment by elemhsb** [comment]
Plus git version should have again continuing tags. e.g. 3.23-xx.

**Comment by fesch** [comment]
I post releases on Github only after some time, because when things do change fast, it will give me to much overhead. Publishing on the official site is nothing more than launching a script ...

**Comment by elemhsb** [comment]
??? You published -00 -01 -02 -03 ... -33 but nobody, including yourself, should now about the source code version ... ???
Please script both.

**Comment by codemanyak** [comment]
@elemhsb Oh, please, come on. This is not the control software of a Diesel exhaust particulate filter, a nuclear power station, or a manned submarine (just for instance). The most up-to-date source code version is always downloadable both from GitHub and the Structorizer home page. Specific source code differences may still be retrieved from the commits and the merge labels. If someone may have missed some defective version, so what?
From a fundamental point of view, you are absolutely right - and it's the very idea of a source code management system to keep every little change identifiable, every published version tagged, and the originator of faults be blamed.
But this is not a commercial product, and Bob does his very best to keep track with the developments and issues here, enables rapid fixing of serious bugs. We owe him a lot, starting with the basic design and so many handy ideas. But he has a job and a family, too. We should keep this whole thing manageable without letting it exhaust us.
And by the way and in reference to this issue heading: **The current version number has always been only one click away via the "about" toolbar button.** While versioning used to be in smooth waters, this had always been good enough for months.
So it will probably be me who is to be blamed for pushing some complex functional enhancements I had been pregnant with the last years and which soon showed their teething troubles, inducing a fast series of somewhat ephemeral bugfix versions. Many of them were urgent enough.
Maybe the release frequency will now be able to slow down a little again and let Bob the time to tag the versions worth to be tagged again.
One of the bigger projects for the future will certainly be to set up an appropriate unit test suite and to establish some kind of continuous integration environment. This will inevitably contribute to some kind of exact specification what the Structorizer is expected to do and how in detail. (And this will be hard work to identify in some cases, I guess.)
But for now please stay calm. No one here tries to deprive the world from knowing about the software version. Okay?

**Comment by elemhsb** [comment]
Ok, I only wan't to do a little help to this incredible project.

I have seen in the last three months a lot of versions on my systems, installed in the class room, and and on the 30 students notebooks, on all os versions. Mixed with a colored set of stuctorizer.ini setup files there is a lot of stuff that goes wrong. Plus the mysterious  java compile errors with build.xml seen from source code. So i found that set Help->About is very **slow**. F1 keypress is faster so I will use this for now.

**Comment by fesch** [comment]
I still recommend to use the JWS version, which - when you are online - will auto update itself always to the latest version.

**Comment by elemhsb** [comment]
@fesch ;-)

**Comment by codemanyak** [comment]
Version 3.26-01 will modify the title text for dependent Structorizer instances (i.e. those opened additionally from Arranger) slightly:
Instead of being enclosd in parentheses, the title text wil now be preceded by an instance number >= 2 within brackets, e. g.
**[3] Structorizer 3.26-01 - Example.nsd**

**Comment by codemanyak** [comment]
Version 3.26-01 will modify the title text for dependent Structorizer instances (i.e. those opened additionally from Arranger) slightly:
Instead of being enclosd in parentheses, the title text wil now be preceded by an instance number >= 2 within brackets, e. g.
**[3] Structorizer 3.26-01 - Example.nsd**
