### ISSUE TITLE
wrong error message for JDK

### ISSUE THREAD

**Issue by MarkRotNF** [fesch/Structorizer.Desktop#1030]
If no Java JDK (Java Development Kit) is installed, an error message appears that JRE (Java Runtime Environment) needs to be installed. JDK should be written there.

![image](https://user-images.githubusercontent.com/39699611/160365572-057fbe6a-480a-4a91-98c4-a672c945f190.png)

Version: [Download the latest version of Structorizer (Windows & Linux)](https://www.fisch.lu/Php/download.php?file=structorizer_latest.zip)

**Comment by fesch** [comment]
The message does not look like any of the message that Structorizer produces. We generally do not mix up languages....

**Comment by codemanyak** [comment]
Apparently, it could be a message of the Java launcher structorizer.exe (which is produced by means of Launch4J, in the configuration script for which the version number 11.0.1 is given as minimum supported Java level) which in turn cites a rather unspecific (Windows) operation system message. (Or the other way round.) This would explain the language mix.

Indeed, an uop-to-date JRE would be quite sufficient to run Structorizer but in recent years many OpenJDK provider haven't bothered to provide mere JREs anymore next to the JDK versions. So this is what might puzzle the users. The [installation](https://help.structorizer.fisch.lu/index.php?menu=45) section of the User Guide discusseds the implications into some detail.

**Comment by codemanyak** [comment]
I think, we do not expect any sensible update here, all necessary explanation is given, so I think we may close this issue.
