### ISSUE TITLE
Converting to code

### ISSUE THREAD

**Issue by lhoreman** [fesch/Structorizer.Desktop#104]
I have problems with export code in some PSDs . I suspect this has to do with the until- loop .
![foutboodschap](https://cloud.githubusercontent.com/assets/11858847/12260408/ffb33128-b91b-11e5-8020-f6e8a5904ea3.png)

**Comment by codemanyak** [comment]
Would you please specify the Structorizer version number, the diagram example, and the target language(s)?

**Comment by lhoreman** [comment]
Structorizer version 3.23 

I tried many languages (Pascal, Python, C#,...) They all give the same
message. 

In attach a few testfiles. 

Lieve 

Kay Gürtzig schreef op 2016-01-12 11:06: 

> Would you please specify the Structorizer version number, the diagram example, and the target language(s)? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-170877541

**Comment by codemanyak** [comment]
Hello lhoreman,

3.23-??
If you happen to use 3.23-00 (the last "big" but faulty release) then 
I'd like to ask you to try 3.23-12, the current latest version.

Regards
Kay Gürtzig

Am 12.01.2016 um 12:14 schrieb lhoreman:
>
>
> Structorizer version 3.23
>
> I tried many languages (Pascal, Python, C#,...) They all give the same
> message.
>
> In attach a few testfiles.
>
> Lieve
>
> Kay Gürtzig schreef op 2016-01-12 11:06:
>
>> Would you please specify the Structorizer version number, the diagram example, and the target language(s)?
>>
>> --
>> Reply to this email directly or view it on GitHub [1].
>
>
> Links:
> ------
> [1]
> https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-170877541
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-170879155
>


-- 
Fachhochschule Erfurt
Fakultät Gebäudetechnik und Informatik
Studiengang Angewandte Informatik
Lehrgebiet Grundlagen Informatik und Betriebssysteme

PF 45 01 55, 99051 Erfurt

Telefon: 0361 6700-677
Telefax: 0361 6700-643
E-Mail: kay.guertzig@fh-erfurt.de
Internet: http://www.fh-erfurt.de

**Comment by lhoreman** [comment]
Sorry, 3.23.10, downloaded last friday 

I've just tested 3.23.12. Same message. 

Kay Gürtzig schreef op 2016-01-12 11:28: 

> Hello lhoreman,
> 
> 3.23-??
> If you happen to use 3.23-00 (the last "big" but faulty release) then 
> I'd like to ask you to try 3.23-12, the current latest version.
> 
> Regards
> Kay Gürtzig
> 
> Am 12.01.2016 um 12:14 schrieb lhoreman:
>>
>>
>> Structorizer version 3.23
>>
>> I tried many languages (Pascal, Python, C#,...) They all give the same
>> message.
>>
>> In attach a few testfiles.
>>
>> Lieve
>>
>> Kay Gürtzig schreef op 2016-01-12 11:06:
>>
>>> Would you please specify the Structorizer version number, the diagram example, and the target language(s)?
>>>
>>> --
>>> Reply to this email directly or view it on GitHub [1].
>>
>>
>> Links:
>> ------
>> [1]
>> https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-170877541
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-170879155
>>
> 
> -- 
> Fachhochschule Erfurt
> Fakultät Gebäudetechnik und Informatik
> Studiengang Angewandte Informatik
> Lehrgebiet Grundlagen Informatik und Betriebssysteme
> 
> PF 45 01 55, 99051 Erfurt
> 
> Telefon: 0361 6700-677
> Telefax: 0361 6700-643
> E-Mail: kay.guertzig@fh-erfurt.de
> Internet: http://www.fh-erfurt.de 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-170882388

**Comment by codemanyak** [comment]
Have you already sent or uploaded some diagram examples? I haven't received any as far as I'm aware of.
I exported about a dozen diagrams, containing nearly all kinds of strcutured elements but couldn't provoke that index error. It might be a good idea to pass me your Structorizer.ini as well - just for the case that some configuration particularity plays a catalyst role -, I you don't mind.

**Comment by lhoreman** [comment]
I hade allready sent you two files. Something went wrong. 

In atach a zip with structorizer.ini and two nsd-files. 

Kay Gürtzig schreef op 2016-01-12 22:50: 

> Have you already sent or uploaded some diagram examples? I haven't received any as far as I'm aware of.
> I exported about a dozen diagrams, containing nearly all kinds of strcutured elements but couldn't provoke that index error. It might be a good idea to pass me your Structorizer.ini as well - just for the case that some configuration particularity plays a catalyst role -, I you don't mind. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/fesch/Structorizer.Desktop/issues/104#issuecomment-171069370

**Comment by codemanyak** [comment]
Okay, now I got it and could identify the problematic piece of code. Thanks a lot!

**Comment by codemanyak** [comment]
Fix available in bugfix3.23 branch.

**Comment by lhoreman** [comment]
Maybe a stupid question, but: Can I allready download the version 3.23.13? If I download the latest version, it is still 3.23.12

**Comment by codemanyak** [comment]
Bob just merged the bugfix branch, so I assume the version will be available by this evening if there isn't a show stopper I might have overlooked. (There might be some unwanted impact on other projects like Unimozer because I had to change an internal interface.)

**Comment by fesch** [comment]
I've uploaded it immediately. If you use the JWS Version, it should auto-update if you restart it.

**Comment by codemanyak** [comment]
@fesch Then obviously the changelog update on the website had been forgotten - which is of course the first place to check whether there might be something new. And the downloadable "latest" version is also still 3.23-12 from 2016-01-08 (downloaded 2016-01-14, 00:01 am).
Something seems to have gone wrong again. This time, it won't have been the build.xml again?

**Comment by fesch** [comment]
:-( ... tried again.

**Comment by lhoreman** [comment]
Thank you for the quick solution!
