### ISSUE TITLE
Bug in structorizer-Python-API Code for fileReadLine

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#1040]
Hi Kay,
the function readFileLine which is linked to the exported Python code never ends and add always the first character of the file to the line, because there is no new character read in the while loop.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Should I know what function readFileLine you are talking about? In the embedded File API code definitions there is no such function but a function `readLine` - is this the one you are referring to?

**Comment by codemanyak** [comment]
Okay, you are absolutely right: The File API method `readLine` is defective.
The correct code would have been:

```python
    @classmethod
    def readLine(cls, fileNo):
        fileHandle = cls._openFileTable[fileNo]
        line = ""
        char = fileHandle.read(1)
        if (char == ""):
            raise IOError("End of File")
        while (char != "" and char != '\n'):
            line += char
            char = fileHandle.read(1)
        return line
```

This will be fixed with the following Structorizer version. Many thaks for your test!
