### ISSUE TITLE
COBOL Parser: add lookup table for lexical symbol labels

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#1046]
>>> It seems to me, the parser does not understand the simplest COBOL constructs like eg. "ENVIRONMENT DIVISION". The error message shows comical constructs as valid COBOL, like eg. END_CALL or NOT_ESCAPE.

>> By the way, END_CALL and NOT_ESCAPE are lexical symbols in the used grammar, they stand for certain scope terminator or a certain condition variant on COBOL exception handling, respectively.

> Is there a way to give the lexical symbols a separate label as it is with Bison? In this case the former is labeled as "END-CALL" and the second as "NOT ON ESCAPE" in the original grammar that was used to build the COBOL grammar.

I guess in order to achieve this, the specific code parser (here: `COBOLParser`) would have to provide an (optional) lookup table with backward translations of the "terminals" defined in the grammar (in *GnuCOBOL.grm* lines 204 through 858 (!) or a subset of them), which should then be used in the syntax error section of method `CodeParser.parse()`. This should be feasible. In the grammar itself, there is rather no option for such an attributing approach like in Bison.

_Originally posted by @codemanyak in https://github.com/fesch/Structorizer.Desktop/issues/1044#issuecomment-1190098791_

Just moving it out of a "related" issue. To not raise any false hopes: I'm unlikely to do any work on Structorizer for the next months myself.

**Comment by codemanyak** [comment]
@GitMensch 
> To not raise any false hopes: I'm unlikely to do any work on Structorizer for the next months myself.

No problem. The proposed solution idea should not be that difficult to be solved, After having had a look into the hundreds of "terminals" definitions in the COBOL grammar it became immediately clear that a general automatic approach would not be helpful (as some of the definitions may bring rather complex regular expressions), so the introduction of a generic mechanism that allows to provide a manually filled translation table should do the trick and is definitely no rocket science. I'll care for it.

**Comment by codemanyak** [comment]
Mechanism implemented and prepared for COBOL import (to be delivered with version 3.32-09). For other import languages this is not relevant as the few terminal definitions in these grammars are rather helpful for readability than confusing, e.g.
`FloatingPointLiteral = {Digit}+'.'{Digit}*{FloatTypeSuffix}? | {Digit}+{FloatTypeSuffix} | '.'{Digit}+{FloatTypeSuffix}?`
(where "FloatingPointLiteral" obviousy seems more instructive in the message than "0 | 1 | 2 | 3 | 5 | 6 | 7 | 8 | 9 | '.'")
