### ISSUE TITLE
Wish: generate multiple filenames in batch mode

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#1047]
Hi.

I have a need to export a lot of code from NSD files for documentation and batch mode do it very well and faster than single program invocations. 
But I would like to have the results in multiple files with names derived from the NSD-file for further manipulation. 
Is it possible? A calling parameter could be "-k" for keep.
Fine regards
Rolf

**Comment by codemanyak** [comment]
Hi Rolf,
it is not possible in existing versions of Structorizer, unfortunately. But the resulting code contains so called "scissor lines". i.e. comment lines looking like e.g. "// = = 8< = = = =" where Sctructorizer recommends splitting the export file into separate files. Then even the proposed file names will be incorparated in the scissor comment. This does not usually happen, however, in cases of a subroutine hierarchy that can syntactically coexist with the main file. The best opportunity to achieve maximum splitting proposals is to export an arrangement group via the conext menu on a group entry in the Arranger index.

It will actually not be trivial to force an export into separate files (if I remember well - I had pondered this some years ago), particularly with respect to the batch export mode where a safe file organisation tends to get a real challenge (think of entire lists of arrangements to be exported, such that a forest of files would have to be created).

I will about it again but don't promise a quick solution (possibly not even a solution at all).

**Comment by reks99** [comment]
Hi Kay
Thank you for your fast response.
The workflow I would like to implement is: Construct the classes of a program with umbrello. Umbrello is able to read in python sourcecode and can export it with file include lines as well.
So I write just one letter in the sourecode tab of an operation (i.e. method). Then I parse the xmi file to find the methods xmi-id and generate files with the name Class.operationname.xmiid and Class.operationname.nsd so I can reimport the source using the xmi-id of the filename. 
The diagrams have the type subroutine because they are just parts of a class.
So I have a graphical representation of the class and its operations (methods).
Of course I can export the code from structorizer with a shell skript, but as I said invoke structorizer took a while. That is where the batch mode can help.
Fine regards
Rolf

**Comment by codemanyak** [comment]
Oh, it seems I missed the point. If you export a bunch of NSD files, you will obtain the export results already in separate files but the names will all be derived from either the first of the nsd file names or from the -o option. You want all of them derived from  the respective nsd file name. Okay this is a sensible desire (at least until first name collisions come up, then it might get difficult). I will have a look.

**Comment by codemanyak** [comment]
@reks99 
Sorry, but I haven't managed to offer a solution by version 3.32-09. I will keep it in mind, though.

**Comment by codemanyak** [comment]
I just found out that the proposed file names in the scissor lines have become totally inconsistent for sequences of nsd files in this batch mode (they may still make sense on archive export, but apparently the needs for these two cases got into conflict).
So this issue will also get the bug label.

**Comment by codemanyak** [comment]
@reks99 
I found a way to enable the requested batch export of a list of NSD files without amalgamating them into a single code file and to fix the missing or misleading label on the scissor lines.
How urgent is this feature? For preview testing I attach a precompiled jar file (just to be unzipped and placed into the appropriate subfolder (Structorizer.app/Content/Jar) of a locally unzipped Structorizer zip package (also containing the scripts for batch execution).
[Structorizer_3.32-10-alpha1.zip](https://github.com/fesch/Structorizer.Desktop/files/9238005/Structorizer_3.32-10-alpha1.zip)

**Comment by reks99** [comment]
Hi Kay.
It seems that Christmas is not far away so wishes become real very soon ;-). Many thanks.

The Program works as expected. I think there is no need more for the scissor lines in the generated code. One comment line with the file name may be, but is not really needed.

Once again many thanks
Rolf

**Comment by codemanyak** [comment]
@reks99 
I am glad the prerelease Jar meets your needs. So I have a little more time for improvements or other fixes, before the next version gets shipped.

> I think there is no more need for the scissor lines in the generated code. One comment line with the file name may be, but is not really needed.

Well, I know, but it turned out to be too difficult for the responsible routine exactly to classify te situation in which it is called (without passing dozens of additional arguments over several levels). I deemed it more important to ensure the scissor lines with correct labels in the concatentating case than to suppress them in the file per file mode. I didn't want to risk inadvertent side effects for other contexts (interactive diagram export with subroutines, interactive group export, library export, arrangement file export in batch mode with or without routine pools, etc.). They all share lots of common code and their entanglement is tricky. (I'd rather fundamentally redesign this later, in combination with #800 and #850 - and the task is rather daunting since we don't want to lose or compromise the continuously grown functionality. It would be a complete re-invefntion. The curse of long-evolving projects...)

**Comment by codemanyak** [comment]
On considering sensible combinations of options -k and -o I bumped into a bug of the preceding versions: If the path specified with option -o names an existing directory then the batch export fails to work, the code files simply won't be created anywhere (without any error message).
The new functional specification will be:
| `-o` option | `-k` option | target folder(s) | code file name(s) | code amalgamated? |
| ----------- | ----------- | --------------- | --------------- | ---------------------|
| (omitted) |  | folder of 1st nsd file / resp. arr[z] file | derived from 1st nsd file | Yes, that from nsd files |
| `-o` &lt;folder&gt; |  | specified &lt;folder&gt; | derived from 1st nsd file | Yes, that from nsd files |
| `-o` &lt;non-folder&gt; |  | from specified path | from specified path | Yes, that from nsd files |
| (omitted) | `-k` | folder of resp. nsd/arr[z] file | derived from resp. nsd/arr[z] file |  No  |
| `-o` &lt;folder&gt; | `-k` | specified &lt;folder&gt; | derived from resp. nsd/arr[z] file | No |
| `-o` &lt;non-folder&gt; | `-k` | from specified path | derived from resp. nsd/arr[z] file | No |

**Comment by codemanyak** [comment]
After the occupation with this issue, the original thoughts came back to me:
The command will by default generate a common code file from all the diagram (_.nsd_) files listed in the command. The idea behind this behaviour originated from the time before arrangement (_.arr_, _.arrz_) files have become processable and was to allow the batch production of a consistent source file from a related set of diagrams without access to an Arranger context. For separate conversion of diagrams the command could be executed in a loop, e.g.
```bash
for FILE in a.nsd b.nsd c.nsd
do
    Structorizer.sh -x Python $FILE
done
```

Code generation for arrangement files (_.arr_, _.arrz_), which had later been allowed to be be included in the file list, will always be held separate. So the new option -k indeed just internally simulates a command loop, i.e. keeps the code generation for the listed _.nsd_ files separate as well. It had not been necessary but may facilitate the conversion of a series of isolated diagrams within a single command line.

**Comment by reks99** [comment]
Hi Kay.

I like the idea to pass an output path to structorizer - but only in batch mode? Why can't I set an output path in the interactive mode as well? It might be saved in the ini-file of structorizer.

Many thank for your effort.
Rolf

**Comment by codemanyak** [comment]
@reks99 
You asked:
> Why can't I set an output path in the interactive mode as well? It might be saved in the ini-file of structorizer.

In a way, this is already the case: Structorizer indeed remembers the last chosen code export folder in the ini file and proposes it the next time again. Alternatively, you may tell Structorizer to prioritise the folder of the currently edited diagram for the export:
![grafik](https://user-images.githubusercontent.com/15326471/184433336-bd8e4feb-ded1-47b0-aa2a-de87d54fcdb6.png)

From my point of view, this should already be pretty close to what you want.

**Comment by reks99** [comment]
Hi Kay.

Thanks for your reply. As written in the option, the path for export will derived (always) from the path of the nsd. In my case I have a lot of nsd files and like to have the generated source files in a different directory to have a better overview.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> As written in the option, the path for export will be derived (always) from the path of the nsd.

This is only true if you choose this option. If you don't select the above option then the file chooser dialog will always suggest you the output folder you had used the last time you exported diagrams. Once chosen, always offered as firts choice (until to decide for a differing folder, then this folder will be the one for the next exports). This last export folder choice is indeed stored in the ini file.
