### ISSUE TITLE
enhancements for french GUI

### ISSUE THREAD

**Issue by tph002** [fesch/Structorizer.Desktop#1056]
Bonjour,
Voici mes propositions de corrections dans l'interface utilisateur française de la version 3.32-09 :
1) dans [Préférences / structures] :
      [ Élargirer ]   devrait s'écrire  [ Élargir ]
2) dans [Préférences / Appellations des éléments ] :
      - [ Appellations des éléments ] devrait s'écrire [ Appellation des éléments ]
      - le titre du popup devrait être : Préférences d'appellation des éléments
      - [ sous programme ] devrait s'écrire [ sous-programme ]
      - [ Inclurible ] devrait être [ Incluable ] (sous réserve)
3) dans [Préférences / Roue de la souris] : 
     [ Invertir le zoom au l'usage de ctrl ] devrait s'écrire [ Inverser le zoom avec Ctrl ]
4) dans [Préférences] : 
    [ Controller aliases ] devrait s'écrire [ Contrôler les alias ] 
    et le titre du popup [Controller Routine aliases] devrait s'écrire [ Contrôler les alias de routine ]

5) dans [ Aide ] : 
    [ Download Guide as PDF ] devrait s'écrire [ Télécharger le guide au format PDF ]

Bravo pour votre travail
Best regards

**Comment by codemanyak** [comment]
Merci beacoup pour votre propositions ou corrections!
S'il vous plais, excusé mon pauvre Francais. So I'd like to answer in English:
1. -> of course, this should have been obvious...
On this occation: Do you have proposals for the missing translations on this popup window as well?
![grafik](https://user-images.githubusercontent.com/15326471/183579430-2865c947-dccf-4606-8c1d-8ba7932361b7.png)

2. -> Okay. Again I would also appreciate your proposals for the remaining captions on that dialog:
![grafik](https://user-images.githubusercontent.com/15326471/183580488-b72eb333-2423-440e-a544-e19e8a3f562e.png)

3. Accepted.
4. Oops, how embarrassing... No idea how this could happen. But what about the missing translations? Proposals?
![grafik](https://user-images.githubusercontent.com/15326471/183583559-59d6ba62-c0f0-4290-a9a2-ba4609e7b310.png)

5. Done, thanks!

If you consider to assist in the completion of the French translation then I would like to recommend the use of the Translator tool (Fichier / Traducteur) and to send us the updated translation file. This might be way more efficient than writing correction lists. What do you think? In fact, there are still lots of untranslated dialogs, unfortunately.

**Comment by codemanyak** [comment]
On this occation I found (and fixed) a defective tooltip association on the speed buttons for the insertion of PARALLEL and TRY elements in the Elements tool bar.

**Comment by tph002** [comment]
Following your suggestion, I have done my best to translate almost the entire French file of the Translator. I am sending it to you herewith.
NB: I have taken over some of the translations I had previously proposed.
Best regards

[fr.txt](https://github.com/fesch/Structorizer.Desktop/files/9332994/fr.txt)

**Comment by codemanyak** [comment]
@tph002 
Magnifique! Exceptionelle! Extraordinaire! Merci beaucoup!
We owe you! (And many French-speaking users certainly do as well.)
I just dared to remove some superfluous blanks (before ':', '!', and '?'). And the apostrophe before the last word in the following translation (line 830) caught my eye in disbelief:
"Sélectionner une licence disponible dans le pool de licences personnelles ou du pool courant pour 'éditer."
I guess it is a mistake (possibly inadvertently inserted instead of the accent aigu)? But even if so, this is nothing in comparison to the enormous efforts you did. A giant improvement.
