### ISSUE TITLE
Bug in bulk (batch) export.

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#1060]
Hi Kay.

When I generate the source code in batch mode with the -k option of the alpha version and the option "no conversion of..." in the export options is set, all equal signs where substituted to two equal signs.

Fine regard
Rolf

**Comment by codemanyak** [comment]
What target language do you refer to? And this happens with the -k option only?

**Comment by reks99** [comment]
Hi Kay.

The export is set to Python and I just tested and found, that the bulk export without the -k option has the same bug.

Fine regards.
Rolf

**Comment by codemanyak** [comment]
Thank you for the update. I still can't reproduce the bug. Could you please attach a diagram sample that provokes it?

**Comment by reks99** [comment]
Hi Kay.

I assumed, that the settings of the "standard" ini-file is used for export by default. I didn't used the -t nor the -s option. With both options the reported problem does not exists.

BTW: May this more explicitly documented?

Many thanks.
Rolf

**Comment by codemanyak** [comment]
I see.

> BTW: May this be more explicitly documented?

Well, actually it *is* explicitly documented (see [User Guide](https://help.structorizer.fisch.lu/index.php?menu=68&page=#batch_export)):
> Note that the [parser preferences](https://help.structorizer.fisch.lu/index.php?menu=81) configured in interactive Structorizer mode will be valid here, whereas the [export options](https://help.structorizer.fisch.lu/index.php?menu=110) configured in interactive mode are not valid here; unless command line option -s explicitly specifies an .ini file as source for export options only the command line options described above will be observed (for binary options, the contrary of the described option effect being the default, e.g. without specifying -l option there won't be line numbers or other old-fashioned relics in BASIC output). The export option "Involve called subroutines" will automatically be enabled for arrangements and disabled for loose diagram files.

Possibly it should be more emphasized or be put in a more prominent place but in the end it is a priority race that is hard to win for a specific aspect...

**Comment by reks99** [comment]
Thanks.

As you can see I'm not a hacker, then "Hacker read manuals!"
Fine regards
Rolf
