### ISSUE TITLE
Subroutine with typed variables, execution and export failed. 

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#107]
![call](https://cloud.githubusercontent.com/assets/2959804/12323428/6ec88b9e-babb-11e5-95c3-f230ba576eef.png)

a) excecutor asks only for a
b) export to C/C++ got this:  int call(int, b:int a)

**Comment by codemanyak** [comment]
This type of parameter specification must adhere to PASCAL syntax, i.e. either
```
call(a, b: integer): integer
```
or
```
call(a: integer; b: integer): integer
```
The separator between complete parameter declarations must be a semicolon.

**Comment by codemanyak** [comment]
Maybe, a new Analyser warning might be created for the case that more than one colon is found within one parameter declaration (i.e. between the parentheses and semicolons as delimiters).

**Comment by elemhsb** [comment]
![min](https://cloud.githubusercontent.com/assets/2959804/12356918/692e145c-bba5-11e5-98f1-d4cf5aaa2e77.png)

Thank you for declaration. :-)

Now i found the C/C++ like ***typed*** version works meanwhile out of the box, for **execution** #49,#61 and **exporting**. Good job.
No  additional modifications to exported sources are needed :-)) I am happy!
Only the unnecessary ```/*type?*/``` (in my case) scratches the look a little bit. ;-)

```
// Funktion liefert den kleineren der beide parameter 
// function Min( int p, int q ) : int 
#include <iostream>

// TODO Revise the return type and declare the parameters! 
int Min(/*type?*/ int p, /*type?*/ int q)
{

        // TODO: declare your variables here: 
        // ret 
        // int ret 

        int ret = 0;
        if ( p <= q ) {
                ret = p;
        }
        else {
                ret = q;
        }
        return ret;
}
```

**Comment by codemanyak** [comment]
Oops, the /*type?*/ comment should only occur if no parameter was detected!
And the variable highlighting still fails with types in prefix position.
And the executor asks for "<int p>"  instead of "<p>". Well, this might even be seen as a useful service, but then it should work for Pascal-like specifications in a similar way.

**Comment by codemanyak** [comment]
This is practically the same issue as #61 now.

**Comment by codemanyak** [comment]
Fix for the mentioned remaining inconveniences available on bugfix3.23 branch.
