### ISSUE TITLE
Cant import Code

### ISSUE THREAD

**Issue by PauLeeBaer** [fesch/Structorizer.Desktop#1079]
Hello, I use structoizer for my school works and have the Problem that i cant import my java code into the programm...
I only can import this pascal code, idk what this even is, some classmates use the programm too and only one of them can do this.
I hope someone can help with my issue
Best regards

**Comment by fesch** [comment]
Do you have any error message on screen or in the console?

**Comment by codemanyak** [comment]
What exactly is going wrong on the attempt to import Java code? Do you get a parser error or doesn't your Structorizer version offer to import java files?
Would you mind telling us the Structorizer version you are using, uploading a minimum Java code sample that fails to be imported and having a look for your import settings in Structorizer (menu item "Preferences > import", in particular with the Java-specifc options (press the left button within the blue oval after chosen "Java SE8" in the choice item, see screenshot)?
![grafik](https://user-images.githubusercontent.com/15326471/223064445-27c10b32-2d89-4f9b-9679-adbdd7e93711.png)

**Comment by codemanyak** [comment]
@PauLeeBaer 
FYI: The Java import capability was integrated into Structorizer with release 3.31, so if you happen to use an older version then there won't be a chance to import Java unless you replace it by an up-to-date Structorizer version.

**Comment by PauLeeBaer** [comment]
> 

With the newest version it dosent even start and with the version 3.21 its starts but only with limited features

**Comment by codemanyak** [comment]
@PauLeeBaer 
> With the newest version it dosent even start and with the version 3.21 its starts but only with limited features

I see. So my next guess is that you will have to upgrade the underlying Java JDK or RE to at least version 11 as well, because that is what the contemporary Structorizer versions require (see #1031 or #1076 for instance or consult the online [User Guide](https://help.structorizer.fisch.lu/index.php?menu=45)).

**Comment by PauLeeBaer** [comment]
> @PauLeeBaer
> 
> > With the newest version it dosn't even start and with the version 3.21 its starts but only with limited features
> 
> I see. So my next guess is that you will have to upgrade the underlying Java JDK or RE to at least version 11 as well, because that is what the contemporary Structorizer versions require (see #1031 or #1076 for instance or consult the online [User Guide](https://help.structorizer.fisch.lu/index.php?menu=45)).

I have these in my programm folder
![image](https://user-images.githubusercontent.com/127091519/223070882-86a63fd1-c91f-4f35-9bed-8d6f51a7f13f.png)

**Comment by PauLeeBaer** [comment]
I have to edit if i use the latest version it just starts shows me the starting screen and then it just disappeare 
![image](https://user-images.githubusercontent.com/127091519/223071340-f9c6b384-d75b-4cca-b5bb-9db320f45e86.png)

**Comment by codemanyak** [comment]
Apparently you have both Java 8 (the JRE) and Java 19 (the JDK) on your computer. Maybe Structorizer is groping for the JRE first und thus ends up dangling. You might try to unpack version [3.31-04](https://github.com/fesch/Structorizer.Desktop/releases/download/3.31-04/structorizer_3.31-04.zip) from the old releases on GitHub and have a look into the path view ("Help > About > Paths") to find out what Java version Structorizer is using. If it gropes Java 8 (what I suspect) then you should try to switch off (disable) Java RE 1.8... (via the Oracle Java monitor) in the hope that Structorizer will then accept the JDK 19 instead.

**Comment by PauLeeBaer** [comment]
> Apparently you have both Java 8 (the JRE) and Java 19 (the JDK) on your computer. Maybe Structorizer is groping for the JRE first und thus ends up dangling. You might try to unpack version [3.31-04](https://github.com/fesch/Structorizer.Desktop/releases/download/3.31-04/structorizer_3.31-04.zip) from the old releases on GitHub and have a look into the path view ("Help > About > Paths") to find out what Java version Structorizer is using. If it gropes Java 8 (what I suspect) then you should try to switch off (disable) Java RE 1.8... (via the Oracle Java monitor) in the hope that Structorizer will then accept the JDK 19 instead.

OMG!! I have to thank u... It worked with ur version...

**Comment by codemanyak** [comment]
> OMG!! I have to thank u... It worked with ur version...
I guess this means you are working with the (obsolete) Structorizer version 3.31-04 on Java RE 8 now? This will enable you to import Java (SE8) code, at least. But on the long run, I recommend to use the newest Structorizer version (on e.g. Java SDK 19) if you want to get rid of the meanwhile fixed bugs and take advantage of all the newer features.
But never mind if I got you wrong. I'm glad you can work now.
Think we can close this issue now?

**Comment by PauLeeBaer** [comment]
> > OMG!! I have to thank u... It worked with ur version...
> 
> I guess this means you are working with the (obsolete) Structorizer version 3.31-04 on Java RE 8 now? This will enable you to import Java (SE8) code, at least. But on the long run, I recommend to use the newest Structorizer version (on e.g. Java SDK 19) if you want to get rid of the meanwhile fixed bugs and take advantage of all the newer features. But never mind if I got you wrong. I'm glad you can work now. Think we can close this issue now?

Yes, we can close it... how can i close it?

**Comment by codemanyak** [comment]
You should see a "Close with comment" button next to the "Comment" button beneath the Comment form...
But I just closed it myself now. Thanks!
