### ISSUE TITLE
yellow background in windows in multiseat environment

### ISSUE THREAD

**Issue by 3gb1e** [fesch/Structorizer.Desktop#1080]
I run an up to date OpenSuseTumbleweed-Installation with seven attached seats in a multiseat educational environment. The seats are connected to "plugable display link usb 2.0 docking stations". The eighth seat is directly connected to the main pc.

If I run structurizer at the 8th seat everything is fine.
If I run on one of the other seats that are connected by a docking station the windows of structorizer only show yellow background:

![yellowscreen](https://user-images.githubusercontent.com/81754780/235978100-cd4ffc89-6890-432b-b565-852110ebaa95.jpg)

The terminal messages on startup on the 8th seat do not differ from the other ones.
There are no graphical problems with other applications than structorizer.
I don't know what to do and what to check.

**Comment by fesch** [comment]
Hi

I've never seen something like that before.

What Java version are you running?

**Comment by 3gb1e** [comment]
Hi

It's very hard to be as fast as you are :)

Unfortunately the multiseat installation is at school and I am at home right now. So I can finally check it out tomorrow. 
Nevertheless as OpenSuSE Tumbleweed is a rolling releaseit will be - quite sure:
java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+0-suse-1.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.19+0-suse-1.1-x8664, mixed mode)

**Comment by codemanyak** [comment]
> These are the docking stations: https://archive.plugable.com/products/ud-160-a/

Well the text on that website mentions some potential compatibility problems, e.g.
> additionally the external graphics may cause display corruption on both the internal and external display as well as errors drawing the mouse pointer. While all internal components do have open source drivers available in the Linux kernel 2.6.32 and newer, drivers for some of this hardware have not been maintained and may not function as expected. In testing with Ubuntu 19.04, 19.10, and Fedora 30 we have experienced significant performance degradation in both external and internal display display performance and USB device connectivity. Please feel free to contact our support team directly at support@plugable.com and we will be happy to help.

**Comment by 3gb1e** [comment]
Yes, indeed, same issue with minimal java applet.
Furthermore same issue with an lenovo docking station that uses identical display link graphics chip.

I didn't know that structorizer obviously has been the only java based program that has been used on the connected terminals last three years. So I thougt it could be related to structorizer itself.

Seems to be related:
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/664
https://github.com/adoptium/adoptium-support/issues/187
I'll try it out tomorrow.

Thanks for your efforts and advice!

**Comment by 3gb1e** [comment]
The problem can be solved by changing the last line in `structorizer.sh`
from ` java -jar "$DIR/Structorizer.app/Contents/Java/Structorizer.jar" "$@"`
to `java -jar -Dsun.java2d.xrender=false "$DIR/Structorizer.app/Contents/Java/Structorizer.jar" "$@"`
as described  [here](https://github.com/AdoptOpenJDK/IcedTea-Web/issues/664).

**Comment by codemanyak** [comment]
@3gb1e 
Thanks for your research and successful test. In https://github.com/adoptium/adoptium-support/issues/187 there are some hints, however, that the option may in some cases degrade display performance. So I still hesitate generally to integrate the change in the product. But maybe for the way Structorizer uses the rendering infrastructure it makes no much difference. We will observe it.
