### ISSUE TITLE
Four flaws on ANSI-C99 import

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#1089]
The C99 import is defective in three aspects related to type definitions:

1. struct initializer expressions with named target components like `struct struct_t s = { .comp1 = val1, .comp2 = val2, …};` (with `struct_s` being some defined struct type) are not correctly imported. The import results in an element with content `var s: struct_t ← struct_t{.comp1 = val1, .comp2 = val2, …}` instead of `var s: struct_t ← struct_t{comp1: val1, comp2: val2, …}`.
2. Typedef instructions with anonymous enum type like `typedef enum {name1, name2, ...} enum_t;` result in an element sequence with wrong type alias: `type Enum0815471162424 = enum{name1, name2, ...}`, `type enum_t = int`.
3. Typedef instructions with anonymous struct construct like `typedef struct{typ1 comp1; type2 comp2; ...} struct_t;` are converted into `type struct_t = struct{comp1: type1; comp2: type2;...}`, but  followed by a semantically redundant (and syntactically still incorrect) element `type struct_t = struct_t`.
4. If a typedef with an anonymous struct or enum defines more than one typeids then the resulting type definitions in Structorizer will be nonsense, e.g.
```C
typedef struct {
	char name[100];
	unsigned int stack_size;
	osPriority_t priority;
} osThreadAttr_t, osThreadAttrs_t[10];
```
produces:
![grafik](https://github.com/fesch/Structorizer.Desktop/assets/15326471/a32d2180-851e-49f7-8c77-74757e72ac2e)

**Comment by codemanyak** [comment]
Fix for 1st aspect is only working if the related struct type had been uniquely defined (still does not work for type aliases). Fix for 4th aspect produces type alias definitions that Structorizer cannot itself interpret.

**Comment by StrandedAlien** [comment]
Actually only super simple Source Code imports without adapting the code. I am not even trying this feature anymore. It never worked and obviously nobody is going to change that. To bad!

**Comment by codemanyak** [comment]
@StrandedAlien 
Your complaint is a very rigorous and fundamental one. "Super simple source code" is not a very precise qualification, either.
What exactly has never worked? In order to make somebody change this it would certainly help if you could provide some more specific expamples of failure.
