### ISSUE TITLE
Save state of diagram in Structorizer is wrong when loaded from Arranger

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#109]
When Arranger opens a diagram in Structorizer, the "Save" state is unsaved. 
Pushing the Save button doesn't toogle the saved state either in this scene.
Very noisy while in Debugging with a lot of subroutines loaded.

**Comment by codemanyak** [comment]
That's why I had reopened issue #103. Fix had been ready. (I just waited for some more issues or an external bug report like yours to instigate the next version.)

**Comment by codemanyak** [comment]
Fix available at bugfix3.23 branch.

**Comment by codemanyak** [comment]
@elemhsb: New version is online. Please test and signal your ok to close the issue (if you find it working acceptably).

**Comment by elemhsb** [comment]
Fixed in 3.23-14 perfectly.
