### ISSUE TITLE
Export of an empty Instruction containing only a comment doesn't work

### ISSUE THREAD

**Issue by bersetm** [fesch/Structorizer.Desktop#1118]
Export/Code preview in Pascal/Delphi works fine:

![image](https://github.com/fesch/Structorizer.Desktop/assets/84186052/86f46460-c4a4-4687-9e2f-07c3758e36a4)

But Export/Code preview in C, the comment of the empty Instruction doesn't appear:

![image](https://github.com/fesch/Structorizer.Desktop/assets/84186052/9dae590a-dc84-439c-89d0-abd8abcf50a7)

Here is what I mean by an "empty Instruction with a comment":

![image](https://github.com/fesch/Structorizer.Desktop/assets/84186052/70153f79-f437-4f7e-a1d2-9e7f036cab4e)

To reproduce the problem: create the same diagram as me, save it, close Structorizer, open the diagram.

Problem with Export to "C", "C#", "C++", "Java", "Javascript", but not to all other languages.

Thank you for considering my comment,
Best Regards

**Comment by codemanyak** [comment]
Thanks for your report. The fix will be integrated in the next version (3.32-15).
