### ISSUE TITLE
Structorizer tells it can't start without at least java 11, though Java 21 is installed

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#1124]
I installed Java several times but structorizer still tells me it can't start without at least java 11....

_Originally posted by @Manoroc1 in https://github.com/fesch/Structorizer.Desktop/discussions/1106#discussioncomment-8165681_

**Comment by codemanyak** [comment]
@Manoroc1 
I'd like to ask you to check the existence (and contents) of the registry keys specified in issue #1100 and for the content of the environment variable `JAVA_HOME`.

**Comment by Manoroc1** [comment]
i have no clue what you want me to do

**Comment by Manoroc1** [comment]
C:\Users\fabrk>echo %JAVA_HOME%
%JAVA_HOME%
thats what console gives out, and if i enter the other things there it tells me it cant find the path.

**Comment by Manoroc1** [comment]
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_401
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Plug-in\11.401.2
Computer\HKComputer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Web Start Caps\11.401.2EY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Web Start\11.401.2
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\21.0.2

**Comment by Manoroc1** [comment]
I just uninstalled java 8 and it worked 😆
Ty alot
