### ISSUE TITLE
Undo / redo during diagram execution is to be prevented

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#114]
It is possible to press the undo or redo button during execution (e. g. when execution is paused). As a consequence, on continuing execution the executor will work on a zombie diagram - which still works but without highlighting, active breakpoint control etc. This is due to the fact that undoing or redoing replaces the current diagram with a stashed copy while executor still refers to the (now invisible) original diagram.
Two options seem sensible to prevent this from happening:
1. Undo and redo buttons (and corresponding menu, hot keys etc.) will be disabled during execution (no regard whether execution being paused or not).
2. On pressing an undo or redo button the user is to be asked whether they want to abort execution or to cancel he undo/redo request.

I think, in order to keep it as simple as possible, option 1 is good enough.

In contrast, the user is not necessarily to be prevented from doing changes in the diagram. Though these will add entries to the undo stack, the diagram will not lose its identity. (This might be different, of course, if elements on the active execution path are moved around, thus compromising the execution trace.)

**Comment by fesch** [comment]
... so finally the "diagram" must also be disabled ....

**Comment by codemanyak** [comment]
...meaning what exactly? The entire Diagram menu?

**Comment by fesch** [comment]
No, I meant the diagram itself. Something to prevent drag & drop while the execution is running.

**Comment by codemanyak** [comment]
I agree. No dragging and dropping. It won't be many editing options left to the user, on deeper introspection what might harm execution consistency. At first glance, editing text or comments shouldn't be a problem in paused mode. But then, regarding loops: some parts of the control already reside on the stack in pre-evaluated form.
So, all elements with "waited" flag (the pale yellowish ones on execution) should better be protected against editing.
And, additionally, a currently executed Root should not be replaceable by loading or doubl-clicking another in Arranger. At least the dialog box mentioned above should pop up in such cases - either execution must be stopped or the intended activity must be cancelled.

**Comment by codemanyak** [comment]
Bugfix available in bugfix3.23 branch

**Comment by codemanyak** [comment]
Closed in advance of version 3.23-15

**Comment by codemanyak** [comment]
The check whether an element should be editable during execution wasn't consistent and a transmutation of elements being part of a sequence with pending execution had still not been prevented.

**Comment by codemanyak** [comment]
New fix available in bugfix3.25 branch.
