### ISSUE TITLE
Java version error on Debian

### ISSUE THREAD

**Issue by VANN-Universal** [fesch/Structorizer.Desktop#1166]
I installed Structurizer using the latest .deb package (Version 3.32-21) on my Debian 12 system.
When running the program, I get the following error:
![***Java runtime environment 23-ea not suited to start Structorizer! We need Java 11 at least.](https://github.com/fesch/Structorizer.Desktop/assets/112238565/cd2d4206-5464-4ea4-b430-022c72dfbb73)

This is the console output:
```
/usr/bin/structorizer: 44: [: Illegal number: 23-ea
/usr/bin/structorizer: 50: [: Illegal number: 23-ea
*** Java runtime environment 23-ea not suited to start Structorizer! We need Java 11 at least.
Mai 14, 2024 11:45:31 AM Structorizer main
SCHWERWIEGEND: *** Java runtime environment 23-ea not suited to start Structorizer! We need Java 11 at least.
```

I assume that 23-ea (Early-Access) could not be interpreted as valid version number to compare it to 11.

**Comment by fesch** [comment]
probably ...

**Comment by codemanyak** [comment]
Indeed the initial self-test (#1100) of Structorizer fails to decipher the version number, which is due to the hyphen in the version string. Structorizer expects only dot-separated numbers. We may have to fix this in the code,

**Comment by codemanyak** [comment]
The workaround was prepared and is ready for delivery.
