### ISSUE TITLE
How is the .deb file build - missing scripts/files in the repo?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#1169]
I've only found the version.deb.txt, but nothing that references it, nor the normal Debian control files.
As the release contains a .deb file there are likely scripts to create it, but they may be missing ion the repo.

This relates to #676 as well.

**Comment by fesch** [comment]
As my build script contains A LOT of sensible data, it is of course NOT contained in the repo. 

- Sorry -

**Comment by GitMensch** [comment]
Maybe it is possible to put the sensible data to environment variables and move the actual processing into a new shell script?
That way your personal processing is not changed and we have the "processing script" available, so could be executed locally when the variables are setup.
