### ISSUE TITLE
Structorizer doesn't start

### ISSUE THREAD

**Issue by jugendhacker** [fesch/Structorizer.Desktop#120]
I have Windows 8.1 and Structorizer won't start!!!

**Comment by fesch** [comment]
Did you get any error message?
Try to run it from the command line to intercept and view console error messages.

**Comment by jugendhacker** [comment]
The Programm loads but thenit didn't do anything!

**Comment by fesch** [comment]
Try to run it from the command line to intercept and view console error messages.

**Comment by jugendhacker** [comment]
Ther are no error messages

**Comment by fesch** [comment]
did you launch it with 

`java -jar Structorizer.app/Contents/Resources/Java/Structorizer.jar`

?

**Comment by jugendhacker** [comment]
The error Message is:
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

**Comment by fesch** [comment]
Fine ... so please reinstall the latest JDK, that should solve the problem.

**Comment by jugendhacker** [comment]
Ok thank you!
