### ISSUE TITLE
Can't add statement on else-side

### ISSUE THREAD

**Issue by IrisLuc** [fesch/Structorizer.Desktop#122]
Structorizer opens the condition-element instead of the instruction-element when I double click to add an instruction on the else-side in an if-block

**Comment by MarcRaey** [comment]
I have the same problem since yesterday afternoon. (Start problem 2016-03-04.) It has been reported to my study coach.

**Comment by fesch** [comment]
I can reproduce this an noticed, that on the left side of the text, it works, but from the starting point of the text to the right, it does not:

![structorizer 3 23-15](https://cloud.githubusercontent.com/assets/1027354/13553142/dadd0530-e37e-11e5-902f-1e376b2c9d96.jpg)

**Comment by MarcRaey** [comment]
Dear Bob Fisch 
I have tried instantly after receiving your mail. 
Your sollution, mentioned as below, does not work at my pc. 
First started from started from Java TM Web start. 
I also tried to download the windows version several times. This is not possible either. 
  
Thank you anyway for trying to help. 
  
Kind regards 
  
Marc 
  

----- Oorspronkelijk bericht -----

Van: "Bob Fisch" <notifications@github.com> 
Aan: "fesch/Structorizer.Desktop" <Structorizer.Desktop@noreply.github.com> 
Cc: "Marc Raeymaekers" <marc.raeymaekers@telenet.be> 
Verzonden: Zondag 6 maart 2016 09:36:42 
Onderwerp: Re: [Structorizer.Desktop] Can't add statement on else-side (#122) 



I can reproduce this an noticed, that on the left side of the text, it works, but from the starting point of the text to the right, it does not:

**Comment by fesch** [comment]
More test cases.
![structorizer 3 23-15 - test nsd](https://cloud.githubusercontent.com/assets/1027354/13553208/77c10b42-e381-11e5-8981-68cda97bb023.jpg)
Here I can't select the green element at all!

![structorizer 3 23-15 - test nsd-1](https://cloud.githubusercontent.com/assets/1027354/13553212/88fdcb66-e381-11e5-8531-3c9cd05a6b6d.jpg)
If I remove the lower left instruction, I can select the green element again!

Very strange. @codemanyak : I think it has to do with the yOffset, no?

**Comment by codemanyak** [comment]
First of all: Sorry, I was offline last weekend.
No, it has nothing to do with the yOffset. Instead it is the xOffset, the issue only occurs when the "enlarge FALSE" option (on the Structure preferences dialog) is set. The old drawing preparation and selection mechanism had not had to take this setting into consideration. I overlooked that the new algorithm now has to.

**Comment by codemanyak** [comment]
Bugfix is prepared and may be delivered.

**Comment by fesch** [comment]
You are right ...

Why did I write "y" when thinking about "x" ?? Tzzz
