### ISSUE TITLE
Collection and visualisation of runtime data by Executor

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#124]
The work on the test coverage visualisation (issue #77) induced the idea of further useful runtime data that can be tracked and visualised by Executor: Total execution counter per element and instruction step load hierarchically associated to Elements.
This is the rough concept:
An execution counter is to be added to every very element, such that after a single run or a series of runs one might easily see, how often a certain instruction or other element was executed.
And a kind of histographic analysis is also sensible and proposed, showing how many steps the entire algorithm took in total and how the load is distributed among the elements (particularly the structured ones). This is practically an empirical abstract execution time model.
In runtime tracking mode, both count numbers (execution counter / operation load) might be written
to the upper right corner of any element, additionally a spectral colouring from deep blue (low count) to hot red (high count) may be used to visualize the hot spots and the lonesome places in the algorithms.
A choice iem (combo box) might select whether coverage oder which of the counting results (collected all in parallel) should be highlighted. The selection may be changed as long as the data haven't been cleared.
All this together with enhancement #77 could be of great help and instructiveness.

**Comment by codemanyak** [comment]
A preview:
1. Colouring (of a recursive QuickSort demo) by execution count per element:
![arrangerexeccount1klein](https://cloud.githubusercontent.com/assets/15326471/13728112/14444638-e90d-11e5-994e-be7f3b60f42f.png)
2. Colouring of the same set of routines after the same run) by number of instruction steps per element
![arrangerstepcountlogklein](https://cloud.githubusercontent.com/assets/15326471/13728122/b335dbda-e90d-11e5-9aab-352352ce8a21.png)

**Comment by fesch** [comment]
nice :-)

**Comment by codemanyak** [comment]
Prototype is ready and the code can be downloaded from [codemanyak/Structorizer.Desktop](https://github.com/codemanyak/Structorizer.Desktop/archive/master.zip) for testing and evaluation.

**Comment by codemanyak** [comment]
Already available with version 3.24-01
