### ISSUE TITLE
Windows: structorizer.exe withholds Java launching errors from user

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#126]
Structorizer sometimes won't start properly because of missing Java installation or incompatible release requirements. Under Windows, the respective error messages are withheld from the user by the wrapper program structorizer.exe. After the short popping up of the splash screen the application just dies without any comment or hint. This is not only annoying but may puzzle and even repel users.
It then requires explicitly to write down the Java launching command from structorizer.sh to the console command line and to have a look what went wrong.
Only the most adamant users will raise an issue (cf. issue #120), read the User Guide, or try on their own. Many may just discard Structorizer as apparently dysfunctional.
The wrapper should be enhanced to fetch the system error message and bring it up in a message box.

**Comment by fesch** [comment]
The wrapper is actually written in Delphi 6 PE, so some question arise ...
- Does that sill exist?
- Do I really need to start Windows right now?

I would prefer to use some ready made wrapper. I am sure some will exist. We just need to find them ...

**Comment by codemanyak** [comment]
What did you mean with "Does it still exist?" Delphi 6?
I haven't looked for readymade wrappers yet. Or say I found some mentioned e.g. Launch4j, but haven't got any experience with them.
And I thought, that the wrapper was only used for Windows such that to me it didn't seem to be a big deal to write it - is it really supposed to be so complicated what the wrapper does? (I think besides bringing up that splash screen, establishing the file type association and launching the Java application it's just the proper reporting of problems, isn't it?) 
If you wrote it in Delphi code, might I have a look at it to see whether it's feasible to convert it to Visual C++ or C# or the like? If the wrappe should also be used for OS/X then, of course, things are different.
Of course it's not so urgent to do something about it. I just thought it might be as easy as to add some lines and good.

**Comment by codemanyak** [comment]
Having had a look at what launchers like Launch4J are able to configure and manage - even the acquisition of the proper JRE -, I do agree it might be sensible not to write an own one in 10 min.

**Comment by fesch** [comment]
Probably the new packaged version 3.24-06 should solve this issue too, as it uses Launch4J as Windows JAR launcher ...

**Comment by codemanyak** [comment]
Yes, Launch4J solved this issue. Thank you.
