### ISSUE TITLE
With "CDE/Motif" Look & Feel, Cut and Paste don't work in the Element editor 

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#127]
I received this complaint by Hubert Klöser via mail today (referring to version 3.23-14):

1. in den Eingabefenstern (z.B. einzugebender Text und einzugebender
Komentar) ist kein Cut and Paste möglich.

Transl.: In the text input areas of the element editor (element text and comment), Cut and Paste doesn't work.

**Comment by codemanyak** [comment]
I tried to cut and paste in an element editor:
- [x] Windows 7: all keybord-based mechanisms (Ctrl-X / Shift-Del, Ctrl-C / Ctrl-Ins, Ctrl-V / Shift-Ins) work flawlessly.
- [ ] Windows 10: ?
- [x] Linux: All works (tested with OpenSuSe in a VirtualBox under Windows 7)
- [ ] Apple: ?.

**Comment by fesch** [comment]
No problem on my Mac ...

**Comment by codemanyak** [comment]
Situation has cleared up.
The described effect only occurs with one look & feel setting. The issue originator (H. Krösel) reported it happened only with one of the Look & Feel setings - and I can back this: it's "CDE/Motif".
Somehow it makes sense because UNIX / Motif adhere to pretty different ways to do things, see e.g. [Copying or Cutting and Pasting Selected Text in UNIX Environments](http://support.sas.com/documentation/cdl/en/hostunx/61879/HTML/default/cutnpast.htm). The hot keys well known from Windows and Linux don't play a significant role there and without an "edit menu" you are lost, it seems.
H. Krösel affirmed that under Windows 10 all other Looks still work fine.
So, for the moment there is no need for urgent action. It will let this issue open, however, for later investigation, whether a context menu might help here.
Also support of undoing and redoing within the JTextAreas would improve the user experience.

**Comment by codemanyak** [comment]
For version 3.24-05, at least a specific hack is implemented in the export option dialog such that the OK button would be visible in "CDE/Motif" look and feel, too, at least.

**Comment by codemanyak** [comment]
For version 3.24-14, the explicit setting of the size of the Export Option Dialog as causing lacking  visibility of e.g. the "OK" butten with some Looks and Feels was simply dropped such that the pack() method will now care for the appropriate size.

**Comment by codemanyak** [comment]
With CDE/Motif look and feel the following hot keys definitely work inside the element editor (tested both under Windows 7 and OpenSuSe Linux):

- Ctrl-Ins to copy
- Shift-Ins to paste
- Shift-Del to cut
