### ISSUE TITLE
Printing of diagrams including the element comments would be welcome

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#128]
I received this enhancement proposal by Hubert Klöser via mail today:

"2. Ein Ausdruck der Kommentare zu den einzelnen Elementen wäre
wünschenswert, eventuell als nummerierte Fußnote oder kleingedruckt im
Element."

The proposed variants are: either to add them as footnotes or to integrate them in the respective element with a smaller font.

**Comment by codemanyak** [comment]
The proposal isn't bad, the question is just, what kinds of output are to be involved? As there are:
- [ ] Printing?
- [ ] Export as PNG (and EMF, WMF, PDF, SVG)?
- [ ] Display (as kind of preview)?

**Comment by codemanyak** [comment]
Hubert Klöser wrote:
"Wenn Sie mich so fragen, dann wäre natürlich in beiden Ausgabedrucken die Möglichkeit toll. Mir persönlich würde die Druckenfunktion aber reichen."
(_If you ask me this way then of course it would be great to have that possibility_ [_to integrate the comments_] _in both export and printing. But for me personally the printing function would be sufficient._)
Again, the easest way would be a general option to include the comments in all diagram drawing independent of the target device or file.

**Comment by reks99** [comment]
Hi.

I do it with to exports one with the shown texts and one with the shown comments (after switching betweent text and comments). So I get the identical structure with different texts.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Solution prepared for next dawning release.

**Comment by codemanyak** [comment]
Some remarks:
In Alternatives and Case selections only the first line of the respective comment will be drawn lest the layout should be compromised due to the lacking space.
The new mode "Comments plus text" overrides mode "Switch text/comments". Even the menu item for the latter will be disabled while mode "Comments plus text" is selected, though the previous setting remains preserved.
Here are some previews:
![datedifference-6](https://cloud.githubusercontent.com/assets/15326471/17278595/f7f1e694-5760-11e6-8c22-bc1dc56935f1.png)
![daysincey1m1d1-3](https://cloud.githubusercontent.com/assets/15326471/17278597/061d3084-5761-11e6-8e59-d2515c7620fd.png)
![daysofmonth-2](https://cloud.githubusercontent.com/assets/15326471/17278599/0e0211ca-5761-11e6-9caa-2f521a17a35d.png)
![isleapyear-1](https://cloud.githubusercontent.com/assets/15326471/17278600/13bd113c-5761-11e6-8648-febdecaab16a.png)

**Comment by codemanyak** [comment]
The presentation of comments within the triangular parts of Alternatives and Case selections induces enormous enlargement of these elements as shown in the following example:
![testissue128a-2pure](https://user-images.githubusercontent.com/15326471/31861708-140aa3c0-b732-11e7-9375-3bcbe4b54377.png)
![testissue128a-2c t](https://user-images.githubusercontent.com/15326471/31861716-29aefcf8-b732-11e7-9b3c-ff97a59793ea.png)
It would be more sensible if the comment were positioned in a small rectangular extra space on top of the triangle but without separating line:
![testissue128a-2lean](https://user-images.githubusercontent.com/15326471/31861725-5a179300-b732-11e7-8c74-84fec5144195.png)

**Comment by codemanyak** [comment]
Specified modification effectuated. With CASE elements, it migt not necessarily save space but usually improves outcome.
Example before:
![testissue128b-1ugly](https://user-images.githubusercontent.com/15326471/31863412-ae1ccd92-b74d-11e7-94f2-cbe8b8d303ee.png)

Example after the fix:
![testissue128b-1lean](https://user-images.githubusercontent.com/15326471/31863414-b9434106-b74d-11e7-8a58-c3c7e1f1c26e.png)

**Comment by codemanyak** [comment]
A lacking readjustment of the scroll area on toggling the mode (it took e.g. a click into the diagram to force a complete redraw) is going to be fixed with version 3.30-14.
