### ISSUE TITLE
Function key for toggle text/comment view

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#142]
Hi,

working with structorizer I like to have the two views i.e. the text (program) and the comment view. So a more descriptive description of the program can be seen in commet view.

To toggle the view one have to move with the mouse to the menue and click on the wanted entry. It can be faster to have a function key to toggle the view.

So I ask to improve strutorizer this way.

Many thanks 
Rolf

**Comment by codemanyak** [comment]
Do you have a mnemonic proposal for the key combination?

**Comment by reks99** [comment]
@codemanyak Hi Kay,

I prefer a function key - perhaps F5 it is not in use.

**Comment by codemanyak** [comment]
Function keys F5 through F13 are already associated to the insertion of certain element types, have a look at the sub-menu Diagram -> Add -> After. As many users may have been accustomed to this mapping, I'm not the one to change it.

**Comment by reks99** [comment]
@codemanyak Hi Kay,

in 3.24-4 in the !diagram! menu is no submenu "add" - only the context menu has an "add before/after" entry. But non of the elements have shown a assoziated function key.
Only the function keys F4 (Highlight variables) and F5 (Analyze structogram) are shown in the "diagram" menu

Fine Regards

**Comment by reks99** [comment]
@codemanyak Hi Kay

perhaps we can use a shifted function key for the toggle?
Rolf

**Comment by codemanyak** [comment]
> in 3.24-4 in the !diagram! menu is no submenu "add" - only the context menu has an "add before/after" entry. But non of the elements have shown a assoziated function key.
> Only the function keys F4 (Highlight variables) and F5 (Analyze structogram) are shown in the "diagram" menu

Oh, the menu still exists. In German it is "Diagramme -> Hinzufügen -> 
Danach" (it is only enabled while an element is selected).

**Comment by codemanyak** [comment]
> perhaps we can use a shifted function key for the toggle?

Sure we can.

**Comment by reks99** [comment]
@codemanyak Hi Kay.

First I have to say excuse me. I didn't found the menue because there was no nsd-element selected, just the main programm. After selecting the first element, the menu was activated - at least it's logical.

About key combination for switch between comments and text I think Alt-v (migth stand for "alternativ view") or Alt-s (might stand for "switch view")
Btw. the shifted keycodes of the function key can be assigned to insert nsd-elements before the current - so the logic of the function keys actin is more logic (at least for me).
Fine regards
Rolf

**Comment by codemanyak** [comment]
Am 01.04.2016 um 12:20 schrieb rolf schmidt:
> About key combination for switch between comments and text I think Alt-v (migth stand for "alternativ view") or Alt-s (might stand for "switch view")
> Btw. the shifted keycodes of the function key can be assigned to insert nsd-elements before the current - so the logic of the function keys actin is more logic (at least for me).

I'm preparing Ctr-Alt-V.

By the way, my problems with accelerator keys are:
  * I take my time to remember them and quickly forget them.
  * If you are working with many tools in parallel or alternatingly, you 
tend to mix them up.
  * The more accelerators there are the higher the likelihood to fire 
one of them unwillingly; you see something change but have no damned 
idea what induced it and how to return to normal mode.

This can really be scaring for beginners. Therefore I often say less is 
more. A menu has at least a reproducible logic (or should have).

**Comment by reks99** [comment]
@codemanyak Hi Kay,

> By the way, my problems with accelerator keys are: * I take my time to remember them and quickly forget them. * If you are working with many tools in parallel or alternatingly, you tend to mix them up. * The more accelerators there are the higher the likelihood to fire one of them unwillingly; you see something change but have no damned idea what induced it and how to return to normal mode. 

Ok, I have similar problems, but then I don't understand why the function key for insert an element are in use. You have to learn them also or ignore them.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Oh, the function keys had been in place before I joined the project, and they offer few risk. It's relatively little likely to push them accidently. But the Ctrl-, Shift- and Alt combinations with letter keys may pretty easily be fired without intension on rapid typing. But well, no risk - no fun...
Never mind, my comment was no rejection of your proposal, just a personal opinion reminding that accelerators should be defined with care, not inflationary.

**Comment by codemanyak** [comment]
Function key Ctrl-Alt-V is established by version 3.24-05
