### ISSUE TITLE
Timeout for the popup text or comments

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#143]
Hi,
when I would modify a statment with a comment, the comment pops up when the mouse is over and the pop up window stays in front even when the input dialog is shown. So it will be nice, if the popup clears when the input dialog will be open - perhaps with a timeout.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Both are good ideas. The editor dependecy seems easy to implement. I will look for the timeout implementation to compare both ideas.
Of course, you could drag the editor away from the sticky popup but not actually a user-friendly behaviour.

**Comment by codemanyak** [comment]
I solved the problem by hiding the popup as soon as an element editor or a file selection dialog is opened. Fix will be available with 3.24-05.

**Comment by codemanyak** [comment]
Version 3.28-03 will apply the missing fix for the PrintPreview as well.
