### ISSUE TITLE
New export option "No conversion of instruction / expression content"

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#144]
Structorizer has gained a lot of cleverness to convert the contents of algorithmic elements on generating source code from a designed algorithm. But this works under the pre-requisite that the element texts adhere to a somewhat general concept of HLL syntax.
If a user fills in very target-specific code, however, particularly if she or he writes shell-script instructions, the syntactical paradigms of which are simply incompatible to those of HLL, then of course Structorizer wouldn't cope because any conversion attempt (done under false assumptions) will necessarily spoil the export.
For such cases, a new export option is proposed, which switches off all language-specific conversion and just translates the control structures into the corresponding syntactic constructs but leaves the element texts unchanged.
This is the logical consequence from issues like #135.

**Comment by reks99** [comment]
Hi Kay,
It seems that the upload has worked now.
Fine Regards
Rolf

**Comment by reks99** [comment]
@codemanyak  Hi Kay,

Btw the code exported from 3.24-3 was better in the case of handling variables inside of messages.
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99, on 2016-03-31, you wrote:
> Btw the code exported from 3.24-3 was better in the case of handling variables inside of messages.

Could you please specify in more detail what this is supposed to mean? 
What is a "message" in your vocabulary?

**Comment by codemanyak** [comment]
@reks99, in your previous comment you wrote:
> As I wrote in another comment, I don't think that a user of structorizer will generate source code in any offert language. So he/she will allways use partly syntactical elements of his prefered language.

I don't follow your argument. At least it's not true for me. I teach the students first to think about an algorithm and then about the possible target language. And from my point of view it's important to show that the source code of any target language is just a translation of the algorithm in mind into a specific dialect. Therefore, I'm not ready to give up the idea of maximum source-code-independence.
That means, of course, that for purposes of newcomers' ease, of executability, of diversity of code export etc., Structorizer will have to continue accepting a very simple, easy-to-understand, self-explaining, basic kind of pseudo HLL syntax, being some "greatest common divisor" of usual programming languages.
I might say, the majority of users will spread among the following two extremes:

1. Newbies, having few or no programming experience at all. For them all the syntactical opportuinties and traps of advanced programming languages are a repelling and frustrating nightmare (be that C or bash), absorbing most of their concentration they would need for the algorithm design.
2. Experienced programmers who just want to document their elaborated program by means of an NSD. They will usually hate to do things twice, so they might accept to design their algorithm in Structorizer and then just export it as is - without interference of a well-meaning but desperate tool inbetween. For them, the reverse mechanism, i.e. is to import source code into structorizer might even be more interesting. By now this works only for Pascal. Unfortunately, this hypothetic feature won't ever be completely possible, either. Particularly because

  - only subsets of common programming languages could be mastered within a lifetime and
  - some algorithmic "artistics" cannot be mapped into the element structure of an NSD.

> A different approch could be to ask the user, before coding which language should be exported. Than the export option allways exports (only) for this language (btw than also a shortcut can be used to generate the code - no more mouse fiddling). May be there is a possibility to switch the export language later.

Of course, your proposal also offers the theoretical chance of some undoubted advantages: If the target source code would be known in adavnce, e.g. a language-specific executor could support the specific code in an optimal way. But this would try to make Structorizer a kind of universal IDE! Something like Eclipse or Netbeans (or VisualStudio), just with additional NSD support. No, thanks. Remember how lost a beginner feels at first contact with one of those great and mighty tools, without a clue what to do and where to start. And it's simply not feasible for one or two spare-time programmers.
And no, with this approach, the "possibility to switch the export language later" would be gone. You cannot hope to translate a Java program that makes maximum use of Java-specific concepts into, say, Pascal or Perl. And vice versa.
It would spoil all, actually. Read the Readme, please, to remember what the idea of this project was.

I think, the option to export all as is, would meet the needs of user extreme 2 as well as possible. We won't get much closer.

**Comment by reks99** [comment]
@codemanyak Hi Kay,

>  Btw the code exported from 3.24-3 was better in the case of handling variables inside of messages.
Could you please specify in more detail what this is supposed to mean?
What is a "message" in your vocabulary? Can you give an example in comparison?

With message I mean "echo Hello $VAR ...". As fare as I remember 3.24-3 did it the right way. But I have no more 3.24-3 version here.

HTH
Rolf

**Comment by reks99** [comment]
@codemanyak Hi Kay,
I haven't in mind to use structorizer as a tool to teach algorithms. I always use the programm to solve problems and to find a suitable solution - so I have to think in the languages I am able to code with.

So you are right in your situation - and indeed it is nice to compare different language outputs from the same algorithm - in learning environments.

Fine regards
Rolf

**Comment by codemanyak** [comment]
> With message I mean "echo Hello $VAR ...". As far as I remember 3.24-3 did it the right way. But I have no more 3.24-3 version here.

Well, 3.24-03 didn't put additional quotes around such composed 
expressions. I'll have a look what other artifact I wanted to avoid by 
this additional quoting...

It is very likely now that mending one issue spoils another aspect. 
Means we'll have to find some viable compromises.

**Comment by codemanyak** [comment]
Option is implemented and will be available with version 3.24-05
@fesch I accidently performed the merge to th master branch myself already. You may release the version 3.24-05, I think
@reks99 Please have a look if the result of an export of a pure shell algorithm (shell syntax) with the new option is okay.

**Comment by fesch** [comment]
no problem ;-)

**Comment by codemanyak** [comment]
I don't see strong objections, so I close this issue now, based on 3.24-05.
