### ISSUE TITLE
new export option - charset to use

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#149]
Hi,

is it possible to export source code with a special charset. 
Another option can add in the export config dialog, where a charset can be selected. This charset is used for the export of code.

When look in the nsd file, the text has Umlaute in utf-8, but the exported code has them in ISO8859. Why?
Also the export to C-code is in ISO8859.

Fine regards.
Rolf

**Comment by codemanyak** [comment]
It is on my TO DO list. I just hadn't enough time to present a solution with the recent version. It's not forgotten though.

**Comment by codemanyak** [comment]
Implementation was easier than expected, the interface had already been in place, thanks to Bob. I had just to pimp up the export option dialog a little. It will look this way by the next published version:

![exportoptionsdialog](https://cloud.githubusercontent.com/assets/15326471/14262694/04e78694-fab7-11e5-8108-7eff2745f7e9.png)

**Comment by fesch** [comment]
Cool :-)

**Comment by codemanyak** [comment]
Rolled out with version 3.24-06
