### ISSUE TITLE
export to C uses wrong comment method

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#150]
Hi,

The C language itself uses /* */ as markers for comments only. C++ uses // as an alternative method for comments.
Because newer C compiler are C++ compilers with different behavior if called with a c-file. So they may accept the //-comment syntax.

Fine regards
Rolf

**Comment by codemanyak** [comment]
I had checked that before. ANSI-C99 standard allows // comments (see section 6.4.9).

**Comment by codemanyak** [comment]
Perhaps I should have been more precise. I'm referring to the ANCI C99 n1256 draft (ISO/IEC 9899:TC3).

**Comment by codemanyak** [comment]
Addendum. If the type of comments actually cuases a problem with some C compiler, it could easily change the comment style for the C Generator. In this case it would be nice if you could name us the compiler that doesn't accept the line comments.
