### ISSUE TITLE
Enhancement: Export parallel elements in bash

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#153]
Hi,
when I set up a paralllel element (yes, I read, that it is not really supported, because there is no possibility to simulate it) :

1. nothing at all is exported, even with the new option #144 
2. it could be exported with an &-char behind to let it run in background.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Yes, currently there is no export strategy for Parallel elements in BASH 
export.
Of course I know how to start a background command.
I just hadn't worked out the solution for the synchronisation problem 
(we need the parent process to wait for the termination of all the 
parallel subprocesses) and later forgot to accomplish the Generator.

**Comment by reks99** [comment]
@codemanyak Hi Kay,

usually the shell kann wait for termiation of a child process, but with "nohup programm &" the program will continue to run even when the shell terminats.

But I think it is ok, if the elements of a parallel column are enclosed in parentheses followed by an ampersand.

Fine regards
Rolf

**Comment by codemanyak** [comment]
I prepared a fix that would translate the shown algorithm...
![testissue153a](https://cloud.githubusercontent.com/assets/15326471/14282296/0599ec4e-fb3e-11e5-9f53-d9bdc3b0627f.png)

... into the following code:
```
#!/bin/bash

# (generated by Structorizer 3.24-06dev) 


# TODO: Check and revise the syntax of all expressions! 

# Prompt manually added
echo "Enter a number "
read nummer
# This is the ultimate test for Parallel export 
# ========================================================== 
# ================= START PARALLEL SECTION ================= 
# ========================================================== 
pids52c2e8dc=""
{
 nameA="Anton"
 codeA=$(( ${nummer} * 1 ))
 echo ${nameA} ${codeA}
} &
pids52c2e8dc="${pids52c2e8dc} $!"
{
 nameB="Berta"
 codeB=$(( ${nummer} * 2 ))
 echo ${nameB} ${codeB}
} &
pids52c2e8dc="${pids52c2e8dc} $!"
{
 nameC="Cäsar"
 codeC=$(( ${nummer} * 3 ))
 echo ${nameC} ${codeC}
} &
pids52c2e8dc="${pids52c2e8dc} $!"
wait ${pids52c2e8dc}
# ========================================================== 
# ================== END PARALLEL SECTION ================== 
# ========================================================== 
echo "Fertig mit der Welt!"
```

**Comment by reks99** [comment]
@codemanyak Hi Kay.

It looks nice except:
- to group commands in a shell normal parentheses are uset at least to call a subshell.
- when run commands in background the pid is generated by the kernel so it is something like a return code when starting the background process. Perhaps the pid can be assigned to a variable. So a call can/shall look like

`currPID=(command_1`
` command_2`
` command_3) &`

But I don't know how this fits in your parser structur or your HLL syntax.

Fine regards
Rolf

**Comment by codemanyak** [comment]
The direct assignment of the pid is what exactly does not work. Instead you would obtain the result of he last command. Therefore $! is used, where the shell parks the pid of the most recently created process.
To group commands, both ( ) and { } work, the former causing a subshell to run, the latter not. Could you briefly explain why it would be better to use a subshell here? Well, I could think of separate name spaces as an advantage. But this would possibly require Structorizer to analyse what variables must be exported to the subshells, right?

> But I don't know how this fits in your parser structur or your HLL syntax.

The HLL syntax hasn't anything to do with it. All I do here is structure translation whithout the Structorizer user having to know of. No source code adaptations are necessary. Henec the parser isn't involved, either.

(As always, however, recursive syntactic structures - which are quite normal in HLL syntax - may cause enormous problems in a shell script translation. To give an example, in theory you might nest expressions and built-in function calls arbitrarily deep in HLL, in a shell script, you may rapidly get to the situation that you can't nest a backward quoted command execution in another. Even if it worked one level, by, say, using escape sequences then you must be aware of it and will eventually be lost the next level, nevertheless. This makes shell syntax so awful.)

**Comment by reks99** [comment]
@codemanyak Hi Kay.

> To group commands, both ( ) and { } work, the former causing a subshell to run, the latter not. Could you briefly explain why it would be better to use a subshell here? 

I tested `{ ls -Rl / | sort } &` and the shell complains with PS2 i.e. the command isn't complet. When I write `( ls -Rl / | sort ) &` it works as expected. Further on I/O redirection behind the closing parentheses  `( ls -Rl | sort) > /dev/null &` redirects the output of every enclosed program. So it's seen as one program.

I have to search, if the returned PID is the PID of the subshell with the included commands - as I thought. 

Fine regards
Rolf

**Comment by codemanyak** [comment]
Whatever you like. I successfully made a hotfix to replace the braces by parentheses before Bob could deliver it.

**Comment by reks99** [comment]
@codemanyak  Hi Kay.

> But this would possibly require Structorizer to analyse what variables must be exported to the subshells, right?

I've never seen a construct that the sub shell uses variables, but you are right if someone will do he/she should export the variable by himself.

Fine regards
Rolf

**Comment by reks99** [comment]
@codemanyak Hi Kay.

You are fast and great and you make everybody a liar who say "open source is unsupported software" as I heard for years.

I'm curious about then new version
Many thanks for yor work.
Rolf

**Comment by reks99** [comment]
@codemanyak Hi Kay,

> (As always, however, recursive syntactic structures - which are quite normal in HLL syntax - may cause enormous problems in a shell script translation. To give an example, in theory you might nest expressions and built-in function calls arbitrarily deep in HLL; in a shell script, however, you may rapidly get to the situation that you can't nest a backward quoted command execution in another. Even if it worked one level, by, say, using escape sequences then you must be aware of it and will eventually be lost the next level, nevertheless. This makes shell syntax so awful.)

But you know, that all recursive structures can be redesigned to loops - not allway that elegant and not allways describe the nature of the problem or solution.

And the main idea of shell is an extended batch language.

Fine regards
Rolf

**Comment by codemanyak** [comment]
> But you know, that all recursive structures can be redesigned to loops - not allway that elegant and not allways describe the nature of the problem or solution.

Maybe you got me slightly wrong. Of course all recursive algorithms can be resolved or rewritten (not always that easy, think of traversing a tree), but is the Structorizer generator responsible for that? (The generators already do a lot of great work to translate array initialisations and loop exits to languages that don't support it directly. But towards another HLL there at least clear and recursively defined ways to do this.)
But what I was talking about were recursive syntax definitions, the core of all context-free and context-sensitive languages. To reformulate e.g. an expression like `max(a + pow(6*7.9, sin(5)) / (abs(b) - sqrt(sqr(a) + sqr(b))), exp(c - cos(d), 1.0 / b))` into a "flat" text you would have to introduce a lot of variables and change the code dramatically. The construction given above may not be very readable (nor likely) but would practically be impossible in Shell (except perhaps in an (( )) island). Okay, real numbers aren't supported anyway. But then function calls are actually commands in shell, their nesting is rather difficult and requires a lot of backward quotes, $( ), or other notations etc., each for a certain case, and there is no general and easy rule when to use what and how to combine it.

**Comment by codemanyak** [comment]
Version 3.24-06 has just been rolled out.
