### ISSUE TITLE
BUG: When open a NSD with a parallel element, the status line (with analyzer info) is not updated

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#154]
Hi,
I found, that the line at the bottom with the output of the analyzer is not updated, when another nsd with  a parallel element in its (main) body is loaded.

It seems that the analyzer has a problem with this element. For example the message "??? is not a valid name for a program or method!" is not removed.

Fine regards
Rolf

**Comment by codemanyak** [comment]
I cannot reproduce this effect. Would you please upload the algorithm (exported as PNG) that causes the Analyser to stall?

**Comment by reks99** [comment]
@codemanyak Hi Kay,

easiest way to see what I mean:
1. open structorizer - it shows progamname "???"
2. insert a parallel element
3. select program frame and give the program a new name
- now you can see, that the Line "??? is not a valid..." didn't disapear. Try it again without a parallel element and the Line "??? is not..." will be cleard.

HTH
Rolf

**Comment by fesch** [comment]
Can't confirm this for OSX

**Comment by codemanyak** [comment]
No, I'm sorry. I did what you described several times (on Windows). Even in switch text/comment mode. Still can't reproduce this effect.
Have you tried to restart Structorizer? Does this behaviour still occur?

**Comment by reks99** [comment]
@codemanyak Hi Kay,

It seems not to happen, if 10 parallel task may be assigned. But if you assign only one parallel task it is reproducable here in Linux Debian jessie

HTH
Rolf

**Comment by reks99** [comment]
[xyz-output.txt](https://github.com/fesch/Structorizer.Desktop/files/204580/xyz-output.txt)
![xyz](https://cloud.githubusercontent.com/assets/18035140/14284034/10636602-fb46-11e5-85c7-65c48ccd116d.png)
@codemanyak Hi Kay,

attached an image showing the problem an the output of the java-vm, when create the nsd. Perhaps you can find some helpful messages.

HTH
Rolf

**Comment by codemanyak** [comment]
Oh, interesting! Now I can reproduce it, but only after having added an instruction line to the Parallel element - as you did.

**Comment by fesch** [comment]
Still not reproducible on OSX ...

**Comment by codemanyak** [comment]
It happens if a Parallel thread contains more unknown variables than initialized ones. Then check 17 crashes (due to a mixed up variable reference), and the rest of the analysis isn't done.
Fix is prepared.

**Comment by codemanyak** [comment]
Fix is delivered with 3.24-06.
