### ISSUE TITLE
Enhancement or question: Instructions following a Jump element

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#161]
![exit](https://cloud.githubusercontent.com/assets/18035140/14433161/758153a2-000d-11e6-8938-c0183c5bf364.png)
Hi,
when an exit element is inserted IMHO no other element should be allowed to be inserted afterwards (in the same level) - or am I wrong?

See attached image - block "hhh" can't be executed anyway.

Fine regards
Rolf

**Comment by codemanyak** [comment]
I wouldn't hinder the user to write such a nonsense. The analyser might warn, however. This would be consistent with the way most IDEs handle such mistakes.

**Comment by reks99** [comment]
@codemanyak Hi Kay.

At least you are right - but as an assistant for learners it might be helpful.
Rolf

**Comment by codemanyak** [comment]
@reks99
> At least you are right - but as an assistant for learners it might be helpful.

Yes, but for this purpose an Analyser check should do - and is promised 
here. (Learners must also learn to read and interpret warnings.)
An unreachable instruction doesn't cause harm. Code beyond a FOREVER 
loop is also unreachable, just for instance. So are branches of 
alternatives with constant condition etc.

**Comment by reks99** [comment]
@codemanyak @fesch 
Hi kay, hi Bob.

Shall we close this issue?

Rolf

**Comment by codemanyak** [comment]
@reks99 Why do you ask US? It was you who raised the issue. The Analyser check is implemented and may be expected with the next version (3.24-07).

**Comment by codemanyak** [comment]
Just a remark: The implementations of #905, #979, and #1161 made the intentions of this issue fully effecive.
