### ISSUE TITLE
Enhancement: Tab around between the input fields of the Element editor

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#163]
Hi,
when working with Structorizer in the last, the "keyboard ready" version, I missed, that one can switch between the text input and the comment input field in the description dialogs.

It will be great to move through the (next) elements of a dialog with pressing the tab key - starting in the text field, next tab goes into comment field, next tab to break-point, next tab goes to the cancle button and the last tab jumps to the save button. Perhaps the next tab starts again in the first window.

The shift-tab option - to go back one element - is not really needed in this small dialogs - imho.
Perhaps the return key can fire the save button.

Fine regards and many thanks for the new version, which is great.
Rolf

**Comment by codemanyak** [comment]
Have you tried Ctrl-Tab? That's the key combination doing what you want. And Shift-Ctrl-Tab wanders backward.
The Tab key creates a tab character in the respective text input field (text or comment), which is sound in my eyes.

**Comment by reks99** [comment]
Hi Kay,

The (Shift)-Ctrl-Tab key combination didn't work for me, because it is reserved for switch the virtual screens.

At least I found no argument for a tab in a (modern) program language and in text formating in a nsd environment. Wanted Inserts are made by the export function.

Ok. I understand, that you see no reason to change the functionallity.

What about more posibilities to configure this (and other) keys?

Fine regards
Rolf

**Comment by codemanyak** [comment]
I will look after the opportunities to alter/configure this behaviour in Swing layouts.

**Comment by codemanyak** [comment]
Solution has been prepared and still seems to be integratable into 3.24-10.

**Comment by codemanyak** [comment]
The code patch is available and waiting for delivery with 3.24-10.

**Comment by reks99** [comment]
Hi Kay,

Tabbing in the editor works great. Thank you very much.

Fine Regards
Rolf
