### ISSUE TITLE
Focus is also lost with Ctrl-X

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#168]
Hi,

I found, that the focus of a nsd is also lost, if an element is cut off with the Ctrl-X key combination - same as with the del-key before. See #164 

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
Oh, of course, I could have thought of it myself...

**Comment by codemanyak** [comment]
Bugfix available on bugfix branch, due for integration (-> version 3.24-09)

**Comment by codemanyak** [comment]
Version 3.24-09 is delivered.

**Comment by reks99** [comment]
Hi Kay,

Ctrl-X and undo now work very well.

Fine regards
Rolf
