### ISSUE TITLE
Enhancement: Switch the input fields for text and comment with Ctrl-Alt-V as well

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#180]
Hi

Since Kay implementet the short cut Ctrl-Alt-V I changed my way to work with structorizer (perhaps more back to the root).

After I gave the program a better name then ??? I swith in the "comment view" mode. Now I develop the structure only with comments. Later on I switch in the "text view" and fill in pseudo- or HLL- or program-code,

The idea behind this proposal is, that if you edit an entry the first field is that, what is shown in the nsd. I can imagine that this is not an option for every one, so a select box in the settings (perhaps in the analyser options - even if it is not a analyser option).

What is you opinion.
Fine regards
Rolf

**Comment by reks99** [comment]
Hi.

Thinking about the place, where the (possible) checkbox may be implemented, the idea came up to implement it in the input dialog of the outer frame. Of course it should be unchecked on start, so the know behavior is set.

All other input dialogs may show the checkbox as well, but disabled. So the switch can only be reversed in the input dialog of the outer frame and the setting is seen in all other frames as well.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@fesch 
Thanks for your proposal. You might have a look to the discussion of issue #39 first. I think it would rather be confusing if the text and comment fields changed places. The proposal back then was just to put the initial focus into the respective field, depending on the current switch mode. I just couldn't make it work back then.
The funny thing is that it was this very morning when I made a notice about what had prevented that change. The solution requires a partial redesign of the layout for the standard element editor and its subclass for FOR loops. This will take me a little more time than I can spend at the moment. But it is planned anyway (remember the radio button proposal for the FOR-IN loop).

**Comment by codemanyak** [comment]
Verison 3.24-13 candidate prepared.
