### ISSUE TITLE
Pascal import doesn't give a useful error description on lexic problems

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#182]
Attempting to import a Pascal file, if the parser detects a lexical problem (e.g. a double quote character) just an error message "gpMsgLexicalError" is written to the standard output (unseen in interactive mode!) with no hint to the illegal character or the line of the problem, not even a message box would pop up.
In case of a syntax problem, at least the error attribute would be filled with the defective token and the line number (which would be misleading, though, because all comments had been removed before parsing).
It might be helpful to show some lines of preceding code context to facilitate the search for the error.

**Comment by codemanyak** [comment]
Work in progress. I implemented some kind of "shift register" for the last ten lines of tokens to present them in case of an error.
An instructive error message with this preceding context may look like this:

![parsererror](https://cloud.githubusercontent.com/assets/15326471/14936948/52bf756a-0ef9-11e6-963f-7af1a6f91c7a.png)
Of course, indentations have gone, but it should be enough information to recognize the part of code.

**Comment by codemanyak** [comment]
Fix available in pull request from codmanyak/Structorizer.Desktop/master

**Comment by GitMensch** [comment]
The current option is obvious much better than the earlier version (= nothing).

Questions:

* Is the indentation gone because of the GUI element used or because it is simply not available in the storage?
* How is the line number calculated (at least with the current C-Importer it doesn't seem to match)?
* Can you please include a "copy to clipboard" button and/or add an event listener for the the standard option [CTRL]+[C] (at least with nearly all "native" applications on Windows you get the message copied to the clipboard).

**Comment by codemanyak** [comment]
Her are soe answers:

> Is the indentation gone because of the GUI element used or because it is simply not available in the storage?

No, the parser ate all spaces. It is just providing the bare tokens.

> How is the line number calculated (at least with the current C-Importer it doesn't seem to match)?

There is some preprocessing of the files. So all comments will have been filtered ot before the parsing starts. Preprocessor directives must also be removed because they are not part of the grammar. I replace at least all simple defines throughout the code. Macros aren't pre-processed. Neither are conditional parts (`#if ... #endif`).

> Can you please include a "copy to clipboard" button and/or add an event listener for the the standard option [CTRL]+[C] (at least with nearly all "native" applications on Windows you get the message copied to the clipboard).

Good idea. But requires a different message box class, obviously.
