### ISSUE TITLE
Wrong translation of FOR-loops to PHP

### ISSUE THREAD

**Issue by FrankSchenk** [fesch/Structorizer.Desktop#191]
When I use a statement like FOR x is 1 to 10 the generated code is correct in all but 1 language: PHP

There it becomes: for ($x = 1; $x >= 10; $x += (1)) and therefore the code does not work. The solutions  looks quite simple to me: replace >= by <=, that should fix it :-)

I am a Teacher ICT and we are going to use this tool as of next schoolyear to train students coding-techniques for use with PHP. It would be nice if this bug can be fixed by then.

Kind regards,
Frank Schenk

**Comment by codemanyak** [comment]
Thank you for your report. I can reproduce the bug. It is as you assumed - a simple equivocation of the branches of an conditional expression. It will be fixed with next version (to be expected in a couple of days).

**Comment by FrankSchenk** [comment]
Great! Thank you very much. 

Verstuurd vanaf mijn iPhone

**Comment by codemanyak** [comment]
Version 3.24-13 is online.
