### ISSUE TITLE
Proposal: Direct link from the help menu to the online User Guide

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#199]
It's a little bit strange that the only thing that seems not available from the Help menu is the help page. It is not actually obvious that it can be reached via the Update sub menu.

So my proposal is to add another submenu item "**(?) User Guide**", which would directly link to the online User Guide. (The "(?)" stands for a question mark icon.) An additional advantage would be that with the true help URL it would be navigatable e.g. by forward / backward buttons (which is not the case when opened via the Structorizer home page menu).

(Actually, the solution is ready, I just ask for approval and an issue number...)

A longer shot would be to write a tool that derives a PDF document from the online User Guide that could be downloaded for offline use. And if the PDF snapshot were delivered with future releases, the menu might open that document in case the URL fails (e.g. because of missing online connection).

**Comment by fesch** [comment]
Strange enough that no one thought about this earlier ;-)

Putting a link is fine I think.

**Comment by codemanyak** [comment]
Fine! Just another question:
I tend to re-dedicate the F1 accelerator (which has recently been used for the About dialog) to the User Guide link and to change the "About" accelerator to Shift-F1 if that is okay. In my eyes it makes more sense than the other way round...

**Comment by fesch** [comment]
yes

**Comment by codemanyak** [comment]
In release 3.27, the help action was also to be supported by a toolbar button, but this had been done defectively (see #468).
