### ISSUE TITLE
Sometimes, seemingly at random, the program will stop being able to save a fil

### ISSUE THREAD

**Issue by fesch** [fesch/Structorizer.Desktop#20]
Issue received via mail:

---

Hi,

I have run across a problem. Sometimes, seemingly at random, the program will stop being able to save a file. 

One such example was a file I had been working on for a while. I'd saved it a few times already, but this time when I tried to save what I had done I got an error saying "Error saving the file" in a dialogue box which contained the options "Yes" and "No". I had absolutely no idea what to click on, so I chose yes. I then tried to save again and this time chose no. 

I have run into this problem a few times today and I must say it's really slowing me down. You see, when this happens, not only does it not save, but it actually erases every line of code from the already saved file. When I closed it and reopened it, I was met with a completely blank file. There was absolutely nothing on it. This was a file I had been edited for a few days.

Luckily I had a backup and I used that, however, the same thing happened to the backup.

I then started trying to work on something else (Because from testing out other files I had it seemed as though the problem only presented on those particular files). However it happened again with a different file.

I've tried to uninstall and reinstall the program to no avail.

Are you aware of this issue and is there anything you can suggest I do to resolve it? I'm using this program as part of an online course, one to which I only have access until next month, I cannot afford to lose time on this.

Thank you
David

**Comment by fesch** [comment]
Reply after having asked to use the latest version:
---
Thanks for your quick reply.

I have just downloaded the most recent version from that site. I had previously only been able to use the JAVA applet version, as the other versions would simply not open properly. This time though, this version did open and seems to be working properly. 

Thank you very much
David

**Comment by codemanyak** [comment]
I remember having seen a similar behaviour some months ago on just a particular computer. Unfortunately, I was not able to fence in the specific circumstances of that failure. Can't even say anymore which Structorizer version it was. Re-installing helped, as far as I remember.
BUT: Recently I had a very good guess in an apparently similar issue: The user had accidently checked the switch text / comments option. In this case, having no comments in the diagram, it shows just a blank algorithm skeleton (element structure without any text), which just looks scaring, though there is no data loss at all. But this is obviously not the isuue reported by David.
