### ISSUE TITLE
Executor GUI fixes and improvements (Slider, Look and Feel, Call Stack)

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#201]
- [x] When the speed slider is moved by cursor keys then the value change isn't shown before the focus gets off the slider. Hence it seems as if nothing would happen.
- [x] It would be helpful to add scales to the slider and to allow its stretching on horizontal resizing the Control window.
- [x] Look and feel changes aren't propagated to the Executor Control.
- [x] It would be more intuitive to have a button to dsplay the Call Stack, the opportunity to double-click on the call level number is too hidden, even though a tooltip gives the respective hint.

**Comment by codemanyak** [comment]
To fix the items of the issue seems easiest by changing the layout from a group layout to a GridBagLayout. After some experiments, a solution is found and will be fed to the bugfix branch.
Preview:
![executorcontrol3 24-14a](https://cloud.githubusercontent.com/assets/15326471/17086410/60ee6f7a-51f1-11e6-8fa1-01d7aba09a83.png)
An additional improvement will be that the Call Stack display will have level indices:
![stacktrace4](https://cloud.githubusercontent.com/assets/15326471/17086417/acd30086-51f1-11e6-80bb-3aa415627a79.png)

**Comment by fesch** [comment]
Feedback after having posed the news: WoW!!
