### ISSUE TITLE
Why isn't the Analyser status (enabled/disabled) saved in the Ini file?

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#207]
Going to report that the Analyser is always enabled on Structorizer start no matter whether or not it had been disabled during last session, I found out that the code for saving and loading of the Analyser status to or from the Ini file, respectively, already exists but had been commented out for a long time (at least since version 3.17 - the oldest source code version I have got).
There must once have been a reason, I guess - my question is: which?

**Comment by fesch** [comment]
Probably there is a reason, but I definitely do not remember it anymore :-/

**Comment by codemanyak** [comment]
I see. Maybe because it's an essential help for beginners that shouldn't be hidden from them just because someone had disabled it once? Actualy, it is efficient enough not to compromise editing experience. And if the user yet starts to get annoyed or they need the extra space then they might switch it off till the end of session? Might that have been a plausible argumentation line?
Well, not remembering anymore, you might simply say: maybe... (so it's just in case it may ring some bells...)

**Comment by fesch** [comment]
Maybe .... ;-) ..... but maybe I got some other idea: I know that, a long time ago, I compiled a special version for a special test with my class: one half of them were forced to use the analyzer and the other half was not allowed to, so maybe this is just a left-over from that time ...

**Comment by codemanyak** [comment]
Well, my own proposed argumentation line is staring to convince myself ;-)
And being sure the Analyser report area will be presen on Structorizer start, I might be tempted to abuse it for an additional warning line in case switched text/coment mode is active. As some issues suggested, a user being unaware of this mode might easily run havoc seeing apparently empty diagrams without having a clue what's the matter. I had already thought about a (non-modal!) warning box on start suggesting to switch the mode off. But the Analyser report area might also be a place for this. What do you think? If a click on the respective line (not being associated to an element, of course) should switch off the text/comment mode then it will require some tricks, though.

**Comment by codemanyak** [comment]
This is how the proposal in the last comment might look like:
![analyserwarningswitchtextcomment](https://cloud.githubusercontent.com/assets/15326471/17176629/dff02836-540d-11e6-8e57-c4c17bef2225.png)

Considering this, however, I'm coming to the opinion that a warning box on start might be less annoying.

**Comment by fesch** [comment]
I personnaly feel that this kind of warning is less annoying ;-)
I also would prefer an indication on how to leave the mode instead of clicking (so the user would know on how to turn it on again too) ...

... just my 2 cents ... ;-)

**Comment by codemanyak** [comment]
Okay, I agree and spend this issue an enhancement label.

**Comment by codemanyak** [comment]
The message will look like this then and there will be no effect on clicking:
![analyserwarningswitchtextcomment2](https://cloud.githubusercontent.com/assets/15326471/17183808/7e51fb24-5429-11e6-9b4f-1c4cc86a430a.png)
I could have named the key combination instead, but with the menu item reference the user will get both information.
