### ISSUE TITLE
Handling of return statements inconsistent (Executor)

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#21]
A return statement just induces the immediate output of the added value but does not end the execution. This behaviour is not what one expects considering Java, C, C++, C#.
Is there a different reading in other languages?

**Comment by codemanyak** [comment]
A modified Executor version letting the execution end after having carried out the return statement is available.

**Comment by fesch** [comment]
In response to "Is there a different reading in other languages?"
I do not know any language with a different reading ...

**Comment by codemanyak** [comment]
Okay, then I'll upload the changes as bugfix together with Issue #24

**Comment by codemanyak** [comment]
Bugfix in master branch
