### ISSUE TITLE
Structure preference "Enlarge FALSE" does exactly the contrary

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#212]
This has been annoying me for long: In order to reduce the FALSE branch of alternatives to their minimum required width then you have to select the "Enlarge FALSE" option and vice versa.
So either it has to be renamed (and refactored in code) or simply the logic in drawing method of class Alternative will have to obey literally.
I opt for the latter option. The advantages are: it's the minimum invasive approach, and the user will rapidly get accustomed to the less twisted logic.

**Comment by fesch** [comment]
Ups ... never noticed that :-(

**Comment by codemanyak** [comment]
No problem. At least it worked somehow.

**Comment by codemanyak** [comment]
Bugfix added to bugfix branch
