### ISSUE TITLE
Language file evaluation: Contained equality signs cut the rest of the message

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#218]
Since the lines of the language files are simply split by `'='` in the first place in order to separate key sequence from message, messages containing equality signs (for what purpose ever) will be mutilated.
Though in many cases the originator of the file may avoid including equality signs and there are ways to circumvent the problem, it may be helpful in certain cases (e.g. for syntax explanations or the like) to be able to have a message containing equality signs.
Actually this is easy to fix because per line only the first and mandatory equality sign should serve as separator.

**Comment by fesch** [comment]
I will patch the translator accordingly by doing only a split on the first symbol.

**Comment by fesch** [comment]
This was easy to fix anyway ;-)
