### ISSUE TITLE
Too easy loss of all done modifications in Translator

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#220]
The Translator immediately forgets all modifications done for a specific language as soon as you change the language. Without warning. This may happen very quickly by mistake - just a short look for how this or hat message is translated in a similar language - and all the changes are gone! Frequently to save isn't a solution, either, since you can't reload a saved file. So it would turn into a puzzle of many files - the contrary of what you intended with Translator. Moreover, Translator overwrites existing files without hesitation. That is the next chance for annoying data loss.

1. The least measure I propose is to register if a modification in the table was done (e.g. by a propertyChangeListener you might have to attach to all three JTables in Translator.tables - you find an example in Control.java) and then raise a commit dialog box as soon as the user selects any language button or the close button.
2. An alternative (and more comfortable) approach would be to cache the JTable contents of the currently loaded language on changing the language. If the user switches back to a language with previously cached contents then this cached content is to be restored rather than loading it from the original file. The warning box is then only necessary on pressing the close butto or when the user selects the currently presented language again - this might mean he wants to discard his own changes, but we should better ask. (Really great, though only feasible with a bigger effort, would be to register which entries of the table have been changed (i.e. to flag every modified element) and to indicate them with a (differently) coloured background, e. g. green, as I had already proposed via E-Mail).
3. Last but not least, a helpful addition, to approach 1 in particular, might be the opportunity to re-load a language file previously saved instead of getting the untouched content from the locale. Practically a single load button might suffice, the language name might be derived from the file name. And if it's "xyz76kjä.poi" then be it so. The good question is whether the Locale may be (ab)used for loading a file that might be a language file and to handle all possible syntax deviations. (In particular, it might be any text or binary file not even faintly similar to a translation file.)

I know that implementing some of these proposals tends to be a lot of work.

**Comment by fesch** [comment]
I would like to add the fact that saving the actual file does not check for an existing file with the same name. So there could be some data loss too! But I'm aware of this

Today the translator component is 2 days old ;-)

**Comment by fesch** [comment]
Each time you load some language, the previous one is being cached (header + values). The corresponding button is being painted in green then. When clicking on a green button, the cached version is being restored, so the modified values will still be marked in green.

**Comment by codemanyak** [comment]
This was really fast! Great news. Will have a look it pretty soon.

**Comment by codemanyak** [comment]
By the way, I have got a pretty simple idea how to make it possible to load a selected language file into Structorizer:
The initially called methods setLang() use a String argument _langfile, which - as induced by one of the menu buttons - used to be one of the predetermined pure file names "en.txt" etc., which the LangDialog class retrieves in the given resource path.
Now, if we add a menu item "from file" to the language preferences menu that opens a simple FileChooser and this would pass an absolute file name instead, then the LangDialog could easily distinguish it from the pure resource file names. In this case an ordinary file stream would be opened instead, and if the syntax is okay: voilà. Otherwise an error message would stop the trial, and the former language remains in place.
It would not even require an API change. Just an additional menu button, a new translatable caption ;-), and a little change in LangDialog.setLang(component, String). Wold you approve this?

**Comment by fesch** [comment]
Yes ;-)
And ass this setting will be save by default as well, closing and reopening Structorizer should automatically load that file too ... at least as long as the file remains in its location ;-)

**Comment by fesch** [comment]
By another very simple modification the "preview" function could also be achieved. For this, the loading method has to be split into 
1) loading the resource
2) parsing the string
Like this, the translator component could easily call the second one by passing it the contents of the generated lang file.

**Comment by codemanyak** [comment]
The updatd Translator works pretty fine. What I'd still like to request (not exactly now) are the two safety warnings / confirmation dialogs:

a) on closing the form if there are unsaved modifications
b) on overwriting an existing file.

And I would ask for a slight modification. No matter what happens behind the scenes, the language button should only turn green if at least one item was edited. Just having had a look without having changed anything might also lead to caching (why not?) but the button shouldn't turn green. Nor should be warned on closing the window unless at least one language had experienced an editing attempt (I think it's not necessary to check whether the resulting value really differs).
The good question however is whether or not the green button colour should be turned off after having saved the file. I'd say yes. The items are still cached in their changed but now also saved state, so they might also turn to white now. As soon as new changes are added after having saved the file, they should turn green again and so on. I think this is what would look logical to the users.

**Comment by codemanyak** [comment]
Oh! There is a problem on reopening the Translator! It it had been used (some editing done but not saved - don't no whether this is important, but for reproducibility), was closed and is opend again then no language file can be loaded. Instead NullPointerExceptions occur, with the following exemplaric stack trace:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at lu.fisch.structorizer.locales.Translator.getComponentByName(Translator.java:314)
	at lu.fisch.structorizer.locales.Translator.getComponentByName(Translator.java:309)
	at lu.fisch.structorizer.locales.Translator.loadLocale(Translator.java:120)
	at lu.fisch.structorizer.locales.Translator.button_esActionPerformed(Translator.java:570)
	at lu.fisch.structorizer.locales.Translator.access$4(Translator.java:569)
	at lu.fisch.structorizer.locales.Translator$5.actionPerformed(Translator.java:395)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by codemanyak** [comment]
Obviously the loadedLocaleName is null though the loadedLocale is not.
The reason seems obvious: loadedLocale is a static attribute while loadedLocalName is not. So the former will persist while a new Translator instance starts with empty loadedLocalNam and hence isn't consistent with it.

**Comment by codemanyak** [comment]
Well, changing the langFileName attribute to static, too, doesn't help, unfortunately. Now the loadedLocaleName is still in place but the button isn't found. The problem now that not all buttons are equipped with names. Only those I had previously used (here it was "es" and "nl". But the loadedLocale and loadedLocaleName on reopening was astonishingly "chs", which I had definitively not opened.
From this point on I leave it to you - you know better the button naming policy you had in mind.

**Comment by codemanyak** [comment]
@fesch Your quick fix mended the acute problem.
In the meantime I found some time to meddle in your code, mainly to see whether my ideas were feasible. Well, they are. On the bugfix branch there is a proposed update. I'll set up a pull request, hoping not to get into conflict with achievements you might have gained concurrently.

There is still a seriuos flaw: You may open various Translator instances from the Structorizer, and then you will get into serious trouble! This is due to the use of static variables for locale activities. The classic mistake in a concurrrent environment.
So we will have to take measures:

1. Either Translator is converted into a singleton. Then of course it must either be reentrant or the instance must remove itself on closing/disposing. Or both.
2. Alternatively, the use of static variables, e.g. in order to store temporary state information (like the current Locale) must be ended bevause different instances interfere here..

**Comment by fesch** [comment]
Making Translator a Singleton seams to be the easiest way to prevent the described problems. Having multiple instances does not make any sense either.

**Comment by codemanyak** [comment]
Moreover, this offers an easy solution for the preview function: 
Translator might simply call the setLang() function on the originating 
Mainframe with a specific key string, say e.g. "Translator", such that 
the LangDialog class could distinguish this from file names. Having 
recievd this specific key string it would simply request the translation 
lines from the Translator instance instead of reading them from file. 
Again, the API wuldn't have to be changed (just its functionality).

What do you think? Of course, this design would again extend the mutual 
interdependency of the packages, which isn't so good an architecture 
after all.
But well, the delivered Structorizer will contain all of them, anyway.

By the way, I think Locales should also be a singleton.

**Comment by fesch** [comment]
I was just asking myself it the language related stuff should not be extracted from the NSDController interface and be put into a separate new interface. Then Arranger and Executor should implement this interface too.

What do you think about that?

**Comment by codemanyak** [comment]
Seems sensible to me. I had recently derived an ILandDialog interface, but this was simply a generalisatiion LangDialog. A new design around the locales would certainly be a better approach.

**Comment by fesch** [comment]
Okay, then I will do that ;-)

**Comment by fesch** [comment]
I finally got a working very nice solution where the inheritance regulates the displayed language. The only thing I have yet to integrate is the setLangSpecific / class_specific thing ... ;-)

**Comment by fesch** [comment]
I've implemented a more generic way to make a translation depend on one of more fields or methods:
The new style will be like this:
`InputBox.title[elementType:Root]=Programmnamen bearbeiten...`

Multiple conditions can be separated by comma:
`InputBox.title[elementType:Instruction,getInsertionType():insert]=Neue Anweisungen hinzufügen...`

**Comment by codemanyak** [comment]
I wonder if this paradigm will cover all difficult cases. Okay, I will wait and have a look at it then.
By the way, the preview works fine, it seems.

**Comment by fesch** [comment]
Puh ... I did a lot of testing, so I hope I did not break toooooo much of what previously worked.

I'm know thinking about some memory-optimization to all this new stuff ;-)
