### ISSUE TITLE
On changing the Look and Feel, table grid lines may get lost

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#224]
The grid lines of tables in Structorizer GUI components (e.g. the variable table in the Executor Control or the translation tables in Translator) used to turn invisible on changing the Look and Feel to "Nimbus". This is not a problem, since "Nimbus" presents table rows with alternating background colour. The trouble is that on switching back to another Look and Feel, the table grid visibility isn't restored.
Though this is essentially a Java Swing defect, a workaround within Structorizer is easy.

**Comment by codemanyak** [comment]
Workaround is prepared and waiting for integration.

**Comment by fesch** [comment]
I have noticed that this morning too ...
