### ISSUE TITLE
Flaw in downloadable "Single HTML page" User Guide version: images not accessible

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#238]
The User Guide download as "Single HTML page" version is defective with respect to the URIs of the included images: they specify a relative path, e.g. `<img src="../Portals/structorizer/Files/something.png ... /img>`. This way, the images aren't retrievable and don't show.
After enriching all path strings "../Portals/structorizer/Files/" with the Dycomasy URL (http://dycomasy.fisch.lu) i.e. replacing them by "http://dycomasy.fisch.lu/Portals/structorizer/Files/" the image retrieval works.
The HTML generator should be modified a little.

**Comment by fesch** [comment]
Fixed!
