### ISSUE TITLE
Title translation mechanism for InputBox (element editor) doesn't work properly

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#241]
The translation of the InputBox title relies on two conditions in the locale files, one of them being a method. The evaluation of the method conditio doesn't work, which is not obvious because the exception mechanism for this part doesn't work, either. As a result, the condition is always regarded as true, in other words, the last provided translation matching all other imposed conditions overrides anything.
Moreover, the key structure for the InputBoxFor subclass wasn't converted at all and provides translation with an obsolete key sequence, which is ineffective.

**Comment by codemanyak** [comment]
Moreover, the implemented mechanism to translate the label of the breakpoint trigger value (lblBreakTrigger) doesn't work anymore.

**Comment by codemanyak** [comment]
Bugfix available in branch "bugfix3.25".

**Comment by reks99** [comment]
Hi,

there is an untranslated message, when close the program window and a modified nsd exists. With german as selected language the message is "Do you wnt to save ther current NSD-File? name_of_nsd".

Fine regards.
Rolf

**Comment by codemanyak** [comment]
@reks99 Thanks for pointing this out. I opened a new issue #243 for your report since it doesn't belong here. I'm going to fix it.
