### ISSUE TITLE
Enhancement: Documentation

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#242]
Hi Kay, hi Bob.

First of all many thanks for the new version of structorizer.
When reading the documentation (yes I did!), I thought a table with all the keystrokes in use will be helpful. So I build one, which is attached - and can or should be correced. Of course it can be added to the documentation as well.

Further on, I found that the description of the keystrokes in the menu are not language specific, so for example when selecting the englisch interface there is still "Strg-Umschalt..." instead of "Ctrl-Shift...". It is not a problem for me, but may be for others.

Fine regards
Rolf

file:///home/rolf/Dokumente/table.zip

**Comment by fesch** [comment]
Thanks!

... but unfortunately the attachment did not pass. If you can't past it here, put a public download link of mail the file (structorizer@fisch.lu)

**Comment by reks99** [comment]
Hi Kay,

so this explains, why the descritption stay in german in my system, even when I switch the language of structorizer (so the question comes up - why should I be able to switch the language of structorizer?). 

Fine regards
Rolf

**Comment by reks99** [comment]
Hi,
make a mistake by close the issue.

**Comment by codemanyak** [comment]
@reks99 Consider this: Should Structorizer actually switch the OS locale? Including e.g. the keyboard mapping? Are all the locales provided by Structorizer also available in the OS installation? Can we change the labels printed on  the keys (i.e. will the key "Strg" show a "Ctrl" label after switching the locale)? Except the "Shift" and "Enter" buttons, which usually are decorated with symbols, the keyboard decoration is normally printed in the same language as the operating system installation or at least the country where the PC is purchased and installed. So, if you are Chinese and work with Structorizer in China, the key descriptions are likely to be in Chinese. And it makes a lot of sense to switch the Structorizer to the Chinese locale as well, doesn't it? If you are a Chinese working in Germany, however, then of course the keyboard may not be helpful to enter Chinese ideograms, anyway, right? And yet switching Structorizer locale to Chinese may help you better to understand Structorizer, while showing key descriptions in Chinese will not actually be helpful to find the respective keys on a German keyboad.
(Wir sollten die Kirche mal im Dorf lassen.)

**Comment by reks99** [comment]
Hi Kay,

I think you misunderstand me. At least, it thought when switching the language the description are switch as well - as done with the accelerator keys for the menu. Than you explain, that the translations of the key names will be done by the operating system depends on the stettings of the locale.
My more or less ironic question - why may a user switch the language - means: the language of structorizer can only be the language found in the settings of the locale. For example GAMBAS, a Visual-Basic like programming language for Linux do so. If one will have a different language, perhaps after translation of the messages of a self written programm, you have to change the locale i.e. the content of the LANG environment variable.

So I think, this can be an option for structurizer too - it is just a suggestion, no whish at all.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99
My use of the word locale may have provoked some mis-understanding. The 
Structorizer language mechanism was fundamentally redesigned by Bob and 
he chose to name the fundamental classes of the new mechanism Locales, 
which makes sense though it suggests more than just language translation 
and may be confused with the OS locales.
Both mechanisms (i.e. that of the OS and that of Structorizer), however, 
are strictly independent. And I think they better stay independent.
Considering that e.g. an average Windows installation will hardly 
provide more than the local language plus American English, we would 
unnecessarily restrict the localization capabilities of Structorizer.

**Comment by codemanyak** [comment]
Bob added a new Chapter "Usage" to the User Guide containing your keyboard table as sole subsection. I just added some missing accelerators and moved some to a more appropriate one of the tables.

**Comment by codemanyak** [comment]
I just chose to rise the "Accelerator keys" subsection to a chapter rank (now named "Key bindings") and to drop the "Usage" chapter because the User Guide is all about usage - and I regard chapters (or sections) with only a single subsection as flawed hierarchy.

**Comment by fesch** [comment]
PDF updated ...
