### ISSUE TITLE
Error with User-Guide, when press F1

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#245]
Hi,

I get the error shown on attached image,
![helperror](https://cloud.githubusercontent.com/assets/18035140/18584817/7f0baa26-7c13-11e6-80ea-d1d7135f156d.png)
when press the F1 key or the corresponding menu entry.

Fine regards
Rolf

**Comment by codemanyak** [comment]
This is strange. I successfully tried it under Windows and within OpenSuSe even out of a virtual machine: no problem at all. In both cases Firefox was the standard browser.
Might it be a firewall configuration problem on your site? Or with browser settings? What browser do you use? Can you get more specific information from some log file?

**Comment by codemanyak** [comment]
@reks99 Well, you will have checked yourself, but just to make sure and in the hope to come closer to the core of the problem:
1. It won't have been a temporary unavailability of Bob's server, will it? (In other words: The error message remains reproducible?)
2. You can open the User Guide page via the following alternative ways on the same system:
a) Via the "User Guide" link from structorizer.fisch.lu;
b) By directly copying the displayed URL into your browser;
c) By clicking on the link in a document (after having copied the URL into it and e.g. printed this document to a pdf file).

**Comment by reks99** [comment]
Hi Kay,

I checked it now, and the problem remains.
The Browser in use is firefox, and the page is reachable when I put the address direct in the browser url-field - so no firewall rules stop the access.

How does structorizer calls the browser in Linux? Did you try "xdg-open http://help.structorizer.fisch.lu/index.php", which is the current method to call the configured default browser with the given URL. I tested the call in a shell window.
HTH
Fine regards
Rolf

**Comment by codemanyak** [comment]
Structorizer doesn't use OS-dependent mechanisms directly. Instead it relies on the Java method Desktop.browse(). This, in turn, will only work if you registered a browser application as standard browser with Linux. Which you apparently did (as the xdg-open attempt suggests.
So the next possible explanation approach might be that your Java installation isn't up to date.

**Comment by codemanyak** [comment]
Additional request: The error message box is popped up by Structorizer as a result of an exception thrown by Desktop.browse(). Structorizer writes a stack trace to the standard error stream before. Could you please report this stack trace? It would at least show which type of exception was thrown.

**Comment by reks99** [comment]
Hi Kay,

here is the stack trace.

java.io.IOException: Failed to show URI:http://help.structorizer.fisch.lu/index.php
        at sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:114)
        at sun.awt.X11.XDesktopPeer.browse(XDesktopPeer.java:98)
        at java.awt.Desktop.browse(Desktop.java:386)
        at lu.fisch.structorizer.gui.Diagram.helpNSD(Diagram.java:3192)
        at lu.fisch.structorizer.gui.Menu$76.actionPerformed(Menu.java:826)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
        at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2870)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:689)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
        at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:668)
        at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
        at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
        at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2962)
        at javax.swing.SwingUtilities.processKeyBindings(SwingUtilities.java:1586)
        at javax.swing.UIManager$2.postProcessKeyEvent(UIManager.java:1476)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:772)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
        at java.awt.Component.dispatchEventImpl(Component.java:4742)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.awt.EventQueue$4.run(EventQueue.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

HTH
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 Thank you very much. According to Javadoc, this type of 
exception is thrown by Desktop.browse(), if:

1. the user default browser is not found,
2. or it fails to be launched,
3. or the default handler application failed to be launched.

Hence, this supports my assumption that it may yet be an X11 
configuration problem in your system.

**Comment by codemanyak** [comment]
@reks99 Additional clarification request: Was the shell you started Structorizer with embedded in a desktop environment at all (sort of xterminal started within the desktop, which was of course assumed) or was it a login shell without a desktop context (this depends on your user profile in use)?

**Comment by reks99** [comment]
Hi Kay,

the call to xdg-open was send from a xterm with a user account and a bash. Of course it is "embedded" in a desktop environment, here trinity, which is a kde3 fork, because the graphic of structorizer needs a graphical environment.

The Linux base is Debian jessie, which is the current stable version, where the java installation come from. As far as I know it is the gnu java version, not the oracle one.

Here a list of the installed packages (which have java in their name). The columns are:

NameOfPackage Version CPU-Architectur, Desription.
ca-certificates-java   20140324   all   Common CA certificates (JKS keystore)
java-common           0.52            all   Base of all Java packages
libatk-wrapper-java  0.30.5-1      all   ATK implementation for Java using JNI
libatk-wrapper-java-jni:amd64   0.30.5-1  amd64  ATK implementation for Java using JNI (JNI bindings)
libjavascriptcoregtk-1.0-0:amd64   2.4.9-1~deb8u1  amd64    JavaScript engine library from WebKitGTK+
libjavascriptcoregtk-3.0-0:amd64   2.4.9-1~deb8u1   amd64    JavaScript engine library from WebKitGTK+
libjna-java  4.1.0-1   all   Dynamic access of native libraries from Java without JNI
libreoffice-java-common  1:4.3.3-2+deb8u5  all   office productivity suite -- arch-independent Java support files
librxtx-java   2.2pre2-13   amd64   Full Java CommAPI implementation
tzdata-java   2016f-0+deb8u1  all   time zone and daylight-saving time data for use by java runtimes

Ask, if you need more information?

Fine regards
Rolf

**Comment by reks99** [comment]
Hi Kay 
the command "java -version" gives the following output

OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

HTH
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 Thank you. I don't need more info, I think.
I already found out that the Desktop class in Java isn't fully integrated with some Linux distributions. I still don't know whether this applays to all Java versions or only to the Gnu Java (It works well with Gnome desktop, though (such that OpenSuSe caused no trouble).
I will try to code a system-specific workaround and test it within a virtual Debian installation.
For the time being, the error message at least reports the URL where the user guide is to be found such that the user may browse himself, though somewhat inconveniently.

**Comment by codemanyak** [comment]
@reks99 I'm sending you an alpha test version of Structorizer 3.25-01 via mail, hoping that you can confirm the workaround is functioning.

**Comment by reks99** [comment]
Hi Kay,

I don't really need the workaround - but will test it, I thought I would help you to find and fix shortcommings in structurizer. Of course I can find the documentation and of course I can live with the englisch messages.
But in case of internationalisation I thought it should be fixed.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 I really appreciate your helpful hints. They have already contributed substantially to improve Structorizer. And I'm sending you the alpha test package because you have the appropriate system context for it (due to lacking bandwidth I can't accomplish my Debian installation currently).
The first attempt to send you the test version failed due to SPAM classification :confounded: . I hope the second attempt will succeed now.

**Comment by codemanyak** [comment]
@reks99 Okay, didn't arrive either. Now I try it here. Upload eventually succeeded. So you may at least download it if this comment will also be deffered as mail.

[structorizer_3.25-01alpha.zip](https://github.com/fesch/Structorizer.Desktop/files/478416/structorizer_3.25-01alpha.zip)

**Comment by reks99** [comment]
Hi Kay,

I downloded the alpha version and try to call the help with F1 key (and the menu entry), but the error remains.

The text when closing the structurizer window with a new nsd is now translated.

Do you need help with the installation of debian?
The best way is the use of the net-install option from a small, around 200MB disk (image). When ask, what else should be installed deselect everything - except the ssh-server for a second way to access the system. Then install only the needed packages, so the system keep small.

Feel free to ask for more help, especially for the work with apt and aptitude. I can try to build a VM for you which will be around 300-400 MByte.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 Hi Rolf,
this is getting more and more mysterious. The opening attempt should now have been done via "xdg-open" when the standard Desktop mechanism fails.
I produced a modified alpha2 version now, which writes info for every single step to the console (lines starting with "#245:").
Please try again with this version:
[structorizer_3.25-01alpha2.zip](https://github.com/fesch/Structorizer.Desktop/files/478645/structorizer_3.25-01alpha2.zip)

With respect to the Debian installation many thanks for your advice and offered help. But at home the problem is the low data transfer rate of my network connection. Downloads of several hundreds of MiB or even GiB tend to last more than 12 hours and usually abort with timeout. I had tried the net-install option, too, but the installer froze after having specified all requested parameters on downloading and installing etc.
So I will have to do it in the office where I have access to an appropriate net.

**Comment by reks99** [comment]
@codemanyak Hi Kay,

Here the console output of the alpha version:

./structorizer.sh 
Loading now locale: de.txt
Loading now locale: de.txt
#245: browseDESKTOP() failed.
#245: os name = linux
#245: linux detected.
#245: $XDG_SESSION_ID = null
#245: $GDMSESSION = null
#245: $GDMSESSION = null
#245: blindly trying KDE...
#245: Trying to exec
   cmd = kde-open
   args = %s
   %s = http://help.structorizer.fisch.lu/index.php
#245: 2 command parts:
 kde-open http://help.structorizer.fisch.lu/index.php
#245: Error running command.
#245: blindly trying GNOME...
#245: Trying to exec
   cmd = gnome-open
   args = %s
   %s = http://help.structorizer.fisch.lu/index.php
#245: 2 command parts:
 gnome-open http://help.structorizer.fisch.lu/index.php
#245: Error running command.
#245: openSystemSpecific() failed.

HTH
Fine regards
Rolf

**Comment by reks99** [comment]
@codemanyak 
Hi Kay,

I just tested kde- and gnome-open in openSuSE Leap... with lxd as window manager and they also don't know the commands, but with xgd-open the browser was started with the give url.

HTH

Fine regards
Rolf

**Comment by reks99** [comment]
@codemanyak 
Hi Kay,

here the description of xdg-open from https://wiki.ubuntuusers.de/xdg-utils/#xdg-open

xdg-open

Hinweis:

Ein Schwachpunkt der xdg-utils ist, dass keine Desktop-Umgebung zwingend verpflichtet ist, die Standardisierungsvorschläge umzusetzen. Daher kann es in der Praxis passieren, dass trotz korrekter Verwendung die jeweilige Desktop-Umgebung ihren eigenen Vorgaben folgt.

xdg-open öffnet unabhängig von der eingesetzten Desktop-Umgebung oder dem verwendeten Fenstermanager das jeweilige Standard-Programm, allerdings abhängig vom MIME-Typ. Das Werkzeug lässt sich zum einen vom Terminal aus nutzen, zum anderen benutzen viele Programme intern xdg-open, um bestimmte Aktionen auszuführen. Wird das Programm in einer Desktop-Umgebung benutzt, so leitet es jegliche Anfragen direkt an die entsprechenden Programme der Desktop-Umgebung weiter (gnome-open, kde-open, exo-open usw.).

Das Programm wird über das Terminal[2] aufgerufen. So öffnet:

xdg-open DATEI.pdf 

die im aktuellen Verzeichnis liegende PDF-Datei mit dem Standard-PDF-Betrachter, während:

xdg-open http://ubuntuusers.de 

die Internetadresse (URL) http://ubuntuusers.de im Browser öffnet. Hierzu ist die Angabe des Protokolls notwendig, in diesem Fall also HTTP.

HTH

Fine Regards
Rolf

**Comment by codemanyak** [comment]
Thank you very much. This explains it now. The environment variables XDG_SESSION_ID and GDMSESSION are first inspected in vain to get a clue which window manager might be active. (Obviously, many Debian distributions don't properly set up the XDG environment variables, which has also been reported elsewhere.) But now after getting no clue, blind attempts are made only with kde and gnome but not with xdg-open, which was forgotten and would certainly have solved the problem. Now I can fix it,

**Comment by reks99** [comment]
Hi Kay,

keep in mind, that there are up to 10 (or more) desktop environments and up to 90+ window manager for Linux available and KDE and GNOME are only two of them.

Since KDE4 and GNOME 3 these environments are real "fat ware" and no more running on older hardware, so a lot of persons switch to different desktop environments.
So can not trust that GNOME or KDE is running.

Fine regards
Rolf

**Comment by codemanyak** [comment]
The fix available on the bugfix branch now and filed for version 3.25-01 ensures that xdg-open is tried next when the java.awt.Desktop class fails to launch the browser and the OS is a Linux derivate. If xdg-open should fail too then the open commands for KDE and GNOME will also tried.
This way, we should cover the vast majority of desktop constellations. If yet some rare constellation for which it doesn't work happens to be reported then we will have to enhance the bugfix adequately.
