### ISSUE TITLE
Bug: Condition for endless loop in bash export is wrong

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#247]
Hi Kay,

when export an endless loop to bash the exported conditon is 
"when [1]"
This is wrong, because there must be spaces around the square brackets.
The parser uses white spaces as seperators, so the expression is seen as one (unkown) element.

Fine regards
Rolf

PS: Can you give me a help for export subfunctions with arranger too - I can't manage it.

**Comment by codemanyak** [comment]
Obviously. Thank you very much. I'm going to fix it.

> PS: Can you give me a help for export subfunctions with arranger too - I can't manage it.

I'll answer this separately as it hasn't anything to do with the 
reported issue.
