### ISSUE TITLE
Turtleizer rounding error propagation: enhancement proposal

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#272]
Turtleizer internally uses an integer coordinate system. This seems sound with the pixel matrix of the screen but leads to dramatic degrading of shapes after many traversal moves due to error propagation, particularly with small features, e.g. on drawing dashed lines, small polygons etc.
From a technical point of view, this is clearly a bug: If Turtleizer internally used a floating-point position, also allowing to pass floating-point lengths with forward and backward routines, then the effect of the biases summing up all along an extended trajectory would mostly be gone.
From a paedagogical point of view, however, this "misbehaviour" is rather a feature - as it allows to discuss these problems, inducing better understanding.
What to do now? The pairs of synonyms for the Turtleizer procedures (e.g. forward/fd) might offer an elegant solution for the dilemma: What if we provide both an integer and a floating-point model, simply by uncoupling fd() from forward() etc.? The one set of procedures might still offer the integer model, the other could accept double arguments (and internally calculate with double coordinates). The same should apply for the rotation procedures (i.e. we re-introduce an integer angle API for the one set of procedures). It makes sense that the short names (often favoured by the pupils and students) adhere to the integer model while the more legible full names offer the real-number model ("short names" = "shortcomings" ;-), which might even have an additional paedagogical benefit):

```
fd(int pixel) <=> forward(double pixel)
bd(int pxel) <=> backward(double pixel)
rl(int degrees) <=> left(double degrees)
rr(int degrees) <=> right(double degrees).
```

It would be sufficient consistently to hold the internal current position with double coordinates, just that any use of the short-named procedures would round the current coordinates or angle, respectively, thus simulating an integer geometry model.
For better demonstration effect, there should be GUI actions (menu items, toolbar buttons, key bindings) to substitute the references to procedures of the one set by the corresponding ones of the other set (integer <--> double) in selected elements - if Root is selected, then recursively for the entire diagram. Possibly, Ctrl-G and Ctrl-Shift-G might be a sensible pair of key bindings to alter the used **G**eometry API.

@fesch Would you approve of such an enhancement?

**Comment by fesch** [comment]
Yes, I agree ;)

**Comment by codemanyak** [comment]
Great. Then I will go ahead.

**Comment by codemanyak** [comment]
Internal coordinate model changed to double, signatures of forward() and backward() also changed to double as proposed. Drawing may work as precise as expected now. Fix available on bugfix3.25 branch.
Against the proposal, rotation API (rl, rr) left as is, however, because diagrams with drawings having worked before (since bugfix in version 3.22-19) shouldn't degrade now.
Conversion opportunities still to be implemented.

**Comment by codemanyak** [comment]
There is an inconvenience in the code replacing actions: They create an undo entry before having cjecked whether there will be any changes at all (i.e. whether the selected subtree contains any Turtleizer commands to be substituted). Of course, a recursive advance check is likely to cost too much time, namely for the button visibility control. But at least during the action it could be detected whether a replacement took place; otherwise an automatic formal undo would get rid of the void entry in the undo stack. Will be prepared for the next version.

**Comment by codemanyak** [comment]
The proposed undo was not an option because it induces an unwanted empty redo entry. Hence, the advance check remained the only wayout and will be done from version 3.25-05 on.
