### ISSUE TITLE
Edit element, little font. Help!

### ISSUE THREAD

**Issue by ebial** [fesch/Structorizer.Desktop#284]
When I open the "Edit element" box, the text entered by me is of a very little size. I used a USB version that worked perfectly on a school computer, and I also downloaded my own version. Still the same little size, only on my laptop.

**Comment by codemanyak** [comment]
Would you please specify
a) what Structorizer version you use
b) the operating system you work with
c) the screen resolution of your computer.
d) whether the font in the element editor is the only wee one or there other dialogs or controls of Structorizer also showing too small fonts.
And would you please send a screenshot of the element editor?

**Comment by codemanyak** [comment]
Well, let me be more precise: Question a) does not ask for qualifications like "USB version" but for the exact version number. You find it in the title bar (with newer versions) or via the `Help -> about` menu (all versions).
Additional request: Please also name the selected Look and Feel (menu `Preferences -> Look and Feel`). (Have you tried to change the look and feel? Has it influence the font size significantly?

**Comment by codemanyak** [comment]
@ebial Would you mind answering our questions? Please understand that we cannot fix a problem never heard of before without knowing the exact facts and circumstances. We need to reproce the issue in order to be able to fix it. Thanks in advance.

**Comment by ebial** [comment]
Thank you. I'm very sorry, I rarely check my mail.

a) what Structorizer version you use3.25. I've tried all versions but same problem
b) the operating system you work withWindows 10
c) the screen resolution of your computer.1920x1080
d) whether the font in the element editor is the only wee one or there other dialogs or controls of Structorizer also showing too small fonts.No. Only the element editor. Everything else seems to be working just fine. 

PS: I tried to update my JAVA, no results.
I have attached a screenshot. Thank you so much for your concern. Hope my answers will be useful

 

    În Luni, 14 Noiembrie 2016 16:26:23, Kay Gürtzig <notifications@github.com> a scris:
 

 @ebial Would you mind answering our questions? Please understand that we cannot fix a problem never heard of before without knowing the exact facts and circumstances. We need to reproce the issue in order to be able to fix it. Thanks in advance.—

**Comment by ebial** [comment]
As for the Look and Feel question. 

I've been using Windows version. The  element editor characters look bigger on the Nimbus and Metal version of Look and feel, but still not the normal size. Again, thank you 

    În Luni, 14 Noiembrie 2016 16:26:23, Kay Gürtzig <notifications@github.com> a scris:
 

 @ebial Would you mind answering our questions? Please understand that we cannot fix a problem never heard of before without knowing the exact facts and circumstances. We need to reproce the issue in order to be able to fix it. Thanks in advance.—

**Comment by codemanyak** [comment]
@ebial Unfortunately, your screenshot attachment didn't work. You might try again - preferrably directly in the [Github browser view](https://github.com/fesch/Structorizer.Desktop/issues/284) for this issue.
As a temporary workaround, you might try to append a line "scaleFactor=2" to the structorizer.ini file (having downloaded the most recent version [3.25-07](http://www.fisch.lu/Php/download.php?file=structorizer_latest.zip) before) as explained in the User Guide article [DPI scaling](http://help.structorizer.fisch.lu/index.php?menu=123), but this would (attempt to) scale up _all_ icons and _all_ fonts, so it won't be exactly what you need.
I might perform some tests with an independent scaling mechanism for the element editor (e.g. by buttons placed there or `Ctrl-Numpad-+` key binding but this is likely to interfere with the scaleFactor workaround just mentioned.

**Comment by codemanyak** [comment]
A working approach temporarily to enlarge or diminish the textfield fonts in the element editor by keys Ctrl-Numpad+ and Ctrl-Numpa-, respectively, is uploaded to bugfix3.25 branch and will be delivered with version 3.25-08

**Comment by codemanyak** [comment]
Now this is a preview of the new buttons in the element editor alllowing individually to scale up or down the text fonts within the element editor:

![inputbox3 25-08](https://cloud.githubusercontent.com/assets/15326471/20547316/77ace30c-b11b-11e6-8326-8cf44c4b4611.png)

Altenatively, the key combinations Ctrl-NumePad+ and Ctrl-Numpad- may be used to resize the fon,
Of course, one will have to be aware that the font changes aren't permanent.

**Comment by ebial** [comment]
I have tried the Ctrl-Numpad+ combination and it still doesn't work. Here is the screen shot. I'm using the 3.25-0.7 version.

![capture](https://cloud.githubusercontent.com/assets/23346153/20569812/b2834bc0-b1a1-11e6-8d0d-2380adb8e433.PNG)
![capture2](https://cloud.githubusercontent.com/assets/23346153/20569813/b2981726-b1a1-11e6-9b9b-3e4d2ca85081.PNG)

I use an Asus gl552vw by the way. Not sure if the laptop has anything to do with it but it really seems like I'm the only one with this problem,

**Comment by ebial** [comment]
As always, thank you.

**Comment by codemanyak** [comment]
1. As described in the User Manual, the file structorizer.ini should be colocated within a (possibly hidden) folder ".structorizer" in your home directory, which is by default "C:\Users\<user_name>", in a German installation seen as "C:\Benutzer\<user_name>.
2. The `Ctrl-Numpad+` and `Ctrl-Numpad-` keys still don't work in the most recent version (neither are the font up and font down buttons seen in the preview screenshot present by now), they were only introduced for version 3.25-08, which hasn't been released yet. I might instigate its delivery now, however, I think. Watch out for the changelog on the Structorizer homepage

**Comment by ebial** [comment]
Indeed, the "Scalefactor=2" makes a difference, but it looks unnatural. Actually, the "Edit element" box looks the way it should normally look, while everything other is sized up. I don't know what's wrong. 
![image](https://cloud.githubusercontent.com/assets/23346153/20607712/dd3ef308-b27a-11e6-8d50-2ff5182ee484.png)

Guess I can only wait for the 08 version :)

**Comment by ebial** [comment]
Oh there we go. The 08 version's font up and font down buttons seem to be just what I needed. Thank you very much for your concern and help ^^
![image](https://cloud.githubusercontent.com/assets/23346153/20607817/da407266-b27b-11e6-8f59-1b712ac4736b.png)

**Comment by codemanyak** [comment]
@ebial Don't mention it. Thank you for your feedback. I hope you enjoy working with Structorizer. I you happen to find some further details that might require improvements, please don't hesitate to report them. We'll do our best to provide maximum usability.

**Comment by ebial** [comment]
Okay. Thank you very much :) 

    În Vineri, 25 Noiembrie 2016 0:43:54, Kay Gürtzig <notifications@github.com> a scris:
 

 @ebial Don't mention it. Thank you for your feedback. I hope you enjoy working with Structorizer. I you happen to find some further details that might require improvements, please don't hesitate to report them. We'll do our best to provide maximum usability.—
