### ISSUE TITLE
Proposal: Latest version notification on Structorizer start

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#300]
With a respective new preference enabled, Structorizer might try to retrieve the most up-to-date version number from the Structorizer home page (e.g. by extracting it from the changelog page) and notify the user about the update opportunity after startup if this version is newer than the currently running one.
Likewise, in the About and the Update dialogs, the latest available version could also be placed if enabled to retrieve and if newer than the current version.
As mentioned above, this behaviour should require explicit enabling because I think applications must not inadvertently connect to some internet site.

**Comment by fesch** [comment]
I agree ...

Maybe if the option is not yet set, Structorizer may ask if the user want's it to check for new releases and instruct the user that this checking is optional and can be changed in the preferences?

We could also drop a simplified version file on the web server, so that parsing out the latest version will not be necessary ...

**Comment by codemanyak** [comment]
I like both of your proposals. Though the version parsing isn't that difficult (I already wrote a working piece of code for it), it's somewhat time-consuming and awkward. So I would highly welcome a lean version request URL.

**Comment by codemanyak** [comment]
With respect to the specific version URI, it must of course be ensured that it is automatically updated by the release script (the parsing of the changelog is supposed to work without extra mechanisms).
By the way, if such an automatic version number update for the web server were implemented then it might automatically place or rewrite a note on the News page of the Structorizer homepage, too (I think version number, date and link to the changelog page would be sufficient).

**Comment by fesch** [comment]
Of course. My release script generates a file that can be found here:

http://structorizer.fisch.lu/version.txt

It takes the string from the Elements.java class.

**Comment by codemanyak** [comment]
Great. Thank you!

**Comment by codemanyak** [comment]
Implemantation on bugfix3.25 branch
