### ISSUE TITLE
Proposal: Several diagram files to be opened in command line

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#306]
By now there is a strange mechanism in the command line evaluation of Structorizer.java: After having ruled out all batch import and export command line variants, the remaining arguments were concatenated (!?) into a single string which was interpreted as an NSD file path to be opened after Structorizer start.
If this was to address an file name containing blanks, then it doesn't make sense frommy point of view because:

1. If a file path contains blanks then it should be quoted in the command line such that it is handled as a single argument by the command line interpreter already.
2. If earlier versions of the Structorizer.exe wrapper (or Structorizer.sh respectively) may have failed to pass quoted arguments as a whole then this defect has alrady been fixed in version 3.24-11.
3. Glueing together the parts of a file name having contained blanks without these blanks won't reconstruct the file name but produce a non-existent file path.

Particularly because of item 3., in version 3.25-09 blanks were re-introduced into the concatenation. This led to an uncrucial inconvenience after having opened Structorizer by double-clicking an nsd file or by starting it from command line with a file argument: The internally cached file name of the diagram gets a trailing blank, which only becomes visible in the name of the backup file *.bak on saving a new diagram version. This is to be mended anyway.

But it suggests the following enhancement:
If the command line happens to contain more than one argument (after the optional command line option "-open") then let them be interpreted as separate files to be opened in series, each of them moving its respective predecessor into the Arranger such that all of them will be open after application start.

**Comment by fesch** [comment]
I agree.

The string concatenation was was needed for the first wrapper to work correctly ... but as this one is no longer in use, the concatenation is somewhat deprecated too.

**Comment by codemanyak** [comment]
Fx is prepared for version 3.25-10

**Comment by codemanyak** [comment]
The fix hadn't been delivered with version 3.25-10. Another consequence of the bux is that on starting Structorizer by double-clicking amn nsd file, the file name is pushed to the recent file list with a trailing blank. When the user tries to reload the file via the menu, just the Arranger opens without the file being loaded (because the trailing blank hinders file type recognition).
The bugfix is rescheduled for version 3.26-02.
