### ISSUE TITLE
Proposal: Context Menu für Arranger Index

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#319]
A Context-Menü would be nice for the arranger Index.
It could at least have the Option to create a new Diagram.

EDIT:
This would lead to a new Button to open the Index in the first place i guess.

**Comment by codemanyak** [comment]
A context menu might facilitate some functions indeed. I think of toggling the test-coverage mark for instance. The benefit of an opportunity to create a new empty diagram from the Arranger index looks rather limited in my eyes.
Actually, while the Arranger index isn't switched off altogether by Shift-F3, it will open automatically as soon as you push the first diagram into the Arranger and will vanish whenever the Arranger is emptied. The next version will alrady bring several substantial improvements: Deletion from index (with del key), asterisks with "dirty" diagram, automatic visibility of Arranger with a click into the Arranger index, displayed virtual file paths for diagrams extracted from a portabel archive (arrz file) etc.
I don't exactly imagine what you mean with the new button proposal.

**Comment by newboerg** [comment]
i meant an show/hide Arranger Index Button or Menu Item

**Comment by codemanyak** [comment]
> I meant an show/hide Arranger Index Button or Menu Item

This menu item has already been existing in the published version 3.25-11: `Diagram > Show Arranger Index?`. Or do I still misinterpret your request?

**Comment by newboerg** [comment]
oh well, i must have been using an old version or simply missed it. everything is fine then :-)

**Comment by codemanyak** [comment]
Here is a list of menu items a context menu in the Arranger index might possibly provide:

- fetch/adopt diagram (= enter key)
- remove diagram from Aranger (= del key)
- mark as test-covered (upto now Arranger button only)
- save unsaved changes of selected diagram

There isn't much more I can think of at the moment.

**Comment by newboerg** [comment]
My students would certainly approve an "magicaly solve my Problem" Option :-)Am 05.01.2017 4:25 nachm. schrieb Kay Gürtzig <notifications@github.com>:Here is a list of menu items a context menu in the Arranger index might possibly provide:
fetch/adopt diagram (= enter key)remove diagram from Aranger (= del key)mark as test-covered (upto now Arranger button only)save unsaved changes of selected diagram
There isn't much more I can think of at the moment.

**Comment by codemanyak** [comment]
This is a preview of the context menu (still without the "magically solve my Problem" item...)
![arranger_index_popup](https://cloud.githubusercontent.com/assets/15326471/21701956/02ca17a2-d3a9-11e6-988d-8538d7ba880a.png)

**Comment by codemanyak** [comment]
The decision to dye the text or text background of index lines the related diagrams got the test coverage marker was not very fortunate: It optically competes and interferes with line selection.
Furtunately this effect occurs only in Run data tracking mode (so most users won't ever see this ugly approach).
A way better solution is to use icons with green borders in these cases, which is also sound with the actual diagram representation and doesn't intefere with the look & feel text highlighting policy.
The change will be delivered with verson 3.26-01
