### ISSUE TITLE
Wrong saving strategy of Arranger on closing

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#321]
On closing, the Arranger is used to iterate through all diagrams placed here and to ask their respective Mainform to save possible changes. This causes annoying behaviour if several diagrams are owned by one and the same Mainform (if they had all been injected by it), which currently contains some dirty diagram: No matter for which diagram the Arranger is asking, the Mainform will (repeatedly) only care about its currently edited diagram but not the other ones associated to it - whether dirty or not! This means it the saving prompt for the same diagram will pop up several times (if always refused to save) but none for the other dirty diagrams belonging to it and causing the request.
Class lu.fisch.structorizer.gui.Diagram needs parameterized (with a differing Root) versions of methods saveNSD(), doSaveNSD() etc.!

**Comment by codemanyak** [comment]
Moreover, if the main Structorizer is closed then the Arranger isn't triggered to check the need for saving diagrams parked there. Instead all unsaved changes will get lost without warning.

The fix for both aspects of the problem is already uploaded to branch "bugfix3.25" and will be part of the next version.

**Comment by newboerg** [comment]
OT: where does Structorizer save its settings?

**Comment by codemanyak** [comment]
The settings are stored in a file "structorizer.ini" in a subdirectory ".structorizer" of your home directory.
Btw: You may explicitly save a backup of them in a different file via menu "Preferences > All Preferences ... > Save to file..." or load such a backup settings file via "Preferences > All Preferences ... > Load from file..."
