### ISSUE TITLE
Default Keywords

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#327]
Maybe we could change the default keywords to something more international...
![clipboard01](https://cloud.githubusercontent.com/assets/7376421/21716341/358f165e-d40a-11e6-925e-10b2a0c36636.jpg)
these are the default values

maybe something like:
if, select, while, until, for, for each

**Comment by codemanyak** [comment]
The french keywords are ther because Bob, the inventor of Structorizer, wrote it for Luxemburgish schools primarily where French is official language. So it is up to him to decide whether this default ought to be changed. I do also think that English (or say "international"?) keywords would be more helpful for beginners all over the world.
An idea would be to let the installation package contain several structorizer.ini files for English, French, and possibly other very common languages such that one of them can be loaded without much manual work.
Then Structorizer might on first start - i.e. if it doesn't find a structorizer.ini in its standard place - offer the choice among the prepared preferences file versions.

**Comment by fesch** [comment]
As in Luxembourg Structorizer lost a lot of importance and is not used anymore as much as before, I think this can be changed now, so: YES

**Comment by codemanyak** [comment]
Oh, possibly it's this what put the delivery of the release off a little... ;-)

**Comment by newboerg** [comment]
Suggestion, Bind those keywords towards localisation, andere and an English- programmiert language

**Comment by fesch** [comment]
No, no and no again. The UI lang should not be bound to the used keywords!

I love to have my UI in English but use french keywords in classes ...

**Comment by codemanyak** [comment]
Well, we have already had this discussion several times over the years. Though it seems sound at first glance, the coincidence between GUI language and preferred coding language is not as tight as it might seem. I might feel okay with a German menu but do definitely prefer English coding...
Oh, I just see, that Bob was faster than me with his answer.

**Comment by codemanyak** [comment]
@fesch 
Bob, are you changing the default keywords already or are you waiting for me to do that?

**Comment by fesch** [comment]
Actually I try to fix a problem in another application, so if you don't mind doing it ... 
Thx

**Comment by newboerg** [comment]
I did not meant to remove the option the change them by hand alltogether.
Just the default values when there is nothing set yet

**Comment by codemanyak** [comment]
I still think it might be better to offer just a choice on first start if several keyword sets are available. I'll think about such a mechanism. It will definitely not be part of release 3.26, we are at the brink of which.

**Comment by newboerg** [comment]
Or a few different defaults via dropdown menu in Parser Optionsscheine :-)

Oh and Element defaults should Change too when changing Parser options

**Comment by newboerg** [comment]
Optionsscheine == options ... Stupid Auto correct

**Comment by codemanyak** [comment]
Well, while I think about the proposal to offer a choice among several default keyword sets (independent of the remaining settings and preferences but the structure preferences), this issue should remain open.

**Comment by codemanyak** [comment]
By the way: How would "for each" be expressed in French? "pour tout" or "por chacun"?

**Comment by fesch** [comment]
pour tout

**Comment by GitMensch** [comment]
I don't suggest to set the keywords according to the GUI language but I think it would be nice to add this to the translatable strings.
This allows the Parser settings to get a new button "Set defaults from language ..." where you can choose the language file to get these strings from (ideally only the ones that actually contain the strings but this can be a post-step, too).

In any case it is reasonable to change the default when starting the application to the English strings.

**Comment by codemanyak** [comment]
@GitMensch 
Yes the default keywords were changed to English with release 3.26 on January 6. And I'm already breeding over a solution to select among different keyword sets, but it will rather be a choice list on the Parser Preferences dialog.

**Comment by GitMensch** [comment]
Sounds like the FAQ on the website is behind this change.

**Comment by codemanyak** [comment]
After some re-consideration, I am now about to follow the suggestion of @GitMensch:
> I think it would be nice to add this to the translatable strings.
This allows the Parser settings to get a new button "Set defaults from language ..." where you can choose the language file to get these strings from (ideally only the ones that actually contain the strings but this can be a post-step, too).

**Comment by codemanyak** [comment]
The Parser Prefereces dialog will be equipped with an additional button that pops up a menu with all locales containing translated parser keywords:
![parserpreferences3 29-05locales](https://user-images.githubusercontent.com/15326471/53702712-2c93f580-3e0a-11e9-8650-45c4a9c6689b.png)

The language-specific configuration can be done via the Translator; a new section (tab) "Keywords" was dedicated for this purpose:
![grafik](https://user-images.githubusercontent.com/15326471/53702785-03c03000-3e0b-11e9-913e-640e7395e0d1.png)
