### ISSUE TITLE
Enhancement: Change Ctrl+Shift+Z for redo to standard Ctrl+Y (or add)

### ISSUE THREAD

**Issue by Fabian42** [fesch/Structorizer.Desktop#344]
The standard key combination across most programs in Windows and Linux to redo an operation is Ctrl+Z. To allow quick keyboard usage of the program, it should use the standard.
The current key combination Ctrl+Shift+Z doesn't have to be removed for this enhancement, the two can be equivalent.

**Comment by codemanyak** [comment]
Thank you for your suggestion. The undo operation has key binding Ctrl-Z binding as usual. Obviously you refer to the REDO operation, which is associated with Ctrl-Y in most applications whereas Structorizer uses Ctrl+Shift+Z. Structorizer is not allone, though: Other applications also use Ctrl-Shhift-Z over Ctrl-Y, e.g. Blender.
Your proposal to offer both is a good idea, therefore, though the menu will only be able to show one of the key bindings. I think it makes sense to keep showing the less common one of the two key bindings there.

**Comment by Fabian42** [comment]
Yes, I meant redo, thanks. Edited.

**Comment by codemanyak** [comment]
Fix is uploaded to bugfix 3.26 branch and scheduled for version 3.26-03
