### ISSUE TITLE
unable to launch the application on Windows 10

### ISSUE THREAD

**Issue by IrisLuc** [fesch/Structorizer.Desktop#352]
Structorizer.jnlp: Error: a JNI error has occurred, please check your installation and try again
[Exceptions.txt](https://github.com/fesch/Structorizer.Desktop/files/803588/Exceptions.txt)
[LaunchFile.txt](https://github.com/fesch/Structorizer.Desktop/files/803589/LaunchFile.txt)
Java version: 8 update 121

Latest version for Windows and Linux: same message

3.26 works but I am prompted that a newer version 3.26-04 is available.

**Comment by codemanyak** [comment]
I can reproduce this effect on Windows 7, too, with JavaWebstart. Unfortunately the exception text isn't actually very helpful as it doesn't tell the name of the missing class or method. At the moment the download of the zip file is blocked on my site, such that I can't test the download version. I will have to do it in  the evening in a differnt net context. My local development jar file works. I attach it here zipped. So you could replace the Structorizer.jar being part of the structorizer_latest.zip from the Structorizer homepage with it and try locally.

[Structorizer.zip](https://github.com/fesch/Structorizer.Desktop/files/804353/Structorizer.zip)

Meanwhile we will analyse what went wrong with the released file. Sorry for the troubles.

**Comment by codemanyak** [comment]
The download clarified the phenomenon a little: The Structorizer.jar in the version currently available as structorizer_latest.zip from the [Structorizer homepage](http://structorizer.fisch.lu) is mutilated i.e. it has about half the size it should have got!
Something must have gone wrong on confectioning the version.

**Comment by fesch** [comment]
I recompiled the package and uploaded everything anew. Please try again ...

**Comment by codemanyak** [comment]
Works on my platform. Thanks, Bob!

**Comment by IrisLuc** [comment]
It's working perfectly. Thank you.
