### ISSUE TITLE
Idea for Enhancement: add a "Report an issue..." option in help menu

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#355]
Something like [QCrash](https://github.com/ColinDuquesnoy/QCrash/) provides for applications using Python QT:
* directly create an issue at GitHub via its API, ideally with the option to send it via mail
* include version / system information (with the option to revise this before it is sent)

**Comment by codemanyak** [comment]
Ooh, nice idea. But the question is whether the gain on convenience justifies the efforts to do it. Structorizer is possibly not just as widespread as Python or QT?

**Comment by GitMensch** [comment]
I *guess* there's a Java class that does a similar thing than QCrash which may can be integrated (and/or extended). In this case it should be worth the inclusion.

**Comment by fesch** [comment]
Maybe something like this?
http://github.jcabi.com/

**Comment by GitMensch** [comment]
Actually JCABI looks like a full library with zero GUI, there is maybe something better which already adds the system information etc.
But something like JCAPBI's `repo.issues().create()` used from a minimal GUI similar to the screenshots at the QCrash page is the idea.

**Comment by GitMensch** [comment]
Just leaving a ping here, before reporting the next issue manually ;-)

**Comment by codemanyak** [comment]
While there are some full GitHub API libraries around (e.g. https://github-api.kohsuke.org/), I haven't found a lean Java access library just for creating GitHub issues yet.
And I'm still wondering for whom this dialog would be implemented. Having a look in the issue history, so it's mainly you (@GitMensch), Rolf and me who are "power issue generators". We usually know what we do and are pretty familiar with GitHub directly. Others would first have to sign on (I wouldn't like to create a sign on proxy in Java). And still there is a sign in needed for already registered GitHub users. Would I like to integrate a login dialog, raising phishing allegations? Rather not. What's left is an email client proxy to Bob. And that's it?

**Comment by GitMensch** [comment]
@codemanyak It could also provide information that otherwise would need to be asked and/or manually added:

* system (Java version, OS, screen size, dpi, ...)
* sysout/syserr trace
* optional: screenshot from Arranger and/or main window

But there are many open issues already and you're right - we can live without it.

I'm closing this issue now as "possibly postponed".
