### ISSUE TITLE
Debugger Window cannot be closed with 'X'

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#356]
Using current version by Java Web Start on Win 10 with current Java Runtime.

All other windows in Structorizer can be closed with the window control 'X' in the upper right corner but the debugger window can only be closed by pressing the stop button.

**Comment by codemanyak** [comment]
RTFM? It had too frequently been closed inadvertently that this closing opportunity was disabled. It would possibly have been nice to remove the button altogether or to pop at least a message that the stop button should be pressed, of course. Or maybe the effect might be dependent on whether an execution is running or not. I'll think about it.

**Comment by GitMensch** [comment]
A Message box when executing (maybe with yes/no) and a direct close if nothing is running sounds *very* reasonable :-)

**Comment by codemanyak** [comment]
Fixed in development branch codemanyak/Structorizer.Desktop/master.
