### ISSUE TITLE
How to create distribution tarball from git repository?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#359]
The dist tarball doesn't has everything in that is stored in the git repository, which is fine. But it misses the following files from the dist tarball and I don't see any obvious possibility to generate them and no entry in README how to do so:

* .classpath
* .project (the thing that is missing to use import -> project from git in eclipse)
* gpl-3.0.txt
* makeBigJar
* makeJar
* makeStructorizer
* startStructorizerAgain
* structorizer.big.manifest
* structorizer.manifest

Note if anyone wants to open Structorizer in Eclipse this is my workaround:

* manually git clone the repository
* in Eclipse use "New Project...->Java Project from Existing Ant Buildfile" choose `build_exclipse.xml` and start as Application -> Structorizor
* set the properties for the src package: Text file encoding: UTF-8

**Comment by fesch** [comment]
.project will be included in the next source package. All other files a use specific script. People who want to have the source are encouraged to use the git system anyway.

**Comment by GitMensch** [comment]
Please help me to understand this: How should people start when they cloned the sources? I just tried and the procedure above worked for me, it just seems a little bit strange and not correct.
Where can I get "the specific script" from? Is there any reason to not place everything needed for preparing a distribution into the git repo? A script that downloads stuff or invoke tools would be OK, too.

**Comment by fesch** [comment]
I can't provide these scripts, because I don't have them. It's as easy as that ...

So these scripts are not needed at all for packaging Structorizer. All you need to do is use the "Build" feature your IDE is providing. For e.g. NetBeans, a folder "dist" is being generated which contains everything needed to distribute the compiled code. No scripting needed here ...

**Comment by GitMensch** [comment]
A non-IDE build seems to be directly possible with the existing scripts makeBigJar, makeJar, makeStructorizer, startStructorizerAgain - can I suggest to add them to git? I assume it wouldn't harm to add gpl-3.0.txt, too.

**Comment by fesch** [comment]
@codemanyak : could you add the files please?

**Comment by GitMensch** [comment]
I should have explicit mentioned this before: I've talked about the files in the [source code release](http://www.fisch.lu/Php/download.php?file=structorizer_latest_src.tar.gz) linked at  http://structorizer.fisch.lu/

**Comment by fesch** [comment]
I know.
This is why I asked @codemanyak to add the file to the repository, so I will get them too in order to include them in the next package ...

**Comment by GitMensch** [comment]
Sounds good. I still suggest to reopen the issue until this is done but maybe @codemanyak added them already in the meanwhile ;-)

**Comment by GitMensch** [comment]
I've rechecked this and can report that the following works now: "Start Eclipse -> Import ... -> Projects from Git -> Clone URI -> [... Git steps ...] -> Import existing Eclipse projects
Start as Java Application works.
There are some things I have to recheck for the scripts and the Eclipse Project, I'll likely add some comments for this later.

All files needed for creating a distribution tarball seem to be in now (with a `cp ./src/lu/fisch/structorizer/gui/gpl.txt ./gpl-3.0.txt`) so this part is finished, too.

But the main original question is still open:
How to create distribution tarball from git repository? Is there any script for this already? If not: is it done from within the IDE or manual?

**Comment by GitMensch** [comment]
Ping:

> How to create distribution [the ones found in the source code release] tarball from git repository? Is there any script for this already? If not: is it done from within the IDE or [is this a] manual [procedure]?

**Comment by fesch** [comment]
I do it in NetBeans using the button called "build".

**Comment by GitMensch** [comment]
I only see options to create jars or maybe exe files, not a source tarball - is some build file you're using missing in the git repository?
