### ISSUE TITLE
Is there any reason to keep lu.fisch.structorizer.generators._old ?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#360]
It looks like the files in this package were updated and stored in-tree - but isn't it enough to keep the old ones in git history?

**Comment by fesch** [comment]
No reason ... just maybe a old fear to loose something ;)

**Comment by GitMensch** [comment]
Don't fear my friend, you use a distributed vcs - even if you only end with a plain checkout of the current version and the git repository here vanishes there are multiple others storing the complete repo for you by doing `git clone` :-)

**Comment by GitMensch** [comment]
Further _old's are:

* src/lu/fisch/structorizer/executor/Control_old.java
* src/lu/fisch/structorizer/executor/Executor_old.java
* src/lu/fisch/structorizer/executor/Executor_old2.java
* src/lu/fisch/structorizer/io/Ini_old.java

Are any of them still needed?

BTW: some of these are in `.classpath`, too.

**Comment by codemanyak** [comment]
At least I wouldn't miss any of them :wink: ...

**Comment by fesch** [comment]
Then go ahead an delete them in your branche. I won't miss them either ;)
