### ISSUE TITLE
Request: Add option to "Refocus turtle after INPUT"

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#366]
Right now an "input"  statement brings the Structorizer main window up to the front. i guess it's because the input windows is a child of the main window. After the user enters the Value the Main window keeps the focus. Would be nice if the turtle would get the focus again if it had it prior to the statement.

**Comment by codemanyak** [comment]
Well it could as well be the Executor conrol or the Aranger that had may have had the focus before. Unfortunately they are different frames such that only the operating system may know which of them had had the focus before. ould even have been a different application :wink:. I will research a little how to get hold of the window stack... But it's not aong my most urgent whereabouts.

**Comment by newboerg** [comment]
Why Not let The Turtle window Spawn the input dialogue this way there would be no findeling around with Windows

**Comment by codemanyak** [comment]
The Turtleizer has nothing to do with the input. The Executor controls the debugging process. The Executor knows of course if there is a "diagramController" plugged in. But it has no clue who owns the window focus. It might rather assume it was the executon control panel...
Maybe I find a strategy whom (i.e. which widget, frame or whatsoever) to saddle on the damned responsibility for the Input dialog. (It might also hold for the output dialogs if they aren't suppressed by the open log window.)

**Comment by codemanyak** [comment]
Fix is prepared to be delivered with version 3.29-05.
