### ISSUE TITLE
Minor: Cannot move multiple elements by mouse

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#374]
Steps to reproduce:
* select an existing element with [LEFT-CLICK]
* use [SHIFT] + [LEFT-CLICK] to select a range of elements

What does work:
* use [CTRL]+[X] or the cut button in menu bar
* use [CTRL]+[V] or the insert button in menu bar

What does not work:
* move the selected items by mouse (only a single item is moved)

Possible approaches:
* remove option to move by mouse completely (this would be perfectly fine) *or*
* implement moving of multiple elements

**Comment by codemanyak** [comment]
Sorry, I had tried but it didn't work out. There is too much interference on dragging a bunch of multiple elements. Therefore I decided to abandon the efforts. But I don't see why I should sacrifice he dragging functionality for single elements only because it doesn't work safely for subsequences.

**Comment by GitMensch** [comment]
OK :-)
