### ISSUE TITLE
[FR]: Open NSD in child window, allowing mulitple NSD in one Structorizer instance

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#375]
Likely not so easy to implement as it has side effects on the debugger, validator (which must use the current NSD's keywords), ...

**Comment by codemanyak** [comment]
I think, the Arranger index is a better approach after all. Usually you won't be able to edit several diagrams simultaneously. In a tabbed approsch, you would have to flip them anyway. If you ry to arrange several subwindows, it's of littel benefit as well. Using Arranger as the hub, you can eithe use the same Structorizer Mainform to swicth among the diarams via the Arranger index or by double-clicking the diagram in the Arranger. By double-clicking diagrams not associated to the main Structorizer instance in rranger you would open additional (dependent) Structorizer instances (detectable by the number in the title). By double-clicking diagram files in the file mangaer, you would ope independent frther Structorizer instances.So you can have as many of them as you like.
This isn't perfect. But the multi-document approach won't be perfect either. I hesitate to make up too many alternative ways to do things. Absolute freedom tend to be absolute chaos.

**Comment by GitMensch** [comment]
Yes, the Arranger seems to be a powerful tool.

> I've just found out about the Arranger shortly after the creating the issue.
> Can you point me to a multi-NSD sample which shows the effects of the Arranger please?

I'd like to recheck how to work with multiple NSDs and new NSDs with the Arranger.
