### ISSUE TITLE
Cannot copy/move elements between NSDs

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#376]
Copy on the complete program/sub places the current NSD's complete XML structure to the clipboard. Nice feature but it isn't possible to use "paste" on a new NSD (for duplicating it), but the workaround Save-As + Opening the old one with a new Structorizer instance (as multiple files per window isn't supported) is OK.

Copy / Cut on a single entry doesn't do anything with the clipboard, therefore a paste to another NSD is not possible (because multiple files per window aren't supported, see #375).

The only workaround is:
* close the target file (needed as the close function is not available, see #371)
* copy the complete NSD to clipboard
* opening a text editor and insert the NSD's complete XML
* opening the target file in a text editor
* manually copy the elements and manually insert them
* close/save
* open target NSD

This issue is therefore about placing the XML nodes of the elements cut/copied into the clipboard and insert them from clipboard in a different Structorizer instance.

**Comment by codemanyak** [comment]
There are definitely more workarounds:
Why don't you simply use "save as" and reopen this renamed file either in the same or a different Structorizer instance?
Another simple approach is to use the Arranger as hub. Open Arranger by pushing a diagram to it via the menu or the "arrange" button. Now you can open another Structorizer, open a file there, copy it to the clipboard and paste it to the Arranger. By double-clicking the diagram copy in the rranger a new Structorizer instance will open and allows you to edit the copy etc.

**Comment by GitMensch** [comment]
"Save As" is my mentioned workaround for a complete NSD. The issue is mainly in copy+paste of some elements (single or multi elements) where a Save-As of the complete file won't help at all.

I've just found out about the Arranger shortly after the creating the issue.
Can you point me to a multi-NSD sample which shows the effects of the Arranger please? I'll recheck how to copy + paste elements between NSDs with the Arranger in between.

**Comment by codemanyak** [comment]
Well no, copying elements between different diagrams doesn't work, not even among Structorizer instances of the same process. This is an enhancement issue. I didn't read carefuly enough. I'm sorry.

**Comment by codemanyak** [comment]
The trivial fix to allow copying elements (also multiple elements of course) among diagrams (at least within the same application) is now prepared and scheduled for 3.2-05 (if it won't be absorbed by the dawning new release 3.27)
