### ISSUE TITLE
auto-generated and auto-deleted files in git repository

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#381]
I'm not sure how much of this only happens if the checkout and build is done with the tested environment (Eclipse Neon on Windows) but I assume this is a general issue.

I've opened the project directly from git import and used Run As->Java Application->Structorizer and the following changes are placed in Git Staging:

Deleted:
* bin/lu/fisch/structorizer/gui/icons/${languages}.png (045_fr, 046_uk, etc)
* bin/lu/fisch/structorizer/gui/${languages}.txt (chs, cht, cz, de, en, etc)

Changed:
* bin/lu/fisch/structorizer/gui/icons/077_bubble.png
* bin/lu/fisch/structorizer/gui/icons/079_marker.png
* bin/lu/fisch/structorizer/gui/icons/100_diagram_drop.png
* bin/lu/fisch/structorizer/gui/icons/103_breakpt.png
* bin/lu/fisch/structorizer/gui/icons/104_nobreakpt.png
* bin/lu/fisch/structorizer/arranger/Arranger.form
* bin/lu/fisch/structorizer/executor/Control.form
* bin/lu/fisch/structorizer/gui/changelog.txt
* bin/lu/fisch/structorizer/gui/license.txt

Created:
*  bin/.gitignore (possibly with the wrong content, see below)

```
/Structorizer$1.class
/Structorizer.class
/Structorizer.clean
/StructorizerApplet$1.class
/StructorizerApplet.class
/com/
/goldengine/
/jsesh/
/lu/
/net/
```

The issue may be solved with removing some of these files from git and place them into .gitignore and/or change the build scripts.

**Comment by codemanyak** [comment]
I guess major parts of the bin folder (if not the entire folder and its contents) should be put to .gitignore because its content is created or updated during he build phase. The resources from the src folder are also copied to the bin folder (e.g. changelog.txt). So it doesn't make much sense to let the bin folder be watched by the source code management.

**Comment by codemanyak** [comment]
I guess, it might be even more sensible to place a .gitignore file with content

    /bin/

in the root directory, wouldn't it?

**Comment by GitMensch** [comment]
Yes, please go ahead, commit the gitignore file while deleting the bin folder from master.

**Comment by codemanyak** [comment]
Wether the directory may actually be removed from master depends on the way Bob's release script works (whether it runs locally or on the server). I won't meddle there. It's up to Bob to maintain the repository.
Actually it seems quite sufficient to have this .gitignore file in the local copy.

**Comment by GitMensch** [comment]
Ping @fesch Are you OK with removing the bin folder and/or add a `.gitignore` file with the content `/bin/`?

**Comment by codemanyak** [comment]
@GitMensch 
As far as I can see there is a .gitignore file with content "/bin" in the repository. Can this issue be closed now?

**Comment by GitMensch** [comment]
@codemanyak No, this issue cannot be closed as gitignore doesn't match the repository, can be closed after integrating https://github.com/fesch/Structorizer.Desktop/pull/460
