### ISSUE TITLE
Enhancement idea: support for constants in Structorizer

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#388]
The concept of constants might be supported by Structorizer.
Rough sketch: The easiest way seems to be to introduce a keyword, preferrably "const" or "constant" (configurable?) to be placed at the very beginning of an otherwise usual assignment line (same assignment operator, i.e. "<-" or ":=", in contrast to Pascal where an equality symbol is used instead) in an Instruction element to mark it as constant definition.
Root should hold an additional look-up set of constant names such that any attempt to reassign a variable declared as constant can be identified and prevented (Analyser, Executor).
The variable display in the debugger should reflect the constant attribute in an appropriate way (additional column or perhaps a different line colour).
For scalar data types, ensuring constantness should be rather easy (though e.g. the use of constants in `inc` and `dec` procedures must be supervised and prevented). For array variables, however, this may get pretty tricky, particularly if passed as argument to a routine. Hence, the concept of constant arguments would have to be supported, too: Like in C++, Structorizer must not allow to call a routine with a constant argument if the routine does not guarantee to respect the constancy of the respective parameter. This is not exactly relevant for scalar types, though, so it is up to the executor at run-time to decide according to the type of the current argument whether the routine must assure the constantness of the parameter with a "constant" keyword in its signature.
This idea came up during implementation of #354 where we frequently have to deal with import of constants.
Comments?

**Comment by codemanyak** [comment]
Well, there is just another thought coming to my mind: What about a new preferences category "global definitions" where e.g. constants might be placed that are globally valid for all diagrams?
This might also be a place for imported global definitions - though there might be the need for some conflict handling.
I haven't thought about a suited structure yet. As GUI possibly some kind of editable JTable like in the debugger Control?
(And then what about global type or class definitions...?)

**Comment by GitMensch** [comment]
Comment: Support for constants would be nice.
Instead of adding multiple GUI options for global/project specific constants (or type/class/function definitions) there is a much more clean and easy way to do it (once there is an option to include them in a NSD): add an "import NSD" instruction (which ideally can be "nested"). 
This way only the NSD files that need these definitions can have them in, the definitions aren't saved as "application/user setting" (which would work on one PC but with the same set of NSD files not on another one) but as "source" (which they *are*), nice side effect: it saves the work for adding GUI options (and handling issues "this worked until I got a new PC").

**Comment by codemanyak** [comment]
> add an "import NSD" instruction (which ideally can be "nested").

Wow, this is really a clever idea! In a way, it might work like a "call" instruction with the difference that the changes to variables etc. are shared with the caller instead of being held local (i.e. the virtual machine is shared rather than nested). Might even look like a call, therefore. Se we need an unambiguous keyword. Your proposed "import" doesn't sound ideal but I can't propose something better ("involve"?, "include"?, "merge"?). So may it be "import" for now.

**Comment by codemanyak** [comment]
Opened a separate issue for the proposed "import" instructions.

**Comment by codemanyak** [comment]
The Analyser should have a check that the value assigned to a constant is a constant expression i.e. only composed of constant values (literals and other constants).

**Comment by codemanyak** [comment]
A problem on assigning an array to another variables (or constant) must be solved. The executor used to place a reference in the target variable rather than a copy. This would now get absurd if one of the two variables is declared as constant. Imagine the following cases:
```
const a <- {3, 6, 9}
b <- {"foo", "bar"}
c <- a
const d <- b
a[1] <- 17              **REJECTED BECAUSE OBVIOUSLY ILLEGAL (ok)**
b[2] <- "dubious"      **APPARENTLY OK BUT ILLEGAL CHANGE TO d!**
c[0] <- -34             **ALSO ILLEGAL BECAUSE OF BEING REFERENCE TO a**
e <- {a, b, c, d}        **ELEMENTS OF e MAY NOW BE REPLACED BUT NOT CHANGED!**
```
This is not quite easy to fix. It's quite simple to keep track of the nominal constantness of a variable as assignment target, but we must now also analyse the potential constantness of expression results (what if a function returns a reference to a constant array?).
Shall we reject the assignment of constant objects (arrays) to variables? Shall we reject the definition of constants with mutable objects (arrays) as value? Or shall we produce copies in these cases? Would the latter also have to apply to elements `a` and `d` on the initialization of `e` in the example above? Later on it would no longer be trackable. Would require a pretty deep expression analysis on execution...

**Comment by codemanyak** [comment]
Well, I found a pretty elegant (though possibly resource-intensive) solution: If the identifier of a constant array (say "foo") occurs as token in an expression then it's internally replaced by "foo.clone()" before the evaluation is done. Conversely, if the value of a constant definition had been evaluated to an array then it's cloned before the value is set. This works pretty fine at least on the outer array level, which might per definition be what's required.
This mechanism may also be applied for passing arguments to called subroutines or on returning results, thus automatially solving the subroutine problem without the need of checking whether the constant status matches between formal parameter and actual argument.

**Comment by codemanyak** [comment]
Still to do:

- [ ] Analyser
- [ ] Parsers
- [ ] Generators.

**Comment by codemanyak** [comment]
Code generators for Pascal, C, C++, and Java updated to handle constant defintions.

**Comment by GitMensch** [comment]
Wow, seems like the last point "code generators" is nearly finished, too.

Do you plan to update the other generators, too or should this ticket be closed and the other generators be left for another ticket (=later version)?

**Comment by codemanyak** [comment]
> Do you plan to update the other generators, too, or should this ticket be closed and the other generators be left for another ticket (=later version)?

Of course I do (meaning the first of the two options), unless I bump into some severe difficulties with some languages. Then of course I might postpone their revision.

**Comment by codemanyak** [comment]
Some export languages don't support constants in a clear way, so the relevant existing generators are done (codemanyak/Structorizer.Desktop/master). Will be part of release 3.27
