### ISSUE TITLE
Debugger button control doesn't work properly in step mode

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#391]
In step mode, the player buttons as well as the call stack button aren't properly handled:

- The call stack button stays disabled though it should turn active after a step is done.
- Once the call stack button is active (after having started with the play button and then paused via pause button or breakpoint) is not set disabled during subsequent step execution (obvious with noticeable delay).
- Step and Play buttons remain active during step execution (this is verifiable with extreme delay).
- Pause button remains inactive (well, this is redundant because the execution will be paused after the step, anayway). And though it might be nice to enable it during step execution in order to avoid user panic on huge delay, this is not recommended due to the toggling effect of the pause button - pressing it during step execution would induce the opposite effect: the step mode would turn into a run mode. So it should stay inactive (this way run can be told from step mode during the activity phase)

**Comment by codemanyak** [comment]
Fixed in branch codemanyak/Structorizer.Desktop/master

**Comment by GitMensch** [comment]
When do you plan to merge codemanyak/Structorizer.Desktop/master with fesch/Structorizer.Desktop/master?

**Comment by codemanyak** [comment]
Well, my idea was to wait for the COBOL stuff, to merge this e.g. into my branch (i.e. definitely not directly in the fesch/Structorizer.Desktop/master - the master should only contain tested and releasable code) then to scrutinize the resulting version thouroughly (both on your and my branch) and then, after it had undergone and passed the tests, induce a pull request on fesch/Structorizer.Desktop/master as last and final step.
So, what I'd like to recommend you is that you either fork from my master branch or pull the content of my master branch into your fork cloned from fesch master. Then we would merge it among our versions until is sufficiently stable and create the eventual pull request for the release.
If you think the COBOL additions will take significantly more time, however, then I might finish release 3.27 still witthout it and we add the COBOL stuff (together with other possible fixes and accomplishments) as a follow-up version.

**Comment by GitMensch** [comment]
I'm able to add the COBOL import as-is, allowing manually pre-modified more-or-less COBOL74 (this what the GOLD 85 is), but the last step "convert tokens to Structorizer elements" is done zero percent. Still better than "nothing" in but nothing that a user would see.
Using the GnuCOBOL grammar allows a much better code import and may need one complete day to finish to the same level (possible beginning of May 2017) - the "convert tokens to Structorizer elements" parts would still be open... (I hope you may do some first parts of this).

So it is on you to decide on the merge plan, given the time table above.

**Comment by codemanyak** [comment]
Well, while there are enough other open issues in the pool here I'd like to solve befor release 3.27 is going to be shipped, we may postpone the decision a little. Anayway I'll have to learn the COBOL grammar to understand what has to be done on diagram generation.
Does the GnuCOBOL grammar completely cover the COBOL74 (or GOLD COBOL 85) language? Then it would of course be worth waiting for the GnuCOBOL import before we ship anything of it. I will certainly have enough things to do to fill my time till May :wink:.
While no urgent support case occurs we have no pressure to force the release in a premature state.

**Comment by GitMensch** [comment]
The GnuCOBOL grammar is the best free COBOL grammar you'll see. COBOL74,85,2002,2014 + vendor extensions :-)

Let's end the off-topic discussion here ;-)
