### ISSUE TITLE
Add GUI options for code import, stored in parsers.xml

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#392]
Moved from #354 

Given that we have parsers.xml already for telling the GUI *which* parsers to show it would be nice to be able to telling the GUI there which options the user has for tweaking the import.
The parser is of course free to read or not read a configuration value but it is currently not possible to set any configuration options for a specific import. I suppose something along (this FR is not about the values in this file, this is just a sample [which may be actually useful for the COBOL parser, but this is a different topic):

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<plugins>
	<!-- a plugin needs to have a title and a class -->
	<plugin title="Pascal" class="lu.fisch.structorizer.parsers.D7Parser" />
	<!-- a plugin may have optional attributes like an icon -->
	<plugin title="ANSI-C" class="lu.fisch.structorizer.parsers.CParser" icon="c.png" />
	<plugin title="COBOL" class="lu.fisch.structorizer.parsers.COBOLParser" icon="cob.png">
		<!-- a plugin may have parsing options to choose from, needs at least a type attribute, values can be resolved only for options with a name attribute -->
		<option type="text" name="includes" help="List of directories where copybooks are resolved from"/>
		<!-- the type attribute is used for minimal validation and for defining the control to draw -->
		<option type="number" title="tab length" default="8"/>
		<option type="checkbox" name="free-form" help="use free-form reference-format, otherwise fixed-form reference-format is used"/>
		<!-- depending on the type an option may have sub-items -->
		<option type="radiogroup" name="sub-diagram" title="generation of sub diagrams" default="1">
			<option type="item" value="0" title="no sub diagrams" />
			<option type="item" value="1" title="sub diagram for sections" />
			<option type="item" value="2" title="sub diagram for paragraphs" />
		</option>
	</plugin>
</plugins>
```

with something like

```java
   String pSIncludes;
   int pSTabLength;
   bool pSFreeForm;
   int pSSubDiagram;
   setValueFromParserSetting("includes", pSIncludes);
   setValueFromParserSetting("tab-length", pSTabLength);
   setValueFromParserSetting("free-form", pSFreeForm);
   setValueFromParserSetting("sub-diagram", pSSubDiagram);
```

Maybe "hide" these settings in the Import Dialog by putting them in a "Parser Options" button (de-activated if the parser has no option defined in parser.xml) and showing a dialogue window if it is pressed.

> Would just a text area (per language) be good enough here (for now) that leaves it to the specific parser to make sense of the respective plain text?

If the approach above is too much for now an unstructured text that needs to be split by the parser (as it is done with the generator for the standard-includes to generate) is not as nice as the one above but would work, too.

**Comment by GitMensch** [comment]
Additional to these options the dialog we should give the user an option to choose the encoding (see #354 for some details) - it is currently fix "per run" (defaulting to "UTF-8", may be changed with `-e encodingname-that-hopefully-is-correct` on process startup) and may get a setting option as temporary workaround. But obviously the files may have different encodings, so importing should be source file specific.

In the new options that are tracked in this ticket I suggest to add another one that isn't set in the parser.xml but always active for each language: the encoding, something like a combo-box would be nice, maybe additional with an option "auto detect", realized with something like [jChardet][1] - but I wouldn't give this a too high priority for now, maybe we should open a FR ticket for this if it is possible addon.

[1]:http://jchardet.sourceforge.net/

**Comment by codemanyak** [comment]
As already outlined for #354, a combobox for selecting the import file encoding has already existed for long. (It just hadn't had an effect for Pascal / Delphi 7 import because the grammar still uses `{Printable}`. Unfortunately I can't derive a new cgt or egt file because the grammar file contains to many conflicts. I will have to repair the grammar first.
An auto-detection attempt would of course by nice. Thanks for the hint to jChardet.

**Comment by GitMensch** [comment]
It would actually make sense to have all settings that are currently available "global" for all imports to the file-specifc import options.

**Comment by codemanyak** [comment]
No, from my point of view we should hold all options that are not language-specific as global settings. I don't see that the character set is a language-specific option. Neither are the saving of the parse tree or the decision whether to import mere variable declarations.

**Comment by GitMensch** [comment]
It is up to you but I think this is not about being language-specific but even about being file-specific. One may wants to import declarations for importing code1.file but not for code2.file - and both files may or may not share the same encoding.

**Comment by GitMensch** [comment]
I've seen that you've added this already and with the xsd we already have the technical doc about the option types we can use.
do you want to add more options for Pascal/C/COBOL before closing this?
The only other thing I see is adding an entry referencing the xsd you've created (even if the validation doesn't work currently it is good as a technical reference).

**Comment by codemanyak** [comment]
@GitMensch 
At the moment I don't see the need to add more C or Pascal options (except the "typeNames" option for C discussed today, which I had simply forgotten). If you can think of further sensible options for COBOL, we (i.e. you) might add them, of course.
(For some later version, I'm breeding about consistent localization support for these options. From a logical point of view, it should be provided by the XML files, themselves, but this extra dimension is likely to make the XML unreadable nad hard to configure, thereby inducing a high inconsistency risk.)
