### ISSUE TITLE
Icon redesign

### ISSUE THREAD

**Issue by rugk** [fesch/Structorizer.Desktop#4]
I'm sorry, but these icons are really not nice. Especially the software icon is a pixelated image of white, grey and yellow, which especially looks bad in higher resolutions than 16x16 pixel.

The software buttons also look quite outdated could be more intuitive.

**Comment by codemanyak** [comment]
@fesch Just a technical hint: Ico files may have to be used in future (they consist of up to 20 PNG files of cascaded resolutions). They may be produced with tools like GIMP or (if the PNG files are already prepared!) by certain online services (e. G. http://icoconvert.com/Multi_Image_to_one_icon/). I'm still lacking experience how to work with them and whether their use is platform-independent.
Of course, the issue rather addresses the aesthetic icon redesign but essentially we have to cope with an increasing range of end devices with very different display resolutions. So the "one size fits all" approach will hardly be an option any longer.

**Comment by fesch** [comment]
All icons may be easily and dynamically replaced. I think this will not be very hard to do.

**Comment by rugk** [comment]
If possible SVGs would of course be the best solution...

**Comment by fesch** [comment]
Never tried to load SVG into Java, but why not. First of all we need new icons ;-)

**Comment by GitMensch** [comment]
When thinking about #81 I've just tested a simple SVG conversion. This actually leads to different icons (which could be exported to standard ico format containing different sizes too - if svg is no option). Here are the rounded and not rounded versions of file new and sub-diagram without any other changes in Inkscape:

![grafik](https://user-images.githubusercontent.com/6699539/27326729-97d59fee-55ac-11e7-9614-21f2ecb5635d.png)

The actual conversion is powered by [Potrace](http://potrace.sourceforge.net/).

Just as an idea...

As another sample: cut (rounded, on the left there's the original png):
![grafik](https://user-images.githubusercontent.com/6699539/27327065-9e4f5a62-55ad-11e7-84eb-1b00287671da.png)

**Comment by codemanyak** [comment]
Your examples rather suggest redesign of the icons, possibly directly in programs like InkScape. Typically, oe will have to design them for several sizes because neither upscaling nor downscaling will lead to acceptable results if the symbols aren't extremely simple (this also holds for vector graphics in very small scales because smaller features are likely to be compromised).
Some of the icons of Structorizer have been constructed pixel by pixel in 16x16 or 20x20 size, others were shrinked from larger images.

**Comment by codemanyak** [comment]
A few new icons added, some icons redesigned (for more symbolic regularity and better scalability).

**Comment by GitMensch** [comment]
This is a good start. Are there more new icons to come soon?

**Comment by codemanyak** [comment]
Maybe not so soon, this is not my highest priority.

**Comment by codemanyak** [comment]
I started with a subset of the icons I had got higher-resultion variants of: https://github.com/codemanyak/Structorizer.Desktop/commit/4bd30d16e3e3b7ad11ccfdbe864bb1392d8fa36a.
The work on IconLoader is in progress.
@fesch Bob, if you have higher-resolution files of some traditional icons (e.g. the turtle) at your disposal, it would be nice if you could contribute them.

**Comment by fesch** [comment]
![turtle](https://user-images.githubusercontent.com/1027354/35384532-df763c3a-01c5-11e8-9cff-4293452ba008.png)

This is the best I have for the turtle :(

**Comment by fesch** [comment]
Most of the used icons came from very old days, so having a 64x64 pixel icon was already a big one ;)

**Comment by codemanyak** [comment]
@fesch 
48 pixel are already much better than 16 pixels. Thanks anyway for the 36 pixels of the turtle ;-)

**Comment by rugk** [comment]
I had to look four times to identify this as a turtle... 😆 So a remaking this would also not be bad.

**Comment by codemanyak** [comment]
I liked the traditional Turtleizer turtle. Okay, I tried to design some tortoises that may look close enough to it...
![turtle3d128](https://user-images.githubusercontent.com/15326471/35872499-4651bb5a-0b67-11e8-9fb6-8c0df3e39210.png)
![turtle10d128](https://user-images.githubusercontent.com/15326471/35872507-4df5a128-0b67-11e8-944d-e816947090ca.png)
![tortoise7d128](https://user-images.githubusercontent.com/15326471/35873091-05aeb47a-0b69-11e8-91ee-52a9fa069c1a.png)
I think, the first of them looks best, but I'm still not pleased.

**Comment by fesch** [comment]
I personally prefer the last one. The middle one is definitely *strange*.

**Comment by fesch** [comment]
![turtle-vector](https://user-images.githubusercontent.com/1027354/35876205-d7e92f6c-0b71-11e8-985d-85a39333b919.png)

I tried myself. Isn't that easy :-/

**Comment by GitMensch** [comment]
Yes, last one of the three turtles looks best but it seems to be not exported "clean" (including transparent background and no compression), as it is now it is hard to recognize when scaled small (via browser).
Otherwise it looks nice.

**Comment by codemanyak** [comment]
@GitMensch 
> as it is now it is hard to recognize when scaled small

Yes, that is the one problem with it. The other one is, that it resembles the original turtle least. Its advantage is that is obvoiusly an abstraction. But in the small scales its recognisability as tortoise if obviously worst:
![054_tortoise](https://user-images.githubusercontent.com/15326471/35890356-c554c180-0b9f-11e8-9747-1960c961aa4c.png)
![turtle10d16](https://user-images.githubusercontent.com/15326471/35890413-fb769694-0b9f-11e8-827e-6256a756ece1.png)
![tortoise7d16](https://user-images.githubusercontent.com/15326471/35890502-53f7d152-0ba0-11e8-9409-180276f3f42e.png)

Now I tried a complete new creation composed from several photos:
![tortoise10a256](https://user-images.githubusercontent.com/15326471/35892786-4b318634-0bab-11e8-9621-eaa086713387.png)
![tortoise10a16](https://user-images.githubusercontent.com/15326471/35892849-8a56218a-0bab-11e8-8337-1ab081c10e69.png)

This not an abstraction, of course, but it looks like a tortoise even in the smallest size - and it looks pretty similar to our good all pal ;-)

@fesch 
On this occasion some more questions:
- Do you happen to have some higher-resolution versions of the locale icons (the - partially combined - flags) at your disposal? If so then ist would be great if you could send them to me.
- The icon for "delete selected element" had a more expectable design in earlier versions (according to the screenshot of version 1.07:
![old_delete_icon](https://user-images.githubusercontent.com/15326471/35888433-e3ef6e2c-0b97-11e8-84a2-88010128dbe5.png)
) - what was the reason to change its appearence towards the recent icon showing something like two connected diagrams under the red cross, which doesn't match with the move, insert, and edit icons?
- What the heck is the edit symbol showing? 
![006_update](https://user-images.githubusercontent.com/15326471/35888486-1416a890-0b98-11e8-8ab0-94d64c45e454.png)
(In my eyes it resembles a crutch or the "râteau" a roulette dealer uses to move the jetons on the table...) I would have expected something like a pencil (and that's what I'm going to design there), but at least I'm curious to know the ideas behind the current symbol.

**Comment by fesch** [comment]
@codemanyak 

- For the author of the **turtle** design, I'm sorry, but I crosschecked with Unimozer and noticed that this is not the author of turtle icon used inside Turtulizer :( but from the main icon of Unimozer.
- No, I don't have high resolution icons of the **flags**, but I think these can be found or made easily.
- I have no idea why the **delete** icon got changed or swapped. Maybe this was not intended but just happened because of some name changing, but I seriously can't remember.
- In the **edit** icon this little thing should be a hammer or some kind of heel (like mine workers used them to crackle down big stones ...).

**Comment by codemanyak** [comment]
@fesch 
>  I crosschecked with Unimozer and noticed that this is not the author of **turtle** icon used inside Turtleizer :( but from the main icon of Unimozer.

So, the attributition in the Structorizer info has been wrong all the time... Okay, in this case I may join in favouring the symbolic tortoise after some cleaning:
![tortoise7f128](https://user-images.githubusercontent.com/15326471/35916501-dfb2d98e-0c0a-11e8-8335-a7f66d08ce59.png)
... and in action:
![turtle_3 27-07](https://user-images.githubusercontent.com/15326471/35916541-025f07be-0c0b-11e8-80e3-7583a99d11a4.png)

Indeed, on rapid moving it looks rather less creepy than the more naturalistic approaches.

> No, I don't have high resolution icons of the **flags**, but I think these can be found or made easily.

Well, in the web there are lots of stores offering national flag icons with more or less sophistcated national emblems or badges; I just hoped I wouldn't have to rummage through them. Mere tricolores aren't the problem, of course. But the Portuguese/Brazilian, British, and Chinese flags shouldn't look cheaper than in 16x16 format.

> I have no idea why the **delete** icon got changed or swapped. Maybe this was not intended but just happened because of some name changing, but I seriously can't remember.

Ok, then I think we'll return to the original icon, which is more consistent: ![turtle_3 27-07](https://user-images.githubusercontent.com/15326471/35888433-e3ef6e2c-0b97-11e8-84a2-88010128dbe5.png)

> In the **edit** icon this little thing should be a hammer or some kind of heel (like mine workers used them to crackle down big stones ...).

Okay, that would be it. If expecting a hammer then one could even guess it right...

**Comment by codemanyak** [comment]
Some icon groups haven't been revised by now but will be updated step by step with subsequent bugfix versions. Graphic artefacts will also be mended continuously.

**Comment by codemanyak** [comment]
I have a proposal regarding the FOR loop symbol. This is identical either to that of the WHILE loop (DIM-conforming) or to that of the FOREVER loop (non-conforming with DIN 66261). This irritates many users though the tooltip help for the toolbar buttons or the menu path are instructive.
But maybe we might add a trifle (morevprecisely an ellipse in the top strip) for better distinguishability:
![for_exp_din](https://user-images.githubusercontent.com/15326471/36098249-8aef99e4-0ffe-11e8-913b-5e2365bd0cb6.png)   ![for_exp_non-din](https://user-images.githubusercontent.com/15326471/36098257-8e9da87e-0ffe-11e8-8b24-08cbe629e202.png)

Would you guis agree?

**Comment by GitMensch** [comment]
Different symbols for different functions are always good - and as you say the difference will also be part of the text I see it as fine... But in general it should represent the drawing - is this already different (including the ellipse) or do you plan to change this, too?

**Comment by codemanyak** [comment]
@GitMensch 
> But in general it should represent the drawing - is this already different (including the ellipse) or do you plan to change this, too?

No, the element shape is of course the same, but the structur of the header (the text) is different. My first impulse was to write the word "FOR" into the symbol but this wouldn't have been legible, not at least in the small icon sizes. It would have looked like three periods at best. And so I thought: fine - may the periods symbolize the three control activities of a FOR loop: initialization, test, and incrementation, which distinguish it from the other loops. So it would be easy to recognize and make more sense than e.g. a differemt colour. A collappsed FOR loop would show the specific symbol (with the ellipse) as well for consistecy reasons, though the control text is of course visible.

**Comment by codemanyak** [comment]
The toolbar would look like this with the differentiated icons: Is not actually nice but a little bit more practical, I'd say:
![toolbar_add_3 27-08](https://user-images.githubusercontent.com/15326471/36117950-ba078376-103b-11e8-8606-33e04edfcf11.png)
