### ISSUE TITLE
(null) on file write, should not set outputfile to 0 bytes

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#40]
When got a (null) on file save, the previous existing outfile should not be truncated to 0 bytes, because it will be data lost.

**Comment by codemanyak** [comment]
Do you speak of an attempt to save the diagram (*.nsd) or do you refer to the init file? Actually, the problem occurs in both cases and should not. (A good practise would be, either first to rename the old file - thus leaving a backup file - or first to write into a temporary flle and then to rename both files after completion.)

**Comment by elemhsb** [comment]
Your solutions sounds good. In my case i lost the .nsd file. The init file isn't so Important for me.

**Comment by codemanyak** [comment]
Acoording to my tests, problem ought to be solved.
