### ISSUE TITLE
GUI: Some popup windows cannot be closed by [ESC]

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#400]
I think it is "standard GUI behavior" to do the same thing when a popup window is open and [ESC] is pressed and when the window close 'X' is clicked.
While this works in some parts (like the syntax error message on code import) it doesn't work in all the popups found in the preference menu.

**Comment by codemanyak** [comment]
I will have a look at it. I think this difference was not established by design. Possibly by using different dialog base classes.

**Comment by codemanyak** [comment]
There is another flaw to be mended on this occasion: Changes in the Analyser Preferences are always accepted  - no matter how the dialog is closed or cancelled.

**Comment by codemanyak** [comment]
Fix is available on codemanyak/Structorizer.Desktop/master.
