### ISSUE TITLE
Export C++ generates additional spaces, so compile failed

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#41]
written text:  std::cout << "Hello World!" << endl
export  text:  std::cout < < "Hello World ! " < < endl;

got 4 additional spaces, so g++ didn't compile and got wrong text constant.

**Comment by codemanyak** [comment]
You are right, shift operators haven't been handled as such by the recent Structorizer versions.
This can (and will) be changed, of course.
May I say it is just an inconvenience (minor bug or even an enhancement request) because manual postprocessing of the exported code is necessary, anyway?

**Comment by codemanyak** [comment]
By the way, try just to write the instruction as
Ausgabe "Hello World!"
(if "Ausgabe" is the configured parser preference for an output instruction, otherwise use the configured keyword) and what you will get on export then is a flawless C++ instruction.

**Comment by codemanyak** [comment]
Provisionally solved.
