### ISSUE TITLE
Executor doesn't cope with unicode escape sequences in string literals

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#411]
At least the following unicode literals cause errors in the `bsh.Interpreter.eval()`:
`"\u000a\u000d'\u0022\u005c"`.
Interestingly, the semantically equivalent octal codes don't cause problems. So the Executor should do an internal conversion of the unicode code points above to the corresponding octal tripletts in string literals to be involved in execution.
(Remark: This problem arose on code import from COBOL #354 the first time)

**Comment by GitMensch** [comment]
3.27 milestone or not (just out of interest)?

**Comment by codemanyak** [comment]
Milestone of course. Just done.

**Comment by codemanyak** [comment]
Fix is uploaded.

**Comment by codemanyak** [comment]
Fix had been defective (see #426) and was accomplished now.
