### ISSUE TITLE
A find/replace dialog should be added

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#415]
For the analysis of large (imported) diagrams a find/replace dialog is sorely missing. This should offer similar options like in usual IDEs (e.g. Eclipse):

- plain string and regular expression search
- find/replace, replace all
- search only in element text or element comments or both.
- scope limitation to a selected part (subtree) of a diagram or extension to all currently open diagrams.
- case-ignorant or case-sensitive mode,
- restriction to whole words.
- restriction to assumed variable names.
- restriction to certain element-types (a checkbox for each element type plus a button to select all).
- checkbox whether disabled elements are o be involved.
- search direction (upward/downwards) from current selection(?)

For the interactive find/replace mode a sensible preview strategy will have to be found to present the findings: An own textarea in the find/replace dialog or scrolling to the element and let that highlight the matching region? The latter way seems more intuitive but wouldn't allow directly to edit around the found position if the find/replace dialog is modal. Well, an edit button might be added which posp the element editor on top of the find/replace dialog.
Subsumes #373

**Comment by codemanyak** [comment]
First prototype is ready. But there are still flaws with regular expressions and the incremental search / replacement within elements.

**Comment by GitMensch** [comment]
The current implementation is really nice with all the options it already has:
![grafik](https://user-images.githubusercontent.com/6699539/27279565-51e9a90c-54e5-11e7-8a17-084773b9287f.png)

Questions:

* What is the intention for the middle part which has no label? I see that it shows kind of a summary of the current entry in the search result but the intention is not really clear as we have the "Preview" below, too.
* Shouldn't the "Preview" contain "this would be the result of the replace"? Otherwise it may be renamed to something like "Inspect current search entry" and get the nice symbol we have in the middle part.

Note: The new dialog doesn't close on [ESC].

**Comment by codemanyak** [comment]
@GitMensch Hi, thanks for your review.
Well, the central part was chiefly intended for the scope "OPENED_DIAGRAMS". In this case, all diagrams in Arranger and Structorizer are involved, but the current element selection can only directly be followed in Structorizer for the current diagram. So the central part schows the linearized tree view of all matching Elements with their respective Roots in a brief line each. You can walk up and down with the "Find" or "Replace/Find" button or you may click at some of the Elements to jump to that position. This is the only scope where the matching results are precomputed. The other two scopes are working incrementally, so the iterator doesn't know in advance if and which elements are matching above or below. I decided to show at least the current Element's collapsed line rather than leaving the area ompletely empty.

You are right with the remark about the "Preview". My original intension was indeed to show the replacement preview, too, but then I changed my mind - it took too much space (and efforts for the first prototype). Maybe I add an option to toggle among Text + Comment or Text + Text preview / Comment + Comment preview. Unfortunately, in element-wise mode you might need all four views at once. Or maybe I put them in a 2x2 matrix where the actual preview might be switched off.

By the way: Element-wise means just what the name says: Element-wise forward/backward. If you have several matches in a single element's texts then element-wise stepping doesn't require you to click through every single occurrence of the pattern within text and comment field but leaps directly to te next element (above or below) being matched. Element-wise is the fast traversal, not element-wise involves slower in-text navigation.

 I'm still pondering whether to allow the user directly to edit the Text and Comment fields and how to commit (or discard) these changes.

Just added the Escape functionality and the German translations, I think I will commit the updates this evening.

**Comment by GitMensch** [comment]
As other items that were coded for https://github.com/fesch/Structorizer.Desktop/milestone/2 are closed already this can be closed, too.

But as this is a mayor change for the GUI (in my case) it can be a good idea to add this to the milestone's description.

**Comment by codemanyak** [comment]
@GitMensch 
> But as this is a mayor change for the GUI (in my case) it can be a good idea to add this to the milestone's description.

Well, if you a way to change the description of a milestone...

**Comment by GitMensch** [comment]
> Well, if you know a way to change the description of a milestone...

I guess the ["Edit milestone" option][1] allows this.

[1]:https://help.github.com/articles/about-milestones/

**Comment by codemanyak** [comment]
@GitMensch 
> As other items that were coded for https://github.com/fesch/Structorizer.Desktop/milestone/2 are closed already this can be closed, too.

If you haven't found functional deficencies I might do so - though I still have some functional improvement aspects in mind I wanted to check, therefore I have left it open by now.

**Comment by GitMensch** [comment]
While I see that you committed the `keyListener`to cater for `VK_ESCAPE` it doesn't work here in every case:
It works on all items but the find/replace text controls (no matter if the `keyListener` was attached before, which it is).
I *guess* that is because the control itself catches the `VK_ESCAPE`. It is a combo box and pressing escape closes the drop down list which can be opened by [ALT]+[DOWN] or the mouse (which is fine but I think if it isn't open the escape should be send to the parent item). Maybe it is and the solution is to remove the `keyListener` from all elements but their containing panels?

**Comment by codemanyak** [comment]
Apparently, the key listener for editable ComboBoxes has to be set on their editor components rather than on the ComboBox as a whole in order to get it working, Then it must check whether the pulldown is active, however. Moreover, after every Look & Feel change these listeners must be restored. (This looks as if I missed some simpler way but at least it works now.) On this occasion, I also fixed a bug on scrolling up and down the pulldown list via cursor keys.

**Comment by codemanyak** [comment]
The current search and replacement mechanism forgot the "hidden" form fields of FOR loops. They must somehow be involved in order to maintain consistency.

**Comment by codemanyak** [comment]
Substitution in FOR elements fixed (consistency problem , see previous comment).
Effect of "Replace All" button somewhat counter-intuitive (depending upon previous selection activities), should be mended.

**Comment by codemanyak** [comment]
Versions up to 3.27-04 it hadn't ensured that the Find&Replace dialog regains focus on `<Ctrl><F>` or by selecting the respective menu item or toolbar button.

**Comment by codemanyak** [comment]
Fix for version 3.27-05 has been prepared and uploaded to the bugfix branch.

**Comment by codemanyak** [comment]
From version 3.29-11 on, the scopes "Current diagram" and "Current selection" will no longer show the poor one-element result tree but also a complete overview of matching elements like with scope "Opened diagrams". The second mechanism produced rather inconstencies like in issue #728, required at least duplicate maintenance efforts and had no reasonable benefit for the user.
