### ISSUE TITLE
Split long lines for drawing Elements by given width

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#419]
We could set the minimal width with a fixed value (hard-coded or from configuration) and the maximum width from the current window size - left position of current element.
Then use the calculated width (in `lu.fisch.structorizer.elements.writeOutVariables` ?) to split the text before drawing it (something like https://stackoverflow.com/a/19864657/5027456).

**Comment by codemanyak** [comment]
Some remarks:

1. We should have issue #416 in mind here, too.
2. The proposal sounds fine with an element that is spreading over the full width of the diagram. But how shall we distribute the available window width among several branches, possibly resulting from different nesting levels? We might end up with more loose ends (unsatisfied variables) than we can handle on precalculating the required element widths. (It is already complicated while we just combine the simulated widths bottom up.)
3. Don't forget that the diagrams must be drawn in different contexts (Structorizer work area, Arranger, print preview, PNG export etc. etc.) By now, the element sizes depend on the font width, syntax highlighting, some padding constants, and the needs of elements with traversal shapes (chiefly alternatives and case selections) - in combination with the sizes of nested elements. This is stable for all views (and still provokes drawing artifacts on radid execution!). This won't be the case anymore if we add more adaptivity here.

I don't reject the proposal but a quick (and dirty) hack without meticulous analysis, careful preparation and abundant tests doesn't help in any way here, I'm afraid. If we add it to milestone 3.27 then the release may never come (it's likely to retreat like the horizon by walking towards it).
This would be so fundamental a change that it should not be mixed with so many other enhancements but be an isolated update project, which can be committed or stopped separately.

**Comment by GitMensch** [comment]
> I don't reject the proposal but...

After some thinking: I would reject it in its current state. But the feature that likely is a good idea and sounds relative easy to implement is to limit to the maximum width by configuration setting to "n" chars: "maximum characters per single execution before a line break occurs during drawing" with a default of 0=unlimited.

This way we don't have to calculate anything but simple take the strlen of the current line (which would be reset by the suggested line continuation "\" #416, too). If it is bigger than this limit add a "soft" line break in the drawing.

Or wouldn't this be possible to handle or useful in all cases?

**Comment by GitMensch** [comment]
Wonderful, also the additional information during edit.
Just one minor editorial thing: is "substructure" the correct word (do we use it otherwise)? Especially as you had "element(s)" in there I'd suggest to use "child-elements" instead.

**Comment by codemanyak** [comment]
@GitMensch 
> Just one minor editorial thing: is "substructure" the correct word (do we use it otherwise)?

Well, at least in the user guide the term "substructure" is frequently used, whereas the word "child" doesn't occur at all, neither in the user guide nor in any message of the English locale file. Moreover, in my eyes "child is somehow associated with inheritence, which isn't the case here. The correct concept is indeed structural embedding, hence substructure.

**Comment by codemanyak** [comment]
The line rebreak function missed to force a diagram redrawing though it obviously induces shape changes. Will be fixed with version 3.30-18.
