### ISSUE TITLE
code import: store the (comment) token and add its value to the NSD

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#420]
These have been found to be returned as token `(comment)` with the actual comment as the token's `value` and were minimal discussed in #354 and #409.

Importing the code comments are likely helpful for NSDs imported from code files.

Here's a sample which shows inline comments from COBOL parsing:

A general "yay" for the comments - I don't know if you did something but the log for DB201A.CBL shows:

~~~

Token (Comment)	at [23,3]: *>                       PROGRAM ABSTRACT                          
Token (NewLine)	at [24,1]
Token (Comment)	at [24,68]: *>
Token (NewLine)	at [25,1]
Token (Comment)	at [25,3]: *>    DB201A TESTS THE CAPABILITY OF THE DEBUG MODULE TO HANDLE    
Token (NewLine)	at [26,1]
Token (Comment)	at [26,68]: *>    DEBUGGING PROCEDURES WHICH ARE MONITORING IDENTIFIERS        
Token (NewLine)	at [27,1]
Token (Comment)	at [27,68]: *>    SPECIFIED WITH AND WITHOUT THE "ALL REFERENCES" OPTION.      
Token (NewLine)	at [28,1]
Token (Comment)	at [28,68]: *>    THIS PROGRAM IS TO BE COMPILED AND EXECUTED WITH BOTH        
Token (NewLine)	at [29,1]
Token (Comment)	at [29,68]: *>    COMPILE AND OBJECT TIME DEBUGGING SWITCHES ENABLED.  THE     
Token (NewLine)	at [30,1]
Token (Comment)	at [30,68]: *>    DEBUGGING PROCEDURES SHOULD BE INCLUDED IN COMPILATION       
Token (NewLine)	at [31,1]
Token (Comment)	at [31,68]: *>    AND GENERATE CODE.  DEBUGGING ACTIONS ON THE FOLLOWING       
Token (NewLine)	at [32,1]
Token (Comment)	at [32,68]: *>    CONDITIONS ARE ANALYZED                                      
~~~

Looks like we have them in and can get their value easily (by taking everything after the first `*>` or in case of C `//`). I'll check multi-line comments next and assume they are likely available in a similar matter.

**Comment by GitMensch** [comment]
Sample from the log for C including both single line and block comments:

~~~
Token (Comment)	at [1,1]: /*
   Copyright (C) 2004-2012, 2014-2017 Free Software Foundation, Inc.
   Written by Roger While, Simon Sobisch, Brian Tiffin

   This file is part of GnuCOBOL.

   The GnuCOBOL compiler is free software: you can redistribute it
   and/or modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation, either version 3 of the
   License, or (at your option) any later version.

   GnuCOBOL is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with GnuCOBOL.  If not, see <http://www.gnu.org/licenses/>.
*/
Token (NewLine)	at [1,1]
Token (NewLine)	at [15,3]
Token (Comment)	at [16,1]: // preparser include: #include	"config.h"
Token (NewLine)	at [16,1]
Token (Comment)	at [16,42]: // preparser include: #include	"defaults.h"
Token (NewLine)	at [17,1]
~~~

Note: I've just recognized (when I tried to fix the wrong positions for the tokens, which I've gave up for now) that the group for both line and block comments is `Comment Line` - shouldn't it be `Comment Block` for the second? This was evaluated by temporarily changing the log line

```diff
-    			logFile.write("Token " + tokenStr + "\tat " + this.getCurrentPosition().toString().trim());
+    			String grpStr = "";
+    			if (token.getGroup() != null) {
+    				grpStr = "(" + token.getGroup().getName() + ")";
+    			}
+    			logFile.write("Token " + tokenStr +"\t" + grpStr + "\tat " + this.getCurrentPosition().toString().trim());
```

**Comment by codemanyak** [comment]
The solution is almost ready. It works already for CParser. I still have difficulties with the Pascal import, apparently because the D7 grammar eats newlines (i.e. subsumes them under whitespace such that a different association strategy will have to be applied.
A flaw might temporarily be tolerated: The imported comments have still their comment delimiters. In theory, I should be able to obtain the necessary information from the parser tables to address this but haven' had the time to find out how.
I think I will be able to upload the code this evening.
I haven't touched the COBOLParser while you are still doing something therein.

**Comment by GitMensch** [comment]
Sounds good. I hope to finish the COBOL-Parser parts that far that the variables and records are (again) defined correctly and - for having at least some new things done with the "COBOL compiler view" of the variables) handle `SET x TO TRUE|FALSE` correctly and handling condition variables in expressions correctly `IF cond` where `cond` is defined as:

```cobol
 01.
   03 name pic x.
     88 cond values 'a' thru 'd', 'x', 'y'.
```

and will be exploded to

```java
   name >= 'a' && name <= 'd' || name == 'd' || name == 'x' || name == 'y'
```

BTW: the detail-rules for the USAGE types cannot be evaluated in the old version (they are never reached), but I've fixed this and some variable types today.

**Comment by codemanyak** [comment]
Ok, the changes are committed. By the way: To get rid of the imported comment delimiters was a fine occasion to test the new Find & Replace tool (#415) ...

**Comment by GitMensch** [comment]
Any change for an inclusion in the COBOL parser? This would allow to close this ticket ;-)

**Comment by codemanyak** [comment]
First comment import draft for COBOL, still somewhat defective (outer program gathers too many comments from substructure elements (without stealing them, just duplicating). So it's merely inconvenient, the superfluous comments may easily be cleared.
It's unclear whether it's a flaw in the mechanism (the same happens sometimes in some C imports) or in the grammar-specific configuration of the stop rules.
Wiping of comment delimiters is now working, too.

**Comment by codemanyak** [comment]
@GitMensch 
Furtunately, it was a rather trivial configuration mistake I made that messed up the COBOL comment import. It is now fixed.

**Comment by GitMensch** [comment]
@codemanyak - I haven't checked yet but I'm quite sure that this works with the COBOL parser now, too, allowing this ticket to be closed.
Thank you!

**Comment by codemanyak** [comment]
Comment retrieval mechanism in class `AuParser` slightly revised, Parser HowTo updated. (To be delivered with 3.30-17.)
