### ISSUE TITLE
code import: maybe use a changed version of `StreamTokenizer`

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#421]
When preparing some information for #420 I've stumbled over a bug in the `StreamTokenizer`: it breaks the line count when empty lines are seen within comments (they aren't counted in `LINENO`).

Additional to fixing this we may want to add two tokens to it: `TT_COMMENT_INLINE` and `TT_COMMENT_BLOCK`. We *could* even add support for non-C-style comments....

Note: As far as I see this is only relevant for the log in the pre-parse phase, should I do this nonetheless or do we want to keep this issue open as nice-to-have (and good-to-remember)?

**Comment by codemanyak** [comment]
What has the StreamTokenizer to do with the GOLDParser Tokens?

**Comment by GitMensch** [comment]
> What has the StreamTokenizer to do with the GOLDParser Tokens?

nothing:

> As far as I see this is only relevant for the log in the pre-parse phase

The StreamTokenizer is used in the C preprocessing.

**Comment by codemanyak** [comment]
> should I do this nonetheless or do we want to keep this issue open as nice-to-have (and good-to-remember)?

The line counting of the parser is different, anyway. So, I think, it's a "nice to have" at most.

**Comment by GitMensch** [comment]
Put it on hold and I'll add it if we need the comment tokens (which I'd implement as an optional return and for different languages, likely similar to GOLDparser with specifying the actual delimiter) to be returned.

**Comment by codemanyak** [comment]
@GitMensch 
As far as I can see this issue has lost its relevance. So I closed it.

**Comment by GitMensch** [comment]
@codemanyak Fine. Maybe add the wontfix label ;-)
