### ISSUE TITLE
Problem installing Structorizer 3.22

### ISSUE THREAD

**Issue by ErvinPoljac** [fesch/Structorizer.Desktop#422]
I tried to install 3.22 version of Structorizer on my MacBook Air with El Capitan. The error message that I get when I try to run the application is 
“Structorizer” is damaged and can’t be opened. You should move it to the Trash."
Anyone that can help?

**Comment by GitMensch** [comment]
Did you install it according to the [Mac OS X instructions](http://help.structorizer.fisch.lu/index.php?menu=48&page=) or with [Java Web Start](http://structorizer.fisch.lu/webstart/Structorizer.jnlp)?

Does it work to use it the other way?

In any case I highly suggest to use the most current version which is currently 3.26. Webstart always uses the newest one, the download for Mac OS manual installation can be found at http://www.fisch.lu/Php/download.php?file=structorizer_latest_mac.zip

**Comment by codemanyak** [comment]
This problem had already been reported as issues #79 and #152 and had to do with an obsolete start wrapper used by the ancient versions and respective Java VM requirements. It was replaced for newer releases such that it should be solved with the current version (3.26-05, actually), which you obtain via the link given by @GitMensch.
If you still observe the problem then you should also try to follow the suggestions given in the two issues mentioned above.

**Comment by codemanyak** [comment]
@ErvinPoljac 
Have you been able to overcome the problem? Please inform us whether this issue may be closed or if further analysis is required.

**Comment by codemanyak** [comment]
@ErvinPoljac 
If you don't reply we will assume the problem being solved and close this issue in 10 days.
