### ISSUE TITLE
Simple find function in Translator

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#425]
Just lest it should be forgotten: It would be nice to be able to search the current Translator tab for some string (just a simple Ctrl-F functionality would certainly be sufficient).

**Comment by GitMensch** [comment]
Yes. We may could place most of the functionality from search and replace for the NSDs into an interface "SearchAndReplaceable", allowing to use it in both places (and just use a different GUI that doesn't use all of the functionality if it isn't necessary).
Or just copy the needed parts and don't add a search function to other parts and don't make changes of the inner behavior afterwards...

**Comment by codemanyak** [comment]
@GitMensch 
> Yes. We may could place most of the functionality from search and replace for the NSDs into an interface "SearchAndReplaceable", allowing to use it in both places (and just use a different GUI that doesn't use all of the functionality if it isn't necessary).

No. It would be an idiotic effort to generalize the diagram-dedicated mechanisms of the Find & Replace dialog to Translator or other contexts. For Translator, a simple case-tolerant substring search would be fully sufficient. It is just about one or two key bindings (Ctrl-F to open a question box requesting a (sub)string to be searched for just on the current tab and another one, possibly Ctrl-N, to find the next occurrence of the previously seeked substring).

**Comment by GitMensch** [comment]
:-) You're absolutely right.
At least an option to set case-sensivity and maybe a replace function would be nice, at least the first one could be added in the question box directly.

**Comment by codemanyak** [comment]
Accomplished (bugfix branch)

**Comment by codemanyak** [comment]
In version 3.27-04, the key binding of Ctrl-F is only effective on the buttons in the toolbar but not while the table or text on the current tab has got the focus. Hence the `tabs` component is also to be equipped with the key binding (-> version 3.27-05).
