### ISSUE TITLE
Turtle package and JavaGenerator could be prepared to produce code that can use Turtleizer

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#441]
I propose to modify the package lu.fisch.turtle (TurtleBox class) in a way that it can be used separately from all the rest of Structorizer. This would only require to move three interfaces (`DiagramController`, `DelayableDiagramController`, and `FunctionProvidingDiagramController`) from package `lu.fisch.structorizer.executor` to a new independent package, say `lu.fisch.diagrexe`, and to dismiss a single StringList reference.
With an additional adapter class (e.g. "lu.fisch.turtle.Turtleizer.java") the JavaGenerator might transform Turtleizer procedure and function calls to static method calls of that Turtleizer class, such that the resulting code would only have to import the `diagrexe` and `turtle` packages to be executible with the turtle.
The code would give this hint as a TO DO comment.
@fesch 
Would this interfere with other projects (e.g Unimozer), or may I go ahead?

**Comment by GitMensch** [comment]
Seems very reasonable and actually would allow for the turtle package to be moved to a single library/project that can be used in other programs more easily (and even could be updated by a newer version after a Structorizer release, too).

**Comment by fesch** [comment]
Cool idea.

No, there will be no interference with any know dependent application, so: yes, go for that change.

**Comment by codemanyak** [comment]
I did the refactoring now.
I think, for the coming release it would be quite sufficient to provide a zip file containing the two source packages  `lu.fisch.turtle` and `lu.fisch.diagrexec` on the Structorizer download page.
@fesch
If this zip will automatically be updated by the Structorizer release script, then all should be fine. In most cases, an update won't even be necessary but better automatize it.
The user obtains a source file on export, so she/he should cope with making a project with some additional source files. (Certainly a library jar file would do as well, of course.)

**Comment by codemanyak** [comment]
I will rename the package `diagrexec` again to `diagrcontrol` since it dawned on me that this may be going to be the very interface to plug in more external interface modules, which actually allow to **control** things by Structorizer (one vague idea might be a _LEGO_ Mindstorm NEXT via bluetooth or other customer hardware).
For this purpose, however, some more redesign steps may be sensible, which I'll outline in a separate issue.

**Comment by fesch** [comment]
@codemanyak 
I did not clearly fetch what you want me to do, I I assume that thinks will get clearer while preparing the release ;)

**Comment by codemanyak** [comment]
@fesch 
Oh, pretty simple: As it isn't that easy to fetch just certain subtrees out of a code project from GitHub, the idea was to zip the source of the two packages lu.fisch.turtle and lu.fisch.diagrcontrol (ideally without the useless Main.java) and to provide this zip file for download on your homepage.
A user that exported a turtle-controlling program to Java could then just unzip the sources into the same project and compile them together. Or organize it in any other suitable way. As it is open-source anyway, this would just be a little convenience without much effort.
If I knew the likely URL in advance, then I could already mention it in the exported Java file comments.
Thanks in advance. 
By the way, I'm preparing also to expose a Turtleizer-mimicking C++ library (WinAPI-based, unfortunately) I wrote some years ago for the same purpose.

**Comment by fesch** [comment]
Okay, that seams quite easy to achieve ;)

**Comment by GitMensch** [comment]
@fesch What do you think about changing the build and dependency system to Maven? This could be used from all major java environments (including IDEs and command line) and would allow easier dependency management on "external" projects. Obviously Structorizer would include a dependency to the turtle package. Benefits: no need for IDE specific files any more (like .project or .settings directories), packaging directly via `mvn`, ... with the down-side that you would have to use maven.

If you like this idea (would change src -> src/main/java) I could give this a go as soon as the refactoring is finished.
If you like to (and PGP sign the release files) the resulting artifacts of both projects could be uploaded to the central maven repository, too, but this isn't a "must have".

**Comment by codemanyak** [comment]
@GitMensch 
In my eyes, there is no urgent need. The packages may well continue to coexist in the same repository. Why should they be developed independently from now on? The intension that the turtle package can be compiled without the rest of the Structorizer packages and all its extra libraries was simply achieved.
Moreover, we talk about four and a half source files here, most of them tiny. The only link between the two parts is a now pretty generic interface. Should this interface file also form an own project?
It's all done. So, if it's not for other, overwhelming advantages, I would say: why bother?

**Comment by fesch** [comment]
I agree with @codemanyak . As long as there is no urgent need for this, I don't see the point in splitting everything up.

**Comment by GitMensch** [comment]
:-) I'm fine with this.
