### ISSUE TITLE
"ArrayIndexOutOfBoundsException: Array index out of range" during COBOL import

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#445]
Just checked the [current release](https://github.com/fesch/Structorizer.Desktop/releases/tag/3.27) with the first file in my temp folder:
[cob600_0.cob.log](https://github.com/fesch/Structorizer.Desktop/files/1428325/cob600_0.cob.log)

First result was a lexical error
![grafik](https://user-images.githubusercontent.com/6699539/32188611-945270ae-bda8-11e7-86e0-283867fdf07e.png)

Seems like the `#line` isn't ignored (should be in the preparser part of the COBOL parser, I've obviously have missed this until now).

After changing the first line to an inline comment manually

![grafik](https://user-images.githubusercontent.com/6699539/32188381-eccf87a4-bda7-11e7-9af1-96c32c2aebbd.png)

Tried the second file:
[cob11540_0.cob.log](https://github.com/fesch/Structorizer.Desktop/files/1428335/cob11540_0.cob.log)

![grafik](https://user-images.githubusercontent.com/6699539/32188812-24d34770-bda9-11e7-897f-124a88f1f775.png)

:-(

Note: tested with 
![grafik](https://user-images.githubusercontent.com/6699539/32188854-419baf6e-bda9-11e7-9437-fad36c5f0145.png)

**Comment by codemanyak** [comment]
In both cases the trouble results from an empty section, i.e. a section without own statements (e.g. because only alreayd extracted paragraphs contained all the statements).
In case of cob600_0.cob it is section MAIN, in case of cob11540_0.cob it is A10_MAIN.
Obviously these cases hadn't occurred in any sample file I had had tested with. The code assumes erroneously that there is at least one element.
I can prepare a formal fix for it. But the good question is: what would be the correct result in these cases? An empty program?

**Comment by codemanyak** [comment]
In the appendix, I send you a fixed jar file for approval of the results or further analysis.
The respective sections will simply be ignored (no diagram derived).

[Structorizer.jar.zip](https://github.com/fesch/Structorizer.Desktop/files/1429101/Structorizer.jar.zip)

**Comment by codemanyak** [comment]
Code changes can be inspected in the bugfix branch.

**Comment by GitMensch** [comment]
Thank you for investigating.

The correct way is likely to fully qualify the paragraphs (if there's a section you could do `PERFORM some-par IN/OF some-sec`) and group the paragraphs (if any) into a section, ideally only create subs if there's more than one paragraph in.

To ignore parts like MAIN00 in the given sample is definitely the correct thing to do. The creation of sub-items in normal cases seems to work fine, too (have to recheck but there are no java-exceptions and generation/inclusion of multiple diagrams).

The second part would be to ignore directives like `#line` (actually everything that starts in column 1 with a `#`) during the minimal preprocessing we already have (btw: Where should I target PR now?).

The last part that I see now after being able to import the diagrams (applies to C/Pascal, too) is tracked with #446.
