### ISSUE TITLE
Structorizer 3.23 Mac/Linux Installation zip-file contains Icon file with trailing "\n"

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#45]
Structorizer/Structorizer.app/Icon^M

$ ls Structorizer/Structorizer.app/Icon  | od -c
0000000   S   t   r   u   c   t   o   r   i   z   e   r   /   S   t   r
0000020   u   c   t   o   r   i   z   e   r   .   a   p   p   /   I   c
0000040   o   n  \n

**Comment by fesch** [comment]
Fixed, new release on structorizer.fisch.lu

**Comment by elemhsb** [comment]
OK fine, did you please remove the distributed .DS_Store directory also.

**Comment by fesch** [comment]
OK
