### ISSUE TITLE
The Print Preview should at least allow to modify paper orientation and margins

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#456]
The Print Preview of Structorizer offers no actual means to modify the print. An orientation button is disabled, the margins can't be modified.
Both is achievable with reasonable effort and may look like this:

![printpreview_3 27-01](https://user-images.githubusercontent.com/15326471/32444173-ee53b4f6-c301-11e7-8e04-11e5ffde8cd9.png)

A nasty side effect that sometimes the page multiplies in the preview is not so easy to fix, it seems.

**Comment by fesch** [comment]
looks great
