### ISSUE TITLE
use a different message box class for allowing copy to clipboard

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#471]
I'm adding a new issue to prevent a loss of the idea that came up in #182 

@GitMensch wrote:
> Can you please include a "copy to clipboard" button and/or add an event listener for the the standard option [CTRL]+[C] (at least with nearly all "native" applications on Windows you get the message copied to the clipboard).

@codemanyak wrote:
> Good idea. But requires a different message box class, obviously.

**Comment by GitMensch** [comment]
Just did a quick check with the error message

![grafik](https://user-images.githubusercontent.com/6699539/33258954-8b04f4cc-d35b-11e7-88f3-6c3064369ed3.png)

The result is presented by the code

```java
	JOptionPane.showMessageDialog(this.NSDControl.getFrame(),
			parser.error,
			Menu.msgTitleParserError.getText(),
			JOptionPane.ERROR_MESSAGE, null);
```

as we pass the String `parser.error` and a String input defaults to a JLabel - but we can use any object we like.

The simplest option is to simply replace `parser.error` in all three contexts where we use it by a TextArea which has the parser error text:

![grafik](https://user-images.githubusercontent.com/6699539/33258783-fc5c4e28-d35a-11e7-915d-d36bc162f793.png)

using the code

```java
	JTextArea ta = new JTextArea();
	ta.setText(parser.error);
	ta.setEditable(false);
	ta.setLineWrap(false);
	JOptionPane.showMessageDialog(this.NSDControl.getFrame(), ta,
		Menu.msgTitleParserError.getText(),
		JOptionPane.ERROR_MESSAGE, null);
```

This allows [CTRL]+[A], [CTRL]+[C].

Specifying the default font we normally use (and adding a newline) looks nicer:

```java
	JTextArea ta = new JTextArea();
	ta.setText(parser.error + '\n');
	ta.setEditable(false);
	ta.setLineWrap(false);
	Font dfltFont = javax.swing.UIManager.getDefaults().getFont("JOptionPane.font");
	ta.setFont(dfltFont);
```

Result:

![grafik](https://user-images.githubusercontent.com/6699539/33259826-5ec804fa-d35e-11e7-828e-6aabbefc92b4.png)


The "nicer" option is to create a showErrorMessage (for general use) or showParserError (for use in the three places we currently use a pure JOptionPane.

This seems, according to https://stackoverflow.com/a/8660349/5027456 , to also allow adding of other buttons (even if not we have the code all in a single place).

**Comment by codemanyak** [comment]
Of course, a second button that copies the content to the clipboard may be added. I think I even had it implemented once and only dropped it later again after having decided that the full message is written to the log file, anyway (which to send in as a whole actually makes more sence in case of an error).

**Comment by GitMensch** [comment]
@codemanyak How to go on now? Do you have your old code still laying around somewhere?

**Comment by codemanyak** [comment]
@GitMensch 
Now I found the code. Indeed I had already performed the addition of a copy button but it had only been for the file-drop mechanism (half a year ago, in May!), and I simply forgot it here. Now both will work the same way.
