### ISSUE TITLE
COBOL import - sub-nsd generation broken on paragraphs

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#475]
For all paragraphs we set a comment showing this was a paragraph and ignore it. But the creation of sub-NSDs get broken on it because they currently do not only end the previous paragraph but also the section.

It got a little bit better after I've commented out 

~~~
		case RuleConstants.PROD_PARAGRAPH_HEADER_TOK_DOT: {
			// <paragraph_header> ::= <IntLiteral or WORD> 'TOK_DOT'
			// Note: this starts a new paragraph AND closes the previous paragraph
 --> this line		this.accomplishPrevSoP(_parentNode);
~~~

but still had issues and would break the "paragraph only" version

Please have a look at the following 
[SAMPLE.cbl](https://github.com/fesch/Structorizer.Desktop/files/1506575/SAMPLE.cbl.txt)

![grafik](https://user-images.githubusercontent.com/6699539/33276291-7864c5f6-d395-11e7-9a7c-b4690fd573fe.png)

Using only paragraphs does work:

[SAMPLE-para.cbl](https://github.com/fesch/Structorizer.Desktop/files/1505831/SAMPLE-para.cbl.txt)

![grafik](https://user-images.githubusercontent.com/6699539/33267068-5e0c7810-d378-11e7-99bd-8a8d3e0d8038.png)

Can you please investigate the missing bit for the sections?

**Comment by codemanyak** [comment]
It would help me a little if you could be so kind to produce a display of the desired result, I guess. This language still puzzles me.

**Comment by GitMensch** [comment]
Desired output of SAMPLE.cbl (I've fixed the missing periods in the sample and re-uploaded it):

![grafik](https://user-images.githubusercontent.com/6699539/33276904-3b36fef4-d397-11e7-92b6-f0c723ca1042.png)

The maybe ideal rule is:

* for each section: create a sub-NSD - the section ends *only* if a new section start (or end of file or END PROGRAM/FUNCTION)
* within the sub-NSD for the section: inspect all paragraphs if they are a target of PERFORM - if yes create sub-NSDs for them, too - otherwise leave them as they are
* for each paragraph that is still in the main program *AND* the target of a PERFORM create a sub-NSD - the paragraph - otherwise leave them as they are
* in general: if a paragraph is empty (= there is no actual code in in, `CONTINUE` and `EXIT` without anything doesn't count) it should be post-removed (which seems to be done as there is no `EX` paragraph generated), ideally only if the paragraph is not a target of a `GO TO` (in this case the programmer should clean the NSD himself)

I don't know how complicated this is for the parser, but the one rule that definitely should and likely could get a fix is the `accomplishPrevSoP(_parentNode);` as this function should be scoped or split as only a section closes the previous section. (the generated NSDs imply that the paragraphs `00` end the sections).

**Comment by codemanyak** [comment]
Okay then the __WORKS-also__ section still causes misbehaviour for this code example after my first fixing approach (and, of course, the due conversion of the exits into return Jumps):

![fix475test1](https://user-images.githubusercontent.com/15326471/33288156-8bca2ed0-d3bb-11e7-97f6-91a4cb47b823.png)

**Comment by GitMensch** [comment]
@codemanyak Note: you're using the original test source which had bug in and wasn't valid COBOL code, please retry with the updated one.

**Comment by codemanyak** [comment]
@GitMensch 
> please retry with the updated one.

Umh. Doesn't make a difference after import ...
It seems that the remaining trouble comes from the RuleConstants.PROD_PROCEDURE_TOK_DOT2 case now, where it is difficult to tell whether a section or a paragraph is ending. What is a "procedure" in this context?
This is getting rather tricky.

**Comment by GitMensch** [comment]
> [the updated source] doesn't make a difference after import ...

At least the "0" and "ex" in the OUTPUT of  "WORKS_also" and "WORKS_again" should be removed. I've just re-downloaded the sample file and rechecked that the uploaded one is the valid one.

From looking at the grammar PROD_PROCEDURE_TOK_DOT2 should be a period that isn't part of any statement or section/paragraph header (which consume one TOK_DOT on their own):
![grafik](https://user-images.githubusercontent.com/6699539/33311864-6c445548-d426-11e7-8261-edf67bade15e.png)
![grafik](https://user-images.githubusercontent.com/6699539/33311985-c996dcde-d426-11e7-9b78-41059d2f05eb.png)

And there isn't one in. Is there a defect in the grammar or the parser?

Rechecked with loading the egt into GOLD Parser builder, loaded the test file, replaced all `*` in there by `*>` and ran it - looks fine:
[SAMPLE.cbl-parser-result](https://github.com/fesch/Structorizer.Desktop/files/1509238/SAMPLE.cbl-parser.txt)

**Comment by codemanyak** [comment]
@GitMensch 
> From looking at the grammar PROD_PROCEDURE_TOK_DOT2 should be a period that isn't part of any statement or section/paragraph header [...] And there isn't one in.

You are right. I fooled myself by a deliberate confluence of the switch cases for `PROD_PROCEDURE_TOK_DOT` and `PROD_PROCEDURE_TOK_DOT2`. So it were the TOK_DOTs at the end of the display statements (put there to separate their item lists from the subsequent labels, i.e. the paragraph headers) that led to the mutilation of the paragraphs.
If I got it right now then paragraphs don't end at such a TOK_DOT but share the following code with a "successive" paragraph possibly beginning there (within the same section). Even a paragraph header doesn't end the previous paragraph but overlaps it. Even an unconditioned EXIT ends a paragraph only in a practical sense but not in a grammatical understanding? Is that right?
If so, then the major bug here is that my COBOLParser mechanism wasn't aware of this overlapping. Manipulation of a "sub-paragraph" was likely to compromise the integrity of its containing `SectionOrParagraph` reference object.
An ending section would of course also close all begun paragraphs. A section ends where a new section begins or at the end of division or file then? Or is it possible that it ends at some otherwise unassociated TOK_DOT as well?

**Comment by GitMensch** [comment]
Not completely. In general:

* sections are optional (you can have a program without a single one)
* paragraphs are optional (you can have sections (and also programs) without a single one)
* `EXIT.` is a dummy stating "there is likely an end of a section or paragraph sequence here", it did never made any difference to write `CONTINUE.` instead
* a section may contain multiple paragraphs
* a section ends ONLY when a new section starts (or at end of program/function or at file ending)
* a paragraph ends ONLY when a new section or paragraph starts (or at end of program/function or at file ending)
* if the paragraphs within a section are not part of a `GO TO` or `PERFORM` statement they don't "do" anything relevant for an import (they *may* have a useful commenting name, but I have only rarely seen this)

**Comment by codemanyak** [comment]
@GitMensch 
> - a paragraph ends ONLY when a new section or paragraph starts (or at end of program/function or at file ending)

This language is sowly driving me nuts.
Can I say that a paragraph only starts with a paragraph header (e.g. some label)?
So if a section consists of a several consecutive paragraphs and the section is called then it runs through all these paragraphs, one after the other, correct? If one of the paragraphs ends with an EXIT statement then execution will still pass to the following paragraph? An EXIT PARAGRAPH, however will jump to the next paragraph.
If I call a paragraph via PERFORM then it will only be executed until the beginning of the next paragraph (if there is a subsequent one) and then return, no matter whether there is an EXIT PARARAPH at the end or not?
Next question: Can paragraphs be nested, e.g. may a paragraph have an alternative in one of the branches of which there is a sub-paragraph? Or do they always begin outside of other statements?

Now I have a solution that works for the SAMPLE file but is conceptually wrong (a paragraph isn't ended by a consecutive paragraph but shares the remaining code). Before I had a mechanism that was conceptually correct but didn't work - you disabled the routine accomplishPrevSoP() in case PROD_PARAGRAPH_HEADER_TOK_DOT to try a fix, remember? So I was somewhat misled, obviously.

**Comment by codemanyak** [comment]
New approach available on the bugfix branch.

**Comment by GitMensch** [comment]
Marvelous result for [SAMPLE.cbl](https://github.com/fesch/Structorizer.Desktop/files/1526767/SAMPLE.cbl.txt):

![grafik](https://user-images.githubusercontent.com/6699539/33549784-0025f0d6-d8ec-11e7-9d6a-2a30ae06abc9.png)

Still should not be closed because the latest change lead to a file that was imported within 30 seconds before now lead to a hanging process [kicked after five minutes, consuming 1,2-1,4GB RAM] :-(

**Comment by GitMensch** [comment]
It looks like the RAM-hogging and unresponsiveness is an SWT issue (I'm still trying to create a minimal sample...).

One thing that I've recognized is a problem with "empty" sections:

![grafik](https://user-images.githubusercontent.com/6699539/33551236-05ac0630-d8f1-11e7-8bae-3cafe4fdf18d.png)
![grafik](https://user-images.githubusercontent.com/6699539/33551059-696120b2-d8f0-11e7-8197-a414f9aa2b94.png)

Updated [SAMPLE.cbl](https://github.com/fesch/Structorizer.Desktop/files/1526884/SAMPLE.cbl.txt)

BTW: "z.Z." may be changed to "zzt", see https://www.duden.de/rechtschreibung/zurzeit

**Comment by codemanyak** [comment]
@GitMensch 
> [...] an SWT issue [...]

Do you mean Swing? As far as I know SWT is an eclipse toolkit.

> One thing that I've recognized is a problem with "empty" sections

The result is definitely inconsistent, What would be your suggestion? To remove the calls or to produce empty diagrams?

**Comment by GitMensch** [comment]
> Do you mean Swing?

... yes ...

> What would be your suggestion? To remove the calls or to produce empty diagrams?

Neither one (ok, more the first one): change the CALLs to comments.

**Comment by codemanyak** [comment]
@GitMensch 
Ok, the last bugfix branch update now disables the calls of empty, vanished or otherwise corrupt sections or paragraphs. The red colour still remains.
