### ISSUE TITLE
COBOL-Import - strange record placeholders %1, %2, ...

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#479]
split from #423 as this is a COBOL import specific issue.

Given the sample [SAMPLE-SEARCH.cbl](https://github.com/fesch/Structorizer.Desktop/files/1509127/SAMPLE-SEARCH.cbl.txt)

The output looks like
![grafik](https://user-images.githubusercontent.com/6699539/33311243-7b0e0706-d424-11e7-9714-c767792f47bb.png)

and has multiple `%num` integrated, for example

    calc_tab[calc_idx].calc[%2].calc_key <- single_record[%1].single_data_part[%2].single_more_data[%3].single_key

**Comment by codemanyak** [comment]
Thanks for the sample. When I import it, then the resulting structogram looks sound and doesn't show the reported defects:
![sample_search](https://user-images.githubusercontent.com/15326471/33337630-ce401bc2-d473-11e7-8858-92fb84126119.png)

**Comment by GitMensch** [comment]
This looks much better - is this the result from plain bugfix branch?

**Comment by codemanyak** [comment]
> This looks much better - is this the result from plain bugfix branch?

Yes it is. But you would also obtain an equivalent result by using the official version 3.27-03. I have absolutely no clue what may have gone wrong at your site.

**Comment by GitMensch** [comment]
I'm closing this - I did a fresh checkout and everything works (both in official bugfix branch and in my cobolparser branch). You may add an "invalid" label...

**Comment by codemanyak** [comment]
> A definite fault is that the due declarations of calc_current and calc_tab got lost, i.e. weren't generated.

I derive a new issue for this fault: 77-level data descriptions break the variable list (particularly after a 78-level constant definition).
