### ISSUE TITLE
Turtleizer delay not immediately updated on modifying the Executor delay

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#48]
When the execution delay is changed via the delay glider while a Turtleizer algorithm is running, the Turtleizer functions continue to work with the animation delay from execution start. Only after restarting the algorithm, the Turtleizer adopt the delay from Executor control.
This can make the test of complex drawing algorithms (particularly with subroutines) very ineffective.

**Comment by codemanyak** [comment]
The executor ought to be allowed to update the Turtleizer delay whenever its own delay is actually changed (by method Executor.setDelay(), provided there is a real difference). By now this only done on executing the init() function, which clears the entire Turtleizer area.
I see two opportunities to fix it:
1. Extend the DiagramController interface by method setAnimationDelay(), which the TurtleBox as implementing class already provides. This approach would force other classes implementing DiagramController also to provide at least a dummy implementation of setAnimationDelay().
2. Add function setAnimationDelay() to the routines interpreted by Turtlebox.execute(double). This approach would allow users to manipulate the Turtleizer animation delay by adding a respective instruction to their diagrams, which is not catastrophic but certainly unwanted.

I tend to the first approach but may possibly not overview all consequences.

**Comment by fesch** [comment]
Option N° 3:
As the method Diagram.goTurtle() is the only one that passes a real value to Executor.getInstance() as second parameter, we could create a descend of the DiagramController interface and add the setAnimationDelay() in that interface.

What do you think about that option?

**Comment by codemanyak** [comment]
I don't quite get it. If I understand your suggestion well then the inheritance path should become something like TurtleBox --|> DelayableDiagramController --|> DiagramController with DelayableDiagramController publicly presenting the method setAnimationDelay()? This would of course require the Executor attribute diagramController to be retyped to DelayableDiagramController, because the Executor will have to forward a noticed delay change to the TurtleBox. Is it this what you mean?

**Comment by fesch** [comment]
Yes :-)

**Comment by codemanyak** [comment]
Did it this way.

**Comment by codemanyak** [comment]
The good question here is: Why do we impose a delay to the `DiagramController` at all? Isn't one delay (the one in Executor) enough? Why don't we just always set the `DiagramController`'s delay to 0?
