### ISSUE TITLE
COBOL import: 77-level data descriptions aren't processed correctly

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#480]
1. If a data description with level 77 follows a constant definition with level 78 then the variable list of the current data section will be broken (both CobVars won't be linked). On building the data declaration part all variables from the level-77 one on won't be generated.
1. If a data description with level 77 follows a hierarchical data definition (i.e. some record structure in usual HLL terms) then it will be interpreted as being nested at the innermost level.

Both ways to process the declaration are wrong.
The buggy behaviour can be studied with the following sample program (for case 2; remove the comment asterisk in line 10, i.e. before the level-78 definition of `calc-max`, in order to reproduce case 1):
[SAMPLE-SEARCH.cbl](https://github.com/fesch/Structorizer.Desktop/files/1522640/SAMPLE-SEARCH.cbl.txt)

The straightforward way to fix it should be to handle level-77 data as if they had level 1 in the CobVar constructor.

**Comment by GitMensch** [comment]
> The straightforward way to fix it should be to handle level-77 data as if they had level 1.

Nearly. Level 77 cannot have any sub-items (or be part of a record), but otherwise handling them like level 1 would be correct.

**Comment by codemanyak** [comment]
Another defect was revealed on fixing this issue: The initialization of arrays of records with default contents isn't properly generated, e.g. the following data description induced a variable initialization that ignored the array level:
```
78 calc-max value 12.
77 calc-current pic 9(02) value 0.
01 calc-tab.
    03 calc occurs 0  to calc-max
            depending on calc-current
            indexed   by calc-idx.
       05 calc-key    pic x(07).
       05 calc-count  pic 9(06)     value 0 comp-5.
       05 calc-sum    pic s9(07)V99 value 0.
```
used to produce:

**Comment by codemanyak** [comment]
Fixed in bugfix branch.
