### ISSUE TITLE
bugfix branch: COBOL code import always imports variable declarations?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#483]
Settings:
![grafik](https://user-images.githubusercontent.com/6699539/33551755-aaa2b00c-d8f2-11e7-9130-df5de6466997.png)
![grafik](https://user-images.githubusercontent.com/6699539/33551778-bc3c69fc-d8f2-11e7-93f3-fd731c996830.png)

Imported code always has variable declarations in ?!?

![grafik](https://user-images.githubusercontent.com/6699539/33551998-909affa6-d8f3-11e7-8e2a-35c38b294871.png)

**Comment by codemanyak** [comment]
Umh, it seems the respective preference has been forgotten when the COBOLParser was redesigned with CobTools. On the ther hand, it wouldn't make sense to suppress record variable declarations because in this case nearly all component access would fail. (Your example shows a record variable...)

**Comment by GitMensch** [comment]
> Umh, it seems the respective preference has been forgotten when the COBOLParser was redesigned with CobTools.

OK, then it is likely a single (?) flag.

If no declarations are given Structorizer (Executor/code export) guess the type, but not for records, correct?

Note: All these declarations in the given sample are created from the variable declarations, therefore they wouldn't be included if this could be turned off.

**Comment by codemanyak** [comment]
> If no declarations are given Structorizer (Executor/code export) guess the type, but not for records, correct?

Yes, you can say so. There are even certain cases where a record variable initialization may replace a declaration (beause the initializer syntax is more ore less unambiguous w.r.t. type).

> Note: All these declarations in the given sample are created from the variable declarations, therefore they wouldn't be included if this could be turned off.

It's true that the type definitions are driven by the variable declaration. But you cannot simply drop them if the respective variable is going to be used somewhere in the code (which is usually the case if the variable isn't redundant).
So it makes only sense to suppress mere declarations of variables of simple types, which indeed may be guessed.
(Some explanation: Originally, Structorizer hadn't supported a thing like a variable declaration. Only C- or Java-like variable initializations like `int a <- 6` were tolerated. Therefore, it hadn't made sense, either, to impot variable declaration from Pascal. Disabled elements hadn't existed, either. So the option to import variable declarations was a benefit when some of the mentioned enhancements became available.)
With the introducton of record types, it makes less sense now to disable this option, and its effect should be limited to primitive-type variables, I think, lest we should produce defective diagrams. On the other hand, if one wants to concentrate on thealgorithmic structure, no matter whether the diagram is executable then it might make sense to omit all the declaratoric stuff.
How do we read the intentions of he user, now?

**Comment by GitMensch** [comment]
> How do we read the intentions of he user, now?

From the import option "Import variable declarations" :-)

Additional Note: most of the imported COBOL code should actually look much cleaner if the variables are not imported as the variable name would (or should) be used as is `single_data` where with variable import activated the names will always be full qualified `single_record.single_data`.

I currently see only the three options:

* executable with variable import and full qualified names - this is what we have now
* simple-as-possible with variable names as they are [+necessary conversions like `-` -> `_`] - this should be the result if no declarations are imported, only "simple" code would be executable (like accept numeric variable, do calculation and output)
* variable import and clean looking code - by changing the Executor to be able to qualify the name from the record (would be quite cool ;-)

**Comment by codemanyak** [comment]
> From the import option "Import variable declarations" :-)

Of course, but what would it ideally mean?

I could agree with the "all or nothing" interpretation.

> - variable import and clean looking code - by changing the Executor to be able to qualify the name from the record (would be quite cool ;-)

The Executor cannot of course interpret anything that isn't there. But this induces another idea: What about a mere drawing option to hide all un-initialized declarations and type definitions without actually discarding them? So Executor might silently execute them to construct its type tables but wouldn't pause there in step mode. Of course, this might provoke some consistency issues in the run data tracking but then the hidden elements may be shown again. A collective place holder (like a collapsed element) might indicate that the definitins are there and can be made visible again.

**Comment by GitMensch** [comment]
> I could agree with the "all or nothing" interpretation.

Yes: checked = "all" (includes complete internal parsing of `DATA DIVISION`), unchecked = "nothing" (= no internal parsing and creation of `CobVar`s necessary).

In general: if a variable cannot be found (because the parsing wasn't done or it simply doesn't exist) we should just use the name from the identifier (this is also what I've added for `SEARCH` [which I try to do a clean-merge with an issue and maybe integrate `SEARCH ALL` this week]).

> The Executor cannot of course interpret anything that isn't there. But this induces another idea: What about a mere drawing option to hide all un-initialized declarations and type definitions without actually discarding them? So Executor might silently execute them to construct its type tables but wouldn't pause there in step mode. Of course, this might provoke some consistency issues in the run data tracking but then the hidden elements may be shown again. A collective place holder (like a collapsed element) might indicate that the definitions are there and can be made visible again.

There are two things here (which may should be tracked in additional issues), and one additional one that comes to mind:

* internal execution but no drawing for the variables / records as suggested by you (+ see variables as "not-initialized" if they are initialized to their type default like "0" for numerics and " " for Strings) - this would improve drawing of "real" code by a lot as it is not uncommon to have 30-50 % of the completely preprocessed code (all copybooks included) to be in `DATA DIVISION`. This is all drawn today and may not be "useful" for understanding the diagram at all;
* additional to the option to "uncollapse" the definitions [which should be - for drawing performance considerations may be done in a new window/dialogue]: it would be nice to support hovering over a variable in the Diagram and when the cursor stays there for 1 seconds show it's definition in a tooltip (if this means too much event handling maybe do so on right click)
* optional: teach the Executor and code generation to resolve the variables internal if the given name does not exist on its own --> from `single_data` to `single_record.sub_type1.sub_type2.single_data` - I don't know if this is COBOL only but this would lead to a quite clean diagram without all those records be shown

**Comment by codemanyak** [comment]
> - [...] it would be nice to support hovering over a variable in the Diagram and when the cursor stays there for 1 second show it's definition in a tooltip (if this means too much event handling maybe do so on right click)

Nice idea, we are coming all the way closer to an IDE here? But that may turn out really tricky as we cannot easily detect the exact word over which the cursor hovers. So it might be more feasible to show the defnitions of all variables / constants in the element text...

> - optional: teach the Executor and code generation to resolve the variables internal if the given name does not exist on its own --> from single_data to single_record.sub_type1.sub_type2.single_data - I don't know if this is COBOL only but this would lead to a quite clean diagram without all those records be shown.

No way. (Among other arguments: Executor is already slow enough.)

**Comment by codemanyak** [comment]
@GitMensch 
> Yes: checked = "all" (includes complete internal parsing of DATA DIVISION), unchecked = "nothing" (= no internal parsing and creation of CobVars necessary).

After having pondered the necessary changes, I realized that it's not quite as simple as that. Of course we will have to import material statements, e.g. assignments. Now consider a record array initialization like in the given illustration example for #480 - in order to make sense it requires two of the preceding type definitions. Even if we omit these in the diagram (and thus provoke Analyser warnings on end), we would need to have imported the data section before, because otherwise we couldn't even find a way to express the setting-up of the array. Otherwise the imported elements would look like before the introduction of record types:
```
calc_count <- 0
calc_sum <- 0
```
Would this really be what we want?

**Comment by codemanyak** [comment]
@GitMensch You wrote a week ago:
> In general: if a variable cannot be found (because the parsing wasn't done or it simply doesn't exist) we should just use the name from the identifier (this is also what I've added for SEARCH [which I try to do a clean-merge with an issue and maybe integrate SEARCH ALL this week]).

Are you still working on it? Otherwise I tend to instigate the next bugfix version 3.27-04 now. It already contains a lot of fixes and enhancements. I would just ask you the withdraw the pull request towards fesch/master before. And maybe redirect it to bugfix after you have consolidated your changes.

**Comment by GitMensch** [comment]
@codemanyak I should be able to complete the fix and rebase on the current bugfix branch until Friday. If I can work on it tomorrow it will be available tomorrow until 5 PM.

**Comment by codemanyak** [comment]
please don't feel pressured, Friday is quite sufficient then. I just wanted to know.
