### ISSUE TITLE
code import options: auto-layout needs some tweaks

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#484]
It looks like a two column layout is used where the size is auto-calculated.

This may be a nice idea in general but the size for the buttons should always stay the same (calculated from the longest button caption) and the left column have a size depending on the longest caption.

It seems that all controls use the same length, calculated from the longest field:

![grafik](https://user-images.githubusercontent.com/6699539/33551850-fd31fc74-d8f2-11e7-8b11-c0281c37923e.png)

**Comment by codemanyak** [comment]
You are right. I used just a simple GridLayout for the first implementation.

**Comment by codemanyak** [comment]
On refurbishing the layout, I also detected a bug in the processing of enumeration options (which hadn't been configured so far, so it didn't show).
The fixes for both are ready and in the bugfix branch now.
