### ISSUE TITLE
COBOL parser error on certain intrinsic functions

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#485]
Got a parser error when trying to import sample file cgiform.cob:

![numval_parser_error](https://user-images.githubusercontent.com/15326471/33553451-1be85d24-d8f9-11e7-8dcc-091dfa10779f.png)

A grammar bug?

**Comment by GitMensch** [comment]
No - the grammar cannot know which names are functions and therefore expects the word `FUNCTION` to be included.

This is a preparser issue which should honor the `REPOSITORY` paragraph and add the "missing" `FUNCTION` token before all functions listed there, in the [given sample](https://sourceforge.net/p/open-cobol/contrib/HEAD/tree/trunk/samples/cgiform/cgiform.cob) it is set to `ALL INTRINSIC` which evaluates to the following list:

* ABS
* ABSOLUTE-VALUE
* ACOS
* ANNUITY
* ASIN
* ATAN
* BOOLEAN-OF-INTEGER
* BYTE-LENGTH
* CHAR
* CHAR-NATIONAL
* COMBINED-DATETIME
* CONCATENATE
* COS
* CURRENCY-SYMBOL
* CURRENT-DATE
* DATE-OF-INTEGER
* DATE-TO-YYYYMMDD
* DAY-OF-INTEGER
* DAY-TO-YYYYDDD
* DISPLAY-OF
* E
* EXCEPTION-FILE
* EXCEPTION-FILE-N
* EXCEPTION-LOCATION
* EXCEPTION-LOCATION-N
* EXCEPTION-STATEMENT
* EXCEPTION-STATUS
* EXP
* EXP10
* FACTORIAL
* FORMATTED-CURRENT-DATE
* FORMATTED-DATE
* FORMATTED-DATETIME
* FORMATTED-TIME
* FRACTION-PART
* HIGHEST-ALGEBRAIC
* INTEGER
* INTEGER-OF-BOOLEAN
* INTEGER-OF-DATE
* INTEGER-OF-DAY
* INTEGER-OF-FORMATTED-DATE
* INTEGER-PART
* LENGTH
* LENGTH-AN
* LOCALE-COMPARE
* LOCALE-DATE
* LOCALE-TIME
* LOCALE-TIME-FROM-SECONDS
* LOG
* LOG10
* LOWER-CASE
* LOWEST-ALGEBRAIC
* MAX
* MEAN
* MEDIAN
* MIDRANGE
* MIN
* MOD
* MODULE-CALLER-ID
* MODULE-DATE
* MODULE-FORMATTED-DATE
* MODULE-ID
* MODULE-PATH
* MODULE-SOURCE
* MODULE-TIME
* MONETARY-DECIMAL-POINT
* MONETARY-THOUSANDS-SEPARATOR
* NATIONAL-OF
* NUMERIC-DECIMAL-POINT
* NUMERIC-THOUSANDS-SEPARATOR
* NUMVAL
* NUMVAL-C
* NUMVAL-F
* ORD
* ORD-MAX
* ORD-MIN
* PI
* PRESENT-VALUE
* RANDOM
* RANGE
* REM
* REVERSE
* SECONDS-FROM-FORMATTED-TIME
* SECONDS-PAST-MIDNIGHT
* SIGN
* SIN
* SQRT
* STANDARD-COMPARE
* STANDARD-DEVIATION
* STORED-CHAR-LENGTH
* SUBSTITUTE
* SUBSTITUTE-CASE
* SUM
* TAN
* TEST-DATE-YYYYMMDD
* TEST-DAY-YYYYDDD
* TEST-FORMATTED-DATETIME
* TEST-NUMVAL
* TEST-NUMVAL-C
* TEST-NUMVAL-F
* TRIM
* UPPER-CASE
* VARIANCE
* WHEN-COMPILED
* YEAR-TO-YYYY

**Comment by codemanyak** [comment]
Okay, so the preparser has to be fixed. Thanks.

**Comment by GitMensch** [comment]
The COBOL preparser currently doesn't do very much (its main use is to internal change fix-form reference-format to free-form reference-format as everything else will completely kick the GOLD parser)...

**Comment by codemanyak** [comment]
I coded a quick-and-dirty workaround for the preparser that evaluates a REPOSITORY section in order to prefix unprefixed cals of declared intrinsic functions with the FUNCTION keyword. The mechanism is somewhat wobbly as it can easily be fooled by string literals or complicated syntax.
