### ISSUE TITLE
A display setting to hide all mere declaratory stuff on drawing diagrams may be helpful

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#487]
The following enhancement idea was derived from the discussion of issue #483:
The declaratory stuff (type definitions, variable declarations without initialization) may get overwhelming, particularly on code import, such that the algorithm structure gets difficult to be found among all the declarations.
To regain the overview without losing executability and type consistency, there should be a display mode hiding all mere declaratory stuff in the diagrams. This could be achieved in a way that every contiguous sequence of type definitions and mere variable declarations delegate their drawing to the first Instruction element of them as surrogate, which presents itself like a collapsed element with a specific icon. This same icon should also be used for the respective check menu items to toggle this mode.
The Executor should carry out such a collapsed declaration cluster in a single step, unless execution trouble occurs, in which case the display might automatically be switched back to full mode.

**Comment by GitMensch** [comment]
As noted in the referenced issue - this would also improve drawing speed of imported source code as the many instructions containing only variable declarations can get big.

**Comment by codemanyak** [comment]
Note that constant definitions are not hidden, they are regarded as material statements.
