### ISSUE TITLE
Executor: Comparison of variables with operator = always fails currently

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#49]
A test for equality among numerical variables like in the algorithm example below fails in the current release. This is obviously due to the fact that the bshInterpreter prefers to store variable values as objects, e.g. rather as Integer object than as int value. As a consequence, the equality operator == works as identity check, which two objects usually fail to pass.
 
![gleichheit_test](https://cloud.githubusercontent.com/assets/15326471/11705410/e2987314-9eef-11e5-8bb4-ed1b644d2088.png)

This bug seems to be an unwanted side-effect of my fixing the comparison of strings and characters and will have to be mended expeditely. Sorry for my untidy work.

**Comment by codemanyak** [comment]
Thing issue tends to get more complcated than thought. It did not result from the string comparison fix, instead I had disabled some apparently useless lines in method Executor.setVar() with release 3.22-31. As it now turns out, their aim seems to have been to override the wrapper objects method interpreter.set() has created by the the more native result of the eval method. To re-enable these double settings of variable values, however works only for scalar variables but not for array elements, since arrays are of type Object[]. Does it make sense to create integer[] or double[] arrays instead of Object[] whenever the first primitive element ist assigned to a new array variable? I don't think so.
To fix it at the other end would mean to parse all logical expressions way more thouroughly before interpretation, not only with respect to strings and characters but also concerning all types of numeric variables (scalar or array elements) and replace equality and unequality operators by methods equals(). I'm notz exactly looking forward to such a modification.

**Comment by elemhsb** [comment]
We got this bug, also. Eingabe a Eingabe b compare works. a:=42 Eingabe b did'nt.

**Comment by codemanyak** [comment]
Managed to find a differentiated solution. For scalar variables, the former double assignment (first by the set method then by the eval method of the interpreter) works, for array elements the replacement of the == and != in analogy to string operands did the job. I hope I didn't overlook some specific constellation where it still doesn't detect equality.

**Comment by codemanyak** [comment]
@elemhsb : You might have a look at the bugfix3.23 branch whether you still find cases where equality comparison doesn't work.
Are you also interested in testing the complex enhancement version (most important: executable calls to subroutine diagrams, recursion, jumps etc.) currently under development, as soon as I will have integrated to recent bugfixes?

**Comment by elemhsb** [comment]
Compare works again,
but in the past i wrote
int a:= 0
Int b:= 0
for perfect Export to c++. This didn't work anymore to  compare ?

**Comment by codemanyak** [comment]
The execution with these typed variables works (to my total surprise, I have to admit). It's just that "int a" etc. is partially interpreted as variable name.
I don't detect a problem on exporting the code to C++, either.
Again, I would like to ask you for more detailed a problem description. (Or what exactly do you mean with "work to compare ?" ?)

**Comment by elemhsb** [comment]
![bildschirmfoto 2015-12-15 um 19 59 11](https://cloud.githubusercontent.com/assets/2959804/11821101/2b0a3908-a368-11e5-8f9c-25d24f890a6c.png)
Sorry, Eingabe cause Executer problems here.

**Comment by codemanyak** [comment]
Okay, you are right: The input mechanism doesn't cope with typed variables. I'll open a new enhancement request, that's not actually a bug. At least there are some inconsistencies.
