### ISSUE TITLE
Translator: long English texts are shown only fragmentarily in the central column

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#491]
Whereas localisation texts in the edited target locale can be inspected by activating the cell editor in the third column, this is impossible with the central column where the English master texts are presented. This way it may be hard to guess what the text says.
There should be a mechanism to pop up a tootltip showing the entire text while hovering over a cell too small for being able to display the full string.

**Comment by GitMensch** [comment]
Question: Why do you want fixing the Translator instead of using gettext for Java where a multitude of very good (even half-automated) translation editors exist?

**Comment by codemanyak** [comment]
Simply because Translator is an editor developed to work with the specific localization mechanisms used in Structorizer. For a multitude of reasons, the localisation mechanism in Structorizer is independent of the operating system localization. One of them is that usually operating systems are installed with a single or sometimes two languages at most, and the Structorizer user community has historically decided on their own what languages are relevant and should be available.
On the other hand, maintenance of a lot of the language file had been lacking, particularly with the growing frequency of functional enhancements.
So Bob designed this integrated tool to allow users to maintain their language environment themselves with way more comfort than editing the text files, which was a great idea. They could set up completely new language files or modify their messages as they like or send the files in for release integration.
Would you say gettext offers the same crowd collaboration feature? And it works well enough.
On the other hand, the entire localization could of course be fundamentally redesigned to make use of way more common frameworks.
For the moment, however, fixing Translator cost me half an hour (less than the retrieval for GNU gettext and this explanation, particularly if I go on). A localization mechanism redesign would be a work of at least a week I assume, but possibly more. And then it would not even be clear if it could replace all of the pretty sophisticated tricks to get reach of already rendered dialog elements for their live re-localization. And then we still would have to integrate an external editor.
My time is too limited for such experiments without need.

**Comment by codemanyak** [comment]
Fixed (bugfix branch), on that occation also fixed some splitting bug in the central table column (English text had still been truncated at equality signs).
