### ISSUE TITLE
Proposal: Translation of the element names in German locale

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#492]
A user (@andybru) proposed a modified German locale file with following translated Element names:
- Instruction: "Anweisungen" -> "Anweisungen" (as before)
- Alternative: "IF-Anweisung" -> "WENN-Anweisung"
- Case: "CASE-Anweisung" -> "AUSWAHL-Anweisung"
- For:
  - "FOR-Schleife" -> "VON-Schleife"
  - "FOR-IN-Schleife" -> "VON-IN-Schleife"
- While: "WHILE-Schleife" -> "WENN-Schleife"
- Repeat: "REPEAT-Schleife" -> "BIS-Schleife"
- Forever: "ENDLOS-Schleife" -> "ENDLOS-Schleife" (as before)
- Call: "Aufruf-Anweisung" -> "Aufruf-Anweisung" (as before)
- Jump: "Aussprung-Anweisung" -> "Aussprung-Anweisung" (as before)
- Parallel: "Parallel-Abschnitt" -> "Parallel-Abschnitt" (as before)

**Comment by codemanyak** [comment]
The proposal shows a structural and a general problem.
The structural problem is that the Element names occur at more than a dozen places in different messages. The general problem is that what pleases one looks gruesome for others. There are different "schools" in designating these algorithmic elements. And all sets of names look somehow inconsistent (e.g. what is translated - what isn't, what is capitalized - what isn't, and so on) . Users of other locales had to endure his conflict for an even longer time.
An idea to address both problems at once might be that the user obtain a new configuration opportunity where they may specify their own Element type names, which wil then override whatever the current language file may contain. More consequently, the language file should no longer explicitly contain the names but specific place holders for Element type names. Each language file should be accompanied by a short language-specific name mapping (like the enumeration above) which is by default used to substitute the specific placeholders. If he user has an own alias set then this will overide the default names.
This approach might possibly be combined with the still open issue #327.

**Comment by GitMensch** [comment]
+1 for the "remove the language-specific tokens in the source and replace it by a "only shown according to configuration" - which itself may derived from the language file(s)"

**Comment by codemanyak** [comment]
Regarding the German default translations of element names, I propose the following, more consistent set:

- Instruction: -> "Verarbeitung"
- Alternative: -> "WENN-Anweisung"
- Case: -> "AUSWAHL-Anweisung"
- For: -> "FÜR ... - Schleife"
  - counting -> "FÜR-BIS-Schleife"
  - traversing -> "FÜR-ALLE-Schleife"
- While: -> "WENN-Schleife"
- Repeat: -> "BIS-Schleife"
- Forever: -> "ENDLOS-Schleife"
- Call: -> "AUFRUF-Anweisung"
- Jump: -> "AUSSPRUNG-Anweisung"
- Parallel: -> "PARALLEL-Abschnitt"

**Comment by andybru** [comment]
[de.txt](https://github.com/fesch/Structorizer.Desktop/files/1564665/de.txt)
Here is the de.txt attached fixed according to the above message
with FÜR-BIS, FÜR-ALLE, AUFRUF, AUSSPRUNG and PARALLEL
all in uppercase letters.

**Comment by codemanyak** [comment]
@andybru 
Thanks for your update. The changes have already been integrated, and the proposed new opportunity for users to name the elements according to their own preferences on top of the locale is implemented. Both will be delivered in the version 3.27-04.
You may have a look at the peview in the on-line User Guide: [Preferences => Element names ...](http://help.structorizer.fisch.lu/index.php?menu=134).
The new version is due by next week. There are just some last tests to be done.

**Comment by codemanyak** [comment]
Localization of the Element Name Preferences dialog doesn't work, which is due to a class name typo in the locale files.
GUI scaling works only partially, the GUIScaler call had been forgotten before the pack() invocation.
