### ISSUE TITLE
Bug at REPEAT UNTIL

### ISSUE THREAD

**Issue by slytab** [fesch/Structorizer.Desktop#498]
REPEAT UNTIL even checks the loop condition before entering the loop. This is against the understandig of REPEAT UNTIL.
The following will produce an error:

REPEAT
   READ X
UNTIL X > 0.

The error message is:
... illegal use of undefined variable ....

**Comment by codemanyak** [comment]
You are right. But this reflects a problem that will arise with many languages on export (e.g. C, Java): If the variable X is introduced within the loop it will often be declared locally, such that the loop condition is out of its scope.
The interpretation in Structorizer is incremental, but the validity of the loop condition is checked in advance, so this is exactly what happens though Analyzer does not complain and the diagram looks fine.

So I agree: For consistency reasons, either Analyzer should warn in advance or the definition should be done implicitly (i.e. the initial condition check might simply be dropped). I'll have a look, which of both approaches is preferrable or easier to accomplish.

**Comment by codemanyak** [comment]
Indeed the disabling of the preliminary executability check in the REPAT loops was easiest. Code export suggests the declaration of the respective variables at the beginning of the generated program or routine, so the simplification shouldn't cause harm there.
The fix will be delivered with Structorizer version 3.27-05.

**Comment by slytab** [comment]
Thanks for the quick response.
> Code export suggests the declaration of the respective variablesHow do you declare variables using structorizer?
s.



      Von: Kay Gürtzig <notifications@github.com>
 An: fesch/Structorizer.Desktop <Structorizer.Desktop@noreply.github.com> 
CC: slytab <slytab@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 0:40 Dienstag, 23.Januar 2018
 Betreff: Re: [fesch/Structorizer.Desktop] Bug at REPEAT UNTIL (#498)
   
Indeed the disabling of the preliminary executability check in the REPAT loops was easiest. Code export suggests the declaration of the respective variables at the beginning of the generated program or routine, so the simplification shouldn't cause harm there.
The fix will be delivered with Structorizer version 3.27-05.—

**Comment by codemanyak** [comment]
>> Code export suggests the declaration of the respective variables

> How do you declare variables using structorizer?

Well, what I meant is that declaration suggestions are inserted into the generated code (often the declarations are even generated - if the type of he variable is unambiguous).

On the other hand, yu may indeed put variable declarations in Structorizer. Their syntax follows mor or less Pascal. See the [User Guide](http://help.structorizer.fisch.lu/index.php?menu=50&page=#declarations).

**Comment by codemanyak** [comment]
The bug is fixed in the just delivered version 3.27-05.
Yet I might try to implement an Analyser warning if variables occurring in a REPEAT-UNTIL condition haven't been introduced before (i.e. outside) the loop body - which is a common mistake in programming languages with block scope. So it is good practise to declare / initialize variables tested in the condition before the loop starts.

**Comment by slytab** [comment]
Hi!I didnt see this mail - your first mail - earlier because it was assigned to my spam folder.
I know, the problem will be solved, but for my understanding:you wrote:"If the variable X is introduced within the loop..."
There is an error message even when the variable ist not introduced within the loop, but declared right at the beginning.The message text is lightly different then in case of missing declaration, but it is an unexpected error.The exported code works fine, however.


Thanks for your effortssly


      Von: Kay Gürtzig <notifications@github.com>
 An: fesch/Structorizer.Desktop <Structorizer.Desktop@noreply.github.com> 
CC: slytab <slytab@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 23:47 Montag, 22.Januar 2018
 Betreff: Re: [fesch/Structorizer.Desktop] Bug at REPEAT UNTIL (#498)
   
You are right. But this reflects a problem that will arise with many languages on export (e.g. C, Java): If the variable X is introduced within the loop it will often be declared locally, such that the loop condition is out of its scope.
The interpretation in Structorizer is incremental, but the validity of the loop condition is checked in advance, so this is exactly what happens though Analyzer does not complain and the diagram looks fine.So I agree: For consistency reasons, either Analyzer should warn in advance or the definition should be done implicitly (i.e. the initial condition check might simply be dropped). I'll have a look, which of both approaches is preferrable or easier to accomplish.—

**Comment by codemanyak** [comment]
@slytab 
> There is an error message even when the variable ist not introduced within the loop, but declared right at the beginning. The message text is lightly different than in case of missing declaration, but it is an unexpected error.

This refers to the old version, I guess. The reason is that a mere declaration (without initialization) does not assign a value (the variable will contain null, which is equivalent with an error in Structorizer). Before version 3.27-05, the loop condition was simply evaluated once on entering the loop. The result was of no other interest than to check the syntactical and structural correctness including the suitedness of the variable contents. And there we go with an uninitialized variable....
With 3.27-05 the problem should be gone.
