### ISSUE TITLE
Analyser recommends bad things

### ISSUE THREAD

**Issue by rugk** [fesch/Structorizer.Desktop#5]
### Test program
![strucanalyse](https://cloud.githubusercontent.com/assets/11966684/10733745/5b7d1112-7c00-11e5-907d-73377be0b26b.PNG)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root text="&#34;Test&#34;" comment="&#34;&#34;" color="ffffff" type="program" style="nice">
	<children>
		<instruction text="&#34;testVar &#60;- something&#34;" comment="" color="ffffff" rotated="0"></instruction>
	</children>
</root>
```

### Issue
In most programming languages variables should be written in `camelCase` and titles e.g. would be written just with one capital letter at the start. (`Capitalletter`)
So it's not really a good recommendation to write everything in capital letters.

**Comment by fesch** [comment]
Not at all!

The program has been developed for the luxemburgish school system. This is indicated in the analyser preferences. If you don't want these checks, please deselect them ...

**Comment by rugk** [comment]
Ah that's what MAN/LUX mean. :smiley: 

Okay, in this case that's okay.

**Comment by fesch** [comment]
Ministry of National Education (MEN)
Luxembourg (LUX)

;-)
