### ISSUE TITLE
Converting subroutines

### ISSUE THREAD

**Issue by lhoreman** [fesch/Structorizer.Desktop#50]
Do you know if there are problems with the export to Pascal in the
latest version of Structorizer?
We have problems with converting subroutines:

In Structorizer:
Machtsverheffing(pGrondtal,pExponent:integer):real
In Pascal:
function Machtsverheffing(pExponent; pGrondtal); 

How can we solve this problem?

**Comment by fesch** [comment]
Can't remember this worked before, but implementing the type export was not that difficult.

Please check the new JWS version.

I'm waiting for your feedback before closing this.

**Comment by lhoreman** [comment]
It works! Thanks! 

Lieve 

Bob Fisch schreef op 2015-12-10 09:12: 

> Can't remember this worked before, but implementing the type export was not that difficult. 
> 
> Please check the new JWS version. 
> 
> I'm waiting for your feedback before closing this. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/fesch/Structorizer.Desktop/issues/50#issuecomment-163539995

**Comment by codemanyak** [comment]
Oh, I had alrady prepared a rather elaborated mechanism for the function header exüort, but it's located in the enhancement branch. I didn't find the time to inform you about this today.
Anayway, it would have cost some time to extract that part and check it for interdependencies.
