### ISSUE TITLE
Parallel and Switch Element in 3.27-05

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#501]
There is a Bug in 3.27-05 regarding both elements.
Parallel gets created without empty fields to put stuff into.
And Switch is not created at all, crashing the whole UI.

**Comment by codemanyak** [comment]
Thank you for your report. The bug can be reproduced. A bugfix is in progress, sorry for the trouble.

**Comment by codemanyak** [comment]
Bugfix is available, delivery of new version is in progress.

**Comment by codemanyak** [comment]
Version 3.27-06 is available for dowload.
