### ISSUE TITLE
Possible Bug with "or"

### ISSUE THREAD

**Issue by newboerg** [fesch/Structorizer.Desktop#503]
Since 3.27 the "or" does not work as expected anymore.

![bug](https://user-images.githubusercontent.com/7376421/35919479-812518b8-0c15-11e8-92c3-0c9bd5801385.png)

Until version 3.26 the second loop would end when the user enters "bla" or "blub"

**Comment by codemanyak** [comment]
Apparently the preprocessing of string comparison fails to split the expression at OR operators. I'm analysing it.

**Comment by codemanyak** [comment]
Bugfix is available and filed for next version (3.27-07).
