### ISSUE TITLE
Why is the element padding constant (and not proportional to the font size)?

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#508]
This is a question I have had for a long time but never asked. It is getting new relevance with high-resolution screens:
When the font size is changed, the padding around the element texts is kept constant (yes it is, I shrunk the large-font image by half, font sizes are 48 and 4, respectively):
![test508large_half](https://user-images.githubusercontent.com/15326471/36064378-84e789a0-0e8a-11e8-8001-2adc381c580e.png)
![test508small](https://user-images.githubusercontent.com/15326471/36064379-8508c1ce-0e8a-11e8-9c25-972fdb7f3e3a.png)

The effect is somehow unexpected. This may prevent the diagram from collapsing with very small fonts and exorbitant diagram growth for large font sizes, but was it intended this way? Or should the padding grow with the font?

It would be possible to allow both behaviours - a checkbox in the font preferences dialog might allow the user to decide among fix or proportional padding.
By the way, the font chooser dialog should display the current font size in a label (the list view doesn't indicate it if none of the predefined sizes is met).

**Comment by codemanyak** [comment]
At least we will have to do something with the padding for GUI scaling factors > 1 because the icons in collapsed elements will enlarge...:

![for_demo_collapsed](https://user-images.githubusercontent.com/15326471/36232793-751bca52-11e3-11e8-8461-79a745310591.png)

**Comment by codemanyak** [comment]
Implemented a workaround for the latter problem: The text in collapsed elements will be moved wide enough to the right such that the element symbol  may not eclips it anymore;
![collapsed_workaround_3 27-08](https://user-images.githubusercontent.com/15326471/36237791-6f0eaf06-11fe-11e8-90a0-3a41efd9e7cf.png)

**Comment by fesch** [comment]
![image](https://user-images.githubusercontent.com/1027354/45252197-0dcd0e80-b353-11e8-99f7-a6d5abb00959.png)
![image](https://user-images.githubusercontent.com/1027354/45252204-23dacf00-b353-11e8-80f9-c26b028b4ded.png)

Does it look better now?

**Comment by codemanyak** [comment]
Oh, I should have closed it myself sometime ago, perhaps. It was only a question - I had just been interested in the - possibly convincing - reasons of the constant paddings before I modified something. In fact, I used to feal somewhat uneasy with the results of my (clandestine) experiments with a proportional padding myself and realized it would have to be something inbetween - if we modify it at all.
Many thanks for your reaction, anyway, but now the result of your modification doesn't produce a clean proportional effect, either (see the lower padding in the bottom elements). Anyway I would prefer to check all the dependencies and impacts more thouroughly before we issue this change...

**Comment by fesch** [comment]
Okay, I got it now. Just didn't remember this afternoon that I did this already in another project:

fm.getHeight() is the total height of the font, included the descending letter space. For vertically centering, this doesn't work.

It has to be replaced by fm.getLeading()+fm.getAscent()

**Comment by fesch** [comment]
![image](https://user-images.githubusercontent.com/1027354/45257499-85c52400-b3a7-11e8-8ea7-c39a4e2c50d8.png)
![image](https://user-images.githubusercontent.com/1027354/45257502-937aa980-b3a7-11e8-862c-731e31d729f9.png)

**Comment by codemanyak** [comment]
@fesch 
Your screenshots look promising. The currently downloadable version (still 3.28-07 with date 2018-08-18  despite of functional modifications in the code??), however, shows a width hysteresis between font down- and upscaling. Maybe your last change overcomes this. I still don't know for sure but will evaluate this the next days. (Just returned.)

**Comment by fesch** [comment]
Ups ... this must be due to my parallel Debian package generation where I tested my build & upload script (grown up again ;-)) ...

**Comment by codemanyak** [comment]
I started to check the details.

First of all, the hysteresis effect was due to the mistake to place method call `adjustPadding()` into the `Root.draw(...)` method - it should have belonged to `Root.prepareDraw()`, otherwise a bias remains between the prepared rectangle sizes and the actually drawn contents. Then I became aware that actually the padding adaption should ideally be moved into method `Element.setFont()` instead, so it will be done exactly whenever the font is modified, and only then. This fixes the hysteresis effect and saves a tiny bit of drawing time.

After having done that I became aware that the replacement of `fm.getHeight()` with `fm.getLeading()+fm.getAscent()` had the side effect to reduce the total height of multi-line texts, which might not be unwelcome.

But somehow this intereferes with the zooming in Arranger in a way I still cannot explain sufficiently: A diagram with multi-line instructions that is loaded into Arranger may look fine there in the first place but gets corrupted on being drawn in the Structorizer at the same time:
![grafik](https://user-images.githubusercontent.com/15326471/45268401-f3db1b00-b47b-11e8-82ce-d05aa3ac988b.png)
![grafik](https://user-images.githubusercontent.com/15326471/45268410-10775300-b47c-11e8-9e4f-d40a7e7378a5.png)
After zooming in the Arranger view, the diagram is also drawn defectively there:
![grafik](https://user-images.githubusercontent.com/15326471/45268503-b4adc980-b47d-11e8-9572-759654c00573.png)
Changing the font size then repairs both views.

The funny thing is that the zooming in Arranger is not done via font size manipulation but by canvas transformation. Apparently the transformed Graphics2D object has an noticably stronger impact on the results of `fm.getLeading()` and `fm.getAscent()` than it has on the result of `fm.getHeight()`. The obtained element record sizes are cached as long as neither the diagram nor fundamental drawing preferences change. Before the metrics change there had been perceptible but acceptable differences in the font appearance between zoomed Arranger and true-size Structorizer representations.
But the defects shown above can no longer be accepted.

I'll see how we may fix this.
It try to compensate this effect.

**Comment by codemanyak** [comment]
> I'll see how we may fix this.
It try to compensate this effect.

I think I may just have found the bug: You oversaw the `fn.getHeight()` calls in methods like `Element.writeOutVariables()`, `Element.writeOutComments()`, etc. Will check that.

**Comment by codemanyak** [comment]
The described fixes were committed to the bugfix branch.

**Comment by codemanyak** [comment]
I wrote in the issue description:
> By the way, the font chooser dialog should display the current font size in a label (the list view doesn't indicate it if none of the predefined sizes is met).

Done (only for the case the size is not in the list, though, otherwise the parenthesis vanishes):
![grafik](https://user-images.githubusercontent.com/15326471/45291194-bfa24180-b4f1-11e8-84a9-11e9aa006f5a.png)

**Comment by codemanyak** [comment]
Added a new checkbox to the FontChooser (if opened from the Preferences menu) to opt for the traditional fixed padding (if a nostalgic person still prefers it):
![grafik](https://user-images.githubusercontent.com/15326471/45304036-76fd7f00-b517-11e8-8cfa-42505bd411f9.png)
(To be delivered with version 3.28-08)

**Comment by fesch** [comment]
Oh ... what did I start there ...

**Comment by codemanyak** [comment]
@fesch 
> Oh ... what did I start there ...

Relax. I think I'm through now. The changes in FontChooser weren't as big as they may seem. Jus tiny and neat stuff. Practically, your effort just revealed some old inconveniences or "buglets" which to fix on this occasion didn't seem so bad an idea.
