### ISSUE TITLE
Reduction of add buttons in toolbar?

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#510]
I have an idea to tidy the crammed toolbar a little: What if we present only one add button per element type in the toolbar, which adds the element of the chosen type after the selected element by default, and inserts it before the selected element if the shift key is being pressed on clicking?
This would:
- follow the same logic as the function keys (e.g. F5: Instruction after, Shift-F5: Instruction before),
- present the pure element symbols without arrows (indeed students were often confused by the blue arrows at first vision) and
- reduce the number of toolbar buttons by not less than 10.

![toolbar_3 27-08_draft_half](https://user-images.githubusercontent.com/15326471/36095312-fbf24fb8-0ff1-11e8-94df-ea6c99a94306.png)

In the menus, it could (should) all remain as is.

What do you think? Would it work on Macs?

**Comment by GitMensch** [comment]
Sounds very reasonable, I like this approach. And if we actually have the same logic for the function keys it makes even more sense.

As Macs can use Upper-Case, too I don't see a reason why it shouldn't work there (if it would the function key logic would have been broken since implemented).

**Comment by codemanyak** [comment]
Okay, I did it and I think the usability will gain with it.
In a way, the arrows in the element icons of the submenus could also be seen as redundant since the submenu itself has a button already:
![redundantarrows](https://user-images.githubusercontent.com/15326471/36116873-1eea41b0-1038-11e8-923b-e3ca4da7b159.png)
But for now, I will the menu stuff as is. If we decide to wipe the arrows from all element icons then this will be 20 icons per scale less to store in the JAR file. But, well, due to their simplicity they are not the largest ones and amount to only some 93 KiB.

**Comment by GitMensch** [comment]
I'd say the additional arrow'd icons are:

* now different from the toolbar which may confuse a little bit
* were always harder to recognize than the "cleaner" version without the arrows

I therefore would vote for replacing the arrow'd icons other than the ones found for the mid-menu entries "Before" and "After". But as I cannot vote I'll come back to recommend this ;-)

**Comment by codemanyak** [comment]
I'm tending in the same direction. But I'd like to see Bob's reaction first.

**Comment by fesch** [comment]
I think that the general idea is fine (pushing Shift to insert before). To make this more intuitive, I would propose to leave the icons with the arrows pointing **down** in the speedbar. If the user pressed <Shift>, then all icons change with arrow **up** symbols, so the user knows that now elements will be inserted before the selected one.

Wouldn't that be less confusing that creating icons without arrows?

**Comment by codemanyak** [comment]
@fesch 
> To make this more intuitive, I would propose to leave the icons with the arrows pointing down in the speedbar. If the user pressed , then all icons change with arrow up symbols, so the user knows that now elements will be inserted before the selected one.

You are right, it would be more obvious. Well, I had actually also pondered this but then decided against it beause:
- As Simon wrote, the element symbols without arrows are easier to recognise.
- Usually the user will want to add elements after the current one (this is not a rebuttal but should support the feeling that at least the downward arrows are rather redundant - though of course consequent).
- To change the icons whenever the user pushes or holds the shift button might get rather scary, wouldn't you say? Remember that the shift button is also used for selection enhancement, certain key bindings etc.
- It would require a lot of low-level key listeners...
- I added a hint in the tooltips "... after (+shift: before) the selected element", so the user should sooner later find out...

Maybe I ponder it again. Or we wait for the user responses...?

Okay, and what about the Symbols in the submenus? Their parent menu item already shows an arrow and its name also says where the element will go. Should that be sufficient? But mayb you had them this way in the beginning and came to the conclusion that the many arrows make it safer?
On the other hand there is little risk in the wrong insertion direction. One may simply undo the insertion or move / swap the elements afterwards.

**Comment by fesch** [comment]
What about smaller "arrows"?
![image](https://user-images.githubusercontent.com/1027354/36141555-6d0cad84-10a5-11e8-91c6-ef04abc0d76c.png)

About the Shift-Key, you might be right, but I'm still thinking that it should be rather easy to do, as only some kind of flag needs to be changed when the key is held down. The event should be passed on for further processing of course.

I would prefer to leave the arrows in the submenus. Maybe they are redundant for experienced users, but what about beginners? Do they remember where they moved the mouse over some seconds ago? (I'm hearing such thinks from my students from time to time ....)

Personally, I can live with both variants :-)

**Comment by GitMensch** [comment]
I'd suggest a solution that only needs one listener and less icons:

* remove all errors (both menu and toolbar)
* on mouse-over add a tooltip which shows the action that will be done when clicked.

This way the menu can say "add xyz after/before the instruction" (fixed entry) and the tooltip for the toolbar is the only place that needs a change depending on the key-listener.

**Comment by codemanyak** [comment]
@fesch 
> [...] but what about beginners? Do they remember where they moved the mouse over some seconds ago? (I'm hearing such thinks from my students from time to time ....)

Well, the intermediate menu item is still visible while the respective elememt type is being chosen (see the lage screenshot further above). So the chances for forgetfulness are low.

@GitMensch 
I have no idea what you might have meant with:
> - remove all errors (both menu and toolbar)

The mouse-over tooltip had already been implemented (for all languages but Chinese - where I have no clue of the grammar):
![toolbar_tooltip_3 27-08](https://user-images.githubusercontent.com/15326471/36154894-1d6e4700-10d3-11e8-814a-aabe70061e4f.png)

This hint must of course be shown while the shift key is NOT pressed -- how would you otherwise guess that the shift key might have this impact? And once having come here, it doesn't make sense anymore to show a different tooltip while the shift IS pressed.
Hence, we don't even need a key listener at all for this simple (but in my eyes effective) strategy.

But I don't adamantly insist on this mode of operation. It just seems to me so stunningly simple and easily remembered that I couldn't resist. Honestly, the apparently clear arrowed symbols had by no means prevented many pupils from being puzzled over their meaning. And even myself often selected a button from the wrong set, also because the less frequently needed "add above" buttons used to come first. And the ways for the mouse were wide.

Frm the discussion above I get the mpression that we agree that a single set of plain element symbols makes it easier to select the right element type, and the other hand may independently decide where to place it. With or without "animation".
From key listeners that have to reconfigure 10 buttons (including tooltips) whenever I touch the shift key I wouldn't expect a benefit in reliability and swiftness - even after all errors may have ben removed...(?)

**Comment by codemanyak** [comment]
@GitMensch 
> - remove all errors (both menu and toolbar)

It just dawns on me: You meant arrows - it was just a typo... Sorry for my dullness.

**Comment by GitMensch** [comment]
Yes, arrows...

I'm fine with your current proposal (and only one arrow-free-set of symbols, including the menu).

**Comment by codemanyak** [comment]
Okay, there you are:

![menudiagramaddafter3 27-08](https://user-images.githubusercontent.com/15326471/36177474-09e6e0fa-1116-11e8-9091-d36627fba17c.png)

**Comment by codemanyak** [comment]
The change had some implications:
1. As there are no prominent arrows on the elements anymore, I decided to enlarge the element symbols such that they occupy the entire available icon area.
2. This made the Instruction button looking exactly like the white colour button.
3. So I experimented with a change of the shape of the colour buttons, which was easy to achieve:

![toolbar_3 27-08_draft2](https://user-images.githubusercontent.com/15326471/36212653-c2013c06-11a4-11e8-99c7-30d7bc7073d2.png)

The stunning effect is that the colour toolbar actually looks like a paintbox. In the 16x16 format it is a little pixeled, I have to admit, but already with scale factor 1.5 (24x24) it looks good enough:
![toolbar_3 27-08_draft2_paintbox](https://user-images.githubusercontent.com/15326471/36212933-8d3c15e4-11a5-11e8-9878-c21e1a58be6a.png)

Would you approve this change, too?

**Comment by codemanyak** [comment]
Alternatively, we could simply omit the borders around the colour buttons like in the Structorizer versions 1 through 2 (see [Screenshots](http://structorizer.fisch.lu/index.php?include=screenshot) on the home page).

**Comment by fesch** [comment]
PaintBox sound OK, as it is that  ... somehow at least ;)
Maybe the round version without the border would be find too.

**Comment by codemanyak** [comment]
@fesch 
> Maybe the round version without the border would be fine, too.

I tried:
![toolbar_3 27-08_draft4_paintbox](https://user-images.githubusercontent.com/15326471/36214198-1f710782-11a9-11e8-915e-7d99ecb6c814.png)

This approach looks better than the rectangular one, I think, but the problem with the borderless shapes is that the colour might come very near the background (see red arrow).

So, it's open for voting... ;-)

**Comment by fesch** [comment]
I vote for kicking the gray color and stay with the round borderless icons :-D

**Comment by codemanyak** [comment]
@fesch 
> I vote for kicking the gray color and stay with the round borderless icons :-D

Should we kick the white colour too? (This screenshot is taken with Windows L&F, scale factor 1)
![toolbar_3 27-08_draft4a_paintbox](https://user-images.githubusercontent.com/15326471/36214852-c5cbc724-11aa-11e8-8bac-656a9be93ab9.png)

I think, the borders induce a more defined air (if it weren't for the pixeled appearence with scale factor 1...). So my favourites are still the bordered round "pots".

**Comment by fesch** [comment]
No, we still need the white one, as this is the default an the use should be able to revert back to it.

OK, then let's go with the border ...

**Comment by GitMensch** [comment]
bordered pain-box, yay!

**Comment by codemanyak** [comment]
I find, it helps alrady to draw the border in gray colour for scale 1.0 - this makes it pixeled character less aggressive but still defines the paint jars against the bakground:

![toolbar_3 27-08_draft2a_paintbox](https://user-images.githubusercontent.com/15326471/36220628-94ebd3d6-11bb-11e8-969f-d0df2f6bb24b.png)

For larger scale factors the fine peripheral line should be black.

**Comment by fesch** [comment]
Did you turn on antialiasing for the painting? Because it doesn't look like turned on ...

**Comment by codemanyak** [comment]
@fesch 
> Did you turn on antialiasing for the painting?

No, you are right. Switching it on does the trick:

![toolbar_3 27-08_draft2a_paintbox](https://user-images.githubusercontent.com/15326471/36228473-97c80732-11d4-11e8-9755-9e326668f5ef.png)

 Many thanks for this hint! (Indeed I had looked - in vain - for a method with something of it in its name but not done a more thorough search. So I assumed that it might not be available at that level. But I was wrong, fortunately.)

On this occasion I would like to propose the removal of that "nice"/"not nice" speed button from the toolbar. I guess it's used once or twice in a decade. Most likely you choose your favourite diagram style once in a lifetime and don't ever touch it again, which would not justify it permanently occupying precious space in the toolbar. If one actually wants to change the style she/he can still do it via the menu.
So if nobody objects I'd kick it out...

**Comment by fesch** [comment]
Now the icons really look better :-D
Yes, kick the nice/not nice icon ...

**Comment by codemanyak** [comment]
With the enlarged element icons, we would now even work to place the word "FOR" in the FOR symbol:
![053_elem_for](https://user-images.githubusercontent.com/15326471/36298496-b990f480-12f8-11e8-96d2-d7d4a4418d6a.png) ![074_elem_for_din](https://user-images.githubusercontent.com/15326471/36298551-fdc89234-12f8-11e8-8a0b-320b309c6f04.png)

So I guess this would be most obvious...
