### ISSUE TITLE
Proposal to improve the placement strategy for diagrams pushed into Arranger

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#515]
Currently, Arranger uses a very simple strategy to place an added diagram: The bounding box around all already located diagrams is composed. Then if between the right bound and the right window border is enough space it will be placed at top just right of the bounding box:
![arrangement0_cut](https://user-images.githubusercontent.com/15326471/36478236-57126504-1704-11e8-9485-e27a5bf73b99.png)

Otherwise it is placed beneath the left bottom of the bounding box (red dashed box). Since this enlarges the boundig box, all further diagrams will be added along the left border downwards, leaving most of the Arranger space empty:
![arrangement1a_cut](https://user-images.githubusercontent.com/15326471/36477965-56c90770-1703-11e8-8694-c47deee3b3e8.png)
![arrangement1b_cut](https://user-images.githubusercontent.com/15326471/36477973-5e8be888-1703-11e8-933b-57936671c871.png)

The new proposal is to compute the lower silhouette line instead (green dashed line) and look for the uppermost breach that is wide enough to acommodate the new diagram:
![arrangement2a_cut](https://user-images.githubusercontent.com/15326471/36478180-2350fa82-1704-11e8-8f37-6ce6316970d2.png)
![arrangement2b_cut](https://user-images.githubusercontent.com/15326471/36478188-2a0e5964-1704-11e8-9ebd-698eb17b92da.png)

Admittedly, this approach may not be so clever if we place empty diagrams there that are supposed to grow...

**Comment by fesch** [comment]
I wanted to protest right now, but I realized then that it was in Unimozer (same problem in the class diagram) where I implemented this optimized space allocation algorithm.

If you want to save time, you may use my "aligner" package (an example is included, see the class DrawPanel):
https://github.com/fesch/Unimozer/tree/master/src/lu/fisch/unimozer/aligner

**Comment by codemanyak** [comment]
@fesch 
I see, I should have communicated earlier. Meanwhile, a prototype is working. But I will have a look how you solved it, if your solution is more elegant then I will adopt (and adapt) it. Thank you for this hint, anyway.

**Comment by codemanyak** [comment]
@fesch 
Your approach seems to follow a completely different paradigm. At first glance it somehow resembles a GridBagLayout in Java, doesn't it? Can the user still freely move entities around (overlapping) or do they snap into free grid positions. If I understand it well, the first entities (Süaces?) define the widths and heights of their cells (und thus of their columns and rows). If some placed entity grows, will it widen the respective column or row or both, right? PapDesigner follows a similar paradigm, whcih makes sense for a flow chart,
I, in contrast, respected current positions, overlappings etc. and just identified precipices to put diagrams in, as illustrated above. But the grid aproach has its charme, I have to admit (particularly with respect to font soze changes etc.). It would be a radical change, though. But its worth to be considered.

**Comment by fesch** [comment]
@codemanyak 
Actually I use this code for a first placement, so the rectangles are not being moved by it. 

I had the following situation: I add a lot of classes to an existing Unimozer project. For each class, an UML diagram is being drawn. I use this algorithm to determine where each newly added class can be placed in order to not make them overlapping. After the first placement, the user can freely move classes around. the algorithm is not applied again, so if the user want's to make classes overlap, he can do so. If rectangle grow, they will overlap.

I no see that you wanted to use this as some "layout manager", which of course, is something different.

**Comment by codemanyak** [comment]
@fesch 
> I now see that you wanted to use this as some "layout manager", which of course, is something different.

No, it was just an initial misconception of your approach, which I have understood meanwhile. It is a complete solution for the problem, nit just a heuristic approximation like mine. On the other hand, it has a time complexity of at least O(N³), in the worst case tending to O(N^4) where N is the number of placed rectangles (I felt already uneasy about the O(N²) of my approach), but I guess N has never got large enough to be noticeable?

**Comment by fesch** [comment]
Of course, if I load really big projects, like Strutorizer e.g., into Unimozer, it takes some time to place all the boxes, but most of the time is needed for the rendering of the very huge painting area itself, not by the placing algorithm.

But you are, or course, right about the complexity.

**Comment by codemanyak** [comment]
Just a little question or possible marginal improvement: Is an `Area` needed (and used) at all if it's not free? (I don't see such a case in your code.) Otherwise you could leave the FOR loop occupying lines 67 through 77 in method `Grille.getArea(int x, int y)` as soon as variable `free` is set to false.

**Comment by codemanyak** [comment]
I close this issue, as there is the heuristic mechanism is working there is no need to replace it just now. May be reopened if new facts should suggest a revision.

**Comment by codemanyak** [comment]
There are some constellations under which the placement results get totally wrong (a defective arrangement silhouette computed, such that introduced diagrams may be placed on occupied places, which is just inconvenient, of course).
Will be fixed in version 3.29-01.
