### ISSUE TITLE
Proposal: Design oo classes with structorizer

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#516]
Hi,

I would suggest a way to (at least for documentation purpuse ) describe classes with structorizer (see picture). 
![class_abcde](https://user-images.githubusercontent.com/18035140/36528309-e7d861b4-17b4-11e8-9a6c-2911e43f0fb5.png)
A class is at least a collection of properties (i.e. constants or varialbles) and methods.
Ok, so what does structurizer shall do with such a concept?

1.  Executer may ignore it, because it makes no sense to call the functions one after the other, but of course the functions it self can be testet.
2. On export:
- if the programing language (f.e. C, Shell ...) does not supports oo, the construct should be ignored perhaps with a message.
- For language with oo features a file with the class name, include all the methods with its language specific syntactical definition shall be generated

As shown in the picture the word **class** indicates the description of a class and triggers the corresponding outpurt. Optionally a parent class may be named after the two colons or with another marker.

Once again the proposal it is just for discussion.

Fine regards
Rolf

**Comment by codemanyak** [comment]
Hi Rolf,
I think this is definitively going beyond the scope of Structorizer now. A Nassi-Shneiderman diagram formalizes an algorithm, not a class. For OO design and documentation there exist other graphical means, which are dedicated better suited, UML in the first place. There are appropriate diagram types that allow to express most aspects of object-oriented projects in different scales.
We should NOT violate this tool.
It's still possible to achieve a class on Structorizer export, as a accidental side effect so to say, e.g. in the following way:
![abcde](https://user-images.githubusercontent.com/15326471/36532633-7daeb0a6-17c1-11e8-9219-c589bfe2e775.png)

**Comment by codemanyak** [comment]
What I do see, though, is that the exported Java code from my example above is inconsistent: The initialization of the attributes (residing in the includable diagram) occur in method **main** but would require them to be static the way the code is expressed, as well as in the other methods. So the global variables and constants must be made static to make sense.

**Comment by GitMensch** [comment]
@codemanyak can I propose to close or tag this issue (we still can discuss the topic here afterwards) and create an issue which will be fixed for Java export of included diagrams?
