### ISSUE TITLE
Structorizer acting really slow / sluggisch

### ISSUE THREAD

**Issue by TiNNiT** [fesch/Structorizer.Desktop#518]
Hello, 

I use Structorizer as a tool to visualize functional paths within software. Lately the program is really slow / sluggish when the diagram becomes a little complex or bigger l (starting from 7 to 8 If-statements or some CASE statements). It becomes hard to move through the diagram and actions are performed really slow. 

Would love to see this tackled.

**Comment by fesch** [comment]
Thanks for your feedback. Could you post an example file here please?

**Comment by TiNNiT** [comment]
Especially the horizontal scrolling is really slow.

[example structorizer2.zip](https://github.com/fesch/Structorizer.Desktop/files/1767487/example.structorizer2.zip)

**Comment by fesch** [comment]
I confirm slow scrolling and suspect too much calling of the repaint method. I will track this ...

**Comment by fesch** [comment]
The drawing of the diagram needs nearly half a second. This is the reason for the slow scroll behavior. 
I have to dig further ...

**Comment by fesch** [comment]
I tracked it down to this command: root.getTypeInfo().containsKey(":" + display)

**Comment by fesch** [comment]
Inside that method, the following line make everything slow: this.traverse(collector);

**Comment by fesch** [comment]
At this point I leave it to @codemanyak, because I can't figure out right now what he intended to do with that line.

@TiNNiT : I hope the propose work-around is fine for you ... at least until this is fixed.

**Comment by TiNNiT** [comment]
Euhhhhh;-)

I'm not that tech savy! Is the workaround that I don't use ":" anymore?

**Comment by fesch** [comment]
Sorry, my post with the workaround did not get through. 

Workaround = disable the "Hightlight variable" option in the "Diagram" menu.

![image](https://user-images.githubusercontent.com/1027354/36853503-fc8a6e9e-1d6e-11e8-806a-b74f6542b5cc.png)

**Comment by TiNNiT** [comment]
Yes that works!

Thx for the effort and workaround!

**Comment by codemanyak** [comment]
@fesch 
My thanks, too, for the localization of the retarding method. I will have a deeper look this evening.
The tree traversal for collecting type info from the diagram elements (using a visitor) takes of course its time but the type info should then be cached until the diagram's changed. So it should be done only once. Maybe the caching fails or is averted by some concurring mechanism. But I'm afraid it's because the Analyser does the type analysis incrementally and therefore ignores the cached type map by providing a temporary one each time the analysis is done.

**Comment by codemanyak** [comment]
In the given example, there is no syntactical anchor for type and variable analysis. Therefore, the type map of the diagram remains empty. Therefore the type retrieval during the highlighting tries to do the entire recursive syntax analysis over and over. In this case, variable highlighting doesn't make a sense, of course, such that the workaround to switch it off does indeed the trick without loss of information.
But I will implement a distinction between an unretrieved type map and an empty type map. This way, the unnecessary repitition of the full diagram traversal can be avoided and the drawing performance for diagrams without any detectable variable or type information in highlight mode would be aleviated.

**Comment by codemanyak** [comment]
The fix is uploaded to the bugfix branch and will be part of the next version (3.28-01).

**Comment by TiNNiT** [comment]
Thx, will test it in the next version!
