### ISSUE TITLE
Bug on exporting variable declarations

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#521]
Variable declarations are not only converted into the (more or less) correct target language syntax but are also copied as are into the target code (among the instructions), possibly an unwanted side effect of a recent bugfix for another issue.
Detected on analysing #520.

**Comment by GitMensch** [comment]
Could this be a good time to re-raise the issue about automated testing? At least one code import and export for each (partly) supported language would help with issues like these.

**Comment by codemanyak** [comment]
@GitMensch 
> Could this be a good time to re-raise the issue about automated testing?

Yes, but I'm starting to doubt it would help in this case: I had just accidently set the export option "No conversion of the instruction/expression contents". If this option is disabled, the xport looks pretty fine. The good question, however, is whether the extraction of the type definition and variable declarations should happen in the "no conversion" mode. This isn't specified exactly.

**Comment by codemanyak** [comment]
The issue is yet valid for Oberon export in unsuppressed transform mode (var declarations had additionally been exported as are in place, i.e. within the routine body).

**Comment by codemanyak** [comment]
Another related bug was detected and will be fixed with the next version (3.28-01): On export to C, C++, C#, and Java broken ordinary instruction lines like
```
a <- 17 *\
(b + c - sin(1.048))
x <- abs(a)
```
weren't correctly joined on export.
