### ISSUE TITLE
Bug: NSD is not saved - only .bak file

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#526]
Hi,

I build a (function not a program) nsd with the name "Postgresql-installieren". When saved and exit structurizer the nsd-file can't be opend after the next start of structurizer because "file not exists". In my file manager I only find "Postgresql-installieren.nsd.bak", which indeed is an older backup file i.e. not with the newest content. When saved with a simpler name this did not happen.
After I found this misbehavior in an older version I tested it with the newest version and the problem still exists.

Why does structurizer hate my filename? Is it the dash or is the name to long?  Or is it a mismatch between the filename and the function name?

Fine regards
Rolf

**Comment by reks99** [comment]
Hi,

further tests show a similar behavior, when add a "statement"-box at the end of a nsd. When saved, and exit structurizer the nsd was not saved only a bak file can befound.

Hope that helps to find the bug.
Rolf

**Comment by codemanyak** [comment]
@reks99 
I have no idea why this happened. Neither the hyphen nor the length nor a file name differing from the diagram name have ever been a problem.
Nor do I understand why a "statement box" (Ithis should mean an ordinary instruction element, shouldn't it?) at the end of a diagram should prevent it from saving. There are thousands of diagrams with these properties.
I'll try to reproduce it. Perhaps you might export the diagram as PNG file and send this before you try to save the diagram?

**Comment by codemanyak** [comment]
@reks99 
As I had expected, I can't reproduce the trouble with a fresh diagram of usual contents. It can be modiied and re-saved with or without backup option activated.
If you start Structorizer via a shell script on Linux then I would like you to look for some error messages in the standard error or standard output stream (I haven't changed Structorizer in such a way that it uses the Java logging system yet).
Please check whether you have checked the backup option in the Saving Prefernces. If not then this could be an indication that Structorizer might fail to gain writing access on a suited temporary directory where it tries to write a temporary copy before renaming. Obviously you managed to write a first versionof the diagram file under its desired name. So it's the overwriting of a previous version that fails. The former version is successfully renamed to *.bak, so either the writing of the new file under a temporary name fails or the replacement, I'd say. And this might be an authorisation problem (just a guess), though I still wonder why you don't get an error message x in such a case.

**Comment by reks99** [comment]
Hi,
the following scenario seems to show the problem:
Use the attached nsd and open it in structurizer. Save it. Start structurizer new and open the file with "last used". Then add an instruction element at the end. Exit structurizer either by click on the exit bottom of the window or use the exit function in the file menu.
Structurizer didn't ask me to save the modified file and silently exits.
Now start structurizer again and try to open the file and.
BTW. there was no output in the terminal window except the message that the german txt-file will be loaded.

Hope that helps
Fine regard
Rolf
[PG.zip](https://github.com/fesch/Structorizer.Desktop/files/1828727/PG.zip)

**Comment by codemanyak** [comment]
@reks99 
Thank you. Now I can reproduce the behaviour, but only under linux. On Windows 7 it works flawlessly. Strange. But at least I had a chance to analyse it now.
The temporary file is indeed written (have a look in /tmp for files Structorizer*.nsd with the respective date and time) but apparently Structorizer fails to move and rename it to the current directory without noticing it. In my case it would have been a move across different file systems and maybe it's the same on your system.
I will program a workaround by an attempt to copy the temporary file bytewise to the target directory in case the renaming failed and then delete the temporary file if that succeeded.

**Comment by codemanyak** [comment]
Succesfully tested bugfix uploaded to bugfix branch for version 3.28-02

**Comment by reks99** [comment]
@codemanyak 

Hi Kay.
Did you change something with the file save functionallity? I use Structurizer since years and the reported bug was never seen bevor.

Is it possible to ge the 3.28-02 version for download?

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> BTW: Did you change something with the file save functionallity? I use Structurizer since years and the reported bug was never seen bevor.

No, that part of code had remained unchanged since bugfix #40 in December 2015. Maybe something in Linux or the implementation of Java method `File.renameTo()` has changed. The description of that method says at least that it may not work properly on certain platforms. Back then I had tested it on both Windows and Linux therefore and not found a deficiency. And nobody had complained ever since. But well, it was some kind of optimistic coding, I shoudn't have relied on it. But I remember now that the knowledge about the existence of the files in the tmp directory would at least prevent losses had made me dare to deliver it.

> Is it possible to get the corrected 3.28-02 version for download?

Sure. I have been working on the logging mechanism (#463) but I upload you an extracted Structorizer.jar file from the code after this fix and before my redesign of the error, debug, and log messages. So you could name it a 3.28-02beta version.

[Structorizer_3.28-02pre.zip](https://github.com/fesch/Structorizer.Desktop/files/1836445/Structorizer_3.28-02pre.zip)
Just replace the Structorizer.jar file in your installation with it. This should solve the problem.

**Comment by codemanyak** [comment]
@reks99 
I wrote:
> The description of that method says at least that it may not work properly on certain platforms.

This is indeed a point I don't understand. The UNIX/Linux `mv` command has no problems with moving or renaming across file systems. So why doesn't `File.renameTo(name)` just use this `mv` command under Linux? Or why haven't the Java developers simply implemented themselves the workaround I had to write (inside method File.renameTo())? If there is an adapter method levelling the platform differences - why can't it be reliable?

**Comment by reks99** [comment]
Hi Kay.

Many thanks for the upload.
When thinking about the bak mechanism I think I would implement it without a tmp-file. I would just  rename (or copy) the orig file after successful load in *.bak and - if needed - overwrite it in the wanted intervalls and save the new file on exit as usual.

Just my 2 ct
Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
Hi Rolf,
> When thinking about the bak mechanism I think I would implement it without a tmp-file. I would just rename (or copy) the orig file after successful load in *.bak and - if needed - overwrite it in the wanted intervalls and save the new file on exit as usual.

You are right - if we only consider this simple case. But the code is a delicate result of merging the handling of first-time saving with re-saving of a) ordinary nsd files and b) nsd files within an arrz archive. For some of the cases a temporary file out of sight of he target directory was inevitable. After a quick scrutinizing I would rather have to write the saving routine again from scratch lest I should compromise some of the bundled cases here by a half-boiled simplification. I will keep a redesign in mind, though.
