### ISSUE TITLE
Two inconvenient aspects with WebStart

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#551]
1. Since the WebStart installation updates itself automatically if online, it doesn't make sense to pop up the message box with the hint about the option to activate the retrieval for new versions. And while offline, the retrieval wouldn't work either, anyway. So the dialog should be suppressed in a webstart environment. That's what I'm preparing.
2. If both a local installation and a WebStart installation coexist on the same machine then launching the WebStart always ensures that there is a desktop icon with name "Structorizer" and tweaks the link info of an existing one. This is somehat ugly if the desktop link for the local installation had been named "Structorizer", too. Of course one might give it a different name to avoid this inadvertent "update", but possibly the Webstart version might use a Shortcut Link named "Structorizer WS" or "Structorizer Webstart" instead?

**Comment by GitMensch** [comment]
+1 for "Structorizer Webstart"

**Comment by codemanyak** [comment]
Version 3.28-05 solved the first aspect, but the second one is still open.
@fesch 
Bob, would you mind changing the name of the desktop link automatically created by the Java WebStart version of Structorizer to "Structorizer WebStart" for the next release?

**Comment by fesch** [comment]
`<menu submenu="Structorizer WebStart" />
`
done

**Comment by codemanyak** [comment]
For the new Windows installer, a similar detection mechanism as for Java WebStart is needed to suppress the hint about the option to activate the update check.
