### ISSUE TITLE
Structorizer gets stuck with huge number of generated diagrams on code import

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#557]
After having managed to import a sample C file from openCOBOL (libcob/common.c), which produced 194 (!) diagrams from this single file, Structorizer became completely irresponsive. Though all the diagrams were rendered once in Arranger, Structoizer didn't react to user interaction of any kind anymore. It had to be killed.
For cases of a huge number of generated diagrams, a workaround allowing at least to save all generated diagrams rightaway rather than to push them into Arranger would be utterly helpful. This way the effort wouldn't be lost and the user may inspect the diagrams one by one or in smaller disciples without trouble.

**Comment by codemanyak** [comment]
Of course, we will also have to identify the contention hot spot and find ways to improve the GUI reaction, but the proposed workaround is still reasonable and easy to achieve.

**Comment by GitMensch** [comment]
What about a general GUI option that defines how many diagrams are seen fully in the Arranger, maybe defaulting to 20. On open/import the most "outer" diagrams would be opened, all others would be shown collapsed and may be unfolded manually. This way you likely start to see that the GUI is becoming slow and can collapse some currently not interesting diagrams (I *guess* nobody can actually follow that much diagrams in parallel in any case).

**Comment by codemanyak** [comment]
An idee worth to be considered. At least while there aren't more precise instruments to reduce the event queue load.
I will think over possible ways to signal the user whether and possibly even which diagrams ought to be collapsed or removed from Arranger.

**Comment by codemanyak** [comment]
The total lock of Structorizer wasn't actually caused by the sheer number of diagrams - this was mere coincidence. Instead, it was one single diagram out of the 149 generated ones that drove Structorizer into an eternal loop on the attempt to classify an Instruction element. The vulnerable loop had been there since version 3.26-06.
It was an instruction line with a qualified variable access, comprising a sequence of both "->" and "." operators (e.g. `cobsetptr->cob_time_constant.hour <- tmptr->tm_hour`), which set the bug loose - a combination that is obviously rather unlikely in Structorizer without massive import of C files.
The fix is being prepared,

Nevertheless the GUI contention with 149 files in Arranger is really annoying, though wouldn't freeze Structorizer totally. Hence, the introduced limitation option still makes sense.

**Comment by codemanyak** [comment]
I experimented with cached images of the interior of diagrams residing in Arranger but this was a complete desaster. It took way more time to draw these buffered images than to redraw the diagrams and it drove Structorizer immediately into an out of memory state. So this was definitely the wrong way to go.

**Comment by GitMensch** [comment]
@codemanyak Do you plan to do something about this issue or do you considered it "finished"?

Completely unrelated other than your finding source: Can you please drop a note somewhere which settings you've used to be able to parse libcob/common.c?

**Comment by codemanyak** [comment]
@GitMensch 
> Can you please drop a note somewhere which settings you've used to be able to parse libcob/common.c?

Sure. I used ANSI-C99 with the following language-specific settings (not all of them where necessary for this file, though):
- Externally defined type names: FILE, LPFILETIME, FILETIME, SYSTEMTIME, sig_atomic,_t, message, vir_clicks, vir_bytes, mpz_t, jmp_buf, cob_u32t
- Redundant preprocessor names or macros: __stdcall, COVB_EXPIMP, COB_A_NORETURN, COB_A_FORMAT12, COB_A_FORMAT_23, COB_A_FORMAT34, COB_A_FORMAT45, DECLNORET
- [x] Use type names and defines from WINAPI

But this wasn't sufficient. I had to manipulate the file itself a little:
1. I inserted a line `#include common.h`
2. I removed the newlines in the block comments in lines 2146/2147, 2175/2176, 2247/2248, 7210/7211
3. I disabled (commented out) line 2249.

What I had forgotten to patch for version 43.28-05, was the workaround for 2 - if a block comment starts within a preprocessor line and doesn't end within the same line then the insertion of `"// preparser define ..."` by method `CPreParser.handlePreProcessorLine(...)` compromises the block comment.
A quick hack would have been to check if `"/*"` occurs in the line but `"*/"`doesn't and then to insert `"/* preparser define ..."` instead of the usual line comment version. But for a clean solution one would have had to ensure that the comment delimiters don't occur within string literals, that there aren't several block comments in the line etc.

**Comment by codemanyak** [comment]
@GitMensch 
The requested progress information in batch mode still hasn't been implemented with version 3.28-05. It stands somewhat in conflict with https://github.com/fesch/Structorizer.Desktop/issues/179#issuecomment-215972231 (option te redirect the output to stdout), I think. So I wanted to have more time to consider the consequences and possible solutions.

**Comment by codemanyak** [comment]
@GitMensch 
> Can you please attach the adjusted common.c file (ideally with reverting step 2 which should not be needed any more, if I understood you) and specify a complete command line that should be able to run the import (in a fresh-built non-configured version) without opening any GUI?

Unfortunately it won't work without appending the following lines to the "virgin" structorizer.ini (i.e. after it had been created by a first Structorizer start) before:
```
C99Parser.typeNames=FILE, VOID, ULONGLONG, LPFILETIME, FILETIME, SYSTEMTIME, sig_atomic_t, message, vir_clicks, vir_bytes,mpz_t, jmp_buf, cob_u32_t
C99Parser.redundantNames=__stdcall, PUBLIC, PRIVATE, FORWARD, COB_EXPIMP, COB_A_NORETURN, COB_A_FORMAT12, COB_A_FORMAT23, COB_A_FORMAT34, COB_A_FORMAT45, DECLNORET
```
You will the options reflected in the screenshot further below (first printings after the command line). Note that not all entries in the preferences _C99Parser.typenames_ and _C99Parser.redundantNames_ may be necessary, but it works if these are present. There is still no opportunity to specify these settings in the command line itself.

This is the modified C file (together with the two header files needed in the same folder), now:
[common_kgu1.zip](https://github.com/fesch/Structorizer.Desktop/files/2415767/common_kgu1.zip)

And here you see the screenshot of the command line, its execution gossip and the folder listing after its accomplishment:
![grafik](https://user-images.githubusercontent.com/15326471/46023446-f167fa80-c0e4-11e8-8fd9-2515ec0047c2.png)

Back to the originary problem:
> I think this may be solved, isn't it?

Umh, no. It hasn't been solved because I still don't know how to solve it. As outlined in https://github.com/fesch/Structorizer.Desktop/issues/557#issuecomment-405136972, the performance still doesn't make me happy though the major problem had been circumvented.

**Comment by codemanyak** [comment]
@GitMensch 
> (ideally with reverting step 2 which should not be needed any more, if I understood you)

Oh no, I haven't solved this either yet because to fix it in better way than with the mentioned quick hack is somewhat tricky.

**Comment by GitMensch** [comment]
> Unfortunately it won't work without appending the following lines to the "virgin" structorizer.ini (i.e. after it had been created by a first Structorizer start) [...]

Was there an issue about specifying a named parser setting via command line. yet (the parser may be "asked" if he understands them)?

We do have an option to specify a different structorizer.ini, don't we? In this case it would be reasonable to add both the test sources and the ini to version control for CI.

**Comment by codemanyak** [comment]
> We do have an option to specify a different structorizer.ini, don't we?

Oh yes, it was the -s option specified in #554. Thanks to remember me.

> In this case it would be reasonable to add both the test sources and the ini to version control for CI.

Where would I preferably place them? I thought of a new "samples" directory on project top level. The further hierarchy might look e.g. like this:
```
samples
  code_import
    import_c
      sample001
        results
          common.c.cb_config_entry-2.nsd
          ...
        common.h
        coblocal.h
        common.c
  code_export
    export_java
       ...
```
In my personal project folder I have gathered hundreds of sample files associated to certain GitHub issues. It would be a pretty hard work to select a subset of them with few overlapings. I do not actually look forward to this effort.
To write sensible test cases will certainly take years.

**Comment by codemanyak** [comment]
I'll put provisional test files to issue #608.

**Comment by codemanyak** [comment]
I wrote in https://github.com/fesch/Structorizer.Desktop/issues/557#issuecomment-403876254:
> Of course, we will also have to identify the contention hot spot and find ways to improve the GUI reaction, but the proposed workaround is still reasonable and easy to achieve.

I now realized that it makes a dramatic difference if syntax highlighting is switched off. So, obviously the complex syntax analysis is a major factor of drawing contention. Hence, the simplest workarond is to switch it off, in many diagrams are held in Arranger.
So, possibly it makes sense to switch off syntax highlighting in Arranger if a certain number of diagrams is exceeded.
On the other hand, I will check whether the drawing can be reduced to the actually shown elements: Whereas this would be a hard task to do for Arranger or Structorizer, it is embarassingly simple for the elements themselves if the viewport bounds are passed to the draw() method.

**Comment by codemanyak** [comment]
Unfortunately the solution delivered with 3.29-05 has a nasty bug: parts of the diagrams are not shown because the visibility detection used the (smaller) predraw records instead of the actual draw records of the elements for intersection check. This has to be fixed immediately.
On this occasion, Arranger will be enabled to detect the contention (based on the time difference between latest event on the queue and he current system time) and to switch off the syntax highlighting unil the contention is gone. This may also cause some drawing artefacts on scrolling but they seem acceptable in comparison to the very annoying slow down. So there will be time for new approaches to accelerate the syntax highlighting (though that will never be as fast as drawing plain texts, of course).
