### ISSUE TITLE
Code import should at least provisonally support enumeration types by generating constants

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#558]
On a longer perspective, it would be nice if Structorizer supported enumeration types, which are available in many languages (including C, Pascal, Java, Python >= V 3.4, etc.) in its syntax, on execution, and export.
On the shorter run, it would at least be helpful to have a provisional support on code import, e.g. by defining the enumeration type members as integer constants such that a C definition like
```c
/* Config dialect support types */
enum cb_support {
	CB_OK = 0,
	CB_WARNING,
	CB_ARCHAIC,
	CB_OBSOLETE = 9,
	CB_SKIP,
	CB_IGNORE,
	CB_ERROR,
	CB_UNCONFORMABLE
};
```
would produce such an element:
![grafik](https://user-images.githubusercontent.com/15326471/42542721-84f65c52-84a8-11e8-8867-dc747570f41f.png)

The recent C import just produces a disabled element with the original code line.

**Comment by GitMensch** [comment]
@codemanyak Do you consider it finished with the "provisional fix" or do you want to reopen it?

**Comment by codemanyak** [comment]
I reopen this issue for an intended complete solution somewhat later.

**Comment by codemanyak** [comment]
A possible syntax for the type definition in Structorizer might be:
`type cb_support = enum{CB_OK, CB_WARNING, CB_ARCHAIC, CB_OBSOLETE <- 9, CB_SKIP, CB_IGNORE, CB_ERROR, CB_UNCONFORMABLE}`
The effect for Analyser and Executor would be the same as from the provisional const definitions, but on code export there would be the chance to produce veritable enumeration types.

Note that an enumerator type definition of this kind would have an actual impact on execution (i.e. defining all comprised constants at once) in contrast to the record type definitions. It is of course a problem that we introduce more and more non-algorithmic stuff into a structogram, which isn't intended to contain non-algorithmic elements. I do see that the pragmatic enhancements to support code export and import are compromising the original ideas of Nassi and Shneiderman.
It might be a good idea to return to an privately proposed idea of Klaus-Peter Reimers to provide a separate assistant area in Structorizer for data type construction. Of course a clever selective connection between algorithmic diagrams and the type pool would still have to be invented.

**Comment by codemanyak** [comment]
@GitMensch 
No, I haven't advanced this issue yet.

**Comment by codemanyak** [comment]
Derived a new issue #739 and closed this one (according to the accomplished task named in the title)
