### ISSUE TITLE
Try ... Catch statement in NSD

### ISSUE THREAD

**Issue by fesch** [fesch/Structorizer.Desktop#56]
A long time ago Hanspeter Thöni asked me integrate a "try ... catch" statement. 

The first drawing I made was this one. I never integrated them.

This issue is thus just a placeholder in order not to lose the idea ;-)

![inbox - local folders](https://cloud.githubusercontent.com/assets/1027354/11752988/07461528-a043-11e5-9be3-657617dec635.jpg)

**Comment by codemanyak** [comment]
Interesting idea. Are we going to propose a new NSD standard?
But seriously: The design is not so bad. It resembles a jump as well as the forced sequence into the finally block.
But how should it look if try and catch block consist of instruction sequences including complex control structures themselves?

**Comment by fesch** [comment]
Your are right, this first drawing omits the "blocks". Maybe, to stay with them, we could do something like this, which resembles the code structure somewhat more:
![skitched-20151212-103053](https://cloud.githubusercontent.com/assets/1027354/11761263/6cdaa444-a0bb-11e5-80a7-c25e540e43fc.jpg)

**Comment by fesch** [comment]
But anyway, that will be very funny to implement in the executor ... especially when such try-statements will include some other try-statements  ...

**Comment by codemanyak** [comment]
... yep! And we shouldn't forget that the request for a throw mechanism would be raised as well, where of course the Jump element might be extended for (fourth semantic variant).

**Comment by reks99** [comment]
Hi,

Try and catch (and final) have been introduced in programming by c++. So at least it is a feature of objectoriented languages. Than the next implementation whishes are for objects, derivation ...
I think that might be implemented in UML - NSD is from the time wher procedural programming was state of the art. I use NSDs to clearify the structure of methods.

Just my 2 ct.
Rolf

**Comment by codemanyak** [comment]
Just some preview...
![grafik](https://user-images.githubusercontent.com/15326471/54502172-84ae1a00-4929-11e9-9683-a47b67fd2c16.png)

**Comment by codemanyak** [comment]
Prototype is nearly ready. Generation of Try elements on Pascal import still to be done.

**Comment by codemanyak** [comment]
Bob (@fesch ) suggested some really good ideas for the further accomplishment. I put them into a new issue.
