### ISSUE TITLE
Rare error with Java WebStart on a computer

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#560]
![grafik](https://user-images.githubusercontent.com/15326471/42753276-acf625ba-88f0-11e8-876c-4b39f7786f71.png)
On one single PC the Java WebStart of Structorizer version 3.28-05 reproducibly fails with the following stacktrace:
```
java.lang.NullPointerException
	at com.sun.javaws.LocalInstallHandler.registerAssociation(Unknown Source)
	at com.sun.javaws.LocalInstallHandler.createAssociations(Unknown Source)
	at com.sun.javaws.LocalInstallHandler.install(Unknown Source)
	at com.sun.javaws.Launcher.notifyLocalInstallHandler(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
The PC is running with Windows 7 and Java 1.8.0_171.
The local installation of Structorizer 3.28-05 runs without problems on this PC. WebStart had also worked last week (with Structorizer 3.28-04).
On all other computers I have tested the WebStart version since yesterday, there haven't been problems, either.

The shown JNLP text seems to be okay as well:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE jnlp PUBLIC "-//Sun Microsystems, Inc//DTD JNLP Descriptor 6.0//EN" "http://java.sun.com/dtd/JNLP-6.0.dtd">
<jnlp spec="6.0+" codebase="http://structorizer.fisch.lu/webstart" href="index.jnlp" version="0.23">
  <information>
    <title>Structorizer</title>

    <vendor>Bob Fisch</vendor>
    <homepage href="http://structorizer.fisch.lu/index.html" />

    <description>Structorizer</description>
    <description kind="short">Creates and executes Nassi-Shneiderman diagrams.</description>
    <description kind="tooltip">NSD Editor</description>
    <icon href="http://structorizer.fisch.lu/webstart/structorizer.png" width="128" height="124" />

	<!-- register file type -->
    <association extensions="nsd" mime-type="application/structorizer" />
    <association extensions="arr" mime-type="application/structorizer" />
    <association extensions="arrz" mime-type="application/structorizer" />

    <!-- hints for setting up shortcuts -->
    <!-- Prefer a shortcut for online operation -->
    <shortcut online="true">
	    <!-- create desktop shortcut -->
	    <desktop />
	    
	    <!-- create menu item for this app under the major heading Structorizer -->
	    <menu submenu="Structorizer" />
    </shortcut>
	
    <!-- allow offline use -->
  	<offline-allowed/> 
  </information>
  
  <security>
    <all-permissions />
  </security>
  
  <update check="always" policy="always"/> 

  <resources>
    <!-- Acceptable JVMs in preferred order, best first -->
    <j2se version="1.7+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
    <j2se version="1.6+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
    <j2se version="1.5+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
     <!-- any vendor -->
    <j2se version="1.5+"      initial-heap-size="128m" max-heap-size="512m" />

    <jar href="Structorizer.jar" main="true" download="eager"/>
	<property name="sun.java2d.dpiaware" value="false"/>
	
  </resources>

  <!-- application class with main method -->
  <application-desc main-class="Structorizer" />
</jnlp>
```

The stacktrace suggests that it may have to do with the file associations to be established (there was indeed a change since last version, i.e. files types .arr and .arrz were included).

When I check the file associations with the OS tools, I see an association for .arr files (see screenshot) and .nsd files, but the intended one for .arrz files is missing:
![grafik](https://user-images.githubusercontent.com/15326471/42753225-7e7df0c8-88f0-11e8-9e00-e4970ac1a23e.png)
But that the OS may never have seen an .arrz file on this computer can hardly explain the error, I think. On the first installation it wouldn't have seen .nsd and .arr files, either. So it should always crash then.
(And there had definitely been and still are .arrz files on this computer.)

**Comment by codemanyak** [comment]
Bingo! Now I forced a file type association by double-clicking an .arrz file, associated Structorizer.exe to it an then tried to start Structorizer WebStart again, and here you are: It asked me whether the arrz association ought to be replaced and then started as if it had always done so. What a f...!

**Comment by codemanyak** [comment]
I will have to continue testing on computers where Structorizer has never run.

**Comment by codemanyak** [comment]
I have not been able to reproduce the error message on other computers so far.
On the other hand, it seems to be pretty well reproducible that only .nsd and .arr file associations are established, whereas WebStart fails to associate .arrz files with Structorizer. (Can only three-character extensions be associated this way?)

**Comment by codemanyak** [comment]
> On the other hand, it seems to be pretty well reproducible that only .nsd and .arr file associations are established, whereas WebStart fails to associate .arrz files with Structorizer.

After having tested the WebStart launch on a dozen other computers, I cannot reproduce even this now. It seems to work fine (all three file extensions are associated), no matter whether there had been an .nsd file association to a locally installed Structorizer (I'm duly asked whether it is to be replaced) before or not. Seems I was chasing after something phantasmal.

**Comment by codemanyak** [comment]
@fesch 
This explains it, now! Thank you.

**Comment by codemanyak** [comment]
@fesch 
I just saw that the Java VM check in the JNLP file starts with version 1.7:
```xml
    <!-- Acceptable JVMs in preferred order, best first -->
    <j2se version="1.7+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
    <j2se version="1.6+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
    ...
```

Shouldn't it perhaps start with Java 1.8+?
```xml
    <j2se version="1.8+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
    <j2se version="1.7+"      href="http://java.sun.com/products/autodl/j2se" initial-heap-size="128m" max-heap-size="512m" />
    ...
```
Or do I interpret something wrong?

**Comment by fesch** [comment]
It has never been updated .. thus ;)

**Comment by codemanyak** [comment]
I see. :smirk: Actually I doubt that Structorizer will even run with Java versions < 1.8 at all ...
