### ISSUE TITLE
Version check doesn't work anymore, due to homepage relocation to https.

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#566]
The version check mechanism of all installed Structorizer versions went out of order since the Structorizer homepage was upgraded to https protocol (the version.txt ressource now contains an information where to look instead, but no longer the expected version information). Fortunately, the code is robust enough not to cause exceptions. But it's not intelligent enough, of course, to understand the redirection info ;-)
The hard-coded homepage link (which the version.txt retrieval relies on) will be adapted in version 3.28-06 only. As it turned out, however, homepage URL references happen to be distributed over about half a dozen locations in the code.
There will have to be one single constant, say in class Element, from now on, which all other methods must refer to.

**Comment by fesch** [comment]
Ups ... didn't think about this when switching to https :(

**Comment by codemanyak** [comment]
@fesch 
Ups ... didn't think about this when switching to https :(

Never mind. Apart from this defect, I appreciate the update to https.

By the way, the URL help.structorizer.fisch.lu/index.php is still on http. Do you intend to upgrade it to https as well?

**Comment by fesch** [comment]
Yes, I will upgrade that one too.

**Comment by codemanyak** [comment]
Just having seen it's done, I think it will be best to launch version 3.28-06 just now...
