### ISSUE TITLE
sub-versions not available as GitHub Release

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#570]
Is there a reason that the sub-versions are available via web-start and as download but not from https://github.com/fesch/Structorizer.Desktop/releases ?

From looking at https://github.com/fesch/Structorizer.Desktop/tags there seem to be no tag for all sub-versions since 3.23 an none at all since 3.25.

It would be nice to at least have a tag allowing to download and compare the source code between all released (sub-)versions.

**Comment by fesch** [comment]
I won't go back to just hitting the button.

**Comment by GitMensch** [comment]
@fesch: Thank you for the current version.

> I won't go back to just hitting the button.

I'm not 100% sure I understand this correctly. For older versions or if the tag just wasn't created you don't need to go back:

`git tag <3.n-s> <SHA-of-the-matching-commit>`

Doing this for older versions already allow for a simpler compare of versions (helpful for bug hunting). A completely different issue is to create a release from the tag via GH button click (I assume you don't use CI for this), copy+paste the parts from the changelog there and possibly adding the artifacts.

What do you think about re-opening the issue and adding the missing tags (later)?

**Comment by fesch** [comment]
Sorry, can't see the point in doing all this work. There is no ROI for me ...
If you want to invest yourself, I can grant you the needed rights.

**Comment by GitMensch** [comment]
> If you want to invest yourself, I can grant you the needed rights.

Thank you. In this case: please reopen and assign to me, I'll likely come back to this within some weeks.
Where would you search for the SHA of the sub-releases done?

**Comment by fesch** [comment]
Assignment is done.
For the search: first look at the change log for the date, then probably by clicking trough the many commits ("Older" button at the bottom) until you reach the desired date of bugfix number.

**Comment by codemanyak** [comment]
Okay, now that I know how it works, I can guarantee that all subsequent versions will be available as releases on GitHub.
