### ISSUE TITLE
3.28-06: Structurizer License in GUI shows Changelog

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#571]
Help->About->Changelog is fine
Help->About->License shows the Changelog, too, not the license.

Please consider to also place the Changelog into the release versions (next to license.txt) and reference or even include (for example with a link) the in-tree version in README.md.

Thank you.

**Comment by codemanyak** [comment]
> Please consider to also place the Changelog into the release versions (next to license.txt) and reference or even include (for example with a link) the in-tree version in README.md.

The file changelog.txt **is** (has always been) located in the source tree next to that license.txt that should have been presented in the About dialog: src/lu/fisch/structorizer/gui.

It might certainly be referenced by README.md

**Comment by GitMensch** [comment]
I didn't meant the source tree (it is clearly in there) but the release package. It currently is missing there:

![grafik](https://user-images.githubusercontent.com/6699539/43419968-c56bce08-9442-11e8-99a8-66dc94f340b3.png)

I *guess* I've asked this before - where in the source tree is the packaging defined?

**Comment by GitMensch** [comment]
> It might certainly be referenced by README.md

it actually *is* referenced (linked, to) but it seems too easy to not see it. Will PR a suggestion.

**Comment by fesch** [comment]
deployment script updated.

**Comment by GitMensch** [comment]
@fesch wrote:

> deployment script updated.

I fail to see the commit, can you please upload it if it is currently missing?

**Comment by fesch** [comment]
No, my deployment script is private and has never been on GitHub as it contains sensible data.

**Comment by GitMensch** [comment]
What do you think about renaming the script to something like
deploy_core_script.sh, switching the sensible parts to use environment variables and create a script with the old name that just set the variables and calls the "core" script, then upload the core script?

**Comment by fesch** [comment]
There are other scripts for building Structorizer which are available at the repository, isn't that enough?

**Comment by GitMensch** [comment]
I failed to see the script that creates the release files structorizer[_latest][_mac].zip, did I miss something?
Actually this is the part of the "deployment" script I'd like to see in the repo (and your current script calling it)...
