### ISSUE TITLE
Do you plan to co-publish releases as stand-alone application, including a "custom" java runtime?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#573]
As noted by [Oracle Java SE EOL roadmap][1]

> Oracle will continue to provide Public Updates and auto updates of Java SE 8, until at least the end of December 2020 for Personal Users, and January 2019 for Commercial Users.

Afterwards you either move to be a paying "Oracle Customer" or use OpenJDK (for example from http://jdk.java.net/11, http://jdk.java.net/10/, http://jdk.java.net/archive/, your distro or the build service I currently prefer: https://github.com/ojdkbuild/ojdkbuild/releases).

The interesting part from the quoted page is:

> [....] we encourage application developers to use the packaging options introduced with Java SE 9 to repackage and deliver their Java applications as stand-alone applications that include their own custom runtimes.

Therefore:

* Can Structorizer be compiled and run with Java 11 (next LTS after Java 8) already?
* Do you plan to co-publish releases as stand-alone application, including a "custom" java runtime?

[1]:http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by codemanyak** [comment]
This is not the answer to your question, but some considerations:
1. Obviously Oracle sees an issue with their ROI in the Java field. It will be interesting what comes next (VirtualBox, perhaps?).
2. At the moment I don't see why Structorizer shouldn't run on Java 11. But JavaWebStart is being faded out by Oracle. If I understand the roadmap well, it will only be supported in combination with Java 8 (till 2025 or so). So this might become a problem unless the now recommended deployment tool(s) can replace it.
3. Now I'm really glad that I didn't start to rewrite the GUI for JavaFX to overcome the lacking DPI awareness, because JavaFX is also doomed now. It seems that Swing is to survive instead.
4. I think the "update" to a paying Oracle Customer is hardly an option unless some commercial Java products in the portfolio required it anyway.

**Comment by GitMensch** [comment]
Concerning 3: I don't think JavaFX is doomed, it just starts to be a separated module that doesn't need to be updated and provided with the more-often planned new Java releases.
I think the change about Java SE will mainly create more pressure to update to newer Java environments and OpenJDK 8 is still expected to be LTS (you'll just need to switch from Java 8 SE to OpenJDK 1.8.x, I'm quite sure both Oracle and the community will apply and provide security patches there).

**Comment by codemanyak** [comment]
Just tried to run a Structorizer bugfix version (anticipating 3.28-10) on OpenJDK11. No severe problems so far, but a long series of messages written to the console on start:
```
Could not instrument class sun/security/mscapi/SunMSCAPI: null.
Could not instrument class sun/security/mscapi/SunMSCAPI$1: null.
Could not instrument class sun/security/mscapi/SunMSCAPI$2: null.
Could not instrument class sun/security/mscapi/SunMSCAPI$ProviderService: null.
Could not instrument class org/jcp/xml/dsig/internal/dom/XMLDSigRI: null.
Could not instrument class org/jcp/xml/dsig/internal/dom/XMLDSigRI$1: null.
Could not instrument class org/jcp/xml/dsig/internal/dom/XMLDSigRI$2: null.
Could not instrument class org/jcp/xml/dsig/internal/dom/XMLDSigRI$ProviderService: null.
Could not instrument class sun/security/pkcs11/SunPKCS11: null.
Could not instrument class sun/security/pkcs11/SunPKCS11$Descriptor: null.
Could not instrument class sun/security/ec/SunEC: null.
Could not instrument class sun/security/ec/SunEC$ProviderService: null.
Could not instrument class sun/security/ec/SunEC$1: null.
Could not instrument class sun/security/ec/SunEC$2: null.
Could not instrument class sun/security/ec/ECDSASignature$SHA1: null.
Could not instrument class sun/security/ec/ECDSASignature: null.
Could not instrument class sun/security/ec/ECDSASignature$Raw: null.
Could not instrument class sun/security/ec/ECDSASignature$RawECDSA: null.
Could not instrument class sun/security/jgss/SunProvider: null.
Could not instrument class sun/security/jgss/SunProvider$1: null.
Could not instrument class sun/security/jgss/SunProvider$ProviderService: null.
Could not instrument class com/sun/security/sasl/gsskerb/JdkSASL: null.
Could not instrument class com/sun/security/sasl/gsskerb/JdkSASL$1: null.
Could not instrument class com/sun/security/sasl/gsskerb/JdkSASL$ProviderService: null.
Could not instrument class sun/security/smartcardio/SunPCSC: null.
Could not instrument class sun/security/smartcardio/SunPCSC$1: null.
Could not instrument class sun/security/smartcardio/SunPCSC$ProviderService: null.
Could not instrument class sun/security/ec/ECDSASignature$SHA256: null.
Could not instrument class sun/security/ec/ECDSASignature$SHA384: null.
Could not instrument class sun/security/ec/ECDSASignature$SHA512: null.
Could not instrument class sun/security/ec/ECDSASignature$SHA224: null.
```

**Comment by codemanyak** [comment]
From Oracle Java 9 on, class `JApplet` (and the entire `java.applet` API) becomes deprecated (see [online documentation](https://docs.oracle.com/javase/9/docs/api/java/applet/package-summary.html)) and will be removed sooner or later. This means, the class `StructorizerApplet` is doomed. Oracle recommends replacement with Java WebStart or installable application (so Structorizer.Desktop will fit in anyway).

**Comment by codemanyak** [comment]
To answer the original question: No, I don't think we will issue "standalone" versions containing their own Java VM, as this tends to be operating-system-specific. By now we haven't seen noticeable problems with the underlying Java infrastructure on the user site.
So I dare to close this issue now.

**Comment by fesch** [comment]
I just want to confirm, that this will be very OS specific. While Windows is no big problem, OSX will have problems depending on the initial setup of the machine. For Linux, I have no idea, but probably there will be no need to some packaged JVM anyway.

So mainly I agree with @codemanyak
