### ISSUE TITLE
Shell script incorrect output redirection

### ISSUE THREAD

**Issue by KimBrodowski** [fesch/Structorizer.Desktop#583]
The current *nix start and build script will create a file called "2" and refuse to start if the user doesn't have write permission in the current working directory. See #582

**Comment by KimBrodowski** [comment]
I guess my PR was merged faster than I could create this ticket?! Closing ;)

**Comment by GitMensch** [comment]
@KimBrodowski Thank you for fixing my mistake.
Isn't it the same for any ".sh" in the repo that I've touched (I guess I copy+pasted this part)? In this case your PR may should apply the same change to the other scripts.

**Comment by KimBrodowski** [comment]
I've encountered these bugs when dealing with the binaries available at https://structorizer.fisch.lu/. I haven't (yet) build this project from source. I just fixed what I saw was broken without further looks around.

From a quick glance at the build scripts I can at least spot one more occasion. I'll file another PR as soon as I find the time to actually go through the whole build process and check what it did.

A bit off-topic: Have you considered submitting this to Debian for packaging? The debs available seem awfully outdated. I believe this would make a good addition to Debian's software portfolio. Especially in Germany Nassi-Shneiderman diagrams are used in education and I'd not take it for granted that every junior dev knows how to build from source and install the binaries properly. Helps with software distribution in schools too. I can offer my help. I package software for my employer - not quite to Debian standards though. Would be a first for me as well.

**Comment by codemanyak** [comment]
@KimBrodowski 
I think, your help in packaging Structorizer for Debian would be highly welcome.

**Comment by KimBrodowski** [comment]
Unfortunately I'm currently unable to build from source due to Apple specific functionality being used in the project. However as far as I can tell the one occurrence mentioned above is the only one remaining.

https://github.com/fesch/Structorizer.Desktop/pull/584

**Comment by fesch** [comment]
I just noticed that the file structorizer.clean in the default package, which was meant to be an apple-free file, does this job no longer. I will need to rebuild it ...

**Comment by fesch** [comment]
I've uploaded a new Structorizer.clean file, so you may use this or put a /* in line 321 of Structorizer.java

**Comment by codemanyak** [comment]
@fesch 
Sorry, I wasn't aware of the purpose of Structorizer.clean and the relation between Structorizer.java and Structorizer.clean, in particular. In future I will have this in mind on doing modifications to Structorizer.java.

**Comment by fesch** [comment]
The script produces a file named "2" in the structorizer directory which should be avoided as an uninstall from the debian package will fail to remove the directory. Can anyone help?

**Comment by fesch** [comment]
The debian package installes, but there is a problem with the line "# check for jar in PATH" because with my modification it can't  find the JAR file anymore and I can't get how this line of code works :(

**Comment by KimBrodowski** [comment]
Debian or Ubuntu? It calls `jar` and checks the return code `rc`. It must be 1 or 0. Usually it's 1 because of the invalid usage. Unknown commands would yield a return code of 127. 0 would indicate no error.

**Comment by fesch** [comment]
Okay, so I could easily replace it with something like this:
`find Structorizer.app/ | grep Structorizer.jar | wc -l`

**Comment by GitMensch** [comment]
> Okay, so I could easily replace it with something like this...

No, this is about the `jar` binary, not the Structorizer.jar. The script cannot work if the `jar` binary is missing.
If this is about structorizer.sh - this shouldn't test for `jar` at all but for `java` (as the java version check will fail with a possibly strange error message otherwise).

**Comment by GitMensch** [comment]
I'll leave a PR to fix structorizer.sh

**Comment by fesch** [comment]
ok, this makes sense now ;)

**Comment by GitMensch** [comment]
See https://github.com/fesch/Structorizer.Desktop/pull/586
