### ISSUE TITLE
Should not close when canceling save dialog

### ISSUE THREAD

**Issue by rugk** [fesch/Structorizer.Desktop#6]
**STR:**
1. Create a new file and do not save it.
2. Close GUI.
3. A question whether you want to save appears. Click "Yes".
4. Click "Cancel"

**What happens:** Program exists without saving.

**What should happen:** Cancel saving *and closing* of the file.
That's how most major programs do it. The user could lose files when such unexpected things happen.

**Comment by codemanyak** [comment]
Just to explain here what induced the fix revision listed among the post-close references: The first fix approach had generally set the defaultCloseOperation to DO_NOTHING_ON_CLOSE and then forced a process exit on answering the question dialog (i.e. if not being cancelled). Unfortunately the Structorizer may also run as a dependent thread of e.g. an Arranger instance, which will then immediately but unintentionally be killed, too. So this fatal behaviour had to be avoided as soon as possible.

**Comment by fesch** [comment]
Yes, I've got the problem ;-) It was the same for Unimozer, who is also launching Structorizer ...
