### ISSUE TITLE
Import to eclipse as project with existing build file failed, build.xml didn't include javac

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#60]
Specified buildfile (build.xml) does not contain a javac task

**Comment by codemanyak** [comment]
I have been developing Structorizer with Eclipse for years now - with unchanged build.xml. Something had to be setup in the beginning (particulerly w.r.t. to the attached libraries), but it's to long back now to know exactly what it was.
What are the error messages you obtain and in what phases or on what activities exactly?

**Comment by elemhsb** [comment]
Debian 8.2 with eclipse 3.8 and openjdk 1.7.xx.
Menu project new Java with existing build.xml file.
Got the error above. ... Not contain javac task.

**Comment by codemanyak** [comment]
Ah, I see. (And remember vaguely...)
You may try to do the following (if configuring the build.xml is no option): Create a new Java project (empty, with separate folders), then import the Structorizer.Desktop from directory into the project.
It will then show you a lot of errors, that are easily fixable bei registering the apparently missing libraries (mostly as Jar) from the lib directory e.g. via project properties > java Build Path > Libraries:
for com.apple you need AppleJavaExtensions.jar, located in lib
for org.jdesktop you need lib/swing-layout/swing-layout-1.0.3.jar
for bsh you need lib/bsh-2.0b4.jar
for org.freehep you need lib/freehep.jar
for org.freehep.graphicsio.svg you need lib/freehep-graphicsio-svg-2.1.1.jar, lib/freehep-graphicsio-2.1.1.jar, lib/freehep-graphics2d-2.1.1.jar etc.
...

**Comment by elemhsb** [comment]
Thanks for eclipse hints, i will try it. Could you generate a build file or export build configuration ?
@codemanyak Yesterday i build codemanyak/master 3.23-05dev from github and run it in lab with 30 students without problems.

The only problem was to build this version (21f96dcc36cf4) with jdk-1.8.0-66 i got a strange error:
$ ant **clean**
$ ant compile
````  
[javac] /tmp/xx/codemanyak-structorizer/src/lu/fisch/structorizer/arranger/Surface.java:161: error: unreported exception SAXException; must be caught or declared to be thrown
    [javac]     					Root root = parser.parse(f.toURI().toString());
    [javac]     					                        ^
```
A little bit the same thing, like the **Integer.** probs for a few days with older 1.7.x JDK.
I get this version work with checkout and older version, compile this, checkout 21f96dc again,
don't clean and compile the remaining (newer) source codes and got Structorizer.jar file. :-)

I am not a java expert, how can it be ? The failing file is the same ...
Today the actual version a4f5591509 compiles out of the box !
 
@fesch When the new version will be packaged ?

**Comment by fesch** [comment]
Depends on when @codemanyak will merge his branche ;-)

**Comment by codemanyak** [comment]
.. and this in turn depends on the load of new enhancement requests and bugs reported.
My plan is 2015-12-20 or rather 2015-12-21.

**Comment by codemanyak** [comment]
@fesch: Shall we replace the build.xml by another one exported from Eclipse or would this meddle with Netbeans or other IDEs?

**Comment by fesch** [comment]
I think NetBeans will re-create a new build.file anyway, so just go for it.
I will add it on my side to the ignore file to not overwrite it again.
Does that sound fair?

**Comment by elemhsb** [comment]
Whatever works ... this terrible, today codemanyak/master b4d52a25 didn't compile with other NEW issues ?????
I tried netbeans 8.1 jdk 1.8.0_65 too, the same ...
```
-do-compile:
    [javac] Compiling 37 source files to /home/work/github/codemanyak-structorizer/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/work/github/codemanyak-structorizer/src/lu/fisch/structorizer/generators/_old/CGenerator.java:68: error: CGenerator is not abstract and does not override abstract method supportsSimpleBreak() in Generator
    [javac] public class CGenerator extends Generator 
    [javac]        ^
    [javac] /home/work/github/codemanyak-structorizer/src/lu/fisch/structorizer/generators/_old/CSharpGenerator.java:52: error: CSharpGenerator is not abstract and does not override abstract method supportsSimpleBreak() in Generator
    [javac] public class CSharpGenerator extends Generator 
    [javac]        ^
    [javac] /home/work/github/codemanyak-structorizer/src/lu/fisch/structorizer/generators/_old/JavaGenerator.java:61: error: JavaGenerator is not abstract and does not override abstract method supportsSimpleBreak() in Generator
    [javac] public class JavaGenerator extends Generator 
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 1 warning

BUILD FAILED
/home/work/github/codemanyak-structorizer/nbproject/build-impl.xml:908: The following error occurred while executing this line:
/home/work/github/codemanyak-structorizer/nbproject/build-impl.xml:257: Compile failed; see the compiler error output for details.
```

**Comment by codemanyak** [comment]
It seems I have forgotten to upload the three "old" generator files because the method **supportsSimpleBreak()** reported to be missing is definitely present in all relevant generator classes as you may see in the diff log of the most recent commit. I have no idea why the legacy generator classes in the subdirectory generators/old are still active in the configuration. As far as I know they aren't needed anymore.
But I will commit them now.

**Comment by codemanyak** [comment]
@elemhsb: Please leave an acknowledging comment here if the build.xml file now satisfies the request, i.e. may the issue be closed?

**Comment by elemhsb** [comment]
At the moment 3.23-06 it build with ant on cli and could imported into eclipse. So the request could be closed.

**Comment by codemanyak** [comment]
Will have a look at it.

**Comment by elemhsb** [comment]
new build-eclips.xml does the job now fine.
issue could be closed.
