### ISSUE TITLE
Enhancement proposal: allow to import specific ranges of a given source file

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#607]
This is kind of a follow-up to #474 and is intended for batch import mode.
The reason for this is that possibly some files cannot be parsed (because they don't match the target language) and/or only specific parts of the code are interesting. Samples:

* a program which includes a complete command line parsing but only the actual functions that are called are interesting
* a program that mixes GUI-components with "logic" (and obviously only the "logic" should be imported)

Maybe we could load the program into a multiline and ask the user for the markers but the actual handling I've had in mind would be to use a good editor and use an external call to do the batch import (for example with NPP mentioned in #474 you can select a code part, then start an external tool and pass the marked block).

Something like

```sh
$ Structorizer.sh -p COBOL -e ISO-88591 -o out -r123-456 Worldcities0.cob
# or, if multiple sources may be specified:
$ Structorizer.sh -p COBOL -e ISO-88591 -o out Worldcities0.cob:13-36 Worldcities1.cob:23-45
```

In general this can only work if the actual parser used supports parsing of incomplete source snippets, but if a parser doesn't handle this it would be good to make it work that way in any case...

**Comment by codemanyak** [comment]
@GitMensch 
You wrote:
> the actual handling I've had in mind would be to use a good editor and use an external call to do the batch import (for example with NPP mentioned in #474 you can select a code part, then start an external tool and pass the marked block).

Hm. If you managed to find out (and select) the interesting line range in some editor then you could simply save this snippet as a new file and have Structorizer convert that, couldn't you?
I still don't see the big benefit in the proposal. In the event, we would just insert an additional preprocessor that extracts the specified lines...

**Comment by codemanyak** [comment]
> (and if any parser cannot handle code-snippets a called script could also insert the necessary parts)...

Yes, and actually I'm lacking the necessary fantasy to imagine a way a _parser_ could guess what parts around a given code snippet might be missing or have to be added. It would have to be a preprocessor again, anyway. Only with the D7Parser there was an obvious and simple workaround if the .pas file contained just one or more function and procedure definitions (without an embedding program or unit definition): to put a dummy unit definition around. Okay, you may have a pretty good idea what context to place around a COBOL snippet, but usually some external definitions will be missing (types, constants etc.). If some structure is incomplete (e.g. a missing block end) then perhaps it might be closed, but this might even confuse and hide the actual issue with the snippet ... Usually the designer of a script will have a more natural guess what kind of parts may have to be inserted.

**Comment by codemanyak** [comment]
Just an additional remark: The interesting code parts of a file might not form a contiguous line sequence, so if the proposal is to be followed then it might even be necessary to allow specifying several intervals for a single file with some fancy syntax.
Of course, you might repeat the file name with several intervals like:
```sh
$ Structorizer.sh -p COBOL -e ISO-88591 -o out sample0815.cob:13-36 sample0815.cob:123-145
```
But I still think it makes more sense to copy the snippets together to a new file, equip it with the appropriate context and import that.

**Comment by GitMensch** [comment]
@codemanyak I agree. Can you please close this and #474 and adding a "rejected" label?
