### ISSUE TITLE
Problems with multiline comment blocks in preprocessor lines on C import (derived from #557)

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#608]
On importing C code, the rare case of preprocessor directives with comment blocks continued in subsequent lines (see example in following code snippet, cf. https://github.com/fesch/Structorizer.Desktop/issues/557#issuecomment-405115160) fooled the file preparation phase:
```c
#ifndef DOOF_H /* Funny remark here
to be continued in subsequent line */
#define DOOF_H /* Also broken
comment block*/
```

**Comment by GitMensch** [comment]
What does "fooled the file preparation phase" actually mean? Does it break / not handle the preprocessor commands any more / mix up line numbers in possible error messages?

**Comment by codemanyak** [comment]
Oh it handles the preprocessor directives more or less but the prepared source file for the parser gets corrupted, e.g.:
```c
// preparser instruction (not parsed!): #ifndef DOOF_H /* Funny remark here
to be continued in subsequent line */
// preparser define: #define DOOF_H /* Also broken
comment block*/
```
As already outlined in https://github.com/fesch/Structorizer.Desktop/issues/557#issuecomment-405115160, the inserted line comment breaks the original block comment, which causes a parser error on the following line.
I prepared a heuristic (i.e. not exact patch) checking whether the line to be reinserted ends with an open comment block and uses a block comment prefix in these cases:
```c
/* preparser instruction (not parsed!): #ifndef DOOF_H /* Funny remark here
to be continued in subsequent line */
/* preparser define: #define DOOF_H /* Also broken
comment block*/
```
This may avoid many such cases but won't cope with a case like this (occurring in line 2247*ff* of file common.c):
```c
#if 0 /* cob_module->param_buf and cob_module->param_field are rw-branch only features
         for now - TODO: activate on merge of r1547 */
		&& !cobglobptr->cob_call_from_c
		if ((*module)->param_buf != NULL)
			cob_cache_free ((*module)->param_buf);
		if ((*module)->param_field != NULL)
			cob_cache_free ((*module)->param_field);
#endif
```
I don't find a simple way to "disarm" the line with the && operator because it is an unexpected code line disabled by the `#if 0` directive, which is not evaluated during file preparation - you may remember that we don't try to evaluate `#if`, `#ifdef`, `#ifndef` etc. directives (your own code btw.).

**Comment by codemanyak** [comment]
These are suitable test files for issue #608 and the command line screen shot:
[batch_import_608.zip](https://github.com/fesch/Structorizer.Desktop/files/2416911/batch_import_608.zip)

![grafik](https://user-images.githubusercontent.com/15326471/46040430-90eeb280-c110-11e8-945d-c15de15a6f7a.png)
