### ISSUE TITLE
Proposal: Additional key bindings Ctrl-Insert, Shift-Del, Shift-Insert for copy, cut, and paste

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#616]
The copy, cut, and paste actions in the diagram are associated with the usual key bindings Ctrl-C, Ctrl-X, and Ctrl-V, respectively. I propose to spend them an additional set of key bindings that is very popular, too:
Ctrl-Ins, Shift-Del, and Shift-Ins.
Any objections?

**Comment by GitMensch** [comment]
> Any objections?

Not from me ;-)

**Comment by codemanyak** [comment]
Solution committed to bugfix branch.
