### ISSUE TITLE
 Error in the comparison with element of a string 

### ISSUE THREAD

**Issue by ramblas98** [fesch/Structorizer.Desktop#621]
I tried to execute the following algorithm and it gave me an error. Can you help me please?

![captura de pantalla](https://user-images.githubusercontent.com/911171/46770523-27e96c00-ccc6-11e8-8de8-51fb3363b349.png)

**Comment by fesch** [comment]
The Executor is Java based and the class String in Java does not have a method get().

https://docs.oracle.com/javase/7/docs/api/java/lang/String.html

**Comment by GitMensch** [comment]
> The Executor is Java based

@ramblas98 Your algorithm uses C based (zero-terminated) strings and therefore is fine in itself but cannot be executed. The only real option you have to *execute* it, is to change it to Java syntax `cad.length()`.

**Comment by codemanyak** [comment]
Moreover, the index syntax for character access in a string isn't supported in Structorizer. You might make use of the Pascal function `copy(s, i, n)` (i counting from 1) or of the Java method invocation `cad.charAt(i)` (counting from 0). But you won't find a '\0' character at the end.
By the way there are severeal ways to travers the characters of a string in Structorizer:
![grafik](https://user-images.githubusercontent.com/15326471/46793518-324b4a80-cd46-11e8-8e2e-224d7d75b8e3.png)

**Comment by codemanyak** [comment]
@ramblas98 
May we close this issue or do you suggest to have Structorizer support the index syntax for character access in strings? This wouldn't be impossible but is likely to cause way more time-consuming efforts to tell strings form (other kinds of) arrays not only in Executor, but - more difficult - in code generators.
To provide full support for NUL-terminated C strings in Structorizer won't be feasible within acceptable effort limits.

**Comment by codemanyak** [comment]
I added a subsection about Strings to the user guide explaining the implications of the Java nature and I propose to close this issue by end of this week unless @ramblas98 contradicts.

**Comment by ramblas98** [comment]
Thank you very much for responding and for adding the use of string in the guide. Finally, I would like to suggest that Structorizer supports the index syntax for character access in strings.

**Comment by codemanyak** [comment]
@ramblas98 
> I would like to suggest that Structorizer supports the index syntax for character access in strings.

I was afraid so... Thanks for rsponse anyway. I don't promise to implement your sugestion because it will be really difficult, is likely significantly to reduce performance, and may cause many ambiguities on execution and export. What I do promise is that I will ponder the implications and look for some feasible approaches.
Only some of the problems we would have to face:

![grafik](https://user-images.githubusercontent.com/15326471/47227350-e7bf7300-d3c2-11e8-9feb-e55723838cf1.png)

**Comment by GitMensch** [comment]
So wontfix again?
