### ISSUE TITLE
How does split work?

### ISSUE THREAD

**Issue by natrius** [fesch/Structorizer.Desktop#628]
I can not find something (riot.im or irc or other chat) where i can just ask questions about some functions or something like that. 

I don't undestand function
split(s: string; sep: string): array of string
If i have an string "test", that is numbers splith a "-". So, split(test;"-") should work, but i get just errors.

Is there another way to split an string into seperate parts after every character and save it into an array. How would i do that?
Or, an easier way: is it possible to adress a part of a string individually with test[3] would show me "t" as result?

**Comment by codemanyak** [comment]
Function split splits a string around some matching substring, e.g. split("2018-10-24", "-") woukd result in an array {"2018", "10, "24"}.
In order to decompose a string into an array of characters you might use a foreach loop:
![grafik](https://user-images.githubusercontent.com/15326471/47427675-57ea4200-d791-11e8-9ebd-4383b12e8739.png)


You may also have a look to the discussion of issue #621. There you'll find all supported access mechanisms to the characters of a string.

**Comment by codemanyak** [comment]
@natrius 
I forgot to mention that you can also (nearly) split a given string into an array of single-character strings by using an empty string as separator pattern:
![grafik](https://user-images.githubusercontent.com/15326471/47428147-ac41f180-d792-11e8-85cc-6b5d91bea9c1.png)
You will simply have to be aware that in this case there will be an additional empty string at the end of the array.

**Comment by natrius** [comment]
Ah, i did not think about the foreachloop, thanks!

I tried that actually, and i see where the problem was: In the coumentation there is a semikolon where i have to use a comma instead to split the string and the separator. Please change the documentation too :)

**Comment by codemanyak** [comment]
@natrius 
> In the coumentation there is a semikolon where i have to use a comma instead to split the string and the separator. Please change the documentation too :)

Umh no. The user guide is correc inasmuch as it documents the function signatures in Pascal syntax where types are to be specified. (Apart from C and BASIC syntax, Structorizer accepts Pascal syntax on creating subroutine diagrams). In a Pascal subroutine declaration the parameter groups are separated by semicolons (where a parameter group is a comma-separated list of one or more identifiers sharing a type, which is to be associated after a colon). If you don't specify types or on doing so in BASIC or C syntax, only commas are allowed, in contrast.
On calling a subroutine, however, the argument expressions are aöways to be separated by comma, no matter in what language flavour.
This may of course be confusing but it is correct.
