### ISSUE TITLE
COBOL import: preparser misses support for REPLACE, at least warn

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#630]
As we defined "somewhere" that all COPY/REPLACE preparsing should be done in the source-to-import it is perfectly fine that sources containing these cannot be parsed yet.

The actual current result is still bad as the parsing fails hard (it shouldn't start at all).
Two samples (actual from one file, I've just deleted the offending line in the first place)

~~~
error.syntax in file "C:\dev\test1.cbl"

Preceding source context:
   37:   *>-----------------------------------------------------------------
   38:   REPLACE STUFF » BY OTHERSTUFF.

Found token BY

Expected: ACCESS | AcuBinNumLiteral | AcuHexNumLiteral | AcuOctNumLiteral | ALPHABET | ALTERNATE | ASCII | ASSIGN
        | BINARY | BLOCK | BooleanHexLiteral | BooleanLiteral | CLASS | COBOLWord | CODE_SET | COLLATING
        | COMMA_DELIM | CRT | CURRENCY | CURSOR | DATA | DecimalLiteral | DECIMAL_POINT | EBCDIC | EIGHTY_EIGHT
        | EVENT_STATUS | EXTERNAL | FloatLiteral | FOR | GLOBAL | HexLiteral | HIGH_VALUE | INDEXED | INPUT
        | IntLiteral | IS | I_O | LABEL | LINAGE | LINE | LOCALE | LOCK | LOW_VALUE | NationalHexLiteral
        | NationalLiteral | NATIVE | NUMERIC | OFF | ON | ORGANIZATION | OUTPUT | PADDING | QUOTE | RECORD
        | RECORDING | RELATIVE | REPORT | REPORTS | RESERVE | SCREEN_CONTROL | SEQUENCE | SEQUENTIAL
        | SEVENTY_EIGHT | SHARING | SIXTY_SIX | SORT | SPACE | 'STANDARD_1' | 'STANDARD_2' | STATUS | StringLiteral
        | SYMBOLIC | TOK_DOT | TOK_FILE | TOK_INITIAL | TOK_NULL | VALUE | ZERO | ZLiteral




error.syntax in file "C:\dev\test1.cbl"

Preceding source context:
  446:   *>-----------------------------------------------------------------
  447:   01 STUFF PIC X(10) VALUE '12.3'.
  448:   78 MORE-STUFF VALUE 'Test some STUFF here'.
  449:   » REPLACE OFF.

Found token COBOLWord (REPLACE)

Expected: (EOF) | ACCEPT | ADD | ALLOCATE | ALTER | CALL | CANCEL | CD | CLOSE | COMMIT | COMMUNICATION | COMPUTE
        | CONTINUE | DELETE | DISABLE | DISPLAY | DIVIDE | EIGHTY_EIGHT | ENABLE | END_FUNCTION | END_PROGRAM
        | ENTRY | EVALUATE | EXIT | FD | FREE | FUNCTION_ID | GENERATE | GO | GOBACK | ID | IDENTIFICATION
        | IF | INITIALIZE | INITIATE | INSPECT | IntLiteral | LINKAGE | LOCAL_STORAGE | MERGE | MOVE
        | MULTIPLY | NEXT | OPEN | PERFORM | PROCEDURE | PROGRAM_ID | PURGE | READ | READY_TRACE | RECEIVE
        | RELEASE | REPORT | RESET_TRACE | RETURN | REWRITE | ROLLBACK | SCREEN | SD | SEARCH | SEND
        | SET | SEVENTY_EIGHT | SIXTY_SIX | SORT | START | STOP | STRING | SUBTRACT | SUPPRESS | TERMINATE
        | TRANSFORM | UNLOCK | UNSTRING | WORKING_STORAGE | WRITE
~~~

In the "long term" it would be nice if `REPLACE` would be handled by the internal preparser, in short-term it would be nice to check for COPY/REPLACE statements in the preparser and raise a "Please preprocess the file with a COBOL preparser or manually adjust before restarting the import." message before starting the parsing which currently will always fail in these cases.

**Comment by codemanyak** [comment]
I wonder, do you propose to fix it yourself or would you like someone like me to do that?

**Comment by GitMensch** [comment]
> I wonder, do you propose to fix it yourself or would you like someone like me to do that?

I didn't plan to do something on this part for now, just created the issue that we not forget about it (if you find time - please check).

**Comment by codemanyak** [comment]
Workaround (abort an warning on detected REPLACE and COPY directives out of the preparation phase) committed to bugfix branch

**Comment by GitMensch** [comment]
The code looks good. As this issue will be closed we may should create a new one with the missing preparser steps for COBOL import (to collect whatever we find missing).

Note: You likely could get the `FIXME` entry that is directly before your changes for REPLACE and COPY working: logging / specifying where in the code the error occurs (I'd suggest to output the complete offending line in cases like this).

**Comment by codemanyak** [comment]
> [...] logging / specifying where in the code the error occurs (I'd suggest to output the complete offending line in cases like this).

Sure. I had pondered it but realized that I should introduce a line counting in the preparation phase for it (which wouldn't be a big deal, of course) and I simply wasn't quite sure whether the line counts would be correct in this phase. But well, why shouldn't they. So of course I can collect the offending lines themselves instead of just counting them.

**Comment by codemanyak** [comment]
Done.
