### ISSUE TITLE
COBOL-import: preparser should remove separator commas/semicolons; import of INSPECT statements

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#631]
For historical reasons COBOL allows to separate words not only by space, but also by comma or semicolon.
The current used grammar cannot handle this and it is likely a food idea to replace these parts in the internal preparser already. Failing sample (showing the current pre-processed source):

```cobol
*>
NORMALIZE-MESSAGE SECTION.
*>00.
*>
    INSPECT SomeMessage
      REPLACING ALL x'0a' BY SPACE,
                ALL x'0d' BY SPACE,
                ALL x'09' BY SPACE
*>
    EXIT SECTION.
```

result:

~~~
error.syntax in file "C:\dev\test2.cbl"

Preceding source context:
 7681:   *>
 7682:   NORMALIZE-MESSAGE SECTION.
 7683:   *>00.
 7684:   *>
 7685:       INSPECT SomeMessage
 7686:         REPLACING ALL x'0a' BY SPACE» ,

Found token COMMA_DELIM (,)

Expected: ACCEPT | AcuBinNumLiteral | AcuHexNumLiteral | AcuOctNumLiteral | ADD | AFTER | ALL | ALLOCATE | ALTER
        | BEFORE | BooleanHexLiteral | BooleanLiteral | CALL | CANCEL | CHARACTERS | CLOSE | COBOLWord
        | COMMIT | COMPUTE | CONTINUE | DecimalLiteral | DELETE | DISABLE | DISPLAY | DIVIDE | EIGHTY_EIGHT
        | ELSE | ENABLE | END | END_ACCEPT | END_ADD | END_CALL | END_COMPUTE | END_DELETE | END_DISPLAY
        | END_DIVIDE | END_EVALUATE | END_IF | END_MULTIPLY | END_PERFORM | END_READ | END_RECEIVE | END_RETURN
        | END_REWRITE | END_SEARCH | END_START | END_STRING | END_SUBTRACT | END_UNSTRING | END_WRITE
        | ENTRY | EOP | ESCAPE | EVALUATE | EXCEPTION | EXIT | FIRST | FloatLiteral | FREE | FUNCTION
        | GENERATE | GO | GOBACK | HexLiteral | HIGH_VALUE | IF | INITIALIZE | INITIATE | INSPECT | IntLiteral
        | INVALID_KEY | LEADING | LOW_VALUE | MERGE | MOVE | MULTIPLY | NationalHexLiteral | NationalLiteral
        | NEXT | NOT_END | NOT_EOP | NOT_ESCAPE | NOT_EXCEPTION | NOT_INVALID_KEY | NOT_OVERFLOW | NOT_SIZE_ERROR
        | NO_DATA | OPEN | PERFORM | PURGE | QUOTE | READ | READY_TRACE | RECEIVE | RELEASE | RESET_TRACE
        | RETURN | RETURNING | REWRITE | ROLLBACK | SEARCH | SEND | SET | SEVENTY_EIGHT | SIXTY_SIX | SIZE_ERROR
        | SORT | SPACE | START | STOP | STRING | StringLiteral | SUBTRACT | SUPPRESS | TERMINATE | TOK_DOT
        | TOK_NULL | TOK_OVERFLOW | TRAILING | TRANSFORM | UNLOCK | UNSTRING | WHEN | WITH_DATA | WRITE
        | ZERO | ZLiteral
~~~

Note - You *could* actually write the perfect valid COBOL source

```cobol
*>
NORMALIZE-MESSAGE SECTION.
*>00.
*>
    INSPECT;;;;;;SomeMessage
      REPLACING;ALL,x'0a' BY SPACE,
         ,,, ;  ALL;x'0d',BY SPACE;;;
                ALL x'09' BY SPACE
*>
    EXIT SECTION.
```

obviously the used code-highlighter here has issues with this, too :-)

**Comment by GitMensch** [comment]
Note: COBOLParser.java `prepareTextfile()` says

> TODO for preparsing:
> remove ';' and ',' that are not part of a string/integer - cater also for ";;,,;"

...

**Comment by codemanyak** [comment]
So any commas and semicolons outside string and integer (???) literals are redundant?

**Comment by GitMensch** [comment]
> So any commas and semicolons outside string and integer (???) literals are redundant?

Not redundant. They serve as delimiter ("[,;]+" -> " ").
This also applies to integer literals if `decimal-point is comma` is not specified in `special-names`, if this isn't specified in the code `11,1` would actually be identical to `11 1`... but luckily I haven't seen any source yet where this would be an issue, therefore I suggest to just leave *this* part aside.

They are not redundant in the following cases: separator for function parameters and as [nested] indexes:
`MOVE FUNCTION TRIM ( myvar (1,2), LEADING) TO var`.

I actually consider this a bug that likely would break to code import often :-(

**Comment by codemanyak** [comment]
> They are not redundant in the following cases: separator for function parameters and as [nested] indexes:
`MOVE FUNCTION TRIM ( myvar (1,2), LEADING) TO var`.

Great. This was what I had in mind. It means there is no easy way to fix this in the file preparation phase. To tell cases where the commas (and possibly semicolons) are essential from those where they may be regarded as or replaced with white space won't be trivial at all but highly context-dependent (far beyond the level of complexity a regular expression could cope with).

**Comment by GitMensch** [comment]
> Great. This was what I had in mind. It means there is no easy way to fix this in the file preparation phase.

Likely not at a single point...
Just because it cannot harm to have some structured information (that's the reason for this program :-) you may want to get the current COBOL draft standard from [iso.org](https://isotc.iso.org/livelink/livelink?func=ll&objId=19468956).

> To tell cases where the commas (and possibly semicolons) are essential from those where they may be regarded as or replaced with white space won't be trivial at all but highly context-dependent (i.e. far beyond the level of complexity a regular expression could cope with).

Actually there are some things that can be done; the main issue is to possibly converting fixed to free form [seems to be working fine, #626 aside] and then change only parts that are not part of a literal (as contents of literals are no separators).

I think a regular expression is just the wrong tool to use here.
We already have a state machine with `COBOLParser.RepositoryAutomaton.process()`.
It seems reasonable to check for left/right parenthesis there, too (just increasing/decreasing a counter) and if the counter is zero replace `,` by ` ` and in any case replace `;` by ` `. If we also increase/decrease a counter for (unescapted) `"` the "FIXME We must find a way to skip string literals" seems to be handled, too.

Would adjusting `COBOLParser.RepositoryAutomaton.process()` to use `StringList.explodeWithDelimiter(StringList, String)` instead of `StringList.explodeWithDelimiter(String, String)` do the trick for all these parts?

Can you investigate this?

________________
Quoting some rules from the linked draft standard as background...

From "Punctuation":

> The separators comma and semicolon may be used anywhere the separator space is used in general formats and other syntactic specifications. In the compilation group, these separators are interchangeable.

From "Separators":

> A separator is one of the following, except when appearing in a literal:
> 1) The COBOL character space is a separator. Anywhere a space is used as a separator or as part of a separator, more than one space may be used. All spaces immediately following the separators comma, semicolon, or period are considered part of that separator and are not considered to be the separator space.
> 2) The COBOL characters comma and semicolon, immediately followed by a space, are separators that may be used anywhere the separator space is used. They can be used to improve readability.
> 3) The COBOL character period, when followed by a space, is a separator. The separator period shall be used only to indicate the end of a sentence, or as shown in formats.

note to 2) obviously the "bad sample" above isn't "improved", but the original sample can be seen as improved by that single comma.

From "COPY statement" (applies to normal text, too):

> Each occurrence of a separator comma, semicolon, or space in pseudo-text-1 or in the library text is considered to be a single space. Each sequence of one or more space separators is considered to be a single space.

**Comment by GitMensch** [comment]
> I have some difficulties to understand the rules above.
According to Separators 2, a comma or semicolon followed by a space is to be regarded as a space. So what if no space follows but e.g some identifier or digit? The Punctuation rule, instead, does not mention a following space. So what is that distinction in Separators 2 good for?

* the punctuation rule defines that *separators* comma and semicolon are interchangeable with the separator space
* separators rule 2 says that the *characters* comma and semicolon, immediately followed by a space, are *separators*

> Then Separators 1 says: [...]

... it says that multiple separators places together are considered a single separator.

> Who needs this kind of explanation?

standard bodies :-) ... if you look further you find that separators have 6 more rules left ...
Actually this *is* important for tokenizing (most tokenizers handle this correctly) and to be able to check if an implementation provides "conformance" to the standard if edge cases arize.

**Comment by codemanyak** [comment]
The commas may even fool the diagram generation like in the following example:
```cobol

*>  start value
    MOVE 1 TO REG0

    PERFORM FOREVER
       EVALUATE TRUE
*>        state 01
          WHEN (REG3 > ZEROES) AND (REG5 > ZEROES)
             ADD      1 TO   REG6             END-ADD
             SUBTRACT 1 FROM REG3, REG5       END-SUBTRACT

*>        state 02
          WHEN (REG2 > ZEROES) AND (REG6 > ZEROES)
             ADD      1 TO   REG0, REG1, REG5 END-ADD
             SUBTRACT 1 FROM REG2, REG6       END-SUBTRACT

*>        state 03
          WHEN (REG1 > ZEROES) AND (REG6 > ZEROES)
             ADD      1 TO   REG7             END-ADD
             SUBTRACT 1 FROM REG1, REG6       END-SUBTRACT 

*>        state 04
          WHEN (REG0 > ZEROES) AND (REG7 > ZEROES)
             ADD      1 TO   REG8             END-ADD
             SUBTRACT 1 FROM REG0, REG7       END-SUBTRACT

*>        state 05
          WHEN (REG1 > ZEROES) AND (REG4 > ZEROES)
             ADD      1 TO   REG9             END-ADD
             SUBTRACT 1 FROM REG1, REG4       END-SUBTRACT
```
The operands of the ADD and SUBTRACT instructions are redundantly separated with comma, which leads to nonsense lines (which don't occur if the commas are eliminated):
![grafik](https://user-images.githubusercontent.com/15326471/47652914-84360200-db87-11e8-8270-70ddaa1c5b18.png)
(Of course it should be trivial to fix it for ADD, SUBTRACT etc, here but underlines the necessity to find a solution.)

**Comment by codemanyak** [comment]
I just revised the INSPECT import. The first solution hadinverted the order of the TALLYING and REPLACING clauses, and the tallying algorithm was totally wrong. It's improved now, such that most (but still not all) of the results comply with those given with the test examples from the ISO draft.

**Comment by codemanyak** [comment]
With the corrected INSPECT_TALLYING diagram, the imported reference examples for the INSPECT statement in section D.23 (annex D) of document ISO/IEC 1989:202x WD 2.01 now pass the test.

**Comment by codemanyak** [comment]
The comma elimination was too radical:
```
01  display-elapsed-seconds pic zz,zz9.99.
01  display-count pic z,zzz,zz9.
```
now gets mutilated to:
```
01  display-elapsed-seconds pic zz zz9.99.
01  display-count pic z zzz zz9.
```
Hence, the import of several diagrams that hadn't caused problems before version 3.28-12 fails now.

**Comment by codemanyak** [comment]
Workaround pushed to bugfix branch (filed for version 3.29-05)

**Comment by GitMensch** [comment]
>Hence, the import of several COBOL sources that hadn't caused problems before version 3.28-12 fails now (since version 3.28-12).

Hm, looks like an automated test for the import (also applies to other parsers) would be desirable. There was an issue for this which I just don't find at the moment, wasn't it?

**Comment by codemanyak** [comment]
> Hm, looks like an automated test for the import (also applies to other parsers) would be desirable. There was an issue for this which I just don't find at the moment, wasn't it?

You are absolutely right. Whereas a complete test suite for Structorizer looks like a century task, test cases for batch code import (and possibly code export) seem to be a sensible point to start with. I'll have a look for the issue that first mentioned the introduction of tests and samples.
