### ISSUE TITLE
Redesign of the Program/Sub editor w.r.t. include list?

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#651]
The editor for Root elements was extended by an additional text area for the include list:
![inputbox_root_3 27](https://user-images.githubusercontent.com/15326471/27775246-8e9d895c-5fa0-11e7-9737-393ad88c57a7.png)

The experience with this layout is not totally satisfying. The following drawbacks are to be considered:
- The space for the diagram title and the comment areas is uncomfortably reduced.
- Every now and then the dynamic vertical balancing between the three text areas gets compromised and e.g. the include list isn't shown at all or has a useless height (by window resizing and/or font resizing the access can be re-gained in most cases but this is hardly acceptable):
![issue651_oaledhbnkppemfhn-1](https://user-images.githubusercontent.com/15326471/50309221-5b066380-049e-11e9-9ebd-958f97663229.png)

- Despite of the (meanwhile) differing background colour and the initial focus in the title text area, the user might get confused among the text areas.
- An include list isn't always needed but the text area always claims its share of the precious editor space.

Having pondered all that, it might be a better idea to remove that text area and add an additional button ("Include List") next to the "Attributes" button, by means of which a dialog could be popped up where the list content may be edited. In addition a label next to the button (or part of the button text) might show the number of referred Includable diagrams:

![grafik](https://user-images.githubusercontent.com/15326471/50230029-084c7f00-03ac-11e9-888c-ea61e444788c.png)

Optionally, a tooltip help might show the list while the mouse is hovering over the button or the label.

_Originally posted by @codemanyak in https://github.com/fesch/Structorizer.Desktop/issues/389#issuecomment-312515609_

**Comment by codemanyak** [comment]
The modification has been uploaded to the bugfix branch. The include list editor popping up on pressing the new button (now named "Diagrams to be included (2)") is very simplistic and like like this:
![include_list_editor_3 28-13](https://user-images.githubusercontent.com/15326471/50309389-f7306a80-049e-11e9-979d-98d2384a5905.png)
It contains just a scrollable text area where the diagram names may be written to (separated by comma or newlines).

**Comment by GitMensch** [comment]
Looks good. The only issue I see with it is "you have to do the click to also get the information" - but as you've already mentioned this would be solved if the "Include List (n)" Button has a tooltip with the list, too.

**Comment by codemanyak** [comment]
The tooltip proposal had already be implemented. In addition, the include list can of course be seen in the drawn diagram itself (cf. #652).
