### ISSUE TITLE
Key bindings for Del and Cursor keys would be welcome in Arranger

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#655]
The following key bindings would be helpful in Arranger:
- `<del>` to remove the selected diagram from Arranger (with commit popup for safety),
- Cursor keys (`<up>`, `<down>`, `<left>`, `<right>`) and page keys (`<pageUp>`, `<pageDown>`) to scroll,
- Cursor keys with `<Ctrl>` pressed to move a selected diagram around.

**Comment by codemanyak** [comment]
There had already been some key bindings for deletions but these were counter-intuitive (even for myself):
- shift-del --> remove the selected diagram (usually a key binding for cut)
- ctrl-del --> remove all diagrams
- ctrl-x --> remove the selected diagram (usually a key binding for cut)

I think the shift requirement for removal was introduced to avoid inadvertent deletions (which makes sense). But we can do better.
First of all, I propose to allow multiple selection (ctrl-click to toggle selection of the hit diagram) and to modify the semantics of the above key bindings as follows:
- del --> remove the selected diagrams (multiple selection supported) with confirmation request
- shift-del - cut the selected diagram (single selection required) with confirmation request
- ctrl-del --> remove the selected diagrams (multiple selection) without confirmation request
- ctrl-shift-del, ctrl-x --> cut he selected diagram (single selection only) without confirmation request
- ctrl-a --> select all diagrams (which makes a specific key binding to remove all diagrams obsolete, the toolbar button overlay shift + "Drop Diagram" for "Remove All" may persist, however).

The multiple selection feature makes it sensible to add a statusbar to the Arranger where besides the current drawing area size the number of selected diagrams should be shown.

**Comment by codemanyak** [comment]
Multiple selection has been set to work, such that several operations (saving an arrangement, removing diagrams frm Arranger, dragging diagrams etc.) may now be related to the current selection rather than all diagrams or just a single one.
(As this inflicts several API and functional modifications, the next version might be release 3.29.)

**Comment by codemanyak** [comment]
On this occasion, I uncoupled the selection flags of diagrams in Arranger from those in Structorizer such that the highlighting doesn't interfere anymore.

**Comment by codemanyak** [comment]
By pressing the shift button together with cursor keys or ctrl + cursor keys the scrolling speed is accelerated by factor 10.

**Comment by codemanyak** [comment]
Further key bindings implemented in Aranger:
- home --> scroll to left margin
- end --> scroll to right margin
- ctrl home --> go to top
- ctrl end --> go to bottom
- F11 --> expand the current selection by all directly and indirectly called subroutines and included diagrams (as far as available).

**Comment by codemanyak** [comment]
Popup menu for Arranger implemented:

![grafik](https://user-images.githubusercontent.com/15326471/50487720-b042f780-09ff-11e9-89ae-e1dadc31a07a.png)

**Comment by GitMensch** [comment]
What is the German translation for "Hit diagrams"?

**Comment by codemanyak** [comment]
@GitMensch 
> What is the German translation for "Hit diagrams"?

By now: "Diagramme unter der Maus"
