### ISSUE TITLE
Request for export option concerning C / C++ / C# / Java code style

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#66]
It might be helpful to have a code export option determining whether the opening block brace of a structured instruction is to be placed at a new line or at the end of the current line, e.g.:
```
if (isNice)
{
    haveFun(veryLong);
}
else
{
    beGrumpy(evenLonger);
}
```
versus
```
if (isNice) {
    haveFun(veryLong);
}
else {
    beGrumpy(evenLonger);
}
```

This is a code style issue chiefly concerning C language and all its offsprings (C++, Java, C#, and - in a modified way - some shell script languages).
Recently, C, C++, and C# export placed the block opener at the next line whereas Java export appended it to the same line.

**Comment by elemhsb** [comment]
if (isNice) {
    haveFun(veryLong);
} else {
    beGrumpy(evenLonger);
}

**Comment by codemanyak** [comment]
This is not an answer to my enhancement request, is it?

**Comment by elemhsb** [comment]
I only wrote my code **style** down here for if else clause.
Oh, i see it's the same from Eclipse-CDT C/C++ and Eclipse-Java with 
"if" Strg-Space -> if .. else ... selection. 
Under Projekt::Preferences::C/C++::General::Formating it looks like good old K&R style.

**Comment by codemanyak** [comment]
Oh indeed, I missed the different placing of the else keyword.
I see, I opened the Pandora box...

**Comment by codemanyak** [comment]
Implemented in enhancement prototype (still without the proposed *else* repositioning).
