### ISSUE TITLE
Executer did not support >1 dimension arrays, the export into C++ looks ugly

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#68]
![array-export](https://cloud.githubusercontent.com/assets/2959804/11896532/94d8cbbc-a587-11e5-9264-6fc6027ed050.png)

```
        array[0] [0] = 1;
        array[1] [0] = 2;
        array[0] [1] = 3;
        if ( array[0] [0] == 1 )
```
Export inserts unwanted " " between ][. Looks here not **so** bad, because of proportional font. EDIT: looks in edit view here not so bad.

**Comment by codemanyak** [comment]
Caused by the same reason as #69. Same remedy.

**Comment by elemhsb** [comment]
Plus overwriting array{0][0] with 3 in **Excecuter**.

**Comment by codemanyak** [comment]
Actually, Structorizer has never affirmed to cope with multidimensional arrays!
The ability to work with one-dimensional arrays was already a big achievement with version 3.22-17 we owe to Gennaro Donnarumma.
On execution, just the first index will be detected.
I don't think we will support the execution with multidimensional arrays very soon.

**Comment by codemanyak** [comment]
Solved with new bugfix (available on branch bugfix3.23, waiting for delivery as 3.23-06)
