### ISSUE TITLE
'c' becomes ' c ' after export to Pascal

### ISSUE THREAD

**Issue by IrisLuc** [fesch/Structorizer.Desktop#69]
I have a new problem with export to pascal code
When there is a string of 1 single char in the code, the export sometimes add extra spaces to the string.

i.e. 
opp <> '='  
sometimes becomes 
(opp <> ' = ')

This doesn't always happen, but there seems te be a logic to it. A new export has the same result. Changes occur in condition of iteration en in writing instructions. They do not occur in case-structure.

[calculator.zip](https://github.com/fesch/Structorizer.Desktop/files/66600/calculator.zip)

**Comment by codemanyak** [comment]
Apparently, the '=' character within the (single) quotes is erroneously regarded as an operator symbol and padded. The entire export translation will have to be transformed from string matching to tokenisation and token-based matching / replacement. This would make padding superfluous and solve this issue. This is an anyway planned, but complex modification.

**Comment by codemanyak** [comment]
Fixed with new bugfix (available on branch bugfix3.23, waiting for delivery as 3.23-06)
