### ISSUE TITLE
scrolling with mouse wheel on linux is 25 times slower then expected

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#717]
Window Scrolling up and down with mouse wheel on Linux in Structorizer and Arranger is 25 times slower than expected.

**Comment by codemanyak** [comment]
May I ask you how you measured that? And what did you compare it with?
What is the element / diagram load, respectively?
Versions 3.29-05/06 did accelerate the scrolling speed daramatically. I just tested again on OpenSuse and Debian in a virtual box, both with mouse wheel and with touchpad, and I cannot confirm or reproduce your observation. The drawing contention on scrolling is very moderate. In comparison with the situation before version3.29-05 it is fast as lightning, even with very large multi-lin elements (which are a particular challenge for the drawing in syntax-highlighting mode).
So I need more details: OS versions or builds, environment, possibly the arrangement archive of the diagrams you held in Arranger when you observed the contention.

**Comment by elemhsb** [comment]
The problem exists over years, it's only on linux, really not new and never changed over years.
I measured it now, the vertical scroll is 14 times shorter the expected. (Sorry feeling was 20+5)
If i scroll a page in firefox for 1 mouse wheel snap, i got 28mm and in Structorizer/Arranger only 2mm way length. Diagram sizes are not importend. Behaviour of Webstart and JAR File are the same.

The scrolling in Structorizer **About...** window ~3.5 lines feels ok.

##### Default Enviroment.
Environment: Debian Cinnamon Desktop, Java Web Start -- Iced Tea 1.6.2 ? 
```
# dpkg  --list  iced\* | grep plugin
ii  icedtea-8-plugin:amd64 1.6.2-3.1  amd64  web browser plugin based on OpenJDK and IcedTea to execute Java applets
```
```
$ dpkg --list openjd\* | grep ^ii
ii  openjdk-8-jdk:amd64          8u212-b01-1~deb9u1 amd64        OpenJDK Development Kit (JDK)
ii  openjdk-8-jdk-headless:amd64 8u212-b01-1~deb9u1 amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-8-jre:amd64          8u212-b01-1~deb9u1 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64 8u212-b01-1~deb9u1 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```
Ok, it looks that i use Openjdk 8u212 (Iced Tea) on x86 and arm7 raspbian it's the same.

##### Test with Oracle (Sun) JAVA 8-201
```
Downloads/jre1.8.0_201)$ bin/javaws ../Structorizer.jnlp
```
Exact the same behaviour scroll only 2mm.

**Comment by codemanyak** [comment]
Okay, I understand this issue is not actually about drawing contention (which was the Structorizer-specific big issue before version 3.29-06) but about scroll units. Here you are right, a Linux environment provides default scrolling unit that differs significatly from that in e.g. Windows systems. This is partially compensated by an also differing scrolling event rate. It's the JVM adaptaqtion to the OS, it seams.
Structorizer hasn't meddled with the default scrolling unit. It is only applying a factor proportional to the size of the diagram (#417).
We could of course apply an OS-specific factor, though I'm not sure whether this would be wise.
Another approach might be to offer a scroll unit configuration in Preferences > Mouse Wheel.

**Comment by codemanyak** [comment]
The mouse wheel base scrolling increment will be configurable from the next version (3.29-09) on (just committed the fix):
![preferences_menu3 29-09_wheel_unit](https://user-images.githubusercontent.com/15326471/55090567-a63c9d80-50af-11e9-9726-9437274e6f9a.png)
![mouse_wheel_scrolling_unit_3 29-09](https://user-images.githubusercontent.com/15326471/55090583-af2d6f00-50af-11e9-9ffe-ed00d2803c60.png)
I resisted the temptation to multiply the user-configurable unit with the size-proportional scrolling factor mentioned in the previous comment - the effect would be too drastic. So they are just added.

**Comment by elemhsb** [comment]
Good news, thanks a lot. :-)
But scrolling in "About Structorizer..."  Window feels already good.

**Comment by codemanyak** [comment]
@elemhsb 
> But scrolling in "About Structorizer..." Window feels already good.

Therefore we won't change it. :smiley:
