### ISSUE TITLE
Idea for a central preference aligner mechanism

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#733]
We have already had several requests to provide some unified set of Structorizer preferences, e.g. for classrooms.
There is some obscure mechanism to load a structorizer.ini file from an alternative directory and if a configuraton file is found in the installation directory then this will always be preferred. I just wrote the following paragraph for the User Guide to discourage it, though:
> It is possible to place a structorizer.ini file in the Structorizer installation directory. In this case, all users will share the same preferences and the individual configuration file(s) would be ignored. At first glance, this may seem sensible in order to achieve unified settings for all users of a PC or even all over a class room (if the installation is on a server). But the approach has obvious disadvantages: Since the file also stores e.g. the file history, current directories etc., it cannot be made read-only, and the activities of several users would interfere. Moreover, any awkward setting by any of the users might bother or pester all users, not to mention concurrency issues, anyway. So be strongly advised not to.

But this raised an idea: What if we implemented a new (or rather modified) mechanism that just initially loads a central ini file (if it exists) with a (limited) set of preferences without turning it to the working preferences file? This way, some centrally configured preferences would always initially override the respective individual settings but still allow all other preferences to be configured individually without interference. During the session users may even temporarily modify the centrally pushed preferences till the next local Structorizer start. (Unfortunately, this would also apply to any Structorizer instance started locally by double-clicking a file etc. and thus affect open instances as well, so further conceptional considerations would be necessary,)
What about the general idea?

@fesch 
On that occasion: Does anybody (meaning Bob, actually :grin: ) still know what that quirky regular/alternate file stuff originally was good for or instigated by? (Gennaro Donnarumma had his fingers in it, chiefly, if this helps or rings a bell.)

**Comment by codemanyak** [comment]
A problem might be, that he ini file is loaded several times on start, not necessarily writing the prefernecs "back" immediately, such that it may not be quite clear when the start is over. But this could be changed of course: Ini should never write to the "alternate" file ad Structorizer might save preferences right after having loaded them the very first time.

**Comment by fesch** [comment]
A long long time ago ... but I can't remember very well. I know that one school needed to have the ini file in a different location, but I can't say if they still use it ...

**Comment by codemanyak** [comment]
In order to produce such an ini file template I deem it highly sensible not always to export all options but rather a subset. Manually to delete all unwanted entries from an (unordered!) complete ini file is not a reasonable task, but a punishment.
So I implemented a mechanism that allows to select categories of settings to be written to a named ini file. When selecting the menu item "Preferences => Alle preferences ... => Save to file .." then the following dialog will appear before the file chooser opens:
![Preferences_selection_3 29-12b](https://user-images.githubusercontent.com/15326471/62417326-f541a300-b64c-11e9-8120-ffc917b1eee8.png)

**Comment by GitMensch** [comment]
And just to leave this information in here where we have the other parts:

* the export creates a new .ini that may be only partial
* this partial one can be referenced on start by ???

**Comment by codemanyak** [comment]
> - this partial one can be referenced on start by ???

It must be named "structorizer.ini" and be placed in the installation directory that Structorizer reports on the tab "Paths" in the "About" window. Please consult the [Preferences](https://help.structorizer.fisch.lu/index.php?menu=77) page in the User Guide.

**Comment by codemanyak** [comment]
> 
> 
> A long long time ago ... but I can't remember very well. I know that one school needed to have the ini file in a different location, but I can't say if they still use it ...

@fesch 
I just bumped into a changelog enry for version 3.01:
> - Moved INI file to "Structorizer.app" folder [FISRO]

This seems to shed some light: I think now, it might have been the other way round - originally the ini file may have been held in the installation directory and later a change was made to put it into the user's home directory in order to separate indiidual settings, such that the "alternate" path might just have been to grant backwards compatibility. This would make sense for me.

**Comment by fesch** [comment]
Oh yes, the changelog. I didn't have the reflex to take a look at that file. 

You are right ;)

**Comment by codemanyak** [comment]
@fesch 
> Oh yes, the changelog. I didn't have the reflex to take a look at that file.

Well, or I could have done it myself in the first place before asking dull questions. Indeed it was version 3.08 when INI went to the user's home directory, and guess who did it :-):
> INI-file now in home directory of user [Klaus-Peter Reimers]

But I just found another relevant aspect there (with version 3.19):
> - Have a backup of the INI file in the current application directory.
  This makes the application "portable" [Peter Ehrlich]

I guess this meant the "installation" directory (e.g. on a stick or so) to be sound with Peter's explanation. I guess this had some of the unwanted side effects, the relics in the code tried tried to aleviate a little. Obviously, there were just too many conflicting aims in the game. I think, the possibility to save and load an ini file as untroduced with 3.22 an refined just now should address the above need sufficiently and in a clean way. So I feel relaxed with the modified functionality.

**Comment by GitMensch** [comment]
... and as long as you add a command line option to specifiy an explicit ini file then you know that there's always an option to run portable/installed/...
And if the .ini file has an option to "include" another ini (like external_definitions=/path/to/ini) you's also provide the option to "split" the files, like author, size, whatever in the student's ini and the others in the classroom's ini. Just a thought...

**Comment by codemanyak** [comment]
@GitMensch 
> ... and as long as you add a command line option to specifiy an explicit ini file then you know that there's always an option to run portable/installed/...

Not a bad idea. The command line option `-s <settings_file>` had already been introduced for batch parsing, and I'm currently extending it to the batch export (see #737). So there should not be a fundamental problem always to to take this command line parameter into account. But I will have to test all the consequences thouroughly. The major issue to solve is where to save the merged preferences and the changes. Into the specified ini-file or always into the individual structorizer.ini in the home directory, or should saving be impeded totally (which makes a lot of sense in batch import / export mode). I'll think of this.

> And if the .ini file has an option to "include" another ini (like external_definitions=/path/to/ini) you's also provide the option to "split" the files, like author, size, whatever in the student's ini and the others in the classroom's ini. Just a thought...

At first glance I am not that convinced of your idea. Though technically possible (all include demands would have to be listed within in a single key-value pair, like in the environment variable PATH), and this property would certainly have to be checked first (or better last?), some complications would have to be solved:
- First of all: order matters if the included ini files are not disjoint, i.e. if they functionally overlap;
- What about recursive and, hence, even cyclic inclusion?
- Who is to keep the overview here?
- Should the INI include list be configurable by any ordinary user via the GUI? :scream:

And there are certainly more risks to be considered. Yet I will ponder it, but "it scares the bejeebers out of me", as a Canadian colleague once formulated.

**Comment by codemanyak** [comment]
Though a little off-topic, this discussion let another question plop up in my mind (backed by my experiments with some more or less partial INI files): Should the loading of an INI file be undoable?
Well, of course a user loading an unknown INI file is well advised to have saved a copy of the recent settings before, but umh, you know...
So perhaps we might always automatically save a backup before loading an INI file via the menu, such that the last backup might be reloaded on "undoing" the last explicit load.

**Comment by codemanyak** [comment]
I just became aware that it would be no good idea to specify the GUI scaling factor in the centra predominant ini file, because this would prevent the user from customizing it to their needs as it gets only into effect on the start - when it will already have been overridden again.
When I started to insert related warnings into the User Guide I realised that we should better just exclude this property from being overridden in code.
