### ISSUE TITLE
Missing menu items [3.29-12]

### ISSUE THREAD

**Issue by teobaldo3524** [fesch/Structorizer.Desktop#743]
As the screenshot shows, I'm missing some items from the File menu. This is on an iMac with 10.11.6 and Java 8 Update 221.
The issue does not occur with 3.29-02.
![Schermafbeelding 2019-08-28 om 11 15 05](https://user-images.githubusercontent.com/54622556/63843149-32682f00-c986-11e9-9182-21e10d7c4618.png)

**Comment by fesch** [comment]
Notice #1 : Arrange, Inspect Attributes and Translator are missing
Notice #2 : If some exception would have occurred during the menu building process, Quit shouldn't be there either. But it is ...
Notice #3 : The three named icons that are missing are being hidden when the "Simplified Toolbars?" in the preferences menu is active. Did you check that this option is _NOT_ checked?

**Comment by teobaldo3524** [comment]
Well I'll be…
Yes, the missing items returned when I unchecked that option.

**Comment by fesch** [comment]
:-)
