### ISSUE TITLE
Structorizer <= 3.23-07 installation on OS X failed.

### ISSUE THREAD

**Issue by elemhsb** [fesch/Structorizer.Desktop#79]
The distributed zip installation files <= 3.23-07 (heise.de / fisch.lu) for OS X didn't run out of the box.
The default behavior, double click on the extracted program app failed on Yosemite and El Capitan.
![structorizer-macos-fail](https://cloud.githubusercontent.com/assets/2959804/12009076/92aee2f2-ac69-11e5-83ae-753ee9b97a99.png).
It's a really show stopper for Mac users!
As a workaround fingering to the ../Resources/Structorizer.jar file and execution of it will work.

**Comment by fesch** [comment]
Well, my local installation still works ... and as the published version is basically just a ZIP of that ... ??!!

I will check and upload a new version ...

**Comment by fesch** [comment]
I'm sorry, but the download link for MAC works fine and the ZIP behind is _NOT_ corrupt. The included app starts as expected.

Just to make sure we are talking about the same file:
http://www.fisch.lu/Php/download.php?file=structorizer_latest_mac.zip

**Comment by elemhsb** [comment]
All the same, the problem exists on 3 different Mac's and all Structorizer versions I have tested the last 3 months. 
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**Comment by codemanyak** [comment]
Just a comment: The Structorizer version currently downloadable from heise.de dates back to the 5th of December and represents 3.23-00. (The date Dec. 24 relates only to the last virus check.) The mac version doesn't differ from the windows version except that the exe file and shell scripts of the root folder are missing.
I don't know whether the empty Icon file might cause the trouble. Unpacking under windows may also complain (depending on which decompressor is used) but at least continues to extract if the users insists. Yet, if the downloading from structorizer.fisch.lu works then this may hardly be what causes the failure on OS X (which had occasuionally be reported by several mac-affine students of mine as well -- already months ago, by the way).

**Comment by codemanyak** [comment]
Another possibly mor helpful comment:
@elemhsb: Java 1.6-x is VERY old and should actually be updated. There are good chances that this is the real show-stopper. This might of course get into conflict with other Java application that still require the obsolete Java SE6 - this seems to be not so rare an issue under OS X?

**Comment by elemhsb** [comment]
You request 1.6+ Java version in your plist file, then a fresh OS X (El Capitan) requests the legacy JAVA version (show above) from APPLE. https://support.apple.com/kb/DL1572?locale=de_DE
I will try a newer Version later.

**Comment by fesch** [comment]
I've re-installed an old Mac with no Java: it ask to install legacy Java 6. After installing this, I get your message. I thus can confirm the problem ....

**Comment by fesch** [comment]
As launching the jar manually works, the problem seams to be with the wrapper stub application, not with Structorizer itself ...

**Comment by fesch** [comment]
Please lower your security settings to allow opening applications from "anywhere". After that, Structorizer will open again on old devices ...

**Comment by elemhsb** [comment]
OK, now it work's. Thanks a lot.
BTW. The official way to start app from uncertified developers with CTRL-key didn't work.
After a successful start the option "Keine Einschränkungen" could be put back. 
This would also be automatically after a period off 30 days.

**Comment by codemanyak** [comment]
Problem raised again as #152.
