### ISSUE TITLE
Open Hub issue

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#796]
https://www.openhub.net/p/structorizer/enlistments says "download failed 6 months ago" and therefore doesn't update the statistic widgets, for example those shown at https://structorizer.fisch.lu/index.php?include=downloads
As "only managers may adjust this data" I suggest to solve this as follows:

* "Edit ignored files" on the last entry; copy + past somewhere
* "delete this location" on the last entry
* create new entry using repo URL https://svn.code.sf.net/p/structorizer/code/Structorizer

**Comment by codemanyak** [comment]
Well, as far as I know, this is an Open Hub internal issue. Actually, they tell explicitly:
"Please do **not** simply delete and re-add the enlistment. In most cases this does not have any effect (our system will recognize the URL and simply re-add the existing broken download), and it will complicate our debugging efforts."
I had reported the same problem some time ago (more than a year as far as I remember), some time later the refresh worked again, then had failed again for half a year. The number of ignored files suggests that the entire repository might cause a problem. "Edit ignored files" seems to get stuck (showing a progress bar for hours on end).

**Comment by codemanyak** [comment]
I tried to shorten the path but it didn't work - OpenHub restored to original path in this place: "svn://svn.code.sf.net/p/structorizer/code/Structorizer /Structorizer"

**Comment by codemanyak** [comment]
Now I used the https URL you suggested. We will see what happens.

**Comment by GitMensch** [comment]
/Structorizer is correct as below this you have the same structure as in this repo and you want to be the files to be recognized to be identical. Concerning the "Edit seems to get stuck" - I only have seen this with not being logged in...

**Comment by codemanyak** [comment]
@GitMensch 
> Concerning the "Edit seems to get stuck" - I only have seen this with not being logged in...

You are right, logging in solved this problem.

Well, the outcome of modifying the SVN URL to https doesn't seem to be much better:
![grafik](https://user-images.githubusercontent.com/15326471/72283950-1ff24780-3640-11ea-84cc-cac7147a5f5f.png)

**Comment by GitMensch** [comment]
:-( ok, then the only way to "fix" it is to either ping them on the support forum or drop the entry (ideally the repo Structorizer.Desktop would be recreated with the SVN being converted and then the current repo content be added "on top". But I think I suggested this before and fesch wasn't happy with it (it actually is a big issue as this would invalidate any existing checkout).
The *easiest* thing to fix it would be to just create a Structorizer.Desktop-History repo by converting the subversion repository and add it here (most services including OpenHub have no issue with git repos) - while this would not fix the history like recreating this repo it still would make the history available "next to" the current development.

**Comment by codemanyak** [comment]
I complained again on the OpenHub [help forum](https://www.openhub.net/topics/15064) more than a week ago, without an answer so far.

**Comment by codemanyak** [comment]
The problems seem to have been overcome. In December 2020, several updates where observable.
