### ISSUE TITLE
sourceforge - add note "project moved"

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#797]
To do so:
* visit https://sourceforge.net/p/structorizer/admin/overview
* on the right side click on "project moved to" and enter https://github.com/fesch/Structorizer.Desktop there
* on the bottom of the page: "save"

**Comment by codemanyak** [comment]
On the URL https://sourceforge.net/projects/structorizer/, there has already been such a remark:
![grafik](https://user-images.githubusercontent.com/15326471/72283045-3dbead00-363e-11ea-9443-18cdef3d1a9d.png)

Well, the download statistics seems to suggest that this may not be sufficient...

**Comment by GitMensch** [comment]
Hm, using the "moved" note the icon would normally be shown here as a standard SF icon.

![grafik](https://user-images.githubusercontent.com/6699539/72283586-57142900-363f-11ea-87a5-3643aa8492a1.png) - is the setting described in the issue is already set?

**Comment by codemanyak** [comment]
@GitMensch 
> is the setting described in the issue is already set?

I guess no, it seems to be a mere comment. But the task to apply the formal setting has to be left to Bob since I am not disposing of administrative privileges on the sourceforge location.

**Comment by fesch** [comment]
done (after resetting my password ...)
