### ISSUE TITLE
Missing export of element

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#808]
Hi Kay,

Test the attached NSD with an export to C-language.
The calculation is not exported or do I something wrong?

[Umrechnungstabelle.zip](https://github.com/fesch/Structorizer.Desktop/files/4181985/Umrechnungstabelle.zip)

**Comment by codemanyak** [comment]
This is a bug, actually. Apparently the generator gets confused among declaration and assignment. It seems to take the wrong bend somewhere...

**Comment by codemanyak** [comment]
Okay, reason found: The unification of the assignment symbol had obviously been forgotten - with `<-` as assignment symbol instead of `:=` it works. So fixing will be trivial.

**Comment by codemanyak** [comment]
@reks99 
By the way, you should force floating-point division in the marked element:
`int grad_C := (grad - 32) * 5.0/9.0`
