### ISSUE TITLE
for loop in style javascript not allowed

### ISSUE THREAD

**Issue by dogmza** [fesch/Structorizer.Desktop#82]
Now I need to code a subroutine in JavaScript. I want to make the diagram. 

The issue I have is that the file (nsd) damage.  I tested it and I follow the block "for" have a problem when I want to use "for ( variable in object )" (style JavaScript)  instead of  classical for loop. I wrote the sentence using the option Full Text Editing.

As workaround I used "while block", because for now I don't need to export the code nor Structorizer export to JavaScript. 

You can make your test as I show you in the images.
Thanks a lot, i apologize because my english is no so good.

![bug_1](https://cloud.githubusercontent.com/assets/16491243/12053458/104f565c-aef8-11e5-9083-b3b0251803b8.png)
![bug_2](https://cloud.githubusercontent.com/assets/16491243/12053459/10520884-aef8-11e5-8318-0dc532bc4a07.png)

**Comment by codemanyak** [comment]
Thanks for the report! Your issue has two aspects:
1. It refers to a different type or understanding of a FOR loop pretty popular in many script languages and also increasingly infiltrating standard languages (like C++, Java etc.) as "foreach" or "for in" loop. I have already considered supporting it in Structorizer but waited for a request - it requires distinguishing the two FOR loop paradigms and some complex work to implement it both in Executor and Code export. So this will instigate a respective enhancement request (as separate issue).
2. Structorizer support for the classical FOR loop was improved (which involved stricter syntax analysis) but this was not meant to obstruct the saving of a "free-style" FOR loop. Hence, this aspect is to be handled as bug, requiring a bugfix.

**Comment by codemanyak** [comment]
Fix #82 (aspect 2) available on bugfix3.23 branch.
