### ISSUE TITLE
Do not close debug window

### ISSUE THREAD

**Issue by mawa290669** [fesch/Structorizer.Desktop#829]
I would find it very nice if the debug window did not always close automatically at the end.

**Comment by codemanyak** [comment]
The debug window will stay open when you have switched on the runtime analysis.
We will ponder your proposal to keep it always open until the stop button is pressed.

**Comment by codemanyak** [comment]
After some period of practical experience I am inclined to revoke this modification. These are the reasons:
- It' cluttering the desktop unnecessarily.
- Usually the debug window will have got buried behind other windows when it is needed again, so to press the toolbar button in Structorizer is in most cases faster than rummaging among the open windows.
- If several Structorizer instances are open (e.g. after having generated a subroutine via "Edit Subroutine" on an unsatisfied Call element) then it's unclear what diagram the debugger will execute. So it's better to ropen it from the very Structorizer instance.
