### ISSUE TITLE
Problems with python export

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#831]
Hi Kay,

I build the program shown in the image.
![Paralleltest](https://user-images.githubusercontent.com/18035140/76087111-c5c59100-5fb5-11ea-8679-b27ea66b4a47.png)
It runs flawlessly in the executer. When exported to python, I doesn't.

**First** -  the sep-argument to the print command gives an error. Btw. the print command in python can nearly be written like the printf-command in C.

**Second** - the arguments for the call of the threads should be in squared brackets to be seen as a list of arguments by the thread.

**Third** the seq-generater in the for-loop uses the argument "param2+1". I don't know, where it comes from.

Attached you can find an archive with the exported and a modified version of the python exports.

[paralleltest.zip](https://github.com/fesch/Structorizer.Desktop/files/4298526/paralleltest.zip)

Fine regards
Rolf

**Comment by codemanyak** [comment]
Let's start with the third item:
Structorizer exports the FOR loop `for i <- 0 to param2 ...` **correctly** as
```python
    for i in range(0, param2+1, 1):
        print(param1, sep='')
```
The second argument of the range function is ***not** included. As the loop includes the end value `param2` the Python export musst apply a larger value as second argument to `range()` in order to be equivalent. As Structorizer assumes the step value to be an integer (by default +1), it should be okay to use `param2+1`.

**Comment by codemanyak** [comment]
With respect to your **first** item:
> First - the sep-argument to the print command gives an error. Btw. the print command in python can nearly be written like the printf-command in C.

What Python version are you working with? The Structorizer export of the output instruction works pretty fine with Python 3.7 (which is what it was configured for).

**Comment by reks99** [comment]
Hi Kay,

see the following example:

`#! /usr/bin/python3

array=["aaa", "bbb", "ccc", "ddd"]

param = len(array)
print(param)

for i in range(0, param):
    print(array[i])`

So param has the value of 4 and all 4 elements of the array are printed. I never added one to the end of loop value - only if the index starts with 1.

BTW my Python3-Version is

> Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux

Fine regards
Rolf

**Comment by reks99** [comment]
Hi Kay, 

I checked the export again and the "sep" option is not the problem of the error. It results from the parentheses around the print statement, because the script is started by python2.x. When modified the shebang to python3 the 'sep' option is accepted.

Fine regards
Rolf

**Comment by reks99** [comment]
Hi,

I checked the loop count either and it prints out 11 times the value, not as asked for 10 times.

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> param = len(array)
> print(param)
> 
> for i in range(0, param):
> print(array[i])`
> 
> So param has the value of 4 and all 4 elements of the array are printed. I never added a one to the end of the loop value - only if the index starts with 1.

Hi Rolf, the index range of an array consisting of 4 elements is 0 through 3. This is exactly what `range(0, 4)` produces. Try 
```python
for i in range(0, 4):
    print(i)
```
if you don't believe me.

**Comment by codemanyak** [comment]
@reks99 
> [...] because the script is started by python2.x. When modified the shebang to python3 the 'sep' option is accepted.

You are right: I missed to adapt the shebang when I modified the generator towards Python 3. Sorry, I used tom test the produced code snippets rather than the entire file.

**Comment by codemanyak** [comment]
@reks99 
> I checked the loop count either and it prints out 11 times the value, not as asked for 10 times.

That's because your FOR loop in Structorizer also runs 11 times (from 0 to 10 are 11 steps, not 10).

**Comment by codemanyak** [comment]
The defective export of CALLs as only elements in parallel branches will be fixed with version 3.30-07 (as well as the shebang).

**Comment by reks99** [comment]
Hi Kay,

the attached archive has a Structorizer version of the array printing program a few comments before. 
When it runs as python script the attached errors are printed and they show, that there was a try to access one more element of the array.

Even executer gives a 5.th element with no meaning full content.
[for_test.zip](https://github.com/fesch/Structorizer.Desktop/files/4305487/for_test.zip)

Fine regards
Rolf

**Comment by codemanyak** [comment]
@reks99 
> he attached archive has a Structorizer version of the array printing program like that from a few comments before.
> When the exported python script runs the attached errors are shown and you can see, that there was a try to access one more element of the array.
> 
> Even executer gives a 5.th element with no meaning full content.
> [for_test.zip](https://github.com/fesch/Structorizer.Desktop/files/4305487/for_test.zip)

Rolf, please! Don't you see that the Executor shows you an error on trying to apply index 4?
![grafik](https://user-images.githubusercontent.com/15326471/76240029-d20a5200-6232-11ea-8c70-acaac36ac8fc.png)

Your loop in routine test is simply wrong (already in Structorizer)! If `param2` is supposed to be the number of elements in the array then `i` must stop *before*  `param2`, i.e. at `param2 - 1`:
![grafik](https://user-images.githubusercontent.com/15326471/76240174-13026680-6233-11ea-91b9-edd91fe82bfc.png)

You cannot expect to obtain a correct Python code if your algorithm is wrong ("garbage in - garbage out")! It is as simple as that. Why don't you get this?
