### ISSUE TITLE
Try-Catch with DIN 66261

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#834]
I wonder, why the try-catch element is still shown, when the diagram option "DIN 66261" was selected. AFAK is try-catch not part of NSD-Definition and so not part  of the DIN.

**Comment by codemanyak** [comment]
The DIN 662621 option only controls the appearance of the FOR loop. It is a mere presentation option. It cannot conjure away inserted TRY elements from the diagrams (as there is no equivalent), and so it wouldn't make sense to hide the buttons, either.

**Comment by codemanyak** [comment]
I will configure a tooltip help for the DIN662621 menu item explaining what to expext from it.

**Comment by codemanyak** [comment]
I just like to add two remarks:
1. The tooltip as proposed in https://github.com/fesch/Structorizer.Desktop/issues/834#issuecomment-597373562 was indeed realized with version 3.30-07.
2. It is the "Simplified" mode that actually makes the button for `TRY` elements vanish (and with it `EXIT` and `PARALLEL` toolbar buttons and menu entries).
