### ISSUE TITLE
Enhancement: Support for FOR-IN loops

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#84]
On the occasion of issue #82, additional support for "FOR IN" loops both on execution and code export is proposed.
Background: In script languages (shell scripts, javascript, Perl) and increasingly other languages as well (e. g. Python, C++11, Java etc.) a special kind of loop is very popular: The FOR-IN (or foreach) loop. In contrast to the traditional FOR loop it doesn't explicitly count something but applies the loop body to all elements of a given collection, e. g.:
```
for name in filenames
    do something with name
```
It might be a good idea to have Structorizer additionaly supported this loop concept.
Options are:

1. Introduction of a new loop type (in toolbar and all menus).
2. Implementation as a selectable variant of the existing FOR loop.

I suggest option 2. The implications are:

- [x] A new checkbox in the FOR loop editor to switch between FOR TO and FOR IN loop and an alternative set of text fields to specify the element variable and the collection (set of elements) for the composition of the respective loop header text.
- [x] A corresponding new attribute in the NSD files to store this distinction (if this new attribute is missing in an NSD file to be loaded, then the traditional FOR-TO loop is to be supposed, for backward compatibility).
- [x] An additional parser preference for FOR loops to configure the separating keyword between variable and collection (e. g. **in**).
- [x] A more sophisticated splitting mechanism for the for loop header to distinguish and decompose both FOR loop types.
- [x] A collection literal syntax accepted by Executor, e. g. "{ item1, item2, item3 }", also usable to assign value sequences to array variables (might cause trouble on code export to many languages, though).
- [x] The acceptance of array variables and the literals just mentioned in the previous item as collection expressions in FOR-IN loops.
- [x] Deft code export strategies for those target languages not providing a FOR-IN loop (at first glance, it seems not very complicated while in Structorizer arrays are used as enumerable collections: it could be translated into a traditional FOR loop running over the index range. The difficulty, however, is to guess the index range if the collection is not a literal: Code export is not a run-time interpretation!).

**Comment by fesch** [comment]
Heavy changes in any case, but yes, I agree on option 2 ...

**Comment by codemanyak** [comment]
The implementation of the FOR-IN prototype will not be my very next activity, anyway, i. e. may take some time.

**Comment by codemanyak** [comment]
All subtasks done, enhancement ready for merge,
