### ISSUE TITLE
Cannot include diagrams in "Diagrams to be included"

### ISSUE THREAD

**Issue by vaxorcist** [fesch/Structorizer.Desktop#842]
I cannot include diagrams in "Diagrams to be included".
No diagrams show up.
Both the Includable and the Subroutine (in which to include) are in the same directory.
OS: Debian 10
Structorizer: 3.30-06

**Comment by codemanyak** [comment]
@vaxorcist 
> I cannot include diagrams in "Diagrams to be included". No diagrams show up.

First of all: The text area opening when you click "Diagrams to be included" is still very poor - it does not show you a choice list or the like. Sorry for this. You will simply write the names of diagrams of type Includable there manually. It think we will improve the usability with some of the next versions.
> Both the Includable and the Subroutine (in which to include) are in the same directory.

Even if we add a choice list or other helping mechanisms then the only pool where the includaböles are looked for is the Arranger. Are aware of what I am talking? You will have to put the diagram(s) to be included there. You might e.g. load it into Structorizer and then press the "Arrange" button on the toolbar or in the "File" menu. If the Arranger window has already been opened then you might simply drag nsd files from the File Manager into it.

**Comment by codemanyak** [comment]
From version 3.30-08, a choice box and an "Add" button will appear above the text box of the include list editor if Arranger is open and contains Includable diagrams:
![include_list_editor_3 30-08](https://user-images.githubusercontent.com/15326471/79118236-a0365f00-7d8d-11ea-9b4c-d683d7ec9b49.png)
So you may simply select the name of an available Incluable in the choice element and append it to the names in the text box via pressing the "Add" button.
