### ISSUE TITLE
Strange effect: Code preview context menu pops open on start

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#868]
Since 2020-05-25, the installed Structorizer (version 3.30-09) automatically pops up the context menu of the code preview on starting - even if the code preview is not enabled!
![grafik](https://user-images.githubusercontent.com/15326471/83245302-d2b2e480-a1a0-11ea-81a9-76a45311fd4e.png)
The context menu is always placed in the upper left corner of the screen and not even vanishes if any of the menu items is clicked (which even induces the associated action). Only after activating the context menu from the code preview, the popup will vanish.
This was first observed on a Windows 10 PC. Even more bewildering, this does not happen with a merely unzipped Structorizer download of apparently the same version on the same computer. On different PCs, this behaviour could not be observed by now, neither with the Windows installer nor the unzipped product.
The Structorizer installation package originates from 2019-12-12 and was installed on 2019-12-13, the Java version in use is AdoptOpenJDK (jdk-11.0.5.10-openj9).

**Comment by codemanyak** [comment]
After having uninstalled and reinstalled Structorizer on that very PC, the problem still exists.

**Comment by codemanyak** [comment]
The effect remains after having replaced the JDK by AdoptOpenJDK 11.0.07.10-openj9-0.20.0.

Possibly it is related to the Windows 10 version (Enterprise 1607), which e.g. also still requires to add JRE keys in the registry after having installed the JDK in order to run some Java applications (see Structorizer User Guide; more contemporary versions like 1909 don't).

**Comment by koe2** [comment]
Hello,

Same here. 
Today structorizer did update itself on startup and then this bug appeared.
I used structorizer last week, had no issues. I assume this is related to some changes.
I tried to reinstall structorizer too, bug still appears.

Is it possible to disable the auto-update function on startup ?
If not i would suggest to add this option to the settings. 
It would be nice to ask the user for installing a new version, instead of doing this automatic.

OS: Windows 7 Pro 64x

**Comment by jochel74** [comment]
Hello,
i just wanted to say, that i get the same effect using Ubuntu 18.04. So it seems not to be a Windows-only-Issue.

**Comment by codemanyak** [comment]
@koe2 
> It would be nice to ask the user for installing a new version, instead of doing this automatic.
> I would suggest to add an option for disabling update-check in the settings section.

Well, this opportunity had been existing both on installation and thereafter in the "Apps" configuration, see [User Guide](https://help.structorizer.fisch.lu/index.php?menu=46). Hence your workaround would not have been necessary (you might just have had to choose "Look for updates but let me decide whether to install it or not").

But your observation was essential: It revealed that there is a difference between the jar file originally installed and the one exposed for update check (though both affirm to be version 3.30-09). Indeed they differ in size.
@jochel74 
Actually all recent downloads except the windows installer package have been changed on 2020-05-25 whereas the release date was 2020-05-13 (which worked correctly). We will check what happened there. I hope we don't have a security issue here.

**Comment by codemanyak** [comment]
I wrote:
> I hope we don't have a security issue here.

Fortunately we don't have a security issue here. It was just an undocumented quick-and-dirty change in order to introduce some "restricted mode" where import and export had to be suppressed. in the master branch without proper testing. We will fix it ASAP with version 3.30-10.

**Comment by codemanyak** [comment]
The bugfix is ready and on the brink of being delivered with version 3.30-10.
