### ISSUE TITLE
Proposal for enhanced collapse / expand functionality

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#87]
On occasion of issue #65, some modifications of the functionality to collapse / expand large NSD elements (having only been available via mouse wheel motions - which used not to work on Linux platforms) are proposed:

1. The functionality shall also be available via toolbar buttons and several menu items (see the green-framed toolbar in the screenshot below).
![collapseexpandbuttons](https://cloud.githubusercontent.com/assets/15326471/12089275/6a358b0c-b2e3-11e5-80dc-80bfca4e5868.png)

2. The possibility to control the collapsing via the mouse wheel might be withdrawn (in favour of mouse-wheel scrolling over the diagram) or restricted. Instead, usual accelerator keys like NumPad+ and NumPad- (maybe in combination with Shift key to avoid unwanted effects on editing expressions) might be associated.
3. Collapsed elements used to be presented like instructions, but with grey background where just the first text line was shown, followed by an ellipse ("...") on the next line. This way, Parallel sections showed just the number of threads, and Endless loops showed nothing at all. In order to provide more useful information, the collapsed elements ought to prsent a type-specific icon in the upper left corner, Parallel elements should look like "Parallel(n)" rather than just "n", and for Repeat loops, it seems more intuitive to revert the line order, such that the exit condition follows the ellipse. See the following image for an example. (Unfortunately, this will tear another breach into the module hierarchy, requiring model classes to grab for UI stuff...)
![collapsed](https://cloud.githubusercontent.com/assets/15326471/12089290/8cf24856-b2e3-11e5-9495-5f001c698517.png)

4. Large Instruction elements (with many instruction lines) showed no effect on being collapsed beyond adopting the grey background colour, which doesn't make much sense. So instructions with more than two lines are to be actually collapsed as well, in order to save space.

**Comment by fesch** [comment]
*like* :-)

**Comment by codemanyak** [comment]
In addition, there was a bug: Selecting a collapsed element didn't work correctly because the (invisible) substructure still "stole" the selection marker. This misbehaviour to be disabled.

**Comment by codemanyak** [comment]
Accelerator keys NumPad+ (KeyEvent.VK_ADD) and NumPad- (KeyEvent.VK_SUBTRACT) were associated with the expand and collapse action, respectively. No additional modifiers were necessary because in editing mode the ScrollPane is inactive, anyway.

**Comment by elemhsb** [comment]
Wow, what a nice version 3.23-10.
Collapse (Buttons/Keypad), Autoscroll and Mouse wheel works fine under Linux now. :-)

**Comment by codemanyak** [comment]
Collapsed CASE elements show wrong icon (instead of the CASE symbol it's a simple Instruction icon).
