### ISSUE TITLE
double clicking an .nsd file does not invoke restricted mode

### ISSUE THREAD

**Issue by fesch** [fesch/Structorizer.Desktop#870]
Maybe we should add an INI entry to set restriced mode system wide ...

Question passed by mail from: 
_Florent Charles – Enseignant de la filière d’Electronique
Département de la formation, de la jeunesse et de la culture
Direction générale de l'enseignement postobligatoire (DGEP)_

**Comment by codemanyak** [comment]
This could make sense. Though the original aim will hardly be achievable if it were configurable via the GUI. As it will have to be documented in the User Guide, the central ini file approach (#733) would have to be used to prevent stealth tweaking of the use-specific ini file, where the "restricted" setting in this predominant ini file in the protected installation folder would have to be put manually.

**Comment by fesch** [comment]
The entry should only be settable and thus being read by the predominant ini file in the protected installation folder where administrators can restrict rights. I think this is the easiest way ...

**Comment by fesch** [comment]
BTW, the -restricted parameter would in that case no longer be needed.

This should of course not be modifiable via the GUI ;-)

**Comment by codemanyak** [comment]
> The entry should only be settable and thus being read by the predominant ini file in the protected installation folder where administrators can restrict rights. I think this is the easiest way ...

I agree. To impose the restricted mode should be aone-way ticket, i.e. it would only be possible to set it but not to lift it for a running Structorizer, so the user could not interfere by tweaking the individual ini file while Structorizer is running. Seems tight.
How urgent is the request?

**Comment by fesch** [comment]
Right ;)

I will ask the one that made the request about the urgency ...

**Comment by codemanyak** [comment]
As the ini properties (the predominant ones, too) are regularly saved to the local ini file, the "restricted" property tends to get sticky. So we have to decide among two alternative approaches:
1. We accept this. The consequence would be that after withdrawal of the predominant ini file (placed there temporarily for the examination), the code export / import remains blocked for all users that had used Structorizer during the restricted period unless they rmove the line from their individual ini files.
1. We avoid this by preventing the specific key from being saved. Then the restriction will only work via a predominant central ini file in the write-protected installation folder. An attempt to block code export / import via editing an inidividual ini file, however, would not last beyond the next Structorizer start.

I guess option 2 is what is most appropriate here?

**Comment by fesch** [comment]
I agree on option #2

**Comment by codemanyak** [comment]
I implemented option 2 choosing "noExportImport" as the ini property key (bugfix branch).

**Comment by codemanyak** [comment]
Another export opportunity to be disabled in restricted mode we had overlooked in version 3.30-09a and 3.30-10 is the group export in the Arranger Index context menu.

**Comment by codemanyak** [comment]
@fesch 
What about urgency at DGEP? Shall we issue a new version or still wait?

**Comment by fesch** [comment]
Not really urgent right now. I helped them to find a solution for deploying Structorizer in restricted mode all over their campus, so there is no need to an immediate release right now.

**Comment by codemanyak** [comment]
Fine with me. Let's hope the students don't find out about the group export... ;-)
