### ISSUE TITLE
Translate internal functions into corresponding working code in PHP

### ISSUE THREAD

**Issue by schlumpfen** [fesch/Structorizer.Desktop#882]
#### Function in structorizer
**Built-in Numerical Functions**
random(n) | returns an integral pseudo-random number in the range between 0 and n-1

#### Function in PHP
**PHP  Function***
rand ( int $min , int $max ) : int | Generate a random integer, min The lowest value to return (default: 0), max The highest value to return (default: getrandmax())

##### Desired state:
random (6) --> rand(0, 5) 

##### Current state:
random(6) --> random(6)
![image](https://user-images.githubusercontent.com/7702969/98463791-4f210900-21be-11eb-9e45-71c462a2c5a8.png)

**Comment by codemanyak** [comment]
Thanks for the report. It will be fixed with the next version.

**Comment by codemanyak** [comment]
On that ocassion, the following replacements will also be done on PHP export:
`randomize` --> `srand`
`toRadians` --> `deg2rad`
`toDegrees` --> `rad2deg`
