### ISSUE TITLE
Executable subroutine calls to other diagrams

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#9]
Enhancement proposal
The execution of a subroutine call to another (open) diagram (let's name it "foreign call") should be supported by the executor under certain circumstances:
1. The call must be placed within a CALL element.
2. To keep complexity feasible it shoud comply with exactly one of the following forms:
     a) procedure call i.e. 
              name(arg1, arg2, ..., argn)
     b) single function call in a simple assignment i.e.
              variable <- name(arg1, arg2, ..., argn)
    No nested foreign calls.
3. A called foreign diagram must be represented by a Root element residing withing the same process. According to my first tests, the Arranger is a well-suited framework providing a pool of fully reacting opened diagrams.
4. Among the open diagrams according to the previous statement, in order to be eligible as callable subroutine, a diagram must of course be flagged as a subroutine diagram and has to be the only one with matching signature (i.e. name and argument count). Name matching is to be case-sensitive.
5. The Executor class being a singleton is a good prerequisite to make execution conflicts rather impossible.
6. Recursive foreign calls are either to be prohibited or require particular care (some kind of stack must be used, anyway).

I volunteer for the implementation of a first version.

**Comment by fesch** [comment]
Sounds good. Go for it ...

**Comment by codemanyak** [comment]
Below there are some example diagrams for testing purposes. A downloadable preview code version is located in branch "enhancements" of codemanyak/Structorizer.Desktop. The code is not robust and no warranty against damages is granted ;-).
![datedifference](https://cloud.githubusercontent.com/assets/15326471/11166617/ef17b5ee-8b3c-11e5-958f-90236118f315.png)
![daysincey1m1d1](https://cloud.githubusercontent.com/assets/15326471/11166618/f8cd2fa6-8b3c-11e5-833c-add2917f3fd3.png)
![daysofmonth](https://cloud.githubusercontent.com/assets/15326471/11166619/01167dd4-8b3d-11e5-835e-89567895985a.png)
![istschaltjahr](https://cloud.githubusercontent.com/assets/15326471/11166620/11bfdab8-8b3d-11e5-845c-436120fbb2ba.png)
![factorial_r](https://cloud.githubusercontent.com/assets/15326471/11166625/3856a0a8-8b3d-11e5-85d1-76f96e16ca6f.png)
![fibonacci](https://cloud.githubusercontent.com/assets/15326471/11166624/384286f4-8b3d-11e5-83b6-7c798da3dc5f.png)

**Comment by codemanyak** [comment]
Perhaps it might make more sense to launch the Arranger from an open Structorizer than the other way round (though this may also remain possible).
Typically, the Arranger would be needed to serve as a pool of open diagrams depending on eachother on execution. This is typically a decision coming up on developing algorithms, not on "arranging pictures".
In this scenario, it seems more practical to let the Arranger be a singleton, otherwise one would soon get lost among a dozen Arrangers being related with several but not necessarily all Structorízers.

**Comment by fesch** [comment]
That's a good idea :-)

**Comment by codemanyak** [comment]
Arranger converted to a singleton (in branch codemanyak/Structorizer.Desktop/enhancements) and now launchable by a Structorizer.
There should exist a possibility to "pin" diagrams to the Arranger surface to protect them from being replaced when the associated Structorizer replaces the diagram recently sent to Arranger. This way, a single Structorizer instance alone might inject several related diagrams to the Arranger (using it as a pool of executable subroutines) and execute the "diagram tree".
