### ISSUE TITLE
Enhancement request: Import of "Processing" code

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#932]
I obtained an enhancement request via e-mail:
> Meine Anregung zielt dahin, auch den Import von Code der Programmiersprache [Processing](https://processing.org) zu ermöglichen.
Processing ist eine auf Java basierende Sprache (bzw.C, C++ ähnlich), die auch gerne für Ausbildungszwecke benutzt wird.
Sie ist nicht so sperrig wie das reine Java mit komplexen IDEs wieEclipse oder ähnlich.
(Es sei denn man nimmt BlueJ : https://www.bluej.org )
Processing ist beliebt bei Künstlern und Designern und insbesondere auch (in der Lehre) weil Processing interpretativ ist.
Und: Processing hat auch einen PYTHON-Modus !
Structorizer ist ja meiner Meinung nach ein tolles Tool, weil es nicht nur TEX erzeugen kann, sondern auch als Konversionstool von Code nach anderem Code benutzt werden kann. .-)
Ich benutze zur Zeit Structorizer, um Code-Teile von Processing in Struktogramme und in TEX umzuwandeln.
Mit einem Trick kann man Teile von Processing importieren. Ist aber noch etwas mühselig.
Ich glaube aber, dass der Import von Processing Code (relativ einfach ?) zu bewerkstelligen wäre…

I obtained some code examples. Several constructs like Java array initializations had to be converted to C syntax, then an import worked surprisingly well, it seems.
The advantage of Processing for a code import (in comparison to Java) seems to be that it is not strictly OOP, but rather used in a more "procedural" style.

**Comment by codemanyak** [comment]
We received an enthusiastic reaction from the instigator of this enhancement:
> Da bin ich ja platt: Das ist ja eine tolle Überraschung !!! TOLL! Funktioniert fantastisch ….

**Comment by hkiel** [comment]
I was thinking of translating code from one language to another, or even developing the whole program in structorizer (for educational purposes only!)
Also, if you import a new pde file, it includes all the constants from Processing (`PI`, `FX2D`, ...) which I would need remove again. Most of them are not required by most sketches (add only the necessary ones?)

**Comment by codemanyak** [comment]
> The only thing I find inelegant is that these extra definitions are mixed with all global variables from the PDE. Maybe you can create two diagrams (one for implicit variables from Processing, one for global variables from program)?

Will be fixed with version 3.31-03.
