### ISSUE TITLE
Structorizer - Probleme mit meiner Schulklasse

### ISSUE THREAD

**Issue by fesch** [fesch/Structorizer.Desktop#943]
Sehr geehrter Robert Fisch,

 

ich möchte mich erstmal für die grandiose Idee bedanken, das Nassi-Shneiderman-Diagramm mit einem intuitiven Tool erfahrbar und greifbar zu machen. Ich bin Lehrer an einer Schule in Mainz und wir lernen das „Programmieren“ mit Structorizer. Ich freue mich, dass Structorizer lebt und immer weiterentwickelt wird. Leider gibt es jetzt bei mir und meinen Schülern das Problem, dass sich Structorizer nicht launchen lässt. „Testing“ und „Start application“ wird angezeigt, hiernach allerdings öffnet sich nicht die Benutzeroberfläche von Structorizer. Wissen Sie woran es liegt? Bei mir ist der Fehler aufgetreten, nachdem ich Java aktualisiert hatte.

 

Die Version 3.26 lässt sich starten. Haben Sie vorübergehend eine etwas neuere Version zur Verwendung bereitliegen, die meine Schüler und ich nutzen könnten, bis das Problem behoben ist?

 

Mit sehr vielen freundlichen Grüßen

Jonathan Platt

**Comment by fesch** [comment]
Hallo

Danke erst einmal für das sehr positive Feedback ;)

Ich habe das 'mal hier auch eingetragen:
https://github.com/fesch/Structorizer.Desktop/issues/943

Gestern habe wir Tests wegen eines Problems unter OSX
gemacht und da gab es bei der Windows Version ein Problem,
welches aber heute morgen behoben wurde.

Könnten Sie vielleicht die aktuelle Version noch einmal testen
bitten?

**Comment by erka2020** [comment]
Hallo,

das ist das gleiche Symptom von #940 mit der aktuellen, aber alten JRE Version 8

Viele Grüße
Rainer Kiehne

**Comment by fesch** [comment]
Wir arbeiten daran ...

**Comment by codemanyak** [comment]
Wie schon unter #940 benannt, es war versehentlich das defekte Jar-File (3.30-16 modifiziert) mit der neuen Version, die eigentlich 3.30-17 sein sollte und nach meinen internen Tests unter Java 8 funktioniert hätte, noch einmal zum Download gestellt worden.

**Comment by fesch** [comment]
Ich habe jetzt erneut kompiliert und lade alles erneut hoch ...
Bei mir klappt es jetzt auf jeden Fall auch mit der 1.8 ...
