### ISSUE TITLE
Upgrade path to Java 11?

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#944]
Issue #940 raises the question how long we want to maintain support for Java 8:
> Starting Structorizer on Windows 10 Java 8 Update 281 fails.
Web Start app throws exception
```
java.lang.ClassNotFoundException: java.awt.desktop.OpenFilesHandler
at java.net.URLClassLoader.findClass(Unknown Source)
at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at Structorizer.main(Structorizer.java:370)
...
```

As it seems, one reason for many users to stick to Java 8 might be the Java WebStart support. But the list of incompatible details between Java 8 and more up-to-date versions is growing, deprecation warnings arise.

So maybe we should **fix a time when we will switch to at least JDK 11 (say e.g. June 2021)** and communicate this to users (as a version hint with following Structorizer versions and on the "News" page)? For AdoptOpenJDK users at least (according to its migration guide), there is the chance to use [IcedTea-Web](https://adoptopenjdk.net/migration.html#icedtea-web) as an alternative to Java WebStart, even for the JDK 11, though it is not bundled with it anymore and is not guaranteed to work, either.

Apparently, the [OpenWebStart](https://openwebstart.com/) project (also based on [IcedTea-Web](https://adoptopenjdk.net/icedtea-web.html)) is determined to fill the gap, such that we could dare to leave it to our users to find a way to keep the JNLP delivery going.

**Comment by fesch** [comment]
By using Upla, I think JavaWebStart isn't any longer needed anyway, so for those who claim "auto-update" and only stick to Java8 because of that feature, we can tell them that Strutorizer includes automatic updates since a while now ... ;-)

**Comment by codemanyak** [comment]
> By using Upla, I think JavaWebStart isn't any longer needed anyway, so for those who claim "auto-update" and only stick to Java8 because of that feature, we can tell them that Strutorizer includes automatic updates since a while now ... ;-)

I personally agee. I take your answer as a go. So we will announce the upgrade from the next Structorizer version on and just wait for user reactions. ☺️

**Comment by codemanyak** [comment]
@fesch 
Just a question with respect to `Mainform.doOSX()` when we revise the code base for Java11 (I am preparing it on branch - surprise! - "java11"):
```java
/**
 * Generates and registers the OSXAdapter, passing it a hash of all the methods we wish to
 * use as delegates for various com.apple.eawt.ApplicationListener methods.
 */
public void doOSX() {
	// this is the old way to go (<=JDK8) on OSX
	try {
		/* Issue #744: The file handler must be the first handler to be established! Otherwise the
		 * event of the double-clicked file that led to launching Structorizer might slip through!
		 */
		OSXAdapter.setFileHandler(this, getClass().getDeclaredMethod("loadFile", new Class[]{String.class}));
		OSXAdapter.setQuitHandler(this, getClass().getDeclaredMethod("quit", (Class[]) null));
		OSXAdapter.setAboutHandler(this, getClass().getDeclaredMethod("about", (Class[]) null));
		OSXAdapter.setPreferencesHandler(this, getClass().getDeclaredMethod("preferences", (Class[]) null));
		OSXAdapter.setDockIconImage(getIconImage());

		logger.info("OS X handlers established.");
	} catch (Exception e) {
		e.printStackTrace();
		logger.log(Level.WARNING, "Failed to establish OS X handlers", e);
	}
	// START FISRO 2021-02-17: Issue #912
	// this is the new way (>JDK8) on OSX
	Desktop.getDesktop().setOpenFileHandler(new OpenFilesHandler() {
		@Override
		public void openFiles(OpenFilesEvent e) {
			for (File file: e.getFiles()) {
				loadFile(file.getAbsolutePath());
			}
		}
	});
	// END FISRO 2021-02-17
}
```
As far a s I can see, the `Desktop.getDesktop().setOpenFileHandler(...)` mechanism is to substitute the `OSXAdapter.setFileHandler(this, getClass().getDeclaredMethod("loadFile", new Class[]{String.class}));` line, but what about the rest? Will the QuitHandler, AboutHandler, PreferencesHandler and the DockIconImage also need replacements for OSX or do they automatically work beyond Java 9? (I found hints on [stackoverflow](https://stackoverflow.com/questions/44359794/dock-icon-under-osx-in-java-9) that some explicit action on class `Desktop` or `Taskbar` might be necessary.)

**Comment by fesch** [comment]
Until now I have not found a replacement for QuitHandler, AboutHandler, PreferencesHandler and the DockIconImage. Some of them seam to work seamlessly without any further code needed. This is based on some tests I've done on different systems I had access to.

DockIconImage fir instance is being configured through the plist of the OSX application structure.

**Comment by codemanyak** [comment]
The announced Java 11 requirement was imposed with version 3.31-05 on 2021-09-18.
The Java Web Start offers on the Structorizer [homepage](https://structorizer.fisch.lu) should hence be removed now.
