### ISSUE TITLE
Code export to shell scripts must prefix variable names with $

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#96]
In analogy to Perl and PHP, variable names are to be prefixed with $ on code export to bash and ksh, with difference that is not to be done on the left-hand side of assignments.

**Comment by elemhsb** [comment]
Yes, you are right, plus the assignment has to be exported also without SPACES. like A=1.
Written in Structorizer ´´´A<-1´´´ will work ´´´A <- 1´´´ didn't. 
The test clause for **if**,**while** ```A = 1``` need to be written as executable test like 
***if expr "$A" '==' "1"; then*** and with spaces ;-). The "" are for variables which have spaces in there content and  and the ' ' are for <=, >=, ... operators.
EDIT: for performance reason no external **expr** programm should be used. Buildin commands test or [
should be used, also the operations need to be convertet -> -gt -le ... :-(
BTW.: I think it's the right way to export **real** working code in all cases.
I miss a testcase area on github.
The processing of commandline options like ***Structorizer.sh --export-to-{bash,cpp,python} *.nsd*** would also be usefull. The commandline is expanded per default from calling shell to Structorizer.sh --export-to-bash --export-to-cpp --export-to-python BIG.nsd break.nsd ...
Also it would be very usefull to have a export button on toplevel and the export menue structure support checkboxes for configuring the desired export languages.
BBTW: A "Code/Comment swab switch" like the "Switch visual style button" on toplevel would also be very nice.

**Comment by codemanyak** [comment]
I was already working on some shell expressions but a completely flawless export won't be possible. It is too much guesswork and the (different kinds of) shell syntax is (are) such a mess. We don't know what contents the variable will have and there are worlds between a typed value concept of many high-level languages and the string-based approach of shell script languages.
We won't be able to write an "eierlegende Wollmilchsau" here. The code export is not meant to create perfect target code in all cases but to support beginners by creating the syntactical skeleton of the algorithm (with as much correct parts as possible, of course) for manual finishing.

@elemhsb BTW: I would like you to separate your commandline and button enhancement proposals from this issue. They having to do with each other. Perhaps you may want to open separate enhancement issues foor them?

**Comment by codemanyak** [comment]
Some additional remark to expressions:
In most cases, standard arithmetic expressions with C syntax are understood by up-to-date versions of bash or ksh if put within ((  ))  or  $((  )), respectively. The crux is that string expressions are to be handeld differently, e.g. they may be put inside [[ ]]. So how does the Structorizer code generator know from untyped code what will be going on?
I might simply put the conditions inside (( )) and assignment expressions inside $(( )), in the assumption that most algorithms that are not specifically targeted for shell scripts will rather work with numbers than with strings. But this is only guesswork as well.

**Comment by codemanyak** [comment]
Bugfix (including variable prefixing, elimination of padding spaces around assignment operator, and embracing test conditions by "(( " and " ))") ready on bugfix3.23 branch

**Comment by codemanyak** [comment]
I close the bug with respect to the original issue description plus the granted modifications described in the previous comment.
(The enhancement proposals ought to be raised as separate issues if they are regarded as important enough.)
