### ISSUE TITLE
Enhancement request: Hide existing translations in Translator GUI

### ISSUE THREAD

**Issue by hkiel** [fesch/Structorizer.Desktop#972]
Missing translations are marked orange in "Structorizer Translator" GUI, however, if you want to check if something is missing in a translation you have to scroll through every line.

Solution: add a check box that says "hide existing translations" and filter out non-empty translations, so that you can easly find missing translations. This would also help when translating for a new language. Probably uncheck the box when selecting another language.

**Comment by codemanyak** [comment]
Hm, implementation turns out to be a little harder than expected: The table structure is established on initialization, i.e., before any specific locale is loaded.
Perhaps certain hotkeys to jump to the next/previous missing translation (or modified translation) might do as well?

**Comment by codemanyak** [comment]
This is how it will look like from version 3.31-03 on:
![grafik](https://user-images.githubusercontent.com/15326471/117889834-78793980-b2b4-11eb-84c4-371479546ed4.png)
