### ISSUE TITLE
Insufficient handling of backslashes in text literals on StrukTeX export

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#975]
The StrukTeX export of diagrams with backslashes in String or character constants causes TeX complaints about them, because it they are not translated to \textbackslash.

**Comment by hkiel** [comment]
Is adding `tokens.replaceAll("\\", "\\textbackslash");` to the beginning of `transformTokens()` enough?
Or should the transformation be placed inside the detection of quoted strings/chars?
As I can see TeX text is usually in math mode, so `\textbackslash` should be `\backslash` in math mode.

Are strings like `"\n"` already handled correctly?

**Comment by hkiel** [comment]
Escaped (`'\'`) sequences in strings are not handled correctly yet.
Also I see that when I export as StrukTeX all diagrams are placed in their own `\begin{document}\end{document}` group in the same file. Maybe they should be placed in one document, but several `\begin{struktogramm}\end{struktogramm}` groups.

**Comment by codemanyak** [comment]
Backslashes and tilde characters within string/character literals will now be replaced by `\textbackslash{}` and `\textasciitilde{}`, respectively (in theory there may be more candidates of characters to be replaced, but these were the most obvious ones). Outside of text literals backslashes should not actually be expected, not at least in executable diagrams, but it won't cause harm to replace backslash tokens (if there should be any), and tilde operators as well.

**Comment by hkiel** [comment]
The next-to-most-obvious TeX special characters are `'%'` and `'&'`.

**Comment by codemanyak** [comment]
> Escaped (`'\'`) sequences in strings are not handled correctly yet.

Fix is in place (see commit [79617f7](https://github.com/fesch/Structorizer.Desktop/commit/79617f7a685ba99643179195dd22bd369eee1594)).

> Also I see that when I export as StrukTeX all diagrams are placed in their own `\begin{document}\end{document}` group in the same file. Maybe they should be placed in one document, but several `\begin{struktogramm}\end{struktogramm}` groups.

Usually this already the case. It may depend on the way of exporting the diagrams, though. If you export an arrangament group with several program diagrams then a compound file with scissor lines (where to cut the file apart) may be generated. If you export a main diagram together with its subroutines then the result will exactly be as you suggest. You might have a look at the [export samples](https://github.com/fesch/Structorizer.Desktop/tree/master/samples/export/StrukTeX).

**Comment by codemanyak** [comment]
> The next-to-most-obvious TeX special characters are `'%'`, `'_'` and `'&'`.

This is the provisional set of replacements within text literals:
```
					token.replace("{", "‽{")
					.replace("}", "‽}")
					.replace("\\", "\\textbackslash{}")
					.replace("\"", "\"{}")
					.replace("'", "'{}")
					.replace("^", "\\^{}")
					.replace("~", "\\textasciitilde{}")
					.replace("&", "")
					.replace("#", "\\#")
					.replace("°", "\\textdegree")
					.replace("^", "\\^{}")
					.replace("%", "\\%")
					.replace("$", "\\$")
					.replace("‽{", "\\{")
					.replace("‽}", "\\}")
```
Underscores have already been handled (in `TexGenerator.transform(String)` this time as it is not token-specific).

**Comment by hkiel** [comment]
Why do you replace "{" -> "‽{" -> "\\{" ?
If doing replace in correct order ("{" -> "\\{" and "}" -> -> "\\}" first, then all others) everything should be fine!?

**Comment by codemanyak** [comment]
> Why do you replace "{" -> "‽{" -> "\{" ?
> If doing replace in correct order ("{" -> "\{" and "}" -> -> "\}" first, then all others) everything should be fine!?

No, then "{" would be replaced by "\textbackslash{}{".

**Comment by hkiel** [comment]
Isn't the `tokens.replaceAll("{", "\\{")`(line 211)  conflicting with the `for() token.replace(""{, "\\{")` (line 252)?

**Comment by codemanyak** [comment]
> Isn't the `tokens.replaceAll("{", "\\{")`(line 211) conflicting with the `for() token.replace(""{, "\\{")` (line 252)?

No, it isn't. The first instruction replaces isolated braces (brace tokens) whereas the second one replaces braces as content in text literal tokens (the tokenization mechanism preserves string and character literals).
