### ISSUE TITLE
Java requirement update in a patch-set version?

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#984]
It is reasonable to have a Java 11 requirement, but do I understand that correctly that this changed in a patch-level update (-04 to -05)?
Isn't that something that may even suggest a major update (3->4)? Otherwise I'd argue it would definitely be enough reason for a minor update (31->32).

... just thinking...

**Comment by codemanyak** [comment]
I think you are right. We should at least have spent it a new minor number and will do with the outstanding two patches.
