### ISSUE TITLE
Startup problem from the zip package on Windows (Structorizer.bat is defective)

### ISSUE THREAD

**Issue by raulus127** [fesch/Structorizer.Desktop#988]
Hi! How are you?
I am writing to you because I have installed the latest version without problems but when I run the app it does not run. I know of many people who have experienced the same thing. Can you help me? Thank you.

**Comment by codemanyak** [comment]
Hi Raulus. We have announced early this year that the required minimum Java version would be cnaged to 11. This was put into effect now. Is it possible that your Java environment is still 8 or otherwise lower than 11?

**Comment by codemanyak** [comment]
@raulus127 
Another request: If Java turns out not to be the problem, would you mind telling us what platform (OS) you are working on? Have you tried to start Structorizer from the downloadable zip version via the included batch or shell script (i.e. Structorizer.bat / structorizer.sh), respectively?

**Comment by raulus127** [comment]
Hi there! I have java version 11 installed. I downloaded the zip version and from the structorizer.sh file it works fine.

**Comment by codemanyak** [comment]
@raulus127 
> I downloaded the zip version and from the structorizer.sh file it works fine.

That is fine. So I conclude you work on a Linux platform. If it is a Debian or Ubuntu distribution then the Debian package should also work. Or doesn't it still?

**Comment by raulus127** [comment]
The platform I use is Windows.

**Comment by raulus127** [comment]
It does not work from the .exe file and from the .sh file it looks with less resolution.

**Comment by codemanyak** [comment]
Uh, so you meant *Structorizer.bat* when you wrote *structorizer.sh*?

**Comment by raulus127** [comment]
The .bat file is not working for me. The .sh yes

**Comment by codemanyak** [comment]
> 
@raulus127 
> It does not work from the .exe file and from the .sh file it looks with less resolution.

Ah, you did not use the Windows installer but the Structorizer.exe from the zip package? In this case you might have to have a look in the registry. Watch out for the "Java Runtime Environment" or "JRE" keys in the  `HKEY_LOCAL_MACHINE/SOFTWARE/JavaSoft/` hierarchy and read the workaround recommendations in the [UserGuide](https://help.structorizer.fisch.lu/index.php?menu=46&page=#open_jdk_trouble).
By the way, the Windows installer package should run even without registry tweaking.

**Comment by codemanyak** [comment]
> The .bat file is not working for me. The .sh yes

Oops, indeed! I haven't been aware that the windows 10 command line is capable of interpreting shell scripts. Thanks for this surprising information!

**Comment by codemanyak** [comment]
@raulus127 
Ok, the new *Structorizer.bat* file seems to contain a syntax error... I will have a look at it. The Structorize.exe ought to run, however, if the registry contains the required Java keys.

**Comment by raulus127** [comment]
> > The .bat file is not working for me. The .sh yes
> 
> Oops, indeed! I haven't been aware that the windows 10 command line is capable of interpreting shell scripts. Thanks for this surprising information!


That's how it is! Windows 10 already brings that particularity.

**Comment by raulus127** [comment]
Now it works from the access that the installer created. Thank you very much as always for everything.

**Comment by codemanyak** [comment]
... and I found the bug in the Structorizer.bat file:

line 30 must be
`   if %%VERSION%% equ 1 set VERSION=%%b`
instead of
`   if %VERSION% equ 1 set VERSION=%%b`

My mistake. Sorry!

**Comment by raulus127** [comment]
Thank you!!

**Comment by codemanyak** [comment]
While the download package hasn't been mended I tend to keep this issue open.

**Comment by codemanyak** [comment]
Okay, Bob updated the downloadable zip package for Windows (and Linux). So at least the *Strutorizer.bat* file doesn't cause problems anymore.
