### ISSUE TITLE
4k-display: 3.32 Skalierung passt nicht

### ISSUE THREAD

**Issue by speedy-10** [fesch/Structorizer.Desktop#994]
Wenn ich unter Einstellungen > GUI-Skalierung auf z.B. Faktor 2 setze, dann vergrößern sich zwar die Icons, leider nicht das angezeigte Struktogramm.

Version: 3.32 (per structorizer.deb File installiert)

System: Ubuntu 20.04 , Kernel: 5.11.0-37-generic x86_64, 
java-14-openjdk-amd64/bin/java

Siehe Bild.

Wie kann ich das ändern?

Liebe Grüße
![Bildschirmfoto von 2021-10-04 14-45-05](https://user-images.githubusercontent.com/20227451/135854392-2bcd9d56-2713-4b3b-8c8f-e674b7738531.png)

**Comment by codemanyak** [comment]
Die Größe des Diagramms wird unabhängig von der GUI-Skalierung ausschließlich über den Font des Diagramms gesteuert:
- Menüpunkt "Einstellungen > Zeichensätze ...";
- Werkzeugleisten-Schaltflächen ![grafik](https://user-images.githubusercontent.com/15326471/135862976-6e718e1b-6475-4e7d-9532-c119ad1e238e.png);
- Tastenkombinationen `Strg + Num+` / `Strg + Num-`.

Das war übrigens schon immer so, nicht erst seit 3.32.

**Comment by speedy-10** [comment]
Alles klar, habe aber erst seit kurzem einen 4k-Monitor und daher die Schwierigkeit bisher nicht gehabt ;-).

**Comment by codemanyak** [comment]
Übrigens kleiner Tipp noch:
Es wären nur geringe Anpassungen nötig, um das Diagramm ausführbar zu machen: 
- Beschreibung des Diagramms in den Kommentar des Rahmenelements, dafür als Text den Programmnamen (einen Bezeichner) einsetzen;
- Wertzuweisungssymbol `<-` oder `:=` statt `=`;
- Kennwörter für Eingabe und Ausgabe mit Parser-Einstellungen abgleichen (Doppelpunkte dürfen leider seit einer Version vor über 10 Jahren nicht mehr in den Kennwörtern verwenden werden - ich weiß nicht, warum nicht, das könnte zumindest bei Eingabe/Ausgabe eigentlich wieder zugelassen werden);
- Bei Division Gleitkomma-Arithmetik erzwingen, etwa durch `Zinssatz/100.0` - sonst dürfte es effektiv auf Nullzins-Politik hinauslaufen 🥲 .

Die Operatoren können bei Bedarf über "Diagram > Operationsanzeige wie in C?" zumindest wie in C usw. angezeigt werden.

Alternativ (wenn die Texte in den Elementen bewusst nicht der Structorizer-Syntax angepasst werden sollen), wäre der Analyser sinnvollerweise abzuschalten (`F3` bzw. "Diagramm > Struktogramm überprüfen?") oder so konfiguriert werden, dass die Warndreiecke nicht stören.

Weiterhin viel Freude und frohes Schaffen.

**Comment by codemanyak** [comment]
Ach ja, und solange das Guthaben jedes jahr immer nur vom Anfangsbetrag und nicht vom vorherigen Guthaben abhängt, wird es sowieso nichts mit der wundersamen Geldvermehrung ...
